### ISSUE TITLE
1.21 Items only show as pieces of paper

### ISSUE THREAD

**Issue by OperationTwelve** [PluginBugs/Issues-ItemsAdder#3838] opened 2024-07-28 21:41 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Updated Minecraft to latest version Spigot 1.21 along with 4.0.2-alpha-test-3 of IA and latest LoneLibs... I tried running the server and /ia didn't bring up the GUI. and all custom items were paper. 

I removed the itemsadder folder from the plugins folder to have it gresh install. When I do /ia the menu pops up but still everything is paper.

I further tested by removing all other plugins.. same issue. the items dont load in. Not even the internal items.

I appreciate the hard work that is put into this I just wanted to make sure these issues are known so that when you have the time you can fix this as well. 

### Steps to reproduce the issue

install latest version 4.0.2-alpha-test-3 and latest spigot version and launch the server on Gportal

### Server version

This server is running CraftBukkit version 4213-Spigot-146439e-f5a63f7 (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.2-alpha-test-3

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.56

### Full server log

https://mclo.gs/hIXvNsu

### Error (optional)

```shell
[16:34:56] [Server thread/ERROR]: [ItemsAdder] Invalid character in folders/name of file: Roasted Chicken
Skipped some lines of output
[16:34:56] [Server thread/ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[16:34:56] [Server thread/WARN]: java.lang.IllegalAccessError: class lonelibs.dev.lone.fastnbt.nms.nbt.CraftItemStack_v1_21 tried to access field org.bukkit.craftbukkit.v1_21_R1.inventory.CraftItemStack.handle (lonelibs.dev.lone.fastnbt.nms.nbt.CraftItemStack_v1_21 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @68b96184; org.bukkit.craftbukkit.v1_21_R1.inventory.CraftItemStack is in unnamed module of loader java.net.URLClassLoader @65b3120a)
```

**Comment by Andre601** [comment] 2024-07-28 21:51
Duplicate of #3833 based on the error. Please check the issue tracker next time, thanks.

**Closed by Andre601** 2024-07-28 21:51 UTC
Labels: type: bug
