### ISSUE TITLE
Mythicmobs incompatibility ?

### ISSUE THREAD

**Issue by neokyle** [PluginBugs/Issues-ItemsAdder#2741] opened 2023-06-15 15:41 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

https://pastebin.com/GFt2DqzH

See above startup error on latest IA and 1.20.1 pufferfish build 3

### Steps to reproduce the issue

Start server

### Server version

This server is running Pufferfish version git-Pufferfish-3 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3128603 on HEAD)

### ItemsAdder Version

3.5.0

### ProtocolLib Version

5.1.0 build 652

### LoneLibs Version

1.0.25

**Comment by LoneDev6** [comment] 2023-06-15 15:58
Duplicate of: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2739

Please use search before opening issue reports.

**Closed by LoneDev6** 2023-06-15 15:58 UTC
Labels: type: bug
