### ISSUE TITLE
I updated and my vehicles now won't let me drive them

### ISSUE THREAD

**Issue by RitsuElAnti** [PluginBugs/Issues-ItemsAdder#3359] opened 2024-01-22 05:32 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Ritsu#9014

### What happened?

I have updated to the latest version (3.6.3-beta-9, I also updated your ProtocolLib
,LoneLibs) and my vehicles now do not allow me to drive them, having their fuel.

### Steps to reproduce the issue

1-I get into the vehicle
2-I use the keys to move
3-the vehicle does not move

### Server version

This server is running Paper version git-Paper-228 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 72f7945)

### ItemsAdder Version

3.6.3-beta-9

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/119564188/db779177-7491-472b-a4e7-43ac748a4ce2)

**Comment by LoneDev6** [comment] 2024-01-29 14:50
Will be checked, but last time I tested vehicles they worked fine

**Comment by LoneDev6** [comment] 2024-01-29 15:28
Seems a duplicate of this: #3242

Try to update the plugins as stated by the other customer in the last message.
Let me know, thanks.

**Comment by RitsuElAnti** [comment] 2024-01-29 16:07
and update plugins although I already had them updated (Lonelibs 1.0.45 and PortocolLib 5.2.0-SNAPSHOT-679), I reinstalled all the plugins from scratch along with itemsadder, and it was not solved.

**Comment by LoneDev6** [comment] 2024-01-29 16:11
Seems still a duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/3242 , I will do some other tests but I couldn't reproduce the issue.
There is something wrong here.

**Comment by RitsuElAnti** [comment] 2024-01-29 16:16
Unfortunately I don't have the previous version of itemsadders to prove what worked for me before, I haven't had a problem with anything, just that, since I was just recording a tutorial and I realized the error.

**Comment by LoneDev6** [comment] 2024-01-29 16:18
> Unfortunately I don't have the previous version of itemsadders

You can download it from the files history.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/f5e3f9f2-7517-4ece-b7ee-f758d4906bfb)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/3732746f-374c-47b2-98b3-4e416f986bef)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/ace1d35f-6533-4c1d-bcd7-294f45d55e8d)

**Comment by RitsuElAnti** [comment] 2024-01-30 09:32
Hello, I have tried several versions of itemsadders, the problem is not this, but protocollib which I also tried several versions, I had to go for an older version, it seems that the latest version throws a small error in the console related to version 1.20. 2, I solved my error with the protocollib version (5.2.0-SNAPSHOT-676) and itemsadders (ItemsAdder_3.6.2c.jar)

![ezgif-1-3760daffc5](https://github.com/PluginBugs/Issues-ItemsAdder/assets/119564188/7e5aed2a-2c63-43e5-a3d1-cbf353aad8b5)

**Comment by RitsuElAnti** [comment] 2024-01-30 09:36
Then I will try with current versions of itemsadders, which I'm sure will work but the fault in my case is protocollib, maybe they removed compatibility with 1.20.2, I wouldn't know why, but the last two versions of protocollib gave me the same fault.

**Comment by LoneDev6** [comment] 2024-01-30 11:40
Can you consider updating to 1.20.4?
There is no reason to stay on 1.20.2, old game builds are usually bugged, you should always update to the latest build of the current game version, for example 1.18.2, 1.19.4, 1.20.4.

**Comment by LoneDev6** [comment] 2024-01-30 13:20
https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/3b6ff123-0ea9-4038-a01f-e977a72e7428

**Closed by LoneDev6** 2024-01-30 13:20 UTC
Labels: type: bug, status: need testing
