### ISSUE TITLE
Can't drop items when killing a mythicmobs entity

### ISSUE THREAD

**Issue by Steve29794** [PluginBugs/Issues-ItemsAdder#3915] opened 2024-08-23 11:36 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

After killing a Mythimobs entity, it should have dropped an object, but it did not and threw an error on the console.

### Steps to reproduce the issue

1. Install the 5.7.x mythicmobs
2. Add the ia items to the drop
3. Kill a mythicmobs mob

### Server version

This server is running Leaf version git-Leaf-"83c2468" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 83c2468 on ver/1.20.4)
* You are running the latest version
Previous version: git-Purpur-2176 (MC: 1.20.4)

### ItemsAdder Version

3.6.4-release-3

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.56

### Full Server Log

https://mclo.gs/BtUKSfZ

### Error (optional)

```shell
[19:32:56] [Server thread/ERROR]: [MythicMobs] [EVENTS] Exception thrown whilst handling event: org.bukkit.event.entity.EntityDeathEvent
[19:32:56] [Server thread/WARN]: java.lang.InstantiationError: io.lumine.mythic.bukkit.adapters.BukkitItemStack
[19:32:56] [Server thread/WARN]: 	at ItemsAdder_3.6.4-release-3.jar//dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.drops.CustomItemDrop.getDrop(SourceFile:28)
[19:32:56] [Server thread/WARN]: 	at MythicMobs-5.7.1.jar//io.lumine.mythic.core.drops.DropExecutor.handleEntityLootDrops(DropExecutor.java:297)
[19:32:56] [Server thread/WARN]: 	at MythicMobs-5.7.1.jar//io.lumine.mythic.bukkit.adapters.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:423)
[19:32:56] [Server thread/WARN]: 	at MythicMobs-5.7.1.jar//io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
[19:32:56] [Server thread/WARN]: 	at MythicMobs-5.7.1.jar//io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131)
[19:32:56] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72)
[19:32:56] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:68)
[19:32:56] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[19:32:56] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616)
[19:32:56] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:996)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.dropAllDeathLoot(EntityLiving.java:1903)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1795)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1607)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.world.entity.monster.EntityZombie.a(EntityZombie.java:363)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1372)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2427)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection$4.a(PlayerConnection.java:2913)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2835)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:150)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1471)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:181)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1449)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1377)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1354)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1244)
[19:32:56] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:308)
[19:32:56] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by Steve29794** [comment] 2024-08-23 11:39
![image](https://github.com/user-attachments/assets/152ae5b3-0513-4dab-b593-965f5835e16d)
Permission has been changed

**Comment by LoneDev6** [comment] 2024-10-15 09:10
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/3879

**Closed** 2024-10-15 09:11 UTC
Labels: type: duplicate
