### ISSUE TITLE
Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v4.0.2-alpha-test-3

### ISSUE THREAD

**Issue by SrMonsterYT** [PluginBugs/Issues-ItemsAdder#3871] opened 2024-08-07 21:23 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

mauriciooficial

### What happened?

error: https://mclo.gs/CEuVkR1

### Steps to reproduce the issue

update your server to 1.21

### Server version

Paper version 1.21-127-master@4e6a2a1

### ItemsAdder Version

ItemsAdder_4.0.2-alpha-test-3.jar

### ProtocolLib Version

ProtocolLib 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs.jar 1.0.56

### Full server log

no error

### Error (optional)

```shell
https://mclo.gs/CEuVkR1
```

### Problematic items yml configuration file (optional)

```shell
metrics: true
update-checker: true
resource-pack:
  uuid: "d69238f2-b7ce-30b0-8262-17cd9490f29d"
  apply-during-chunk-load-phase: true
  hosting:
    no-host:
      enabled: false
    lobfile:
      enabled: false
    self-host:
      enabled: true
      server-ip: '.....'
      pack-port: 25575
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  atlas_support: true
  fix_force_unicode_font_images: true
  expert_users:
    allow_other_plugins_resourcepacks: false
  protect-player:
    hide-hud: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: "ipaexg.ttf"
    shift: "[0,0]"
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    ignore-files-ext:
      - db
      - yml
      - xcf
      - psd
      - html
      - gz
      - rar
      - zip
      - 7z
    extract_internal_utility_assets: true
    contents-folders-priority:
      - vanilla
      - _iainternal
    merge_other_plugins_resourcepacks_folders:
      - "ModelEngine/resource pack"
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  custom_blocks_sounds_patch:
    enabled: true
    step:
      enabled: true
      allow_non_player: true
    other: true
config_files:
  lang: 'en'
  dictionaries-lang: 'en'
  force-sync-loading: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire_enhancements:
    enable: true
    unlit_on_place: true
    allow_any_item: true
    drop_when_broken: false
  custom:
    note: true
    mushroom: true
    chorus: true
    wire: false
    fire: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  remove-unused-palettes-on-region-save: false
items:
  fix-show-attack-and-damage-as-lore: true
  hide-custom-durability-lore: true
  show_item_durability:
    in_ia_menu: true
    in_inventory: false
  fix_trades_guis_match_custom_items:
    itemsadder_trade_machines: true
    vanilla_villagers: false
    other_plugins: true
  optimizations:
    kick_on_quickbar_spam:
      enabled: true
      ms: 200
      clicks: 6
liquids:
  enabled: true
huds:
  enabled: true
  force_color:
    enabled: false
    color: "#FFFFFF"
  hide_if_pack_not_accepted: true
cooldown_bars:
  enabled: true
  refresh_ticks: 1
  bossbar:
    color: WHITE
    style: SOLID
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  enabled: false
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    add-hover-suggestion: true
    tab-autocompletion_1_19_1_plus: true
  command:
    enabled: true
    commandblocks: true
    excluded:
      - home
      - sethome
      - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  iaimage-book:
    max-line-length: 18
    placeholder-font: "minecraft:default"
effects:
  hide-scoreboard-numbers: false
  hide-scoreboard-numbers-old-clients: false
  text-effects:
    enabled: true
    customitem-name-and-lore:
      enabled: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  custom-entitites:
    enabled: true
    emotes: true
    expert_users:
      delay_packets: false
  furniture:
    auto_convert_to_item_display: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: true
        ingredients: true
      on-item-click:
        any: true
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      "DIAMOND_SWORD": false
      "IRON_INGOT": false
player_stats:
  save_type: CUSTOM_NBT # CUSTOM_NBT, PLAYER_DAT
show_plugin_logo_on_enable: true
debug:
  benchmark: false
  resourcepacks:
    log_player_install: false
  items:
    log-files-loading: false
    log-files-reloading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  issues:
    log_font_image_replace_json_syntax_exception: true
```

**Comment by Asleeepp** [comment] 2024-08-08 00:34
1.21 is currently not supported

**Comment by Andre601** [comment] 2024-08-08 00:59
> 1.21 is currently not supported

That's wrong information. 1.21 is supported by ItemsAdder. However, ItemsAdder is still in alpha, so bugs may appear.

**Comment by SrMonsterYT** [comment] 2024-08-08 13:26
I discovered that this error appears when I set emotes to false

entities:
  max-furniture-vehicles-per-chunk: 30
  custom-entitites:
    enabled: true
    emotes: false
    expert_users:
      delay_packets: false
  furniture:
    auto_convert_to_item_display: false
    
    @LoneDev6

**Comment by SrMonsterYT** [comment] 2024-08-08 17:10
the problem happened again, so it wasn't solved

generated new errors:

error https://mclo.gs/LPzFs9K

**Comment by JerichoTorrent** [comment] 2024-08-11 20:06
I am also dealing with this exact same error. Please help.

**Comment by KeithR77** [comment] 2024-08-22 18:29
Error occurred for me as well, but it was because I had disabled text effects from the config file. Once I set the value back to true, the issue stopped occurring and the resourcepack successfully loaded.

**Comment by skrevt** [comment] 2024-08-22 21:51
> Error occurred for me as well, but it was because I had disabled text effects from the config file. Once I set the value back to true, the issue stopped occurring and the resourcepack successfully loaded.

Problem persists with me text-effect on true pack is not loaded :/

**Comment by LoneDev6** [comment] 2024-08-28 15:28
> [14:05:07 ERROR]: Could not pass event PlayerJoinEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.NoSuchFieldError: Class net.minecraft.world.entity.Entity does not have member field 'net.minecraft.server.level.ChunkMap$TrackedEntity tracker'
https://mclo.gs/LPzFs9K

Duplicate of: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3854
Already fixed.

**Closed by LoneDev6** 2024-08-28 15:28 UTC
Labels: type: bug
