### ISSUE TITLE
Enabling emoji and chat related settings breaks chat and plugin message output

### ISSUE THREAD

**Issue by neokyle** [PluginBugs/Issues-ItemsAdder#3414] opened 2024-02-08 13:43 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

On 3.6.3 Beta 11 enabling these below settings breaks chat and causes it to output as raw json or not appear to the client at all, this includes messages sent directly from plugins not just chat. I use venturechat 3.7.1, which I've tried without, this bug will make plugin messages sent in the chat not show at all as well. This occurred after updating IA to the latest release today, removing IA, downgrading or changing these settings fixes the issue.

chat: enabled: true
add-hover-suggestion: true
tab-autocompletion_1_19_1_plus: true

This is on pufferfish 1.20.1, lonelibs 1.0.45 and protocollib 679

### Steps to reproduce the issue

Enabling the following settings:

chat: enabled: true
add-hover-suggestion: true
tab-autocompletion_1_19_1_plus: true

### Server version

pufferfish 1.20.1

### ItemsAdder Version

3.6.3 Beta 11

### ProtocolLib Version

679

### LoneLibs Version

1.0.45

**Comment by LoneDev6** [comment] 2024-02-28 15:40
Duplicate of #3397

**Closed by LoneDev6** 2024-02-28 15:40 UTC
Labels: type: bug
