### ISSUE TITLE
Plugin Drop2Inventory - Duplication bug chorus fruits

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2717] opened 2023-06-08 08:58 UTC
More info: https://forum.devs.beer/d/601-bug-give-frutti

The issue is caused by Drop2Inventory somehow giving the chorus fruit to the player in some cases when it shouldn't.

**Comment by Distolfix** [comment] 2023-06-15 13:28
So from what I understand it depends on another plugin?

**Comment by Distolfix** [comment] 2023-06-15 13:30
Perfavore, controlla la risposta nel ticket. Sei stato gentilissimo

**Comment by mfnalex** [comment] 2023-06-18 15:12
Drop2Inventory listens to ItemSpawnEvent on a configurable priority, HIGHEST by default. Setting it to MONITOR in D2I fixes it, however MONITOR is not recommended to use as cancelling it in that stage is not allowed as per the Spigot API docs. It looks like ItemsAdder itself cancels the event on HIGHEST priority, while actually LOWEST would be advisable - that's the only way to ensure that other plugins get notified that this event was already cancelled.

Alternatively, ItemsAdder could cancel the event on LOWEST (to let other plugins know) and on HIGHEST too (to maybe undo uncancelling caused by other plugins). However, only listening on HIGHEST causes issues with other plugins who need to ultimatively cancel the ItemSpawnEvent, as seen here.

**Comment by Distolfix** [comment] 2023-06-18 17:31
@LoneDev6

**Comment by LoneDev6** [comment] 2023-06-18 19:44
I cannot listen to LOWEST since I wouldn't be able to detect permissions plugins which cancel this event.
I listen on HIGHEST to make sure the event is triggered only if other plugins didn't cancel it before.

The whole Spigot events API is flawed and this kind of issues is usual, btw.

For now I don't really have any proper solution to fix this

**Comment by mfnalex** [comment] 2023-06-19 06:01
I see, yeah the API is indeed a bit stupid here. Maybe you could add a setting to change the priority in the config, which defaults to HIGHEST? This'd be the only way to ensure other plugins can still cancel the event without doing so on MONITOR, if needed.

**Comment by Distolfix** [comment] 2023-06-19 06:06
So let me tell you what I think: I'm not a Minecraft plugin developer, so my experience in this is equal to zero. However, I'm sure that this bug isn't just related to Drop2inv, but nearly all plugins that make items end up in the inventory. We need to find a way to fix this problem, because the issue surely comes from the fact that when opening the trapdoor, the block breaks. This generates an event, which is then cancelled, but as you can see, some plugins like Drop2inv don't have time to register this, and hence the issue. I'm afraid this could lead to other bugs. Wouldn't it be better, if possible, to try to come up with a solution that prevents this trapdoor opening and closing glitch? For example: couldn't it be possible to make it so at the plugin level that the chorus fruit doesn't grow as you said to modify in the purpur.yml file? I believe that would be the most suitable option. Right now, I might be the only one affected by this annoying bug, but I assure you that many others may not be aware of it. However, I might not be the only one it's happening to.

**Comment by LoneDev6** [comment] 2023-06-19 09:04
> I'm sure that this bug isn't just related to Drop2inv, but nearly all plugins that make items end up in the inventory

Yea, that's what I meant. The Bukkit Events API itself it flawed.
Some years ago I found the original repository of the Bukkit Events API which wasn't coded by the Bukkit developers, they took it to include it into Bukkit.
The original author had put a comment in that repository clearly stating that the system is flawed and it's not ready for production.
(I can't find it anymore sadly, but I'll post it here if I ever find it again).

I wonder why Bukkit team decided to include this system as the priority limitation makes plugins development unreliable.


> couldn't it be possible to make it so at the plugin level that the chorus fruit doesn't grow as you said to modify in the purpur.yml file?

No as Purpur modifies the game code, plugins cannot do it (at least cannot do it without requiring the server owners to setup some complex stuff on their Java launch params).

----

> Maybe you could add a setting to change the priority in the config, which defaults to HIGHEST

What I can do is just set the priority to LOWEST as the only reason why I set it to MONITOR is for performance reasons, because my code could be a bit heavy, but idk, it can cause lag only if you have a very high intensity items spawning condition on your server for some reason.

My code:
```java
    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    private void onItemSpawn(ItemSpawnEvent e)
    {
        if (e.getEntity().getItemStack().getType() != Material.CHORUS_FRUIT)
            return;

        if (Core.inst().hasNearCustomBlocks(e.getLocation().getBlock()))
            e.setCancelled(true);
    }
```

`hasNearCustomBlocks` has to check if there is any custom block near the current block, to prevent chorus fruit spawning from blocks.

**Comment by Distolfix** [comment] 2023-06-29 10:12
@LoneDev6 volevo chiederti se fosse disponibile o implementare una funzione di cambio di priorità manualmente oppure se puoi abbassare le priorità. Poichè appunto se dovessi cambiare in MONITOR Drop2Inventory+ alcuni plugin non funzionano correttamente. Te lo chiedo perchè questo bug potrebbe colpire tutti i plugin che appunto hanno una funzione di far finire i drop nell'inventario. ti chiedo se puoi fare dei test abbassando la priorità. Se non è fattibile me ne farò una ragione. Però, se io drop2inventory lo lascio in monitor crea conflitti con altri plugin e non posso tenerlo. Fammi sapere

**Comment by Distolfix** [comment] 2023-06-29 10:18
Per esempio con Drop2Inventory+ su monitor mi inserisce nell'inventario oggetti che non dovrebbe inserire, e così via.. Quindi ti chiedo gentilmente se puoi indagare sotto questo aspetto anche per chi non ha Pufferfish. Poichè appunto, pufferfish non essendo basato su purpur non posso disabbilitare quella impostazione. Chiedo se gentilmente puoi effettuare qualche piccolo test, e se è sicuro ovviamente implementare una diminuzione di priorità oppure renderlo manuale, dove un utente può selezionare la priorità

**Closed** 2023-07-04 16:07 UTC
Labels: type: bug, type: other plugin bug, priority: HIGH, compat: plugin, status: need more info, result: breaks gameplay
