### ISSUE TITLE
Vulcan compatibility

### ISSUE THREAD

**Issue by Mikarim** [PluginBugs/Issues-ItemsAdder#2889] opened 2023-07-20 19:10 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

.mikarim

### What happened?

when I launch my server, this is what appears in the console:

```
[20:46:41 ERROR]: [ItemsAdder] Failed to check Vulcan anticheat compatibility
[20:46:41 WARN]: java.lang.NullPointerException: Cannot invoke "me.frep.vulcan.api.VulcanAPI.getEnabledChecks()" because the return value of "me.frep.vulcan.api.VulcanAPI$Factory.getApi()" is null
[20:46:41 WARN]:        at ItemsAdder_3.5.0c-r2.jar//dev.lone.itemsadder.Core.OtherPlugins.vulcan.VulcanHook.<init>(SourceFile:34)
[20:46:41 WARN]:        at ItemsAdder_3.5.0c-r2.jar//dev.lone.itemsadder.Core.OtherPlugins.vulcan.VulcanHook.register(SourceFile:25)
[20:46:41 WARN]:        at ItemsAdder_3.5.0c-r2.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:438)
[20:46:41 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:46:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372)
[20:46:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550)
[20:46:41 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:630)
[20:46:41 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:544)
[20:46:41 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640)
[20:46:41 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439)
[20:46:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:344)
[20:46:41 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
[20:46:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[20:46:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[20:46:41 WARN]: [ItemsAdder] "ItemsAdder v3.5.0c-r2" has registered a listener for com.destroystokyo.paper.event.inventory.PrepareGrindstoneEvent on method "private void ia.m.fG.a(com.destroystokyo.paper.event.inventory.PrepareGrindstoneEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [LoneDev].
```

can you help me please ? because I searched in the vulcan config and there is no information about compatibility

### Steps to reproduce the issue

1. install vulcan and the other plugins (lonelibs, protocolibs, itemsadder,)

### Server version

1.19.4

### ItemsAdder Version

the lastest

### ProtocolLib Version

the lastest also

### LoneLibs Version

the lastest also

### Screenshots/Videos (you can drag and drop files or paste links)

https://media.discordapp.net/attachments/901798642707484672/1131662333735866490/image.png

**Comment by LoneDev6** [comment] 2023-07-21 07:55
Are you using the latest vulcan anticheat version?
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2693

**Closed by LoneDev6** 2023-07-21 07:55 UTC
Labels: type: bug

**Comment by Mikarim** [comment] 2023-07-21 12:02
yes i have the lastest version
