### ISSUE TITLE
Something is preventing me from deleting maps from mythic dungeon

### ISSUE THREAD

**Issue by chaboon7777** [PluginBugs/Issues-ItemsAdder#3691] opened 2024-06-06 03:52 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

chaboon (discord)

### What happened?

itemsadder is preventing me from deleting mythicdungeon's map folder.
Is there a workaround?
mythicdungeon told me to raise the issue with itemsadder.
Because of this problem my server creates dozens of mapfolders in my absence and I have to delete them manually.
It causes lag and crashes.
Please tell me the solution

### Steps to reproduce the issue

Configure the dungeon in mythic dungeon.
Play a dungeon.
mythicdungeon creates mapfolders and attempts to delete them automatically when the dungeon ends, but sometimes fails to do so.

### Server version

git-Paper-493 (MC: 1.20.4)

### ItemsAdder Version

3.6.4-release-3

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.54

### Full server log

https://mclo.gs/Xuyhd32

### Error (optional)

```shell
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: org.apache.commons.io.IOExceptionList: 1 exception(s): [org.apache.commons.io.IOIndexedException: IOException #3: Cannot delete file: .\dungeon2_1\itemsadder]
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.IOExceptionList.checkEmpty(IOExceptionList.java:49)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.function.IOStream.forAll(IOStream.java:352)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.function.IOStreams.forAll(IOStreams.java:42)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.function.IOStreams.forAll(IOStreams.java:36)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.function.IOConsumer.forAll(IOConsumer.java:80)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:333)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at MythicDungeons-1.4.0.jar//net.playavalon.mythicdungeons.dungeons.Instance.lambda$dispose$3(Instance.java:604)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:842)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: Caused by: org.apache.commons.io.IOIndexedException: IOException #3: Cannot delete file: .\dungeon2_1\itemsadder
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.function.IOStream.lambda$forAll$11(IOStream.java:347)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.function.IOStream.forAll(IOStream.java:338)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	... 12 more
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: Caused by: java.io.IOException: Cannot delete file: .\dungeon2_1\itemsadder
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1340)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.function.IOStream.lambda$forAll$11(IOStream.java:340)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	... 15 more
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: Caused by: java.nio.file.FileSystemException: .\dungeon2_1\itemsadder\region\r.-1.0.pregion: 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:159)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:37)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.PathUtils.visitFileTree(PathUtils.java:1654)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.PathUtils.deleteDirectory(PathUtils.java:517)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:476)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1337)
[08:16:43] [Craft Scheduler Thread - 129 - MythicDungeons/WARN]: 	... 16 more
```

### Other files, you can drag and drop them here to upload. (optional)

Undeleted folders
[dungeon2_0.zip](https://github.com/user-attachments/files/15602641/dungeon2_0.zip)

**Comment by Andre601** [comment] 2024-06-06 20:24
Is MythicDungeons automatically adding and removing worlds from your server? Because that doesn't sound like a good aproach to do here, especially in terms of performance (Creating worlds is resource intensive).
If that is the case, then the problem *could* be ItemsAdder adding its custom World files for custom blocks, and not properly closing them when the world gets deleted. Tho, this could also be an issue with MythicDungeons not unloading the world properly for ItemsAdder to clean up.

Either way, if this issue really only happens with MythicDungeons being enabled is this a compat issue between ItemsAdder and it.

**Comment by LoneDev6** [comment] 2024-06-07 11:59
Duplicate of #3245
I can't reproduce the issue so I can't really fix it if there is no clear way to reproduce it.
In the other issue report you can see all my tests and I can't reproduce the issue.
I still need to get a proper way to reproduce it to find the cause.
All resources are released immediately on world unload.

**Closed by LoneDev6** 2024-06-07 12:00 UTC
Labels: type: bug
