### ISSUE TITLE
Add /iaupdate Command

### ISSUE THREAD

**Issue by xyzjesper** [PluginBugs/Issues-ItemsAdder#4097] opened 2024-11-05 11:41 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

xyzjesper

### Describe the solution you'd like

Add an command with i can update my Funiture and items if i change modeldata etc. and then itemsadder autoupdate all models

### Is your feature request related to a problem?

Yes if i change modeldata i have the problem that ia display other items/models

### Describe alternatives you've considered

i have no alternative!

**Comment by LoneDev6** [comment] 2024-11-22 10:35
Duplicate of #2247

**Closed by LoneDev6** 2024-11-22 10:35 UTC
Labels: type: feature request
