### ISSUE TITLE
Cant custom craft

### ISSUE THREAD

**Issue by EfeBrr** [PluginBugs/Issues-ItemsAdder#2839] opened 2023-07-02 19:09 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

efebrr

### What happened?

when someone tries custom craft, nothing happens and in the console there is a message comming constantly

### Steps to reproduce the issue

```diff
- [Sun 21:51:59 ERROR Minecraft] Could not pass event PrepareItemCraftEvent to ItemsAdder v3.5.0c
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1213)
    at net.minecraft.world.inventory.ContainerWorkbench.a(ContainerWorkbench.java:89)
    at net.minecraft.world.inventory.ContainerWorkbench.lambda$0(ContainerWorkbench.java:100)
    at net.minecraft.world.inventory.ContainerAccess.lambda$0(ContainerAccess.java:61)
    at net.minecraft.world.inventory.ContainerAccess$2.a(ContainerAccess.java:48)
    at net.minecraft.world.inventory.ContainerAccess.a(ContainerAccess.java:60)
    at net.minecraft.world.inventory.ContainerWorkbench.a(ContainerWorkbench.java:99)
    at net.minecraft.world.inventory.InventoryCrafting.splitStack(InventoryCrafting.java:133)
    at net.minecraft.world.inventory.SlotResult.a(SourceFile:66)
    at net.minecraft.world.inventory.Container.lambda$6(Container.java:564)
    at java.base/java.util.Optional.ifPresent(Optional.java:178)
    at net.minecraft.world.inventory.Container.b(Container.java:562)
    at net.minecraft.world.inventory.Container.a(Container.java:366)
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2435)
    at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:55)
    at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:11)
    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
    at net.minecraft.server.TickTask.run(SourceFile:18)
    at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
    at net.mine```

### Server version

This server is running CraftBukkit version 3284a-Spigot-3892929-0ab8487 (MC:1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)


### ItemsAdder Version

ItemsAdder version 3.5.0c

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11931170/latest.log)


### Error (optional)

```shell
- [Sun 21:51:59 ERROR Minecraft] Could not pass event PrepareItemCraftEvent to ItemsAdder v3.5.0c
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1213)
    at net.minecraft.world.inventory.ContainerWorkbench.a(ContainerWorkbench.java:89)
    at net.minecraft.world.inventory.ContainerWorkbench.lambda$0(ContainerWorkbench.java:100)
    at net.minecraft.world.inventory.ContainerAccess.lambda$0(ContainerAccess.java:61)
    at net.minecraft.world.inventory.ContainerAccess$2.a(ContainerAccess.java:48)
    at net.minecraft.world.inventory.ContainerAccess.a(ContainerAccess.java:60)
    at net.minecraft.world.inventory.ContainerWorkbench.a(ContainerWorkbench.java:99)
    at net.minecraft.world.inventory.InventoryCrafting.splitStack(InventoryCrafting.java:133)
    at net.minecraft.world.inventory.SlotResult.a(SourceFile:66)
    at net.minecraft.world.inventory.Container.lambda$6(Container.java:564)
    at java.base/java.util.Optional.ifPresent(Optional.java:178)
    at net.minecraft.world.inventory.Container.b(Container.java:562)
    at net.minecraft.world.inventory.Container.a(Container.java:366)
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2435)
    at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:55)
    at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:11)
    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
    at net.minecraft.server.TickTask.run(SourceFile:18)
    at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
    at net.mine
```

**Comment by LoneDev6** [comment] 2023-07-03 08:15
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2835

This is caused clearly by a broken Spigot installation.
Use Paper.

**Closed by LoneDev6** 2023-07-03 08:15 UTC
Labels: type: bug
