### ISSUE TITLE
"Shapeless Shaped" Recipes (And another small recipe improvement.)

### ISSUE THREAD

**Issue by ItzASecret** [PluginBugs/Issues-ItemsAdder#2600] opened 2023-05-05 01:40 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

ItzASecretBoi#1300

### Describe the solution you'd like

I know the title doesn't make sense, but I didn't really know how to put it.

Basically,  I mean making recipes, but ones similar to the torch. The torch is made stick at bottom, and coal at the top, but you can do that pattern in any slot. Meaning you can make it on the left side of the inventory or the right side, or in any two slots of the crafting table.

If I make it a shaped recipe, I can do it in any slot, but the coal wouldn't have to be on top of the stick, it could just go anywhere.

I know I could just make multiple recipes, but having it done this way would be cool too.

I know previously there was some type of issue where shapeless recipes would probably be bad for server preformance, but it seems you got that solved, so maybe there's room for this?

Also, there was one time I was making a shapeless recipe (Which was a sandwich) 

But you can't put two of the same item in a shapeless recipe, if you put the same ingredient two times, it still only needs one to craft. Obviously, a sandwich needs two bread slices, which I couldn't really do in the shapeless recipe. (Another small thing.)

I just made it a shaped recipe instead, but having that feature for shapeless recipes would be cool too.

### Is your feature request related to a problem?

I made a custom soul torch recipe, but cant make the recipe function how the actual torch recipe works without extra steps.

It's another one of those small features, so it doesn't really matter, just suggesting.

### Describe alternatives you've considered

None

### Additional context

👋🏽

**Comment by LoneDev6** [comment] 2023-05-09 15:56
Seems to be a duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2545

**Closed by LoneDev6** 2023-05-09 15:56 UTC
Labels: type: feature request
