### ISSUE TITLE
Biome decorators (idea Ⅱ)

### ISSUE THREAD

**Issue by Jamaplawer** [PluginBugs/Issues-ItemsAdder#4142] opened 2024-11-16 20:33 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Jamaplawer#0353

### Describe the solution you'd like

If you've read my previous Feature Request, you’ll already be familiar with the concept I’m proposing. This is a second idea related to adding Biome Decorators.

The idea is to enable the replacement of specific blocks with custom ItemsAdder blocks in designated biomes, including those created via data packs.

For example, let’s say I want all the stone blocks in the Plains biome to be replaced with a custom ItemsAdder block. This feature would only affect new chunks, meaning blocks in already-generated chunks remain unchanged.

Another example: I’ve created a custom biome in the Nether, and I’d like to replace all the end stone within that biome with a custom block I’ve designed. The configuration for this would be managed via a .yml file, which might look like this:

info:
  namespace: mypack
biome_decorators:
  custom_block:
    block: mycustomblock
    biome: plains
    replaceable_block:
      block: STONE

### Is your feature request related to a problem?

I need to add custom biomes that have Itemsadder blocks and work on 1.21.
All the plugins are either outdated (or aren't updated to 1.21) or won't work in the end (like Iris)

### Describe alternatives you've considered

World populators, but it can't do it so massively as I need it to do!

### Additional context

This is a simplified version of the same idea I posted a few days ago!
I really hope this gets added :)

**Comment by Andre601** [comment] 2024-11-16 20:36
I feel like it would be better to add to the pre-existing issue, rather than opening a separate one, as it only causes us to track two issues that could easily be tracked in one.

So because of this am I closing this as duplicate of #4124

**Comment by Jamaplawer** [comment] 2024-11-16 20:37
So this feature is not going to be added

**Closed** 2024-11-16 20:36 UTC
Labels: type: duplicate

**Comment by Jamaplawer** [comment] 2024-11-16 20:37
Can I just re-write the first one

**Comment by Andre601** [comment] 2024-11-16 20:38
Just make a comment on the other issue with this info.

**Comment by Jamaplawer** [comment] 2024-11-16 20:39
Ok
BTW do you like this idea/could this idea be useful in itemsadder
