### ISSUE TITLE
Allow for automatic category organization, depending on .yml name.

### ISSUE THREAD

**Issue by ItzASecret** [PluginBugs/Issues-ItemsAdder#2364] opened 2023-02-26 00:07 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

ItzASecretBoi#1300

### Describe the solution you'd like

Not long ago I made about 15-16 armor sets, and to allow players to see them in the IA menu, I have to individually type the helmet, chestplate, pants, and boots of each armor set to put it in the IA menu. 

And yes of course I know, boo hoo poor me, right? I apologize for my laziness, but I feel like this could be a nice config option or something, that would allow for people to take all items in food.yml (for example) and place them in the "Food" category in the IA menu. If yml name is "armor" place all items in "Armor" category. This way, things go smoother, and over create less hassle for anyone creating for a server.

And if I already have my items organized in separate .ymls, why organize them once again in categories file?

And as a person who adds like 1-3 items per day, has organized ymls, and sometimes randomly even creates 10+ items in a day. It would for sure be a welcomed addition in my eyes.

Thanks!

### Is your feature request related to a problem?

It's inconvenient to type every item into the categories, when I already have them perfectly categorized in the .yml files separately.

### Describe alternatives you've considered

Maybe a web converter, that will read .yml file, and convert into a category? Otherwise none.

### Additional context

Thanks for reading, LoneDev!

**Comment by LoneDev6** [comment] 2023-02-28 14:27
I can maybe add a special rule support to make some categories add items into categories based on their name?
For example:
```yml
add_all_by_name:
 -  "*_helmet"
 -  "*_chestplate"
 -  "*_leggings"
 -  "*_boots"
```
I don't know..

**Comment by ItzASecret** [comment] 2023-02-28 18:58
> I can maybe add a special rule support to make some categories add items into categories based on their name?

This would work aswell, I'd probably end up having to rename a lot of my items I've already created, but for convenience sake it would be worth it.

Either way, it was just a suggestion, no sweat if you can or can not add it.

**Comment by LoneDev6** [comment] 2023-04-06 13:41
Duplicate of: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2467

**Closed by LoneDev6** 2023-04-06 13:41 UTC
Labels: type: enhancement, type: feature request
