### ISSUE TITLE
Error after /iazip (ItemsAdderLoadDataEvent)

### ISSUE THREAD

**Issue by Weyl1** [PluginBugs/Issues-ItemsAdder#2746] opened 2023-06-16 10:21 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I have an error message in the console, I don't know how to fix it.

### Steps to reproduce the issue

/iazip
and check console

### Server version

git-Purpur-1995 (MC: 1.20.1)*

### ItemsAdder Version

3.5.0

### ProtocolLib Version

5.1.0-SNAPSHOT- 652

### LoneLibs Version

1.0.25

### Error (optional)

(https://pastebin.com/jsMQBW2S)

**Comment by LoneDev6** [comment] 2023-06-16 12:52
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2739

Please next time check if there is an identical issue report.
Thanks.

**Closed by LoneDev6** 2023-06-16 12:52 UTC
Labels: type: bug
