### ISSUE TITLE
Permission problem to prevent break a block/minerai...

### ISSUE THREAD

**Issue by Talinsodark** [PluginBugs/Issues-ItemsAdder#2529] opened 2023-04-12 11:20 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Hello, since 3 days I'm looking for how to add a permission that allows to break a new Ore, but after several searches on all pages no info...
I would like the players to unlock a mineral (a permission to break) every x level but since there is no command to block the break block I can't do it...

### Steps to reproduce the issue

start the server

### Server version

Paper 1.19.2

### ItemsAdder Version

ItemsAdder version 3.4.1-r5

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.24

### Error (optional)

```shell
not errors
```

**Comment by LoneDev6** [comment] 2023-04-12 15:15
Hello, this is not a bug report, but a feature request.

Currently there is no permission for breaking blocks.
I can add it in the future if you need.

Anyway for a more vanilla experience you should set a whitelist of tools for blocks, so your players would need some particular tools to break some special blocks.
So you can make these tools require a permission to be crafted.

Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/1145

**Closed by LoneDev6** 2023-04-12 15:15 UTC
Labels: type: bug
