### ISSUE TITLE
ItemsAdder - optimization

### ISSUE THREAD

**Issue by daniel-skopek** [PluginBugs/Issues-ItemsAdder#3517] opened 2024-03-24 14:01 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

ItemsAdder takes 3,94% of the server's performance

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/117641078/5c37aa1b-034d-463d-a760-0f293167102e)

Spark: https://spark.lucko.me/JkumBByh36

Is it possible to optimize it? For example adding support for PacketEvents instead of ProtocolLib.

### Steps to reproduce the issue

Run ItemsAdder

### ItemsAdder Version

v3.6.3-beta-13

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

**Comment by LoneDev6** [comment] 2024-04-04 14:18
Seems to be a duplicate of: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3534

**Closed by LoneDev6** 2024-04-04 14:18 UTC
Labels: type: bug
