### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Distolfix** [PluginBugs/Issues-ItemsAdder#2878] opened 2023-07-14 13:37 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

https://pastebin.com/pHQXiR3n

### Steps to reproduce the issue

no

### Server version

1.19.4

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/73421268/31fcf897-6e36-4b80-bff0-e0fe03557dd1)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/73421268/6b4312ef-6aeb-488b-b4a9-3790a7608da9)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/73421268/a11cf256-98e2-4242-a70c-ab247cabfd3d)

**Comment by LoneDev6** [comment] 2023-07-17 09:17
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2847
Will be fixed

**Closed by LoneDev6** 2023-07-17 09:17 UTC
Labels: type: bug
