### ISSUE TITLE
Stuck on "Joining World" when no-host is enabled

### ISSUE THREAD

**Issue by GamefactsIG** [PluginBugs/Issues-ItemsAdder#3428] opened 2024-02-14 12:52 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

xbakeem

### What happened?

When using a clean instal of ItemsAdder, Procollib and Lonelibs, putting No-host on enabled and the resource pack URL in server.properties, the player that tries to join is stuck in an endless "Joining world" screen OR a "reconfiguring" screen if through a proxy

How do I know this is a itemsadder issue?
1> I've removed all plugins but ItemsAdder and dep. and issue still persists,
2> I've removed ItemsAdder and issue resolves
3> I've changed resourcepack + resourcepack hosting site WITH itemsadder on, issue persists
4> I've turned on Self-host and issue is solved

### Steps to reproduce the issue

1. Enable no-host
2. Put resource pack in server.properties
3. Try to join server

### Server version

This server is running Paper version git-Paper-409 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9e171ef)
You are 14 version(s) behind

### ItemsAdder Version

[12:47:56 INFO]: ItemsAdder version 3.6.3-beta-12
[12:47:56 INFO]: Customized Minecraft without client mods!
[12:47:56 INFO]: Website: devs.beer
[12:47:56 INFO]: Author: LoneDev

### ProtocolLib Version

[12:48:10 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[12:48:10 INFO]: Provides read/write access to the Minecraft protocol.
[12:48:10 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[12:48:20 INFO]: LoneLibs version 1.0.45
[12:48:20 INFO]: Collection of libs used by my plugins
[12:48:20 INFO]: Authors: LoneDev and others

### FULL server log

SERVER LOGS:
https://mclo.gs/ztLeL3W

CLIENT LOGS:
https://mclo.gs/fjpFqW9

### Problematic items yml configuration file (optional)

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
ignore-server-compatibility-check: false
resource-pack:
  hosting:
    no-host:
      enabled: true
    lobfile:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  1_19_3_atlas_support: true
  fix_force_unicode_font_images: true
  expert_users:
    allow_other_plugins_resourcepacks: false
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: true
    contents-folders-priority:
    - vanilla
    - _iainternal
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  custom_blocks_sounds_patch:
    enabled: true
    step:
      enabled: true
      allow_non_player: true
    other: true
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire_enhancements:
    enable: true
    unlit_on_place: true
    allow_any_item: true
    drop_when_broken: false
  disable-REAL: false
  disable-REAL_NOTE: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  convert-legacy-ia-region-files: true
  remove-unused-palettes-on-region-save: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: true
  show_item_durability:
    in_ia_menu: true
    in_inventory: false
  handle-wear-held-actions-on-unexpected-inventory-changes: true
  fix_trades_guis_match_custom_items:
    itemsadder_trade_machines: true
    vanilla_villagers: false
    other_plugins: true
liquids:
  enabled: true
huds:
  enabled: true
  force_color:
    enabled: false
    color: '#FFFFFF'
  hide_if_pack_not_accepted: true
cooldown_bars:
  enabled: true
  refresh_ticks: 1
  bossbar:
    color: WHITE
    style: SOLID
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    add-hover-suggestion: true
    tab-autocompletion_1_19_1_plus: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
effects:
  hide-scoreboard-numbers: false
  hide-scoreboard-numbers-old-clients: false
  text-effects:
    enabled: true
    customitem-name-and-lore:
      enabled: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    expert_users:
      fast_packets_creation: true
      bundle_packets: false
      delay_packets: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: true
        ingredients: true
      on-item-click:
        any: true
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
player_stats:
  save_type: CUSTOM_NBT # CUSTOM_NBT, PLAYER_DAT
debug:
  benchmark: false
  items:
    log-files-loading: false
    log-files-reloading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

### Other files, you can drag and drop them here to upload. (optional)

https://youtu.be/h5QNN8vFcbM

**Comment by LoneDev6** [comment] 2024-02-14 14:51
I will do some testing, but may I ask why are you putting the resourcepack url in the server.properties instead of using the ItemsAdder configuration and setting external-host?

**Comment by GamefactsIG** [comment] 2024-02-14 14:52
Yes,

I am using mine hut for an external server and this is the only way to
bypass mine hut blocking resource packs


Op wo 14 feb 2024 om 15:51 schreef LoneDev ***@***.***>

**Comment by LoneDev6** [comment] 2024-02-15 11:39
why are you using an hosting service which is blocking resourcepacks?
This doesn't sound like a very good hosting service, i'd move elsewhere.

**Comment by GamefactsIG** [comment] 2024-02-15 11:42
It’s not my main host it's to bring in extra players, they join through a
separate proxy

Op do 15 feb 2024 om 12:39 schreef LoneDev ***@***.***>

**Comment by LoneDev6** [comment] 2024-02-20 13:36
Fixed in the upcoming update, the cause is unclear but I managed to mitigate it with a workaround.
Basically the client doesn't receive the `ClientboundFinishConfigurationPacket` packet when no-host is enabled.

**Closed** 2024-02-20 14:13 UTC
Labels: type: bug, verdict: workaround implemented
