### ISSUE TITLE
Display Mythicmobs customentity name

### ISSUE THREAD

**Issue by jeffry1829** [PluginBugs/Issues-ItemsAdder#1839] opened 2022-07-10 18:42 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

jeffry1829#0568

### Describe the solution you'd like

Add an option not to hide Mythicmobs display name if we use
```
Skills:
- customentity{model=mobs:sandmite} @self ~onSpawn
```

### Is your feature request related to a problem?

Mythicmobs customentity name is invisible.

### Describe alternatives you've considered

Can't find alternatives.

**Comment by LoneDev6** [comment] 2023-01-18 10:54
Sorry I don't understand.
Is the entity name tag visible or not?
Do you want to hide it or show it?


It's not clear

**Comment by LoneDev6** [comment] 2023-05-18 19:49
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/1613

**Closed by LoneDev6** 2023-05-18 19:49 UTC
Labels: type: duplicate
