### ISSUE TITLE
Error: Failed to Load 

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#2697] opened 2023-06-04 16:50 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Updated Itemsadder and ran iazip

Dont even use player animation feature

### Steps to reproduce the issue

1.install latest itemsadder and run iazip

### Server version

[12:46:43 INFO]: This server is running Paper version git-Paper-530 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9daa019)
You are 15 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-526 (MC: 1.19.4)

### ItemsAdder Version

[12:46:25 INFO]: ItemsAdder version 3.4.1e
[12:46:25 INFO]: Customized Minecraft without client mods!
[12:46:25 INFO]: Website: devs.beer
[12:46:25 INFO]: Author: LoneDev

### ProtocolLib Version

[12:45:50 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-644
[12:45:50 INFO]: Provides read/write access to the Minecraft protocol.
[12:45:50 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[12:45:05 INFO]: LoneLibs version 1.0.24
[12:45:05 INFO]: Collection of libs used by my plugins
[12:45:05 INFO]: Authors: LoneDev and others

### FULL server log

Nothing else in server log accept for the error below

### Error (optional)

```shell
[12:41:53 ERROR]: [ItemsAdder] Failed to load: iainternal:player
[12:41:53 WARN]: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[12:41:53 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[12:41:53 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[12:41:53 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[12:41:53 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:361)
[12:41:53 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[12:41:53 WARN]:        at ItemsAdder_3.4.1e.jar//ia.m.G.a(SourceFile:2920)
[12:41:53 WARN]:        at ItemsAdder_3.4.1e.jar//ia.m.ak.a(SourceFile:109)
[12:41:53 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[12:41:53 WARN]:        at ItemsAdder_3.4.1e.jar//ia.m.ak.b(SourceFile:71)
[12:41:53 WARN]:        at ItemsAdder_3.4.1e.jar//ia.m.V.a(SourceFile:185)
[12:41:53 WARN]:        at ItemsAdder_3.4.1e.jar//ia.m.V.u(SourceFile:319)
[12:41:53 WARN]:        at ItemsAdder_3.4.1e.jar//ia.m.G.a(SourceFile:2323)
[12:41:53 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[12:41:53 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[12:41:53 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:41:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:41:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:41:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:41:53 ERROR]: [ItemsAdder] Failed to read player animation data. player model is null.
```

**Comment by LoneDev6** [comment] 2023-06-05 08:50
I wonder why you keep not using the search button even after years being part of the community.
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2666

**Closed by LoneDev6** 2023-06-05 08:50 UTC
Labels: type: bug
