### ISSUE TITLE
The sound of the basic note block cannot be changed

### ISSUE THREAD

**Issue by StarYunmeng** [PluginBugs/Issues-ItemsAdder#2105] opened 2022-11-20 17:03 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

#note block

### What happened?

The lower block cannot change the sound of the note block,The note block can only play one sound

### Steps to reproduce the issue

Install plug-ins - enter the game - place different blocks - place note blocks above them - click on note blocks - sample note blocks make a sound

### Server version

git-Paper-142 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ef0e5a6)

### ItemsAdder Version

 ItemsAdder version 3.2.5-r3

### ProtocolLib Version

 ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

 LoneLibs version 1.0.21

**Comment by StarYunmeng** [comment] 2022-11-20 17:17
https://user-images.githubusercontent.com/39673949/202916058-057568c4-1004-4469-9144-9b907bf0eae5.mp4

**Comment by StarYunmeng** [comment] 2022-11-21 14:07
![world_](https://user-images.githubusercontent.com/39673949/203074898-7eaf76b4-43c5-49df-b726-3c63b979f451.png)
This is also a problem

**Comment by LoneDev6** [comment] 2022-11-22 15:53
Noteblock issue will be fixed.

> This is also a problem

This is not a bug, it's a normal behaviour if you enabled REAL_TRANSPARENT.
Disable it in config.yml and regenerate the end world.
`disable-REAL_TRANSPARENT: true`.
This is mandatory to create custom blocks of type REAL_TRANSPARENT, there is no solution other than that.

**Closed** 2022-11-22 16:52 UTC
Labels: Bug
