### ISSUE TITLE
Error on start & Invalid paths on Windows

### ISSUE THREAD

**Issue by envizar** [PluginBugs/Issues-ItemsAdder#3264] opened 2023-12-29 11:38 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Error on start

### Steps to reproduce the issue

Just start server with latest IA
If you want to reproduce MISSING FILE PROPERTY errors, start server on Windows

### Server version

This server is running Paper version git-Paper-361 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 5e978d3)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-3

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.42

### FULL server log

https://mcpaste.io/dad108def53c8100

**Comment by AsleeppMC** [comment] 2023-12-29 23:47
Happening to me too.

**Comment by envizar** [comment] 2023-12-30 08:58
Looks like it's two issues, not one
```
[11:54:48 ERROR]: [ItemsAdder] Error initializing plugin 'ItemsAdder_3.6.3-beta-3.jar' in folder 'plugins' (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.getDataFolder()" because "<parameter1>" is null
        at ia.m.qY.<init>(SourceFile:118) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at ia.m.qY.<init>(SourceFile:78) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at ia.m.qY.<init>(SourceFile:68) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at ia.m.P.m(SourceFile:601) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at ia.m.O.m(SourceFile:436) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at dev.lone.itemsadder.Main.bN(SourceFile:592) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at dev.lone.itemsadder.Main.onLoad(SourceFile:180) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:833)      
```
This error without "MISSING FILE PROPERTY" appeared when I started server on Ubuntu

LoneDev needs to:
- Make paths like `plugins\ItemsAdder\lang/en.yml` just support Windows
- Fix `"<parameter1>" is null` error

**Comment by EagL3-GIT** [comment] 2023-12-30 15:29
+1, same error for me

**Comment by LoneDev6** [comment] 2023-12-30 17:35
Duplicate of #3253

**Closed by LoneDev6** 2023-12-30 17:35 UTC
Labels: type: bug
