### ISSUE TITLE
Custom fonts doesn't work with the last version of itemsadder

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#2135] opened 2022-11-25 16:27 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

SLoKer#5953

### What happened?

Custom fonts doesn't work with the last version of itemsadder 

### Steps to reproduce the issue

just updated my server from = 3.2.5-r3 to 3.3.0-beta-r8 , and the problem happened

### Server version

![image](https://user-images.githubusercontent.com/68678154/204025056-addbcbaa-3288-46ba-85bc-55f02032ae4b.png)

### ItemsAdder Version

3.3.0-beta-r8 

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/68678154/204025141-de503718-e9f8-4865-b34d-6efdd7cb5ce2.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/68678154/204025201-b64d509a-df9b-4dd6-987b-c49a933f48d0.png)

**Comment by DexterSK** [comment] 2022-11-26 09:04
same problem

**Comment by LoneDev6** [comment] 2022-11-28 13:34
Update to `r9` and test, reported issues were fixed in this update and this could also have been fixed too.

**Comment by LoneDev6** [comment] 2022-11-28 14:00
> Custom fonts doesn't work with the last version of itemsadder

**Comment by LoneDev6** [comment] 2022-11-29 15:50
it probably is due to the font file name, use lowercase characters only.

**Comment by LoneDev6** [comment] 2022-11-29 16:54
> if you tried this old version `3.2.5-r3` it's gonna work with you

Do you still have an OLD generated zip from 3.2.5? Please send here the default.json font file.

**Comment by LoneDev6** [comment] 2022-11-29 17:00
Np I found the cause

**Closed** 2022-11-30 16:55 UTC
Labels: Bug
