### ISSUE TITLE
bundle_packets - custom entity not teleporting, only shadow

### ISSUE THREAD

**Issue by PlayerSchark** [PluginBugs/Issues-ItemsAdder#3726] opened 2024-06-11 10:22 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Research found that if you set `entities.custom-entitites.expert_users.bundle_packets` to `true` several rendering issues occur.
The custom entity is not moving, only the shadow (falling block).
Seems the entity bones are not moving, they are correctly rotating but not moving.

### Steps to reproduce the issue

see mentioned issues

### Server version

Paper version 1.20.6-138-master@906df69

### ItemsAdder Version

ItemsAdder version 4.0.1-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-713

### LoneLibs Version

LoneLibs version 1.0.54

### Error (optional)

```shell
see mentioned issues
```

**Comment by LoneDev6** [comment] 2024-06-13 12:21
Duplicate of #3721

**Closed by LoneDev6** 2024-06-13 12:21 UTC
Labels: type: bug
