### ISSUE TITLE
Error with minecraft:update_attributes

### ISSUE THREAD

**Issue by billynational** [PluginBugs/Issues-ItemsAdder#3736] opened 2024-06-14 21:06 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Billymn

### What happened?

WHen using the latest dependencies and version of itemsadder, i recieve two errors:

Error sending packet clientbound/minecraft:update_attributes (skippable? false)

 As well as,

Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:update_atributes'

I assume they are linked, and i cannot find a solution anywhere.

### Steps to reproduce the issue

Cannot reproduce as no clue to cause.

### Server version

Paper version 1.20.6-138-master@906df69 (2024-06-10T06:32:15Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.1-alpha-test-4

### ProtocolLib Version

5.3.0-SNAPSHOT-720

### LoneLibs Version

1.0.54

### Full server log

https://pastebin.com/cHedHXfY

### Error (optional)

```shell
Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:update_atributes'
```

**Comment by Andre601** [comment] 2024-06-14 21:32
Duplicate of #3708

**Please check issues first before creating one!**

**Closed by Andre601** 2024-06-14 21:32 UTC
Labels: type: bug
