### ISSUE TITLE
Guns complete overhaul and enhancements

### ISSUE THREAD

**Issue by Bobbyharron** [PluginBugs/Issues-ItemsAdder#2311] opened 2023-01-31 15:45 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

bobby_harron#7548

### Describe the solution you'd like

make the gun behaviour have different reload speed, damage and range.

the gun behaviour right now is as empty and simple as it was back in 2020. I cant make custom weapons with itemsadder because the gun behaviour just works a semiautomatic pistol, you cannot make snipers since the range is too low, you cannot make weapons like muskets or any low reload weapon because theres no feature. And also having the ammo item in the offhand to reload is a bit akward.

Adding these features to the gun behaviour will open a lot of opportunities to make custom weapons (or else taking in mind that the ia community does crazy things with any feature).

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

The only alternative is to use another plugin, ive looked every thread and comment in discord about this and theres no solution.

**Comment by SirCraftypants** [comment] 2023-01-31 16:47
Would be cool to be able to limit a custom weapon to only be able to use a specific custom ammo, maybe some kind of nbt check when fired. 

I believe you can already set the damage and range of a custom bow or crossbow.
An arrow naturally has no range due to the custom weapon controlling the range but the arrow damage can be set.

Here's a few examples

Custom Weapon https://paste.helpch.at/gibavozito.yaml

Custom Arrow https://paste.helpch.at/ojewamuyol.yaml

Reload Speed i think isn't possible at present, however it would be cool to have an ammo type limit.

**Comment by LoneDev6** [comment] 2023-02-28 14:43
Another related suggestion: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1443

**Comment by ItzASecret** [comment] 2023-03-27 21:00
I know this isn't a gun plugin, so such detailed features aren't necessary, But I love guns, and a revamp would be awesome so I'm gonna idea dump here anyways!
 
 1. Seeing Live Ammunition Mid-Air!
 
 It would be cool if we could see the ammo type flying through the air, similar to when you are throwing snowballs, or an egg. It would be pretty nice/immersive if you could literally see the ammunition flying towards you before you take massive damage. Maybe make this toggleable though, because this would look good with say, a musket bullet, which is circular and evenly shaped, but a modern ammo type would probably look goofy as a PNG flying through the air. 
 
 
2. Ricochet Physics! 

This idea is very extra, but it would be pretty cool to have ricochet physics as well. I remember when I first installed this plugin and I shot a gun at a window and the window actually broke, I thought it was so cool, this would be a similar thing where its small, but a good detail. Bullets would obviously only ricochet off iron blocks, iron ore etc, possibly stone. Or maybe make it configurable.

3. Gun Recoil/Knockback!

Some guns are heavy, and all guns have recoil whether small or large, so this would be a cool idea too!
This would be done be being able to set the knockback a player receives per ammunition being launched. This way if the player shoots 1 bullet, he gets pushed slightly backwards as well, this would add that recoil effect games have. And maybe if the player has a more explosive weapon, he would get sent 2-3 blocks backwards, which would be set in the explosive weapons config, something like. "knockback: 3"

We should also be able to set how much knockback the weapon causes to the player getting damaged.


 
 Note: This idea is REALLY extra, but maybe allow us to see ammo casings hitting the floor when players are shooting the gun based item, another small detail that would spice up how gunplay looks. This could be done a couple of ways, and should be toggleable, because something like a flintknock pistol, wouldn't drop a casing.
 
 1. By showing the breaking particles of the ammo type, this is already done for itemsadder items that are throwable, the broken up versions of that texture are shown on impact.  (Vanilla Example: Broken egg particles that show when throwing the egg.)
 
 2. Being able to set a custom texture for the empty casing, which will just drop to the floor, break, and disappear beside the player while shooting his weapon.
 
 If you actually read all this, sorry/thanks lol.

**Comment by LoneDev6** [comment] 2023-03-30 11:07
I agree weapons require a total rewrite to be more realistic and to offer more variety in both their behaviours and usages.
I hope to find the time as soon as possible because right now there are A LOT of scheduled requests.

**Comment by LoneDev6** [comment] 2023-04-07 15:39
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/1107

**Closed by LoneDev6** 2023-04-07 15:39 UTC
Labels: type: enhancement, type: feature request
