### ISSUE TITLE
NoSuchMethodError: 'org.bukkit.block.Block org.bukkit.entity.Player.getTargetBlock(int)'

### ISSUE THREAD

**Issue by Micky117** [PluginBugs/Issues-ItemsAdder#3362] opened 2024-01-22 20:02 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Recently the plugin spams a series of errors in my console, but this one works fine, for now I will leave the error that it is spammed too much in my console.

### Steps to reproduce the issue

I don't know if it's because of ArcLight but the only thing I've done is put my texturepack

### Server version

This server is running Arclight version arclight-1.20.1-1.0.3-ec79af9 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-9

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### LoneLibs Version

 LoneLibs version 1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14014825/latest.log)

### Error (optional)

```shell
[22Jan2024 19:44:01.323] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to ItemsAdder v3.6.3-beta-9
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight-1.20.1-1.0.3-ec79af9.jar%23174!/:arclight-1.20.1-1.0.3-ec79af9] {re:mixin,re:classloading}
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight-1.20.1-1.0.3-ec79af9.jar%23174!/:arclight-1.20.1-1.0.3-ec79af9] {re:mixin,re:classloading,re:mixin}
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight-1.20.1-1.0.3-ec79af9.jar%23174!/:arclight-1.20.1-1.0.3-ec79af9] {re:mixin,re:classloading,re:mixin}
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactoryMixin.java:566) ~[arclight-1.20.1-1.0.3-ec79af9.jar%23174!/:arclight-1.20.1-1.0.3-ec79af9] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactoryMixin.java:528) ~[arclight-1.20.1-1.0.3-ec79af9.jar%23174!/:arclight-1.20.1-1.0.3-ec79af9] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactoryMixin.java:524) ~[arclight-1.20.1-1.0.3-ec79af9.jar%23174!/:arclight-1.20.1-1.0.3-ec79af9] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7953_(ServerPlayNetHandlerMixin.java:3007) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundSwingPacket.m_5797_(ServerboundSwingPacket.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.game.ServerboundSwingPacket.m_5797_(ServerboundSwingPacket.java:7) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.PacketUtils.md8de8fa$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.protocol.PacketThreadUtilMixin,pl:mixin:A}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.block.Block org.bukkit.entity.Player.getTargetBlock(int)'
	at ia.m.sa.e(SourceFile:184) ~[?:?] {}
	at ia.m.cK.a(SourceFile:325) ~[?:?] {}
	... 23 more
```

**Comment by LoneDev6** [comment] 2024-01-23 12:24
You're using Forge which is not officially supported by ItemsAdder and by any other Spigot plugin, because plugins are made for Spigot not Forge.
You have to contact Arclight team and ask them to add this Spigot method, because I have no idea why they didn't implement it as it should have it.
`org.bukkit.block.Block org.bukkit.entity.Player.getTargetBlock(int)'`

**Comment by Micky117** [comment] 2024-01-23 14:08
Oh, I understand, thank you very much and if they changed me to the Mohist API, would these types of errors stop happening?

**Comment by LoneDev6** [comment] 2024-01-23 16:23
Nvm, seems that this method is [Paper only](https://github.com/uplol/Paper/blob/9fd76fa387cc901db60c3668e3cb050b1274e666/Spigot-API-Patches/0145-Add-ray-tracing-methods-to-LivingEntity.patch#L83), so it's an issue which all Spigot builds have.
I will fix that in the next update, thanks for the report!

**Comment by Micky117** [comment] 2024-01-23 19:01
Great, I'll be waiting for you and finally, what could be causing this error?

https://pastebin.com/PH60YnQC

**Comment by LoneDev6** [comment] 2024-01-24 12:34
Seems to be a duplicate of this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3364

**Closed** 2024-01-31 21:02 UTC
Labels: type: bug, type: paper bug

**Comment by Micky117** [comment] 2024-02-05 00:47
Hello, I hope you are well, I actually don't know if I should open a new discussion or this one, but both the error above and a new one have been spamming my console and I would like to know how to fix it. Thank you
https://pastebin.com/jDiDd3WX
