### ISSUE TITLE
Slimefun lore compatibility.

### ISSUE THREAD

**Issue by RexTempestas** [PluginBugs/Issues-ItemsAdder#2598] opened 2023-05-04 04:33 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Rex_Tempestas#0399

### Describe the solution you'd like

Hi, I am very grateful for fix the graphic bug with the lore in the last beta, but I use Slimefun and when you enchant something in the autoenchanter the damage lore doesn't update, I don't know if this is a bug, but I think's not. In that case, is possible to add some compatibility between Slimefun autoenchanter and custom items stats of ItemsAdder?

Thank you.

### Is your feature request related to a problem?

If someone use SlimeFun, this is a problem.

### Describe alternatives you've considered

Nothing.

**Comment by LoneDev6** [comment] 2023-05-04 07:07
It's not a bug. ItemsAdder can detect only vanilla enchant events to update the lore.
I'll have to check if I can hook into Slimefun to detect custom enchant events and update the lore.
Will be checked in the future.

**Closed** 2023-11-13 20:56 UTC
Labels: type: feature request, compat: plugin
