### ISSUE TITLE
Custom Model Not Loading on Citizens NPC After Update 3.6.2d-beta-2

### ISSUE THREAD

**Issue by Jeremylo1** [PluginBugs/Issues-ItemsAdder#3231] opened 2023-12-22 03:48 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Jeremylo1

### What happened?

Attempting to set a custom model on a Citizens NPC using the command `/iaentity citizens <ID> model <name>` results in an internal error.

### Steps to reproduce the issue

1) /npc create test --type IRON_GOLEM
2) /iaentity citizens 20 model crate_machine:crate_machine
3) The NPC disappears/becomes invisible and the error is displayed in the chat and on the console
4) Resstart server and NPC becomes visible but without custom model

### Server version

Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
Previous version: git-Paper-194 (MC: 1.20.1)

### ItemsAdder Version

ItemsAdder version 3.6.2d-beta-2

### ProtocolLib Version

LoneLibs version 1.0.40

### LoneLibs Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### Error (optional)

```shell
[04:29:34 INFO]: Jeremylo1 issued server command: /npc create test --type IRON_GOLEM
[04:29:48 INFO]: Jeremylo1 issued server command: /iaentity citizens 20 model crate_machine:crate_machine
[04:29:48 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iaentity' in plugin ItemsAdder v3.6.2d-beta-2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.2.jar:git-Paper-318]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2208) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2168) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1410) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getConstructor(java.lang.Class[])" because "<parameter1>" is null
        at ia.m.iS.b(SourceFile:478) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at ia.m.iN.a(SourceFile:125) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at ia.m.ka.a(SourceFile:20) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at ia.m.X.D(SourceFile:280) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at ia.m.X.a(SourceFile:258) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at ia.m.X.a(SourceFile:183) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at ia.m.X.a(SourceFile:178) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at ia.m.U.a(SourceFile:756) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at ia.m.U.a(SourceFile:729) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at dev.lone.itemsadder.Core.OtherPlugins.Citizens.CustomEntityTrait.attachNewPlayerRenderer(SourceFile:217) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at dev.lone.itemsadder.Core.OtherPlugins.Citizens.CustomEntityTrait.initRenderer(SourceFile:212) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at dev.lone.itemsadder.Core.OtherPlugins.Citizens.CustomEntityTrait.applyModel(SourceFile:129) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at ia.m.hQ.onCommand(SourceFile:98) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more
version
[04:48:52 INFO]: Jeremylo1 lost connection: Disconnected
[04:48:52 INFO]: Jeremylo1 left the game
[04:48:56 INFO]: UUID of player Jeremylo1 is 8b8ba53f-47db-4406-b6ed-1af9d1d62ac7
[04:48:56 WARN]: [BetonQuest] Loaded 'officialQuests.loginfirsttime' objective from the database, but it is not defined in configuration. Skipping.
[04:48:56 WARN]: [BetonQuest] Loaded 'officialQuests.ObjTest1' objective from the database, but it is not defined in configuration. Skipping.
[04:48:56 INFO]: Jeremylo1 joined the game
[04:48:56 INFO]: Jeremylo1[/76.67.210.195:38590] logged in with entity id 11526 at ([world]-175.08034259049543, 74.0, 17.282082104628877)
[04:48:56 ERROR]: [Citizens] An exception occurred while the trait customentity was spawning for NPC ID 20.
[04:48:56 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getConstructor(java.lang.Class[])" because "<parameter1>" is null
[04:48:56 WARN]:        at ItemsAdder_3.6.2d-beta-2.jar//ia.m.iS.b(SourceFile:478)
[04:48:56 WARN]:        at ItemsAdder_3.6.2d-beta-2.jar//ia.m.iN.a(SourceFile:125)
[04:48:56 WARN]:        at ItemsAdder_3.6.2d-beta-2.jar//ia.m.ka.a(SourceFile:20)
[04:48:56 WARN]:        at ItemsAdder_3.6.2d-beta-2.jar//ia.m.X.D(SourceFile:280)
[04:48:56 WARN]:        at ItemsAdder_3.6.2d-beta-2.jar//ia.m.X.a(SourceFile:258)
[04:48:56 WARN]:        at ItemsAdder_3.6.2d-beta-2.jar//ia.m.X.a(SourceFile:183)
[04:48:56 WARN]:        at ItemsAdder_3.6.2d-beta-2.jar//ia.m.X.a(SourceFile:178)
[04:48:56 WARN]:        at ItemsAdder_3.6.2d-beta-2.jar//ia.m.U.a(SourceFile:756)
[04:48:56 WARN]:        at ItemsAdder_3.6.2d-beta-2.jar//ia.m.U.a(SourceFile:729)
[04:48:56 WARN]:        at ItemsAdder_3.6.2d-beta-2.jar//dev.lone.itemsadder.Core.OtherPlugins.Citizens.CustomEntityTrait.attachNewPlayerRenderer(SourceFile:217)
[04:48:56 WARN]:        at ItemsAdder_3.6.2d-beta-2.jar//dev.lone.itemsadder.Core.OtherPlugins.Citizens.CustomEntityTrait.initRenderer(SourceFile:212)
[04:48:56 WARN]:        at ItemsAdder_3.6.2d-beta-2.jar//dev.lone.itemsadder.Core.OtherPlugins.Citizens.CustomEntityTrait.onSpawn(SourceFile:72)
[04:48:56 WARN]:        at Citizens-2.0.33.jar//net.citizensnpcs.npc.CitizensNPC$1.accept(CitizensNPC.java:374)
[04:48:56 WARN]:        at Citizens-2.0.33.jar//net.citizensnpcs.npc.CitizensNPC$1.accept(CitizensNPC.java:341)
[04:48:56 WARN]:        at Citizens-2.0.33.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:417)
[04:48:56 WARN]:        at Citizens-2.0.33.jar//net.citizensnpcs.EventListen.spawn(EventListen.java:872)
[04:48:56 WARN]:        at Citizens-2.0.33.jar//net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:853)
[04:48:56 WARN]:        at Citizens-2.0.33.jar//net.citizensnpcs.EventListen.lambda$loadNPCs$0(EventListen.java:210)
[04:48:56 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[04:48:56 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[04:48:56 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1470)
[04:48:56 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[04:48:56 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1379)
[04:48:56 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[04:48:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[04:48:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: crate_machine
entities:
  crate_machine:
    display_name: "Machine"
    type: IRON_GOLEM
    model_folder: entity/crate_machine
    silent: true
    can_sun_burn: false
    speed:
      movement: 0.3
      flying: 0
    max_health: 60
```

### Other files, you can drag and drop them here to upload. (optional)

Citizens version 2.0.33-SNAPSHOT (build 3277)

### Screenshots/Videos (you can drag and drop files or paste links)

![Vidéo sans titre ‐ Réalisée avec Clipchamp](https://github.com/PluginBugs/Issues-ItemsAdder/assets/11772547/964ad007-8c06-41ce-821d-a1fdf23529b5)

**Comment by LoneDev6** [comment] 2023-12-24 17:28
Duplicate of #3232
Will be fixed in the upcoming update.

**Closed by LoneDev6** 2023-12-24 17:28 UTC
Labels: type: bug
