### ISSUE TITLE
v4 - Legacy armors ItemStacks from 1.20.4 break quickly - durability conversion issue

### ISSUE THREAD

**Issue by sennby** [PluginBugs/Issues-ItemsAdder#4039] opened 2024-09-30 14:37 UTC
### Discord Username (optional)

senby8

### What happened?

Firstly, I am not 100% sure this is directly from IA, but i know this issue happened in the past with AE/IA and the two talked and then an update came out and it was fixed for me in the past. Basically all of my custom gear lost its custom durability when i upgraded to 1.21, so all my gear is breaking quickly now which is a problem.
https://gyazo.com/d9243647928bdf7bf269d914a9457b4a here is a quick clip of it happening. I also told AE this as the gear has custom enchants on it as well im reporting to both sides, but IA handles the custom durability.

### Steps to reproduce the issue

I was on the latest 1.20.4 build then i updated to the latest 1.21 build.
Put armor on that existed in the game already such as gear a player was wearing.
that gear will break extremely fast.

### Server version

1.21 

### ItemsAdder Version

[14:34:54 INFO]: This server is running Paper version 1.21.1-112-master@e3c8a8e (2024-09-29T21:33:03Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ProtocolLib Version

version protocollib
[14:35:10 INFO]: ProtocolLib version 5.2.0

### LoneLibs Version

 LoneLibs version 1.0.59
[14:36:00 INFO]: Collection of libs used by my plugins
[14:36:00 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/olPUtSB

**Comment by sennby** [comment] 2024-09-30 17:08
Here is a paper dumpitem on one of the items:
https://mclo.gs/qdtpole The leggings have custom durability with max_custom_durability set to 2048 and current_custom_durability at 1983.

**Comment by SliderKP** [comment] 2024-10-02 04:45
hey bro this is the same:
https://github.com/PluginBugs/Issues-ItemsAdder/issues/3988#issuecomment-2387543172
the problem stay when you join with 1.20.4, if u join with 1.20.6 or 1.21.1 durability works fine.
so some servers actually are disabling join with old versions before 1.20.6

**Comment by Andre601** [comment] 2024-10-02 11:22
ItemsAdder does not officially support ViaVersion at all, as [was mentioned in the above linked issue](https://github.com/PluginBugs/Issues-ItemsAdder/issues/3988#issuecomment-2356083515), so don't expect any fixes for it and instead remove legacy version support altogether. It's not worth the trouble.

Duplicate of #3988

**Comment by sennby** [comment] 2024-10-02 14:23
But i play on 1.21.1 client?

**Comment by sennby** [comment] 2024-10-04 13:08
Issue still occurs with 1.20.6+ only.

**Comment by nhanledev** [comment] 2024-10-18 01:28
This also happens with custom armor because of mojang's chances in NBT, and it only happens with old armor get from previous version (1.20.4), new armors from current version (1.21.1) dont  have this issue. I think ItemsAdder needs to read all old NBT tags and convert them more precise :)

**Comment by sennby** [comment] 2024-10-29 14:48
I also want to note ive been replacing existing gear manually as players report pieces (my crates with 100 items are messed up as well)
Side note that if you have gear that is messed up (usually says 75 durability) you CANNOT use /iadurability on it. it throws an error in chat and the only way to fix the gear is hand redoing it (that i know of rn) Which sucks when there is trackers and 10 custom enchants etc on the items.

**Comment by nhanledev** [comment] 2024-11-04 07:51
I just want to add another note that previous weapons and tools might have a random "durability reset" when moving around. Looks like something is wrong with the migration feature.

**Comment by LoneDev6** [comment] 2024-11-12 14:41
The plugin should already update durability.
It does that only on opened chests.
I will update the plugin to also do that on player inventories on join.

Anyway a little bug was in this version, I will fix it, I'm sure it will work fine after that.

**Comment by sennby** [comment] 2024-11-12 16:36
> @sennby
> 
> > it throws an error in chat and the only way to fix the gear is hand redoing it
> 
> I need this info in order to correctly identify the issue.

u closed the ticket i had with that info in it lol.

> The plugin should already update durability. It does that only on opened chests. I will update the plugin to also do that on player inventories on join.
> 
> Anyway a little bug was in this version, I will fix it, I'm sure it will work fine after that.


https://mclo.gs/FbpRFRk

all of the custom items that were on my server when i upgraded to 1.21.1 from 1.20.4 have broken durabilitys. all of my items in my crates (excellentcrates i use) is all broken durability (over 300+ items)

**Comment by LoneDev6** [comment] 2024-11-13 09:07
@sennby update the plugin to 4.0.4

#3822 had some little issues I fixed in 4.0.4, for example conversion triggers only on inventory open, now it will trigger on player join and on world change, to make sure all items are always converted.

Which value did you set when using `/iadur`?
Which max durability and durability did the item have before using `/iadur`?

**Closed** 2024-11-14 14:05 UTC
Labels: type: bug, compat: new minecraft update
