### ISSUE TITLE
[ItemsAdder] Error moving corrupted region to 'corrupted_data' folder

### ISSUE THREAD

**Issue by SrMonsterYT** [PluginBugs/Issues-ItemsAdder#3975] opened 2024-09-03 13:20 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

mauriciooficial

### What happened?

error: https://mclo.gs/YFZQ6En

### Steps to reproduce the issue

use plugin new version

### Server version

This server is running Paper version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder_4.0.2-beta-release-9

### ProtocolLib Version

ProtocolLib (5.3.0-SNAPSHOT-726)

### LoneLibs Version

LoneLibs_1.0.58

### Full Server Log

.

**Comment by Andre601** [comment] 2024-09-03 13:56
Duplicate of #3966

**Closed** 2024-09-03 13:56 UTC
Labels: type: bug, type: duplicate
