### ISSUE TITLE
Rendering entity in world | could not reload shaders | FO 1.21.1 / Vanilla 1.21.4 | 4.0.6

### ISSUE THREAD

**Issue by DxrkCat** [PluginBugs/Issues-ItemsAdder#4260] opened 2024-12-19 16:03 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

Client version: 1.21.1 FO-6.2.1
Server version: Purpur 1.21.1
The problem is current on the latest version.

To retest, I enabled shader creation in the ModelEngine config, deleted the .data and resourcepack folder, wrote /meg reload, and after /iazip.
https://mclo.gs/XAsZdg6

Fabric 1.21.4, mo mods
When I went into the radius of visibility of the model from ModelEngine I crashed the client, previously just the client did not load textures. and there was a label resourcepack failed load.
https://mclo.gs/RHFVgS5

### Steps to reproduce the issue

above

### Server version

![397432469-bbad158f-70c3-4d27-b8f4-b1e68b379574](https://github.com/user-attachments/assets/46a2fa9a-babe-4bd0-b433-2b331f20d3f0)

### ItemsAdder Version

photo above

### ProtocolLib Version

6.3.0 from jenkins

### LoneLibs Version

photo above

### Full Server Log

null

**Comment by Andre601** [comment] 2024-12-19 16:55
As was stated by Lone dev is this a possible duplicate of #4159

**Comment by DxrkCat** [comment] 2024-12-19 16:57
> As was stated by Lone dev is this a possible duplicate of #4159
> 
> Your issue has been marked as **duplicate**! Please always check the issue tracker first for any existing issues of the same problem/suggestion (including closed ones!) before creating your own. Thank you.
"Please do not comment on old issues. Make a new one with your own information instead.
Anyway check the server log, you probably have some duplicate files."

**Comment by DxrkCat** [comment] 2024-12-19 17:02
The problem is not fixed, you are closing my issue as duplicate, Andre_601 maybe you could try researching the issue and see what LoneDev wrote in the past issue before closing it? Or do you only know how to make forks?

**Comment by Andre601** [comment] 2024-12-19 17:05
My only responsability here is managing issues as support member. I have no obligation to look into the code of IA here.

Given the circumstances will I reopen this issue.
Also, for further help do we ask you to give us the latest.log of your server.

**Comment by DxrkCat** [comment] 2024-12-19 17:07
Here is the log from the moment where I enabled shaders in the ModelEngine config.
https://mclo.gs/Zv2cbcw

**Comment by DxrkCat** [comment] 2024-12-19 20:40
Completely reconfigured ItemsAdder from scratch, removed all warrnings and errors, but that's not the problem. https://mclo.gs/HEX3Mym

**Comment by LoneDev6** [comment] 2024-12-20 15:54
Try with only ModelEngine resourepack.
Anyway seems to be a typo in ModelEngine resourcepack `rendertype_entity_translucent.json`, as noted in the error.
```
Caused by: java.io.FileNotFoundException: minecraft:shaders/core/core/rendertype_entity_translucent.vsh
```

should be `core/rendertype_entity_translucent`.
This is most likely not be caused by ItemsAdder as this is my code to update shaders, I don't see how it can be related (stating this just as proof for future readers).

```java
if (json.containsKey("vertex"))
{
    if (!json.getString("vertex").startsWith("core/") && !json.getString("vertex").startsWith("minecraft:core/"))
    {
        json.put("vertex", "core/" + json.getString("vertex"));
        isLegacyShader = true;
    }
}

if (json.containsKey("fragment"))
{
    if (!json.getString("fragment").startsWith("core/") && !json.getString("fragment").startsWith("minecraft:core/"))
    {
        json.put("fragment", "core/" + json.getString("fragment"));
        isLegacyShader = true;
    }
}
```

**Comment by DxrkCat** [comment] 2024-12-20 15:58
> Try installing only the ModelEngine resourepack, remove ItemsAdder pack temporarily. I think the error should be triggered anyway, just to confirm that this is not an ItemsAdder shaders converter issue. Anyway seems to be a typo in ModelEngine resourcepack `rendertype_entity_translucent.json`, as noted in the error.
> 
> ```
> Caused by: java.io.FileNotFoundException: minecraft:shaders/core/core/rendertype_entity_translucent.vsh
> ```
> 
> should be `core/rendertype_entity_translucent`. This is most likely not be caused by ItemsAdder as this is my code to update shaders, I don't see how it can be related (stating this just as proof for future readers).
> 
> ```java
> if (json.containsKey("vertex"))
> {
>     if (!json.getString("vertex").startsWith("core/") && !json.getString("vertex").startsWith("minecraft:core/"))
>     {
>         json.put("vertex", "core/" + json.getString("vertex"));
>         isLegacyShader = true;
>     }
> }
> 
> if (json.containsKey("fragment"))
> {
>     if (!json.getString("fragment").startsWith("core/") && !json.getString("fragment").startsWith("minecraft:core/"))
>     {
>         json.put("fragment", "core/" + json.getString("fragment"));
>         isLegacyShader = true;
>     }
> }
> ```

Yes the problem is present only with ModelEngine Resourcepack

**Comment by DxrkCat** [comment] 2024-12-20 16:07
> @DxrkCat so if you install the ModelEngine pack, ignore the ItemsAdder pack, and join, you get the same issue? Correct? If yes, you have to report this to ModelEngine not to me as I can't do anything about that.

![изображение](https://github.com/user-attachments/assets/a48dcf9e-c191-4b10-8bca-a873d7e52c5f)

ModelEngine config: https://mclo.gs/hGMQ74s
ModelEngine version: 4.0.8 2073
Client error log: https://mclo.gs/VKiNLpy

**Comment by LoneDev6** [comment] 2024-12-20 16:27
> so if you install the ModelEngine pack, ignore the ItemsAdder pack, and join, you get the same issue? Correct?

Please answer clearly with yes or no

**Comment by DxrkCat** [comment] 2024-12-20 16:35
> > so if you install the ModelEngine pack, ignore the ItemsAdder pack, and join, you get the same issue? Correct?
> 
> Please answer clearly with yes or no

Yes.
If I put a clean texturepack on the client, which has not changed anything except ModelEngine, then yes.

**Comment by LoneDev6** [comment] 2024-12-20 16:47
More info here: https://git.lumine.io/mythiccraft/modelengine/-/issues/110

I suggest you to answer on [their issues website](https://git.lumine.io/mythiccraft/modelengine/-/issues/110) and paste my Github issue link so that they can read this chat.

**Closed** 2024-12-20 16:47 UTC
Labels: type: other plugin bug
