### ISSUE TITLE
Darkened Default Backgrounds in Minecraft After Updating to ItemsAdder 4.0.4

### ISSUE THREAD

**Issue by zikehalil3535** [PluginBugs/Issues-ItemsAdder#4181] opened 2024-11-25 16:51 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

whiskeytr

### What happened?

After updating from ItemsAdder version 4.0.3 to 4.0.4, we noticed that Minecraft's default backgrounds for the Tab list, chat, and scoreboard appear excessively dark. This issue occurs specifically with resource packs generated using ItemsAdder 4.0.4, while previous versions did not exhibit this problem.

We believe this issue might be relatively simple to resolve, and we're requesting support to it. Please let us know if additional details or files are needed.

### Steps to reproduce the issue

Update ItemsAdder to version 4.0.4.
Generate a new resource pack using the plugin. /iazip
Join with older version like 1.20.1-1.19
Load the resource pack in Minecraft and observe the Tab list, chat, and scoreboard backgrounds.
You should try with Pufferfish or Purpur 1.21.1 latest based version.

### Server version

[14:00:47 INFO]: Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*

### ItemsAdder Version

[14:00:58 INFO]: ItemsAdder version 4.0.4
[14:00:58 INFO]: Customized Minecraft without client mods!
[14:00:58 INFO]: Website: devs.beer
[14:00:58 INFO]: Author: LoneDev

### ProtocolLib Version

[14:01:10 INFO]: ProtocolLib version 5.3.0
[14:01:10 INFO]: Provides read/write access to the Minecraft protocol.
[14:01:10 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[14:01:17 INFO]: LoneLibs version 1.0.61
[14:01:17 INFO]: Collection of libs used by my plugins
[14:01:17 INFO]: Authors: LoneDev and others

### Full Server Log

No Logs Needed

### Other files, you can drag and drop them here to upload. (optional)

Expected Behavior:
The default backgrounds should retain their standard brightness as in previous versions.

Observed Behavior:
The backgrounds are noticeably darker than intended, creating visual inconsistency.

### Screenshots/Videos (you can drag and drop files or paste links)

![Screenshot_4](https://github.com/user-attachments/assets/41fe4bdc-8cc6-4922-9f8b-1c54c051f586)
![Untitled-1](https://github.com/user-attachments/assets/acdead40-208b-4168-bc1f-a9871900495d)

**Comment by Andre601** [comment] 2024-11-25 17:15
Duplicate of #4169 

Do us a favour and don't re-post the exact same issue word for word.

**Closed** 2024-11-25 17:15 UTC
Labels: type: duplicate
