### ISSUE TITLE
Item models are not updated

### ISSUE THREAD

**Issue by 1821698021** [PluginBugs/Issues-ItemsAdder#2625] opened 2023-05-16 09:18 UTC
### Terms

- [ ] I'm using the very latest version of ItemsAdder and its dependencies.
- [ ] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [ ] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [ ] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [ ] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

none

### What happened?

I found that the models data is not updated in time
/iacleancache items 
The update was also not completed
(Google Translate)

### Steps to reproduce the issue

1.I updated the models value of item
2.After entering/iazip /iacleancache items  it is clear that there is no update

### Server version

purpur-1.18.2-1632

### ItemsAdder Version

itemsadder-3.4.1c

### ProtocolLib Version

ProtocolLib-5.0.0-SNAPSHOT-636

### LoneLibs Version

LoneLibs-1.0.24

### FULL server log

none

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: ny_items
items:
  air:
    display_name: '空图标'
    permission: ny.items
    resource:
      material: GOLD_NUGGET
      model_id: 100
      generate: true
      textures: 
        - air
```

### Other files, you can drag and drop them here to upload. (optional)

none

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/99568806/86c26808-984c-49e9-ae73-a852f931a180

**Comment by 1821698021** [comment] 2023-05-16 09:32
https://github.com/PluginBugs/Issues-ItemsAdder/assets/99568806/7a632a5c-c622-4b36-8d3b-8a3e56d8b0a1

I swapped itemsadder back to the previous version and it worked fine

**Comment by 1821698021** [comment] 2023-05-16 09:35
HELPP ME
HELPP ME
HELPP ME

**Comment by EpicPlayerA10** [comment] 2023-05-16 11:17
I think it's a duplicate of #2621

**Comment by 1821698021** [comment] 2023-05-16 11:33
> 我认为这是#2621的副本

Sorry, I didn't notice it had already been posted

**Comment by 1821698021** [comment] 2023-05-16 11:42
How do I delete this post

**Closed** 2023-05-16 12:10 UTC
Labels: type: bug
