### ISSUE TITLE
Error in my consoly

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-ItemsAdder#3255] opened 2023-12-28 04:27 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Coder#6926

### What happened?

Error

### Steps to reproduce the issue

Error

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/51a74855-75f1-46f6-979d-a465a79a64a6)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/fe0e2a15-1a68-4ac6-9e8b-b14c7ea00df3)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/fd70d305-8738-4f5c-9680-f2d3bf930acc)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/73fd4fe4-abdc-4594-8f58-4f04334af1ee)

### Error (optional)

```shell
[07:01:05] [Server thread/INFO]: [ItemsAdder] Loading ItemsAdder v3.6.3-beta-3
[07:01:05] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] Cannot invoke "org.bukkit.plugin.Plugin.getDataFolder()" because "<parameter1>" is null initializing ItemsAdder v3.6.3-beta-3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.getDataFolder()" because "<parameter1>" is null
	at ia.m.qY.<init>(SourceFile:118) ~[?:?]
	at ia.m.qY.<init>(SourceFile:78) ~[?:?]
	at ia.m.qY.<init>(SourceFile:68) ~[?:?]
	at ia.m.P.m(SourceFile:601) ~[?:?]
	at ia.m.O.m(SourceFile:436) ~[?:?]
	at dev.lone.itemsadder.Main.bN(SourceFile:592) ~[?:?]
	at dev.lone.itemsadder.Main.onLoad(SourceFile:180) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(:399) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(:281) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(:1071) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$1(:289) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by nhanledev** [comment] 2023-12-28 06:23
This error throws on Papaer 1.20.2 buid 318 too

```
[13:17:38 INFO]: [ItemsAdder] Loading server plugin ItemsAdder v3.6.3-beta-3
[13:17:38 INFO]: [ItemsAdder] Using custom language file 'plugins/ItemsAdder/lang/vi.yml'
[13:17:38 ERROR]: [ItemsAdder] Error initializing plugin 'ItemsAdder_3.6.3-beta-3.jar' in folder 'plugins' (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.getDataFolder()" because "<parameter1>" is null
        at ia.m.qY.<init>(SourceFile:118) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at ia.m.qY.<init>(SourceFile:78) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at ia.m.qY.<init>(SourceFile:68) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at ia.m.P.m(SourceFile:601) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at ia.m.O.m(SourceFile:436) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at dev.lone.itemsadder.Main.bN(SourceFile:592) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at dev.lone.itemsadder.Main.onLoad(SourceFile:180) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by JuergenUniVie** [comment] 2023-12-28 09:01
[09:56:29 ERROR]: [ItemsAdder] Error initializing plugin 'ItemsAdder_3.6.3-beta-3.jar' in folder 'plugins' (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.getDataFolder()" because "<parameter1>" is null
        at ia.m.qY.<init>(SourceFile:118) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at ia.m.qY.<init>(SourceFile:78) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at ia.m.qY.<init>(SourceFile:68) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at ia.m.P.m(SourceFile:601) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at ia.m.O.m(SourceFile:436) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at dev.lone.itemsadder.Main.bN(SourceFile:592) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at dev.lone.itemsadder.Main.onLoad(SourceFile:180) ~[ItemsAdder_3.6.3-beta-3.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.4.jar:git-Paper-355]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.4.jar:git-Paper-355]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.4.jar:git-Paper-355]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-355]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:505) ~[paper-1.20.4.jar:git-Paper-355]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.4.jar:git-Paper-355]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-355]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-355]

**Comment by LoneDev6** [comment] 2023-12-28 12:12
Please provide the full server log, something failed before.
Most likely an incompatible plugin.
Thanks.

**Comment by LoneDev6** [comment] 2023-12-28 12:14
Duplicate of: #3253

**Closed by LoneDev6** 2023-12-28 12:14 UTC
Labels: type: bug
