### ISSUE TITLE
Exception on server boot, and error preventing player connection

### ISSUE THREAD

**Issue by Sixsoul** [PluginBugs/Issues-ItemsAdder#2526] opened 2023-04-11 20:46 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I've been noticing this exception span on server boot and just randomly. This started 2 days ago now, out of nowhere with nothing changed. Doing anything on the server makes it worse, increases spam amount until console is completely illegible. 

I realized I was one IA version behind, so updated hoping it'd fix it. But now it's worse, now when I connect i'm just trapped in a black void, getting an error about the PlayerResourcePackStatusEvent.

I see a few other people in the discord reporting that that the same issue started out of nowhere for them as well.

### Steps to reproduce the issue

No idea, this just started happening out of nowhere.

### Server version

Paper(509) 1.19.4-R0.1-SNAPSHOT

### ItemsAdder Version

3.4.1-r5

### ProtocolLib Version

5.0.0-SNAPSHOT-b633

### LoneLibs Version

1.0.24

### Error (optional)

```shell
https://mclo.gs/7jG7pmS
```

**Comment by IAmRiven** [comment] 2023-04-12 00:08
I have the same problem :/

**Comment by sarhatabaot** [comment] 2023-04-12 05:59
I have the same problem as well. 
Running: 
git-Purpur-1957 (MC: 1.19.4)
LoneLibs 1.0.24
ItemsAdder 3.4.1-r5
ProtocolLib 5.0.0-SNAPSHOT-b633

**Comment by CoasterFreakDE** [comment] 2023-04-12 08:12
Same problem here.

Updated the server (paper 1.19.4) and every plugin to the latest version.

**Comment by CoasterFreakDE** [comment] 2023-04-12 09:57
duplicate of #2524

**Closed** 2023-04-12 10:20 UTC
Labels: type: bug
