### ISSUE TITLE
Custom armor textures dont work with Optifine 1.21.1

### ISSUE THREAD

**Issue by MrUnaiMillan** [PluginBugs/Issues-ItemsAdder#4047] opened 2024-10-08 02:03 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

When a put the myarmorexample, when i start the game with optifine is not rendering, only appears the leather with color. I dont know why. I have activated the:

 generate-custom-armors-textures:
      vanilla: true
      optifine: true

But it works with vanilla minecraft 1.21.1

### Steps to reproduce the issue

1- Put Armor set
2- Start server
3- Start Minecraft 1.21 with Optifine HD 1.21.1 J1 Ultra
4- Put armor and not render, only show leather armor

### Server version

This server is running Paper version 1.21.1-118-master@fb76840 (2024-10-02T12:49:56Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.2-beta-release-11

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-732

### LoneLibs Version

LoneLibs version 1.0.59

### Full Server Log

https://mclo.gs/VGJUL4q

### Error (optional)

```shell
No error
```

**Comment by PSYCHEER** [comment] 2024-10-11 07:51
Duplicate of #4004

**Closed** 2024-10-11 11:05 UTC
Labels: type: bug, type: duplicate
