### ISSUE TITLE
Custom entities not spawned on world change (specific steps to reproduce)

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#3270] opened 2023-12-30 18:13 UTC
### What happened?

If I create a Citizens NPC that I use "/iaentity citizens..." on the spawn, it appears then goes to another world and I come back by doing /spawn or /mvtp nouveau_spawn and there it is no longer visible , there is only his name visible. If I come back through a Multiverse portal it reappears or if I log out and log back in too.

I don't have a problem with my other non-ItemsAdder "NPC citizens" disappearing.
(Citizens = OK / Shopkeepers Citizens = OK)

No issue on:
- 3.6.1-beta

Bug on:
- 3.6.3-beta-3 
- 3.6.2d-beta-2
- 3.6.2c

I tried with 5 different ItemsAdder mobs that come from 4 different people and the result is the same.

### Steps to reproduce the issue

I create a Citizens NPC that I use "/iaentity citizens..." it appears fine :
/npc create TEST --type ZOMBIE
/npc select [ID]
/iaentity citizens [ID num] model []

Then I leave the world where it is (spawn - name of this world in multiverse: new_spawn) through a portal made with Multiverse or by the command "/mvtp [world]".
1. If I return to this world (spawn) where there is the "NPC Citizen iaentity" through a multiverse portal, the NPC is visible.
2. If I return to this world (spawn) with the command "/mvtp nouveau_spawn" the "NPC Citizen iaentity" is invisible.
3. If I return to this world (spawn) with the "/spawn" command from EssentialsX the "NPC Citizen iaentity" is invisible.
4. If I am on this world (spawn) when the NPC is visible and I do /spawn the NPC remains visible, if I do "/mvtp new_spawn" (which is the spawn world) the NPC remains visible.
If, on the other hand, I leave this world (spawn) for any other world on my server and I return with "/spawn" or "/mvtp new_spawn" the NPC disappears.
5. If I stand in front of the "NPC Citizen iaentity" when it is invisible, disconnect from the server and reconnect, the NPC is visible when I arrive on the server.

### Server version

Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-3

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.42

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13798894/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80985545/deb8944d-14b2-43e3-9e40-d2d0645a25ba)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80985545/fc8778da-47c3-495e-bb8d-ac9befef386d)

**Comment by LoneDev6** [comment] 2024-01-03 19:39
Seems a duplicate of this report: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3186

**Closed** 2024-01-04 18:04 UTC
Labels: type: bug, verdict: workaround implemented

**Comment by Verzante** [comment] 2024-01-06 21:11
Hello, I just want to say that this bug is still happening after updating IA to 3.6.3-beta-6 and all its dependencies.

**Comment by LoneDev6** [comment] 2024-01-07 19:55
I tested it like 50 times and couldn't reproduce it.
This is very strange
