### ISSUE TITLE
Some noteblocks are playing incorrect note

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-ItemsAdder#2284] opened 2023-01-21 22:51 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

EpicPlayerA10#3800

### What happened?

Noteblocks are playing incorrect note.
Noteblocks without ItemsAdder: https://www.youtube.com/watch?v=APzQi4M-jSQ
Noteblocks with ItemsAdder: https://www.youtube.com/watch?v=_yqET-p4zec

### Steps to reproduce the issue

1. Place for example gold block and noteblock on top of it
2. Hit noteblock

! Noteblock plays incorrect note (harp)

### Server version

This server is running Paper version git-Paper-371 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 035f9d7)

### ItemsAdder Version

ItemsAdder version 3.3.0b-r5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs version 1.0.23

**Comment by LoneDev6** [comment] 2023-01-23 14:32
Will be checked in the next hours, thanks

**Comment by LoneDev6** [comment] 2023-01-23 15:07
Try to remove and place blocks.
It works fine for me.

https://user-images.githubusercontent.com/27242001/214074111-758acc33-8fb0-49bb-bef5-ccc387e3d523.mp4

**Closed by LoneDev6** 2023-01-23 15:07 UTC
Labels: Bug

**Comment by EpicPlayerA10** [comment] 2023-01-23 16:39
> Try to remove and place blocks.
It didin't work.

What are your client, server, and protocollib versions? Are they the same as mine? My version of the client was 1.19.3

**Comment by Norbiros** [comment] 2023-01-23 16:43
I created new docker server (based on marctv/minecraft-papermc-server:latest) and I installed ItemsAdder, LoneLibs and ProtocolLib and I can reproduce this bug.

**Comment by LoneDev6** [comment] 2023-01-23 17:02
1.19.3 both server and client.

Strange.
Try to remove all other plugins.

**Comment by EpicPlayerA10** [comment] 2023-01-23 17:23
I tested it only with itemsadder, protocollib and lonelibs

**Comment by LoneDev6** [comment] 2023-01-24 10:09
Me too, this is strange that I cannot reproduce.
Try to remove and place the note block.

**Comment by EpicPlayerA10** [comment] 2023-01-24 15:47
I tried it and still didn't work

**Comment by LoneDev6** [comment] 2023-01-24 17:38
I'll try again but as you can see in my video it works fine for me.
It's definitely something different in your server.

Can you also try placing the blocks elsewhere? In another location, exactly how I did.
