### ISSUE TITLE
[Suggestion] Custom Crafting Table

### ISSUE THREAD

**Issue by kozankun** [PluginBugs/Issues-ItemsAdder#957] opened 2021-06-19 12:14 UTC
A crafting table but chest. I want this feature in Items Adder, so I can add Custom GUI Texture

I want to have a chest that will act like a crafting table, it would be nice if we can configure where the 3x3 crafting grid will be so it will match the customized Custom GUI Texture

![image](https://user-images.githubusercontent.com/84431345/122641867-7075aa80-d13a-11eb-8cb8-bb0e6fedf393.png)

![image](https://user-images.githubusercontent.com/84431345/122642178-ac5d3f80-d13b-11eb-999e-55a1ede319c0.png)
(Hypixel Skyblock Crafting Table)

**Comment by LoneDev6** [comment] 2023-01-24 14:57
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/1406

**Closed by LoneDev6** 2023-01-24 14:57 UTC
Labels: Feature request
