### ISSUE TITLE
Emote offhand/helmet rendering problems

### ISSUE THREAD

**Issue by glutaminus** [PluginBugs/Issues-ItemsAdder#2232] opened 2023-01-01 10:28 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

they look unfixable/fixable I don't know but there are 3 main problems. 
1. when play emote with headgear on, the headgear will be showed but stay still on the place.(doesn't move with head)
![image](https://user-images.githubusercontent.com/90768288/210167204-88c37da4-f60d-4bd1-8a33-87c73f98d19a.png)

2.weird offset when play with offhand accessory, .. (yeah I know if you move hand too much the offhand accessory will look weird, and it might only happen when using on accessory with custom offset like wing but this is just too wrong, please compare offhand vs main hand with picture down below)
Offhand:
![image](https://user-images.githubusercontent.com/90768288/210167233-9d3acc34-cb6e-4f2d-ab4d-ae5ddf4aaa56.png)
 Mainhand:
![image](https://user-images.githubusercontent.com/90768288/210167312-01978675-4a5c-446a-acd8-bd487684f9ec.png)

3. this one look the most unfixable in my opinion. what happening here is, during you play the emote (while emote is play) if you swap item from main hand to off hand the item on emote will be duplicate and it doesn't remove the old one even though you already swap it to the offhand. and after a while it will become like the 2nd picture 
![image](https://user-images.githubusercontent.com/90768288/210167350-9a167f9d-63fb-47f9-99a7-1a22821c74d8.png)
after a while
![image](https://user-images.githubusercontent.com/90768288/210167342-d04d2497-3de7-472e-b234-0eb803c0ef37.png)

### Steps to reproduce the issue

already demonstrate on top

### Server version

git-Purpur-1838 (MC 1.19.2)

### ItemsAdder Version

ItemsAdder version 3.3.0b-r2

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b602

### LoneLibs Version

LoneLibs version 1.0.22

**Comment by glutaminus** [comment] 2023-01-26 16:44
> The first issue is not normal, I cannot reproduce the issue, equipment correctly follows the player while walking around. Other issues might be related to this bug and it was fixed in the upcoming version: #2125

@LoneDev6 hello, i should be more specific. after i reproduce it again, yes head item correctly follow player while walking, but it's only on some emotes.
when I tried "/iaemote walk" and most of my custom emotes, the head equipment didn't follow, meanwhile "/iaemote magic_trick_head"and some of emotes the head item following properly. I don't know what makes the difference. but the bug seems to exist.
(sorry for pinging because I can't reopen the issue)

**Comment by LoneDev6** [comment] 2023-01-27 10:51
The helmet issue is probably fixed on the latest ItemsAdder update 3.3.1, which is going to be released these next days.

**Comment by glutaminus** [comment] 2023-02-05 16:23
> The helmet issue is probably fixed on the latest ItemsAdder update 3.3.1, which is going to be released these next days.

somehow the helmet issue is available again in 3.3.1

**Comment by LoneDev6** [comment] 2023-02-06 11:21
You probably have some malformed emotes files, try to check if you deleted any bone from the custom emotes file in blockbench,

**Comment by glutaminus** [comment] 2023-02-06 14:21
> You probably have some malformed emotes files, try to check if you deleted any bone from the custom emotes file in blockbench,

yeah, you are right. it only happened on custom emotes, my bad there. 
but anyways, seems like the offhand problems[2.] is still here though

**Comment by glutaminus** [comment] 2023-02-06 14:34
> You probably have some malformed emotes files, try to check if you deleted any bone from the custom emotes file in blockbench,

now I tried create new emotes pack through blockbench ItemsAdder plugin with ItemsAdder Entity Model, and the helmet still didn't follow. any chances the bone you mention is probably missing from the start? it happen to custom emotes only. but the built-in emotes's helmet are follow correctly.

**Comment by glutaminus** [comment] 2023-02-06 14:54
> You probably have some malformed emotes files, try to check if you deleted any bone from the custom emotes file in blockbench,

ok, now i tried redownloading the plugin from the start to generate the built-in emote pack to see. yeah the missing bone is hat_slot. which is probably not added to the blockbench's ia plugin yet. so maybe update this plugin soon! 
ps.offhand slots is still a problem

**Comment by LoneDev6** [comment] 2023-02-28 15:05
Basically creating the emote directly form blockbench causes the missing bone issue?

**Comment by LoneDev6** [comment] 2023-04-04 14:54
> ok, now i tried redownloading the plugin from the start to generate the built-in emote pack to see. yeah the missing bone is hat_slot. which is probably not added to the blockbench's extension plugin yet. so maybe update it to the bb extension plugin soon when you have time!

Thanks! It was the cause. I will push an update for the Blockbench extension very soon.

> ps.offhand slots is still a problem

I tested and I cannot reproduce the issue.


https://user-images.githubusercontent.com/27242001/229832364-3f9bc121-a6d1-4576-a191-e01a1d1cb51c.mp4

**Closed** 2023-04-04 14:55 UTC
Labels: Bug, Compatibility with other stuff

**Comment by LoneDev6** [comment] 2023-04-05 09:55
Update released: https://github.com/LoneDev6/itemsadder-entity/releases
