### ISSUE TITLE
Compatibility with GeyserMC

### ISSUE THREAD

**Issue by Distolfix** [PluginBugs/Issues-ItemsAdder#2673] opened 2023-05-28 16:16 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Find a method to allow texture packs to be downloaded from the Bedrock Edition using GeyserMC.

I'm sending you a link to a guide where you can set custom items using a JSON file: [GeyserMC Custom Items](https://wiki.geysermc.org/geyser/custom-items/).

Could you create a method that automates this process?

### Is your feature request related to a problem?

No problem, but it could potentially increase player count on servers and boost the popularity of your plugin as well.

### Describe alternatives you've considered

According to my understanding, implementing the feature to allow custom textures from both Java and Bedrock editions can be challenging. However, considering that there are servers in Italy that have achieved this, it's evident that with some ingenuity and automating certain processes, it can be accomplished. One possible approach could be to include a configuration option, such as "Geysermod: true" or "Geysermod: false," in the config.yml file. This option would enable or disable the GeyserMC integration, thereby allowing servers to customize their texture pack experience for both Java and Bedrock players.

**Comment by Distolfix** [comment] 2023-05-28 17:58
I know it was open, but look at the date, it's 2020. And he promised that when things were stable, he would work on it for 3 years. Things have changed. Can it be done?

**Comment by dinobossytnew** [comment] 2023-05-28 18:20
geyser the responsibility is not ia's if you want to support other platforms use it outside the pack for bedrock to java works that is what it is intended for if you want to support bedrock just convert your pack to bedrock and download it outside the sv.

**Comment by Distolfix** [comment] 2023-05-28 18:41
However, it could create a way that does everything automatically. This I mean

**Comment by LoneDev6** [comment] 2023-05-29 11:47
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/206

Geyser is not a priority for me because it is not stable.
Bedrock and Java clients are completely different and what appears on screen is not the exact same thing that appears on Java.
Adding official compatibility would open the door for lot of bug reports about glitches which I cannot fix because of how unstable is the Bedrock -> Java conversion layer implemented by Geyser.

For now it's not doable.

**Closed by LoneDev6** 2023-05-29 11:47 UTC
Labels: type: feature request
