### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: Expected id to be a string was an array ([-71...67])

### ISSUE THREAD

**Issue by tetz24** [PluginBugs/Issues-ItemsAdder#3280] opened 2024-01-02 21:23 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

tetz18

### What happened?

When a User kills another User all Players will be kicked form the Server with the Message: 
Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: Expected id to be a string was an array ([-71...67])

### Steps to reproduce the issue

1. Player kills antother Player
2. All Users will be kicked from the Server

### ItemsAdder Version

3.6.3-beta-5

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.42

### Screenshots/Videos (you can drag and drop files or paste links)

https://prnt.sc/ay5eePinjVAi

**Comment by LoneDev6** [comment] 2024-01-03 11:22
Can you try this other JAR file?
https://lobfile.com/file/GLI8.jar
(rename it `LoneLibs`).
Thanks.

**Comment by tetz24** [comment] 2024-01-03 12:31
I've tried it but all Players still get kicked with the same message when a Player dies or got killed by another Player.

**Comment by tetz24** [comment] 2024-01-03 13:36
Server version: https://prnt.sc/_ju9vNTwUYdh
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13819535/latest.log)

**Comment by LoneDev6** [comment] 2024-01-03 17:27
I will do some testing, probably has to do with Spigot since the plugin works fine on Paper.

**Comment by LoneDev6** [comment] 2024-01-03 18:33
Duplicate of: #3282

**Closed by LoneDev6** 2024-01-03 18:33 UTC
Labels: type: bug, type: duplicate
