### ISSUE TITLE
memory leak in itemsadder

### ISSUE THREAD

**Issue by necodex777** [PluginBugs/Issues-ItemsAdder#2240] opened 2023-01-05 17:01 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

can help with a memory leak in itemsadder?

### Steps to reproduce the issue

memory leak in itemsadder

### Server version

Purpur 1.18.2-R0.1-SNAPSHOT

### ItemsAdder Version

ItemsAdder_3.2.5-r3

### ProtocolLib Version

name: ProtocolLib
version: 4.8.0

### LoneLibs Version

name: LoneLibs
version: 1.0.22

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/116894571/210837819-5de2515c-42bd-4072-a21f-b7c7e29838ca.png)
![image](https://user-images.githubusercontent.com/116894571/210837837-d3f4378a-a694-44b5-b79b-35d8a73ab3c2.png)
![image](https://user-images.githubusercontent.com/116894571/210837860-5d1d6dee-155c-4ff9-98ee-9ea4a525a152.png)

**Comment by LoneDev6** [comment] 2023-03-02 16:24
This is surely fixed in the new updates since the regions system totally changed.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2246

**Comment by LoneDev6** [comment] 2023-03-02 16:24
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2246

**Closed by LoneDev6** 2023-03-02 16:24 UTC
Labels: Bug
