### ISSUE TITLE
SlimeTinker's pickaxe digging Itemsadder's new block will cause the pickaxe to duplicate.

### ISSUE THREAD

**Issue by Meawerful** [PluginBugs/Issues-ItemsAdder#2219] opened 2022-12-27 12:03 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Meawerful#7634

### What happened?

SlimeTinker's pickaxe digging Itemsadder's new block will cause the pickaxe to duplicate.

### Steps to reproduce the issue

Slimetinker:https://github.com/Sefiraat/SlimeTinker

### Server version

This server is running Mirai version git-Mirai-24 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e0a26d7 on HEAD)
You are on the latest version!
Previous version: git-Mirai-6 (MC: 1.19.2)

### ItemsAdder Version

ItemsAdder 3.2.4-beta-1

### ProtocolLib Version

ProtocolLib 5.0.0

### LoneLibs Version

LoneLib 1.0.21

### LightAPI Version (optional)

none

### LibsDisguises Version (optional)

none

### FULL server log

none

### Error (optional)

```shell
none
```

### Problematic items yml configuration file (optional)

```shell
no need
```

### Other files, you can drag and drop them here to upload. (optional)

https://github.com/Sefiraat/SlimeTinker/issues/150
Some SlimeTinker users have reported issues on there

**Comment by LoneDev6** [comment] 2023-01-09 13:37
Answered on the https://github.com/Sefiraat/SlimeTinker/issues/150 issue.

**Comment by LoneDev6** [comment] 2023-05-31 11:48
Was caused by this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2687
Will be fixed in the upcoming update.

**Closed** 2023-05-31 12:51 UTC
Labels: type: bug, compat: plugin
