### ISSUE TITLE
Tile block textures are glitchy when placed

### ISSUE THREAD

**Issue by WataLaker37821** [PluginBugs/Issues-ItemsAdder#2616] opened 2023-05-12 17:01 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

DOGE#1690

### What happened?

I've set aqua block's placed model for a tile block, then started to place it, with some chance (i think near 50%) it becomes glitchy
It helps to visually fix it when i run /iazip again (i use self-hosting method) but its not a solution

### Steps to reproduce the issue

1. set placed model of any block to "TILE" 
2. run commands: /iareload and /iazip
3. place some blocks and see that half of them or more are glitchy
4. run /iazip to fix some of them and if not every block fixed (visually) run /iazip again

### Server version

git-Purpur-1632 (MC: 1.18.2)

### ItemsAdder Version

ItemsAdder version 3.4.1b

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b626

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11466313/latest.log)

(dont pay attention for world populators errors, it was for test) 

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: iasurvival
items:
  aqua_aura_block:
    enabled: true
    display_name: display-name-aqua_aura_block
    permission: iasurvival.minerals.aqua_aura_block
    resource:
      material: PAPER
      generate: true
      textures:
        - block/minerals/aqua_aura_block
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles_material: PRISMARINE_BRICKS
        break_tools_whitelist:
          - PICKAXE
          - pickaxe
        sound: 
          break: 
            name: BLOCK_STONE_BREAK
            volume: 1
            pitch: 0.9
          place: 
            name: BLOCK_STONE_PLACE
            volume: 1
            pitch: 0.9
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/121085310/aa2464b2-0987-40cc-8c35-4f560b474817)

**Comment by LoneDev6** [comment] 2023-05-13 11:51
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/31#issuecomment-521959968

**Closed by LoneDev6** 2023-05-13 11:51 UTC
Labels: type: bug
