### ISSUE TITLE
API method to get all recipes

### ISSUE THREAD

**Issue by dan28000** [PluginBugs/Issues-ItemsAdder#2624] opened 2023-05-15 16:43 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

method in API to return all recipes that are loaded can be a new class called CustomRecipe contaning recipe name, group, crafting type and container, ingridients and output CustomStack and additional crafting data
ingridients could be a map of Integer and CustomStack

### Is your feature request related to a problem?

Currently in API there is only option to get all items but no recipes for them I want to add those recipes to other plugin that already handles recipe GUI

### Describe alternatives you've considered

There are none that I can think of

**Comment by LoneDev6** [comment] 2023-05-15 17:14
Good idea, refer also to this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2507

**Comment by LoneDev6** [comment] 2023-10-12 09:58
Duplicate of #2507

**Closed by LoneDev6** 2023-10-12 09:58 UTC
Labels: type: feature request, scope: api
