### ISSUE TITLE
Spam Could not pass event EntityDamageByEntityEvent to ItemsAdder

### ISSUE THREAD

**Issue by Belceebuh** [PluginBugs/Issues-ItemsAdder#2405] opened 2023-03-11 20:37 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Daddy Belce#8666

### What happened?

For some reason unknown to me the plugin spammed this:

https://bytebin.lucko.me/xXOo5pFCom

### Steps to reproduce the issue

only spam in console

### Server version

git-Purpur-"09970b1" (MC: 1.19.3)

### ItemsAdder Version

ItemsAdder version 3.4.0c-beta

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b614

### LoneLibs Version

LoneLibs version 1.0.23

### Error (optional)

```shell
[Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to ItemsAdder v3.4.0c-beta
java.lang.StackOverflowError: null
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.dR.a(SourceFile:53) ~[ItemsAdder_3.4.0c-beta.jar:?]
```

**Comment by LoneDev6** [comment] 2023-03-13 10:24
Will be checked, thanks

**Comment by LoneDev6** [comment] 2023-03-14 10:13
It probably is caused by a custom item you created which is damaging the entity on damage, so it gets called in a loop forever.
Example:
```yml
info:
  namespace: git_2405
items:
  damage_test:
    display_name: damage test
    resource:
      generate: false
      material: PAPER
      model_path: minecraft:block/stone
    events:
      attack:
        damage_entity:
          damage: 20   
```

**Comment by LoneDev6** [comment] 2023-03-14 10:14
Will be fixed

**Closed by LoneDev6** 2023-03-14 10:14 UTC
Labels: Bug, Need testing
