### ISSUE TITLE
Using emote will cause mainhand-item disapper

### ISSUE THREAD

**Issue by minecraft-dripdrop** [PluginBugs/Issues-ItemsAdder#2125] opened 2022-11-23 12:51 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

neverlag#6619

### What happened?

Look this video,mainhand is a wooden_sword,and offhand is a shield.
After I use /emote bow ,the wooden_sword disapper,then I swap item with offhand,the sword come back

video upload on discord:https://discord.com/channels/533407895010803753/1041819076810514462

### Steps to reproduce the issue

1. hold a item in mainhand
2. use emotes
3. the item disapper
4. swap hand
5. the item come back

### Server version

git-Purpur-1765 (MC: 1.19.2)*

### ItemsAdder Version

ItemsAdder version 3.3.0-beta-r8

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b602

### LoneLibs Version

 LoneLibs version 1.0.21

**Comment by LoneDev6** [comment] 2022-11-24 15:58
Minecraft creative mode is known to have such issues.

Basically each time the client receives an inventory packet it will overwrite the current item even if it's just a packet item and not a real item on the server.
This doesn't happen on survival because player has special internal game permissions in creative which allows any item to be spawned in the inventory without particular checks.

**Comment by LoneDev6** [comment] 2023-01-07 12:03
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2232

**Closed by LoneDev6** 2023-01-07 12:03 UTC
Labels: Bug, No solution, Clientside bug
