### ISSUE TITLE
Durability with ViaVersion, dont work fine

### ISSUE THREAD

**Issue by SliderKP** [PluginBugs/Issues-ItemsAdder#3988] opened 2024-09-05 19:50 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

exxslider

### What happened?

i updated my server from 1.20.4 to 1.21.1 and armor attributes and durabilities dosnt work fine usign advancedenchantment 9.11.0

### Steps to reproduce the issue

updating server from 1.20.4

### Server version

pufferfish 1.21.1 build 15

### ItemsAdder Version

version 10 hotfix

### ProtocolLib Version

build 726

### LoneLibs Version

LoneLibs 1.0.58

### Full Server Log

i cant uplaod to mclo.gs

**Comment by Andre601** [comment] 2024-09-05 20:51
> i cant uplaod to mclo.gs

If you can't upload to that site, use any other paste site then such as https://paste.helpch.at, https://pastes.dev or similar.

**Comment by SliderKP** [comment] 2024-09-05 20:55
> > i cant uplaod to mclo.gs
> 
> If you can't upload to that site, use any other paste site then such as https://paste.helpch.at, https://pastes.dev or similar.

https://paste.helpch.at/iyisorixob.makefile

**Comment by SliderKP** [comment] 2024-09-05 21:37
![image](https://github.com/user-attachments/assets/c287b890-af16-4789-a29b-944559110eb1)
im not using leak actually, just in this test server xD

**Comment by LoneDev6** [comment] 2024-09-06 14:39
Provide a video of the issue and configurations of the items which have issues.

**Comment by SliderKP** [comment] 2024-09-06 18:55
> Provide a video of the issue and configurations of the items which have issues.

in this image you can see the problem:
![image](https://github.com/user-attachments/assets/308adfa9-0ff8-4f25-b688-4c811ed04117)
"Durabilidad 26/55"
(durability 26/55) and when i stay in older version (1.20.4) the durability working are the upside ("Durabilidad 602/602")
this is the config:
```
  ecknighthelmet:
    display_name: Knight Helmet
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsbundle/ecdarkknighthelmet.png
    durability:
      max_custom_durability: 602
    specific_properties:
      armor:
        slot: head
        custom_armor: ecknightarmor
    attribute_modifiers:
      head:
        armor: 8
        armorToughness: 3
```

Thanks a lot for your answer, if u think this is not detailed i can make a video but, i think is innecesary, i still waiting for another answer.

**Comment by DxrkCat** [comment] 2024-09-13 09:25
https://p.reflex.rip/onoj.md some problem

**Comment by SliderKP** [comment] 2024-09-14 04:52
That can be fixed soon? @LoneDev6

**Comment by SliderKP** [comment] 2024-09-17 13:00
I think this error is something similar to the problem happens on this issue:
https://github.com/GC-spigot/AdvancedEnchantments/issues/4228#issuecomment-2177911056

**Comment by SliderKP** [comment] 2024-09-17 13:19
the error occours when the user joins with 1.20.4 version, if the user join with 1.21.1 looks to work fine, 
![image](https://github.com/user-attachments/assets/8307f7ce-79b9-47cd-a5de-b8d6b5a0b309)

**Comment by Andre601** [comment] 2024-09-17 14:45
Not sure if I understood you right here. The server is 1.21.1? If so, then having clients joining with 1.20.4 encountering issues with AE is not a IA issue here, but more an issue with ViaVersion, which we highly recommend you **not** use for anything more than a multi-version lobby server.

See #1876 for more info.

**Comment by SliderKP** [comment] 2024-09-17 16:41
> Not sure if I understood you right here. The server is 1.21.1? If so, then having clients joining with 1.20.4 encountering issues with AE is not a IA issue here, but more an issue with ViaVersion, which we highly recommend you **not** use for anything more than a multi-version lobby server.
> 
> See #1876 for more info.

yes my server is 1.21.1 and im using viaversion and viabackwards on 5.0.3

im from latin america and not all my users can use the latest version, i think is a ItemsAdder problem because durability looks fine in 1.21.1 but not when im join in 1.20.4, i think this problem is not related with AE actually, just maybe with ViaPlugins and ItemsAdder in the images, and in 1.21.1 the texturepack dosnt work, simply i get an error when trying to load it and dont getting errors on console or anything, just "Error al cargar el recurso" in enligsh: "error loading the texturepack"

**Comment by SliderKP** [comment] 2024-09-24 01:44
Texturepack now works fine in 1.21.1 but the durability continues broken

**Comment by Askeshine** [comment] 2024-10-02 03:08
Same problem here.

New server only with itemsAdder and ViaVersion

**Comment by Andre601** [comment] 2024-10-02 11:24
I will close this issue given that ItemsAdder does not actively support nor recommend ViaVersion to be used outside a lobby-server.
This plugin causes way too many issues, especially with the item changes introduced in 1.20.5, which may be the cause of this.

If LoneDev thinks this is an issue worth fixing will he most likely do so and provide a response here, but given his own comment on ViaVersion (See my linked issue above) is it unlikely he will implement a fix, especially if ViaVersion could be at fault here too.

**Closed by Andre601** 2024-10-02 11:24 UTC
Labels: type: bug

**Comment by SliderKP** [comment] 2024-10-02 14:36
I understand until many people complain about the inconvenience, we will ignore those who have it, a shame but I bought this plugin to use it.

**Comment by sennby** [comment] 2024-10-04 15:24
My viaversion is 1.20.6+ and this issue still is railing me bad.

**Comment by LoneDev6** [comment] 2024-11-05 15:26
Without any clear way to reproduce the issue I can't do anything.
Anyway could be a ViaVersion issue as far as I know.
