### ISSUE TITLE
Better custom leaves

### ISSUE THREAD

**Issue by Momaxguy** [PluginBugs/Issues-ItemsAdder#2899] opened 2023-07-24 16:51 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

_mo_max_

### Describe the solution you'd like

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/95580747/d1d5e06b-a99f-4517-bbc1-86efcf87532d)
**How to add Better custom leaves:** Freeze the distance from log state and give each leaf a custom texture based on that I know %100 this would work because that is what a certain minecraft server does to add custom leaves.

Message me on discord for better explation.

### Is your feature request related to a problem?

Yes, I would like to add trees with real leaves and this would fix my problems.

### Describe alternatives you've considered

I have used the chorus block 1 but its not the same. And I will not be using spawners.

**Comment by LoneDev6** [comment] 2023-07-26 10:15
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2399

**Closed by LoneDev6** 2023-07-26 10:15 UTC
Labels: type: feature request
