### ISSUE TITLE
Error loading region file

### ISSUE THREAD

**Issue by matipoirierg** [PluginBugs/Issues-ItemsAdder#2560] opened 2023-04-20 00:33 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

maty#5498

### What happened?

When I load a new world to the server itemsadder go crazy and start spamming errors in console https://pastebin.com/gmKqupDb
Problem is not fixed by restarting the server so rn I can't read console due to this errors spamming all the time. It would be nice an option to make itemsadder don't access worlds for region data/chunks, I don't even use that feature and still the plugin creates a folders on all my worlds to convert regions.

### Steps to reproduce the issue

import an external pre-generated world to a server with itemsadder

### Server version

git-purpur-1962

### ItemsAdder Version

3.4.1-r6

### ProtocolLib Version

5.0 - 636

### LoneLibs Version

1.0.24

### FULL server log

Impossible it's too big due to the spam

### Error (optional)

```shell
https://pastebin.com/gmKqupDb
```

**Comment by matipoirierg** [comment] 2023-04-20 01:44
https://pastebin.com/B1WcDD9k
also getting this errors

**Comment by LoneDev6** [comment] 2023-04-28 15:22
Post the whole server log of when the issue occurred.

**Comment by matipoirierg** [comment] 2023-04-28 20:24
the issue is happening all the time I don't have the logs when it started

**Comment by matipoirierg** [comment] 2023-04-28 20:26
> https://pastebin.com/B1WcDD9k also getting this errors

I'm pretty sure this error is the first one

**Comment by LoneDev6** [comment] 2023-05-02 12:34
delete the world, remove terralith and rest if the error persists.

**Comment by matipoirierg** [comment] 2023-05-05 21:59
> delete the world, remove terralith and rest if the error persists.

Found the triiger, happens if you set convert-legacy-ia-region-files to false,

**Comment by LoneDev6** [comment] 2023-05-08 10:01
> convert-legacy-ia-region-files

Thanks, this is the cause, will be fixed in the upcoming version.

> Also, is ia.m.cQ.b() related to that function? I've enabled it back, so I can use my console again, but I have noticed worse performance by the plugin.

ia.m.cQ is related to the `fix-glitched-blocks` property of config.yml
It's the logic which fixes glitched mushrooms and similar: https://itemsadder.devs.beer/faq/blocks-minerals-issues/custom-blocks-glitch-texture/avoid-glitched-blocks

You can disable it if you don't need.

**Closed** 2023-05-08 14:48 UTC
Labels: type: bug
