### ISSUE TITLE
Add Built In Geyser Support [Read, Don't Ignore]

### ISSUE THREAD

**Issue by CitizenPrayer** [PluginBugs/Issues-ItemsAdder#1999] opened 2022-09-30 15:23 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

CitizenPrayer🙏#7777

### Describe the solution you'd like

I have been trying to get this to work for quite some time now. Using Geyser and ItemsAdder together is a dream I wish could work the best way possible. Given the amount of support both Geyser and ItemsAdder teams have provided and brought together, I feel like some collaboration can be done to make this a more fluid-supported feature.

Here's the gist of what I'm asking.

Geyser has several features that already work well for customer data packs, and ItemsAdder already zips resource packs and makes them available with the /iazip command.

[Geyser's Custom Data Pack Working Solution](https://discord.com/channels/613163671870242838/1008027013161959444/1008028235608621096)

At the very least, I would like to ask if this functionality can be created:

- User issues: /iazip
- In addition to zipping and uploading the new resource pack, convert and create a bedrock resource pack
     - Base this bedrock pack off of Geyser's provided API: https://wiki.geysermc.org/geyser/custom-items/#geyser-extensions
- Add the mcpack file to /plugins/geyser-spigot/packs/
- Add the geyser_mappings.json file to /plugins/geyser-spigot/custom-mappings/
- Schedule or conduct a server reboot (this is required for geyser to be able to host the newly created resource pack)

Given this collaboration, I think this feature could be done mostly automated, making it much simpler for the end user.

Additionally, please make pre-made default resource packs for java fully compatible and hosted for bedrock as well. The functionality is there, and those resource packs need to be made available on the website (pretty please).

### Is your feature request related to a problem?

This is not bug related, and is only feature related.

### Describe alternatives you've considered

Unfortunately the only other alternative is for the end user themselves to do the resource pack conversions and is entirely dependant on the skill and ability of the end user themselves.

**Comment by vp-en** [comment] 2022-09-30 15:31
Just reposting something I posted in another issue:
 

They seemingly added support for ItemsAdder in this [PR](https://github.com/GeyserMC/Geyser/pull/2822).

According to one of the Geyser developers, it [should be possible](https://github.com/GeyserMC/Geyser/issues/1114#issuecomment-1094092519) for ItemsAdder to support Geyser. It's also available on the master/release branch [as of now ](https://github.com/GeyserMC/Geyser/issues/210#issuecomment-1251361472) (3 days ago from this writing).

They have a small [wiki page](https://wiki.geysermc.org/geyser/custom-items/) up and running as well.

**Comment by LoneDev6** [comment] 2022-10-13 13:28
I don't see why you felt the urge to write: 
> Read, Don't Ignore

No report is ignored, but some are not doable.
Duplicate of: https://github.com/PluginBugs/Issues-ItemsAdder/issues/206
This is the feature request on Geyser Github and has been opened since 2020, it has more than 180 messages: https://github.com/GeyserMC/Geyser/issues/210

> According to one of the Geyser developers, it https://github.com/GeyserMC/Geyser/issues/1114#issuecomment-1094092519 for ItemsAdder to support Geyser.

ItemsAdder has an API which is also accessible from who doesn't own the plugin.
Geyser changed A LOT during the years and faced multiple rewrites.
I sincerely would prefer someone else to code this compatibility hook instead of me since I have no idea if Geyser will get another major rewrite.
I will be more than happy to help someone coding this hook but not coding it from scratch, learn the Geyser API and go through trial and error.

**Closed by LoneDev6** 2022-10-13 13:28 UTC
Labels: Feature request
