### ISSUE TITLE
Server crash on world load and unload

### ISSUE THREAD

**Issue by WaterArchery** [PluginBugs/Issues-ItemsAdder#3595] opened 2024-05-01 12:33 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

waterarchery

### What happened?

When a world is loaded or unloaded by MythicDungeons or AdvancedSlimeWorldManager, there is a chance that server crashes. It is not happening without ItemsAdder.

The "gorgonboss_4" map in the error log is generated by MythicDungeons and it is not a slime world. So, it is not related to Slime World Manager neither. 

In the other logs, server is crashing when player's island is loaded by Slime World Manager with the same error.

### Steps to reproduce the issue

It is hard to reproduce because it happens randomly. 

Load a new world with or without AdvancedSlimeWorldManager
Unload it

### Server version

[15:21:00 INFO]: Current: git-SlimeWorldManager-43 (MC: 1.20.4)*
Previous: git-SlimeWorldManager-15848 (MC: 1.20.4)

I am using it with Purpur

### ItemsAdder Version

[15:20:32 INFO]: ItemsAdder version 3.6.3-beta-14
[15:20:32 INFO]: Customized Minecraft without client mods!
[15:20:32 INFO]: Website: devs.beer
[15:20:32 INFO]: Author: LoneDev

### ProtocolLib Version

[15:21:24 INFO]: ProtocolLib version 5.2.0
[15:21:24 INFO]: Provides read/write access to the Minecraft protocol.
[15:21:24 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[15:21:42 INFO]: LoneLibs version 1.0.45
[15:21:42 INFO]: Collection of libs used by my plugins
[15:21:42 INFO]: Authors: LoneDev and others

I don't know why it is showing 1.0.45. I am pretty sure I am using the latest version 1.0.46

### Full server log

https://mclo.gs/DvrGhac

### Error (optional)

```shell
https://mclo.gs/39oLgNk
```

**Comment by Andre601** [comment] 2024-05-01 14:22
Could you update protocolLib to the latest development build? Maybe it's an issue with the version you're using.

Also, given you seem to use a SWM-specific fork of a server, it could also just be an issue on their end.
If you you can reproduce this bug on a Paper or Purpur server, share the logs of it please.

**Comment by WaterArchery** [comment] 2024-05-01 14:56
It is also happening on the Bukkit worlds. For example, in this log the world that crashes is not slime world. It is Bukkit world already.  

This is probably happening because ItemsAdder is trying to access a chunk that belongs to the unloaded/not exist world.

**Comment by Andre601** [comment] 2024-05-01 15:16
I still suggest to test on a Paper or Purpur server before jumping to conclusions.
This fork could mess with internals that IA may expect or use.

I can see warnings from Multiverse core too in the logs, so there may be something that may not inherently be ItemsAdder's fault.

**Comment by WaterArchery** [comment] 2024-05-01 17:22
I understand you but there is no way for me to test this issue on those platforms. This happens in very rare cases. It happens once in 6 hours of constant world loading and unloading by 150 active players. There is no way for me to imitate that load on my test server by myself.

Also, I can't just convert the jar to Paper or Purpur on the main server. Islands are located in slime worlds and they are managed by AdvancedSlimeWorldManager. If I change the jar, players can't go to their islands.

I don't know which method is triggering the error. If the method is related to ItemsAdder blocks that are located in the chunk. the config option that disables that entirely would be perfect for us. We are not using ItemsAdder blocks on those worlds.

**Comment by LoneDev6** [comment] 2024-05-02 15:34
Can you copy and paste here the part of the log where you see the error?
Thanks

**Comment by WaterArchery** [comment] 2024-05-03 07:07
Sure, I uploaded 2 of them on mclogs.

https://mclo.gs/q6aL4Z1
https://mclo.gs/meKIqfD

**Comment by bruhhhwarrior** [comment] 2024-05-09 07:50
I experience this issue currently as well.
I use MythicDungeons which quickly loads and unloads worlds,
and the dev there pointed me to this issue which seems to be mine too.

https://mclo.gs/AHCIbpB

**Comment by bruhhhwarrior** [comment] 2024-05-09 07:53
> I still suggest to test on a Paper or Purpur server before jumping to conclusions. This fork could mess with internals that IA may expect or use.
> 
> I can see warnings from Multiverse core too in the logs, so there may be something that may not inherently be ItemsAdder's fault.

hey, my comment above is on paper 1.20.1

**Comment by LoneDev6** [comment] 2024-05-09 10:11
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/3245
Currently couldn't find a clear way to reproduce the issue on a clean environment with just MythicDungeons, ItemsAdder and its dependencies.
Sadly I can't fix the issue if I can't find a clear cause of it.
I already make sure everywhere that I release the custom world data files on world unload, so this is quite strange.

**Closed** 2024-05-09 10:12 UTC
Labels: type: duplicate
