### ISSUE TITLE
[Suggestion] add a condition for loots to make blocks only drop items if mined by specific tools

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#2103] opened 2022-11-18 21:14 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

something like:

loots:
  blocks:
    ruby_ore:
      type: itemsadder:ruby_ore
      tools:
        - IRON_PICKAXE
        - GOLD_PICKAXE
        - DIAMOND_PICKAXE
        - NETHERITE_PICKAXE
        - itemsadder:ruby_pickaxe
      items:
        ruby:
          item: itemsadder:ruby
          min_amount: 1
          max_amount: 2
          chance: 100

This "tools" category would mean that if the block is broken by any other items it will drop nothing

### Is your feature request related to a problem?

I want to able to add ores that can only be obtained with iron pickaxes or higher, but I can't find anything in the docs to do that, the closest I can find is "break_tools_whitelist", but it completely prevents breaking a block with other tools and doesn't really feel vanilla at all.

### Describe alternatives you've considered

Using MythicCrucible for custom ores, but Crucible custom blocks are pretty new and not as easy as IA custom blocks (plus the documentation is terrible so it might not even be able to do it), and IA could easily end up messing up those custom blocks.

**Comment by LoneDev6** [comment] 2023-01-24 15:03
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/125

**Closed by LoneDev6** 2023-01-24 15:03 UTC
Labels: Feature request
