### ISSUE TITLE
ItemsAdder cannot run on the latest server

### ISSUE THREAD

**Issue by ZeroJoKCN** [PluginBugs/Issues-ItemsAdder#2528] opened 2023-04-12 10:52 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When I used the latest version of Paper to load ItemsAdder, I encountered many error logs, This is the first time I have encountered such an error, and I don't know what to do, This issue was not discovered in previous versions of Paper

### Steps to reproduce the issue

1.Go to the official website of Paper to download the latest server
2.Place ItemsAdder in the plugin folder
3.Start Server

### Server version

paper-1.19.4-510

### ItemsAdder Version

ItemsAdder_3.4.1-r5

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b633

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[18:42:26] [Server thread/WARN]: [ItemsAdder] Task #21 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
	at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-510]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-510]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:42:26] [Server thread/WARN]: [ItemsAdder] Task #22 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
	at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-510]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-510]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:42:26] [Server thread/WARN]: [ItemsAdder] Task #25 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
	at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-510]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-510]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:42:26] [Server thread/WARN]: [ItemsAdder] Task #26 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
	at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-510]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-510]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-510]

**Comment by LoneDev6** [comment] 2023-04-12 10:53
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2498

**Closed by LoneDev6** 2023-04-12 10:53 UTC
Labels: type: bug
