### ISSUE TITLE
Allow to use more kinds (or even ANY kind) of blocks to serve as a solid furniture's hitbox

### ISSUE THREAD

**Issue by AllayBreeze** [PluginBugs/Issues-ItemsAdder#2327] opened 2023-02-05 23:19 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Raenzil#7359

### Describe the solution you'd like

It is not perfect to just use barriers as hitboxes for various kinds of furniture. Since a server uses the furniture function, a resourse pack will be must needed, and at the same time, the texture of all blocks can be redesigned, so that more kinds of fully transparent blocks are able to be made. Therefore, can it be an additional option to allow setting the block types of the furniture hitbox?
Some application examples:
1. Create a kind of REAL_TRANSPARENT or REAL_WIRE block and make it totally transparent, then use it as a furniture's hitbox.
2. Give some kinds of blocks totally transparent textures and use them on furniture:
(1) Campfires. Perfect to make half height furnitures and slabs.
(2) Tripwire hooks. For servers enabling REAL_WIRE, tripwire hooks are usually not used anymore, so they can also be used as hitboxes.
(3) Spawners/Shulker boxes. To make opaque furniture. Shulker boxes can also be used to make containers.
(4) Chests. To make hitboxes with 14 length and width, or be used to make containers.
(5) Player heads/Mob skulls. To make hitboxes with 8 length and width.
(6) By modifying the minecraft shader core, there'll be even more blocks such as fence/fence gate/door/trapdoor/button/pressure plate/etc. that can be changed into transparent, to make more kinds of these functional blocks or other things.
3. Even if blocks have not changed their textures at all, they are still suitable to be used as furniture hitboxes at some times. Such as using lily pad to make a furniture "Lily flower", only the flower's model will be needed to make, and the furniture will be able to have same properties as normal lily pads (e.c. can be put onto water).

### Is your feature request related to a problem?

No. It's just a new idea.

### Describe alternatives you've considered

These expansion methods seem also to be quite suitable for TILE blocks? Maybe they can also be used to expand the hitbox kinds of TILEs.

### Additional context

My idea for configurations:
`behaviours:`
`    furniture:`
`        solid: true`
`        solid_hitbox_block: CAMPFIRE #BARRIER for default if this attribute is not set. If want to use a custom block use format like namespace:id.`
`        hitbox_has_functions: true #If using containers, campfires or some other functional blocks as hitbox, set if their functions can be used or not.`

Since blocks that are not barriers are hard to deal with custom hitboxes, I think it's good to disable custom hitboxes if not using BARRIER.

**Comment by LoneDev6** [comment] 2023-02-06 11:17
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/805

> By modifying the minecraft shader core, there'll be even more blocks such as fence/fence [...]

Shaders code won't be modified because tons of people will blame your server for not working correctly.
These people are the users using shaders mods which are not compatible with resourcepack shaders.
Read more here: 
https://github.com/IrisShaders/Iris/issues/1042
https://github.com/sp614x/optifine/issues/6391

There seem to be no way for shaders mods developers to support resourcepack shaders.

You will now surely want to tell me: "But I don't care if a person is using shader mods! If they want to play on my server they must disable them!"
You will lose a lot of players because of that, so you should really consider this a valid argument, a lot of people use shaders mods to play Minecraft now days, we must continue providing a complete experience also for these users.

**Closed by LoneDev6** 2023-02-06 11:17 UTC
Labels: Feature request
