### ISSUE TITLE
IA Dungeon Loot

### ISSUE THREAD

**Issue by Unipotatoo** [PluginBugs/Issues-ItemsAdder#3660] opened 2024-05-25 02:52 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Unipotatoo

### Describe the solution you'd like

I added a new item to the server, and I want players to obtain it in chests throughout the world. So ideally, there would be a new loot or world populator option that allows users to put custom itemsadder items into chest loot pools.

### Is your feature request related to a problem?

Not necessarily. 

### Describe alternatives you've considered

Currently, I havent. I do not want this item to be craftable, and it needs to be common so selling it in shops is not what I want. We came up with the idea of putting it in dungion chests. EX: Chest Minecarts in Mineshafts, Spawner dungeon loot, 1.20 vault loot, etc.. .

**Comment by LoneDev6** [comment] 2024-06-10 12:53
Duplicate of #98

**Closed by LoneDev6** 2024-06-10 12:53 UTC
Labels: type: feature request
