### ISSUE TITLE
Armor textures have simply stopped displaying, everything else does

### ISSUE THREAD

**Issue by EmptyFile000** [PluginBugs/Issues-ItemsAdder#3909] opened 2024-08-20 20:10 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

Armor textures are not displayed after server restart. They only appear as colored leather armor. When I type the command /iazip , an error "Failed to lock player movements." pops up, BUT all other textures work without problem: swords, tools, material, font, gui, emotes... I don't know why this is happening all of sudden. All I did is I switched from server version 1.20.4 to 1.21 and for a while everything worked just fine, but after the last /iazip an error popped up and the armor textures are not showing up.

### Steps to reproduce the issue

Just go in game and type /iazip

### Server version

Server is running Paper version 1.21-127-master@4e6a2a1 (2024-08-07T12:50:10Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.2-alpha-test-3

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.56

### Full Server Log

https://mclo.gs/FHKZCwJ

### Error (optional)

```shell
21:48:17[ERROR] [ItemsAdder] Failed to lock player movements.
21:48:20[ERROR] Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.NoSuchFieldError: Class net.minecraft.world.entity.Entity does not have member field 'net.minecraft.server.level.ChunkMap$TrackedEntity tracker'
at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.a(SourceFile:147) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.b(SourceFile:39) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.jG.c(SourceFile:334) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.iR.aQ(SourceFile:112) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.mg.nz(SourceFile:67) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.mf.by(SourceFile:118) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.lX.a(SourceFile:255) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor600.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-127-4e6a2a1]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleResourcePackResponse(ServerCommonPacketListenerImpl.java:233) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:30) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:15) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-127-4e6a2a1]
at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

### Screenshots/Videos (you can drag and drop files or paste links)

![f45ec3g5e4a3](https://github.com/user-attachments/assets/8ed5d572-0890-4d60-8c3b-3d93e1469195)

**Comment by Andre601** [comment] 2024-08-20 21:49
The error reported is a duplicate of and related to #3854
And the leather armor thing may be related to #3896 (Try the steps suggested by PSYCHER [here](https://github.com/PluginBugs/Issues-ItemsAdder/issues/3896#issuecomment-2294957461))

Please check the issue tracker next time for the error before writing an issue. Thanks.

**Closed by Andre601** 2024-08-20 21:49 UTC
Labels: type: bug

**Comment by PSYCHEER** [comment] 2024-08-21 04:39
Additionally for the error, look in config.yml for lock-player and disable it, it will throw no more error
As is not recommended to do /iazip with online players etc and on 1.21 loads RP on playerprejoin event, after RP is loaded successfully, then is player positioned into world. So no need to lock them in place anymore
