### ISSUE TITLE
Error in console when player dies

### ISSUE THREAD

**Issue by Nunchakin** [PluginBugs/Issues-ItemsAdder#3441] opened 2024-02-18 10:44 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

nunchakin

### What happened?

I got this error in console when player left the server and died (it's setup for combat mode that when player leaves the server while he is in combat, he dies). I'm not sure what it means, but it could be a problem so I just want to let you know that.

### Steps to reproduce the issue

A player dies and leaves the server at the same time.

### Server version

This server is running Paper version git-Paper-429 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 351923d)
You are running the latest version
Previous version: git-Paper-426 (MC: 1.20.4)

### ItemsAdder Version

[11:42:53 INFO]: ItemsAdder version 3.6.3-beta-12

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

 LoneLibs version 1.0.45

### Error (optional)

```shell
[11:14:38 ERROR]: Could not pass event PlayerRespawnEvent to ItemsAdder v3.6.3-beta-12
java.lang.NullPointerException: Cannot read field "D" because the return value of "java.util.Map.get(Object)" is null
at ia.m.bp.a(SourceFile:423) :[ItemsAdder_3.6.3-beta-12.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) :[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) :[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-429]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) :[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) :[paper-1.20.4.jar:git-Paper-429]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) :[paper-1.20.4.jar:git-Paper-429]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) :[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:913) :[paper-1.20.4.jar:git-Paper-429]
at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:816) :[paper-1.20.4.jar:git-Paper-429]
at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:811) :[paper-1.20.4.jar:git-Paper-429]
at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.respawn(CraftPlayer.java:3264) :[paper-1.20.4.jar:git-Paper-429]
at com.nickuc.login.ςλενφεΨΛνγεΦΦο.d(:48) :[?:?]
at com.nickuc.login.ΓφτνρνυρΣ.c(:43) :[?:?]
at com.nickuc.login.ςλενφεΨΛνγεΦΦο.c(:40) :[?:?]
at com.nickuc.login.βκνξςλχζΦηζΓΓζ.a(:179) :[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor122.execute(Unknown Source) :[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) :[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) :[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-429]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) :[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) :[paper-1.20.4.jar:git-Paper-429]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) :[paper-1.20.4.jar:git-Paper-429]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) :[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:344) :[paper-1.20.4.jar:git-Paper-429]
at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) :[paper-1.20.4.jar:git-Paper-429]
at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) :[paper-1.20.4.jar:git-Paper-429]
at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) :[paper-1.20.4.jar:git-Paper-429]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) :[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) :[paper-1.20.4.jar:git-Paper-429]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) :[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) :[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) :[paper-1.20.4.jar:git-Paper-429]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) :[paper-1.20.4.jar:git-Paper-429]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) :[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) :[paper-1.20.4.jar:git-Paper-429]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) :[paper-1.20.4.jar:git-Paper-429]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) :[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) :[paper-1.20.4.jar:git-Paper-429]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) :[paper-1.20.4.jar:git-Paper-429]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) :[paper-1.20.4.jar:git-Paper-429]
at java.lang.Thread.run(Thread.java:840) :[?:?]
```

**Comment by LoneDev6** [comment] 2024-02-20 14:12
Can't reproduce it but should be fixed.

**Comment by Nunchakin** [comment] 2024-02-20 16:53
Yes it's fixed, thank you very much!

**Closed** 2024-02-20 16:53 UTC
Labels: type: bug, verdict: can't reproduce
