### ISSUE TITLE
Color water cannot be placed 

### ISSUE THREAD

**Issue by 1111qqjzja** [PluginBugs/Issues-ItemsAdder#2641] opened 2023-05-18 15:39 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Color water cannot be placed,I restart the server it's not working,when I placed the color water the background will report an error

### Steps to reproduce the issue

null

### Server version

This server is running Paper version git-Paper-306 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: b07d5e0)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-307 (MC: 1.19.2)

### ItemsAdder Version

itemsadder version 3.4.1c

### ProtocolLib Version

protocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

lonelibs version 1.0.24

### FULL server log

https://mclo.gs/wivgC4q

**Comment by LoneDev6** [comment] 2023-05-18 17:26
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2639
Please do not open multiple reports for the same thing. Do not spam the repository.

**Closed** 2023-05-18 17:26 UTC
Labels: type: bug
