### ISSUE TITLE
All tools can break blocks but only 1 can break it fast

### ISSUE THREAD

**Issue by Momaxguy** [PluginBugs/Issues-ItemsAdder#2900] opened 2023-07-24 16:57 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

_mo_max_

### Describe the solution you'd like

I would Like to be able to be able to have custom stone be mined fast with a pickaxe but slow with a axe. BUT STILL ABLE TO BE MINED WITH A AXE (I dont want any thing to drop when mined with a axe). I would like it to work the same way as regular vanilla stone.

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

Whitelist and blacklist. But it doesn't work the way I want it to.

**Comment by LoneDev6** [comment] 2023-09-03 14:09
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/1268

**Closed by LoneDev6** 2023-09-03 14:09 UTC
Labels: type: feature request
