### ISSUE TITLE
Errors in console / Resourcepack doesn't load | Paper 1.19.4

### ISSUE THREAD

**Issue by xIdentified** [PluginBugs/Issues-ItemsAdder#2518] opened 2023-04-08 18:43 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

xIdentified#6759

### What happened?

I updated to Paper build #499 and ItemsAdder version [3.4.1-r5]. Now when I start my server, I get a ton of errors in console and when I join the game my resourcepack does not load. I get stuck standing there with a black screen that tells me the pack is loading, but it never does and my character remains locked in place. 

### Steps to reproduce the issue

1. Update to paper 499
2. Use latest itemsadder
3. self host resource pack
4. join game

### Server version

Paper build #499 

### ItemsAdder Version

ItemsAdder version 3.4.1-r5

### ProtocolLib Version

Build #631 (Apr 8, 2023, 1:58:28 AM)

### LoneLibs Version

Lonelibs version 1.0.24

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11183917/latest.log)

### Error (optional)

```shell
[13:42:00 WARN]: [ItemsAdder] Task #3880 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:42:00 WARN]: [ItemsAdder] Task #3884 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:42:00 WARN]: [ItemsAdder] Task #3887 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:42:00 WARN]: [ItemsAdder] Task #3890 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:42:00 WARN]: [ItemsAdder] Task #3893 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:42:00 WARN]: [ItemsAdder] Task #3896 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:42:00 WARN]: [ItemsAdder] Task #3899 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:42:00 WARN]: [ItemsAdder] Task #3902 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:42:00 WARN]: [ItemsAdder] Task #3905 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:42:04 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.4.1-r5
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at ia.nms.aF.impl.v1_19_R3.a(SourceFile:205) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.nms.aF.aK.a(SourceFile:55) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.iJ.cB(SourceFile:111) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.iI.ak(SourceFile:184) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.iA.a(SourceFile:175) ~[ItemsAdder_3.4.1-r5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor999.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-499]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-499]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-499]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleResourcePackResponse(ServerGamePacketListenerImpl.java:2075) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by ofunny** [comment] 2023-04-09 00:02
Can confirm the issue, performed an update from ItemsAdder 3.3.1 to v3.4.1-r5 and from Paper 1.19.3 to 1.19.4 build 499 and ItemsAdder throws `java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'` on each chunk load.

Breaking bug!

**Comment by ofunny** [comment] 2023-04-09 18:14
A little update: This bug only occurs with Paper 1.19.4 build 499 and higher. The builds 499, 500 and 501 (https://papermc.io/downloads/paper) did some upstream merges with Bukkit, CraftBukkit and Spigot, according to Paper there have been internal changes on the Spigot side so it might be necessary to adapt NMS here.

**Comment by aXe18** [comment] 2023-04-09 19:56
Yeah same here

**Comment by IncludivicS** [comment] 2023-04-10 14:47
Same here too.

**Comment by LoneDev6** [comment] 2023-04-12 10:19
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2498

**Closed by LoneDev6** 2023-04-12 10:19 UTC
Labels: type: bug
