### ISSUE TITLE
Per action cooldown and etc

### ISSUE THREAD

**Issue by DxrkCat** [PluginBugs/Issues-ItemsAdder#2803] opened 2023-06-23 09:22 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Can you implement a delay for a specific action, rather than as now only for all events.

### Is your feature request related to a problem?

Yes, I can not competently customize, my desires, to make a delay for certain actions at the items.

### Describe alternatives you've considered

    events:
      interact:
        right:
          potion_effect:
            cooldown: 200
            amplifier: 1
            duration: 500
            type: LEVITATION

**Comment by DxrkCat** [comment] 2023-06-23 09:43
target_potion_effect:
          type: LEVITATION

No duration and amplifier of effect

**Comment by DxrkCat** [comment] 2023-06-23 09:52
block_break:
        multiple_break:
          size: 3
          keep_ores: true
          drop_all_blocks:
            enabled: true
            need_silk_touch: true

Add binding to a block or to all blocks, or add lists (Strange that a shovel can break trees 3 by 3)

**Comment by DxrkCat** [comment] 2023-06-23 11:34
potion_effect:
          amplifier: 0
          duration: 9999999999
          type: WATER_BREATHING
          
I don't know if there is such a feature, but this one in the example doesn't work. You can't make the effect infinite.

**Comment by DxrkCat** [comment] 2023-06-23 19:53
events:
      bow_shot:
        decrement_durability:
          amount: 6
        execute_commands:
          burn_cmd:
            command: "burn {target-player} -s"
            as_console: true
            
{target-player} doesn't working in bow_shot

**Comment by LoneDev6** [comment] 2023-06-24 14:06
Please do not send multiple messages, edit the previous message.
I get 1 notification for each one of these messages.

Thanks.

**Comment by DxrkCat** [comment] 2023-06-24 16:41
> Please do not send multiple messages, edit the previous message. I get 1 notification for each one of these messages.
> 
> You also are reporting multiple suggestions in the same page. Don't do that. Use a single page for each one of the suggestions.
> 
> Thanks.
> 
> > Per action cooldown and etc
> 
> It's already implemented, it should work even if not shown by the files editor as suggestion: `delay` property. Let me know if it works.
> 
> ```yaml
> events:
>   interact:
>     right:
>       potion_effect:
>         cooldown: 200
>         amplifier: 1
>         duration: 500
>         type: LEVITATION
>         delay: 40
> ```

No you do not understand it is a delay so that the player is not used often events that is delay for each individual event, but not for all at once.

**Comment by LoneDev6** [comment] 2023-06-26 08:40
How would you notify the user about the cooldown per-event?
It will definitely cause confusion to the player.

**Comment by yorik100** [comment] 2023-06-27 09:36
> How would you notify the user about the cooldown per-event? It will definitely cause confusion to the player.

I see that being useful in cases of small cooldowns like 1-2 secs paired with https://github.com/PluginBugs/Issues-ItemsAdder/issues/2779

**Comment by LoneDev6** [comment] 2023-07-04 16:12
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2834

**Closed** 2023-07-04 16:12 UTC
Labels: type: feature request, status: need more info, status: need testing
