### ISSUE TITLE
[BUG] [Mobs] CreaturesPlus - ItemsAdder addon 0.1 > Mobs do not spawn without adding lines in the mobs.yml file

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1121] opened 2021-08-20 14:08 UTC
**Describe the bug**
Hello, I'm coming back to you about this addon, I know you had fixed something in itemsAdder itself so that the mobs work again when I contacted you a few months ago, I had not changed my config file "mobs.yml" that I had to modify so that they want to spawn, without modification none of the 2 mobs spawns even if I only touch the setting "chance: 90" to try to have nothing at all! I then tried "max_sky_light: 15" but nothing spawns, I added to the Soul "spawn_another: true" same nothing, I also added to the Soul "material: POTION" comparing with the "brush_stooge" nothing, I changed "lore-0-soul" in "lore-1-soul" always comparing with the "brush_stooge", I changed "start: MIDNIGHT" in "start: NOON" = nothing nothing none of the 2 mobs spawns ! And finally I added the line which was not there "end: MIDNIGHT" and there immediately after restart of the server that spawns everywhere the 2 mobs.
So I confirm that it is necessary to modify the configuration of this Addon otherwise nothing spawns naturally.
I don't say that I made all the right settings but I know that thanks to those the mobs spawn naturally.
Would it be possible to make a new version with the right settings, thanks.
If I ask for a new version it's for the others already but also because by making these modifications I regularly have a lot of errors in my server console and it's very annoying I can't follow when it happens what's happening on the server, so I think I need to improve my settings.

Here are my settings which are for some personal choices so not everyone will want certain settings but with these settings the 2 mobs spawn directly at night :
-----------------------
info:
namespace: creaturesplus
items:
soul:
enabled: true
display_name: display-name-soul
permission: creaturesplus
click_in_ia_gui: false
lore:
- lore-1-soul
- lore-life-soul
- lore-2-soul
- lore-3-soul
- lore-4-soul
- lore-5-soul
- lore-6-soul
- lore-7-soul
- lore-8-soul
resource:
generate: false
material: POTION
model_path: "mob/soul/soul"
behaviours:
mob:
ai: HUSK
hit_color: ff7e7e
max_health: 40
lock_head_rotation:
y: 0
animation:
attack: soul_attack
walk: soul_walking
# potion_effects:
# SLOW_FALLING:
# type: SLOW_FALLING
# amplifier: 100
# duration: 9999999
replace_mobs_spawn:
mob1:
type: ZOMBIE
spawn_another: true
reason: NATURAL
chance: 90
time:
start: NOON
end: MIDNIGHT
soul_walking:
display_name: soul_walking
permission: creaturesplus
show_in_ia_gui: false
resource:
generate: false
material: POTION
model_path: "mob/soul/walking"
soul_attack:
display_name: soul_attack
permission: creaturesplus
show_in_ia_gui: false
resource:
generate: false
material: POTION
model_path: "mob/soul/attack"
brush_stooge:
enabled: true
display_name: display-name-brush_stooge
permission: creaturesplus
click_in_ia_gui: false
lore:
- lore-1-brush_stooge
- lore-life-brush_stooge
- lore-2-brush_stooge
- lore-3-brush_stooge
- lore-4-brush_stooge
resource:
generate: false
material: POTION
model_path: "mob/brush_stooge/brush_stooge"
behaviours:
mob:
ai: SILVERFISH
baby: true
hit_color: ff7e7e
max_health: 30
lock_head_rotation:
y: true
animation:
walk: brush_stooge_walking
replace_mobs_spawn:
mob1:
type: ZOMBIE
spawn_another: true
reason: NATURAL
chance: 90
time:
start: NOON
end: MIDNIGHT
brush_stooge_walking:
display_name: brush_stooge_walking
permission: creaturesplus
show_in_ia_gui: false
resource:
generate: false
material: POTION
model_path: "mob/brush_stooge/walking"
loots:
mobs:
soul:
type: HUSK
metadata:
ItemsAdderMob:
name: "ItemsAdderMob"
value: "creaturesplus:soul"
type: "string"
items:
LEATHER:
item: EMERALD
min_amount: 1
max_amount: 3
chance: 30
SLIME_BALL:
item: SLIME_BALL
min_amount: 1
max_amount: 2
chance: 100
brush_stooge:
type: SILVERFISH
metadata:
ItemsAdderMob:
name: "ItemsAdderMob"
value: "creaturesplus:brush_stooge"
type: "string"
items:
LEATHER:
item: EMERALD
min_amount: 1
max_amount: 2
chance: 30
SLIME_BALL:
item: SLIME_BALL
min_amount: 1
max_amount: 2
chance: 100 

**To Reproduce**

Here are the errors that I have in the console of the server in relation to the mobs but the mobs are well present on the server and work, so my settings must surely be reviewed and corrected or validated I know nothing :

>.... [09:31:20 ERROR]: [ItemsAdder] Corrupted mob file for entity 02f05477-3163-4e79-9981-d66099f74860
>.... [09:31:20 WARN]: java.lang.NullPointerException: Cannot invoke "me.libraryaddict.disguise.disguisetypes.FlagWatcher.setDisguise(me.libraryaddict.disguise.disguisetypes.TargetedDisguise)" because the return value of "me.libraryaddict.disguise.disguisetypes.TargetedDisguise.getWatcher()" is null
>.... [09:31:20 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerDisguise.deserialize(SerializerDisguise.java:29)
>.... [09:31:20 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerDisguise.deserialize(SerializerDisguise.java:11)
>.... [09:31:20 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
>.... [09:31:20 WARN]: at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
>.... [09:31:20 WARN]: at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:887)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:852)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:801)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:773)
>.... [09:31:20 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:244)
>.... [09:31:20 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:295)
>.... [09:31:20 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:290)
>.... [09:31:20 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.d(SourceFile:403)
>.... [09:31:20 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1085.execute(Unknown Source)
>.... [09:31:20 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [09:31:20 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [09:31:20 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [09:31:20 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:875)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$15(PlayerChunk.java:775)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1080)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1057)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1235)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:672)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
>.... [09:31:20 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [09:31:20 WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
>.... [09:31:20 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerFlagWatcher.deserialize(SerializerFlagWatcher.java:34)
>.... [09:31:20 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerFlagWatcher.deserialize(SerializerFlagWatcher.java:24)
>.... [09:31:20 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
>.... [09:31:20 WARN]: at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
>.... [09:31:20 WARN]: at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:887)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:952)
>.... [09:31:20 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
>.... [09:31:20 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerDisguise.deserialize(SerializerDisguise.java:22)
>.... [09:31:20 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerDisguise.deserialize(SerializerDisguise.java:11)
>.... [09:31:20 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
>.... [09:31:20 WARN]: at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
>.... [09:31:20 WARN]: at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:887)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:852)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:801)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:773)
>.... [09:31:20 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:244)
>.... [09:31:20 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:295)
>.... [09:31:20 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:290)
>.... [09:31:20 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.d(SourceFile:403)
>.... [09:31:20 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1085.execute(Unknown Source)
>.... [09:31:20 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [09:31:20 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [09:31:20 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [09:31:20 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:875)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$15(PlayerChunk.java:775)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1080)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1057)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1235)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:672)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
>.... [09:31:20 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [09:31:20 ERROR]: [ItemsAdder] Corrupted mob file for entity b55fd047-d612-4d7a-80ba-354c72ec8d01
>.... [09:31:20 WARN]: java.lang.NullPointerException: Cannot invoke "me.libraryaddict.disguise.disguisetypes.FlagWatcher.setDisguise(me.libraryaddict.disguise.disguisetypes.TargetedDisguise)" because the return value of "me.libraryaddict.disguise.disguisetypes.TargetedDisguise.getWatcher()" is null
>.... [09:31:20 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerDisguise.deserialize(SerializerDisguise.java:29)
>.... [09:31:20 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerDisguise.deserialize(SerializerDisguise.java:11)
>.... [09:31:20 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
>.... [09:31:20 WARN]: at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
>.... [09:31:20 WARN]: at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:887)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:852)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:801)
>.... [09:31:20 WARN]: at com.google.gson.Gson.fromJson(Gson.java:773)
>.... [09:31:20 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:244)
>.... [09:31:20 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:295)
>.... [09:31:20 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:290)
>.... [09:31:20 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.d(SourceFile:403)
>.... [09:31:20 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1085.execute(Unknown Source)
>.... [09:31:20 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [09:31:20 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [09:31:20 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [09:31:20 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:875)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$15(PlayerChunk.java:775)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1080)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1057)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1235)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:672)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
>.... [09:31:20 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
>.... [09:31:20 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [09:31:44 WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
>.... [09:31:44 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerFlagWatcher.deserialize(SerializerFlagWatcher.java:34)
>.... [09:31:44 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerFlagWatcher.deserialize(SerializerFlagWatcher.java:24)
>.... [09:31:44 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
>.... [09:31:44 WARN]: at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
>.... [09:31:44 WARN]: at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
>.... [09:31:44 WARN]: at com.google.gson.Gson.fromJson(Gson.java:887)
>.... [09:31:44 WARN]: at com.google.gson.Gson.fromJson(Gson.java:952)
>.... [09:31:44 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
>.... [09:31:44 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerDisguise.deserialize(SerializerDisguise.java:22)
>.... [09:31:44 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerDisguise.deserialize(SerializerDisguise.java:11)
>.... [09:31:44 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
>.... [09:31:44 WARN]: at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
>.... [09:31:44 WARN]: at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
>.... [09:31:44 WARN]: at com.google.gson.Gson.fromJson(Gson.java:887)
>.... [09:31:44 WARN]: at com.google.gson.Gson.fromJson(Gson.java:852)
>.... [09:31:44 WARN]: at com.google.gson.Gson.fromJson(Gson.java:801)
>.... [09:31:44 WARN]: at com.google.gson.Gson.fromJson(Gson.java:773)
>.... [09:31:44 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:244)
>.... [09:31:44 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:295)
>.... [09:31:44 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:290)
>.... [09:31:44 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.d(SourceFile:403)
>.... [09:31:44 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1085.execute(Unknown Source)
>.... [09:31:44 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [09:31:44 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [09:31:44 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [09:31:44 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:875)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$15(PlayerChunk.java:775)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1080)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1057)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1235)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:874)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:683)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:850)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:767)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
>.... [09:31:44 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [09:31:44 ERROR]: [ItemsAdder] Corrupted mob file for entity c16743a3-a87d-460e-88d1-d38b75db423d
>.... [09:31:44 WARN]: java.lang.NullPointerException: Cannot invoke "me.libraryaddict.disguise.disguisetypes.FlagWatcher.setDisguise(me.libraryaddict.disguise.disguisetypes.TargetedDisguise)" because the return value of "me.libraryaddict.disguise.disguisetypes.TargetedDisguise.getWatcher()" is null
>.... [09:31:44 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerDisguise.deserialize(SerializerDisguise.java:29)
>.... [09:31:44 WARN]: at me.libraryaddict.disguise.utilities.json.SerializerDisguise.deserialize(SerializerDisguise.java:11)
>.... [09:31:44 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
>.... [09:31:44 WARN]: at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
>.... [09:31:44 WARN]: at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
>.... [09:31:44 WARN]: at com.google.gson.Gson.fromJson(Gson.java:887)
>.... [09:31:44 WARN]: at com.google.gson.Gson.fromJson(Gson.java:852)
>.... [09:31:44 WARN]: at com.google.gson.Gson.fromJson(Gson.java:801)
>.... [09:31:44 WARN]: at com.google.gson.Gson.fromJson(Gson.java:773)
>.... [09:31:44 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:244)
>.... [09:31:44 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:295)
>.... [09:31:44 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:290)
>.... [09:31:44 WARN]: at dev.lone.itemsadder.Core.f.a.c.a.a.d(SourceFile:403)
>.... [09:31:44 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1085.execute(Unknown Source)
>.... [09:31:44 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [09:31:44 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [09:31:44 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [09:31:44 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:875)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$15(PlayerChunk.java:775)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1080)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1057)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1235)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:874)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:683)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:850)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:767)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
>.... [09:31:44 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
>.... [09:31:44 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)

**Info (please complete the following information):**
 Minecraft PaperSpigot 1.16.5 #786 + java 16 et 1.17.1
[Mobs] CreaturesPlus - ItemsAdder addon 0.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: sur Paper 1.17.1 > 2.4.9 & Paper 1.16.5 > 2.4.6
 - LightAPI Fork version: sur Paper 1.17.1 >& LightAPI Fork 3.5.2 Paper 1.16.5 > LightAPI-fork-3.4.6
 - LoneLibs version: sur Paper 1.17.1 > LoneLibs 1.0.14 & Paper 1.16.5 > LoneLibs 1.0.14
 - ProtocolLib version: sur Paper 1.17.1 > #531 & Paper 1.16.5 > #531

**Comment by LoneDev6** [comment] 2021-08-21 14:42
Hello, thanks for the report.
Can you please edit your message and post the configurations and logs inside pastebin or similar? I can't read correctly and this slows down my analysis of the problem.

Thanks a lot for your time

**Comment by vdl19** [comment] 2021-08-22 10:32
Hello, I put you 2 files :

- A log of my server in 1.16.5 from a few minutes ago where if you search : 
[ItemsAdder] Corrupted mob 
you will see several of these errors.

- And I add the mob configuration file. To be able to send it easily I just renamed it to mobs.yml.txt, so just remove .txt (but it opens anyway without doing that)

Hope this helps you and is easier to process, have a nice day

[2021-08-22-6.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7027141/2021-08-22-6.log)

[mobs.yml.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/7027145/mobs.yml.txt)

**Comment by LoneDev6** [comment] 2021-08-24 08:50
Can you please use the latest version of the plugin and let me know if it works?
I see you're using `2.4.6` which is old

**Comment by vdl19** [comment] 2021-08-24 11:34
Hello, it's the same, I just installed the latest version of ItemsAdder on my test server:

Paper 1.17.1 #209 > 2.4.12 = [ItemsAdder] Corrupted mob file for entity 65df9376-c3b0-483d-877d-a1aedc09317b
> I send you the startup log, the error happens there just after the server startup but it's not just there it happens then during the game (otherwise I know there are errors on other plugins it's normal in 1.17.1 I have worlds that can't be imported and those that can some make me errors but it's not related the problem with the is the same on the official server with version 2.4.6)

It was the same with version 2.4.9 I just didn't send logs as I'm not often on the test server playing and so I trigger less mass errors in the console.
Paper 1.17.1 > 2.4.9 = ERROR

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7038749/latest.log)

**Comment by LoneDev6** [comment] 2021-09-07 16:34
Thanks, this issue will be fixed in the upcoming update.
Sadly some mobs won't load anymore if they were spawned before the update, this is caused by the fact that LibsDisguises updated their files format to support Java 16, but this has broken the old mob files.
I can't really do anything about that.

**Closed** 2021-09-08 15:40 UTC
Labels: bug

**Comment by vdl19** [comment] 2021-09-08 18:31
Good evening, the update seems to have removed all the errors that I had with the mobs, but I have other messages I put you 2 screenshots but I will make you an issue on purpose, thank you

I had blockus so I removed it at the next capture but I find myself with the same type of message:
![blockus2021-09-08_200611](https://user-images.githubusercontent.com/80985545/132565074-9176b30a-6e3c-4dd9-a726-12b3a5585c06.jpg)

![sans blockus2021-09-08_201032](https://user-images.githubusercontent.com/80985545/132565029-b4e057a9-c273-408a-a7e6-0de05a0a4bdc.jpg)

**Comment by LoneDev6** [comment] 2021-09-10 12:19
@vdl19 update the plugin
