### ISSUE TITLE
[BUG] Memory leak when testing Itemsadder on 1.17 with the latest ProtocolLib Dev Build

### ISSUE THREAD

**Issue by RedZephon** [PluginBugs/Issues-ItemsAdder#987] opened 2021-06-28 19:32 UTC
**Describe the bug**
Server crashes on boot due to out of memory error.

**To Reproduce**
1. Install Itemsadder 1.17 latest version
2. Install ProtocolLib 1.17 latest dev build
3. boot server
4. Server crashes and restarts

**Expected behavior**
Server should boot properly

**Screenshots**

**Info (please complete the following information):**
 - Server version: Paper 1.17 b53
 - Client version: 1.17 Optifine 23
 - Plugin version: 2.4.1 beta

**Additional context**
Didn't notice the memory leak on my dev server, however it was present when testing on my production hardware.

[crash-2021-06-28_15.25.34-server.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/6728835/crash-2021-06-28_15.25.34-server.txt)
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/6728836/latest.log)

**Comment by LoneDev6** [comment] 2021-06-30 08:12
Is crash still happening you remove ItemsAdder?
I don't have this problem on my server and I'm running the very latest Spigot.

Anyway would be nice to know your hardware specs, thanks.

**Comment by SirCraftypants** [comment] 2021-06-30 19:34
i was having the same problem with my Server halting on startup due to being out of memory. I'm still yet to find out which plugin out of the 72 plugins i have has a memory leak but. To solve the issue i had my Host limit the amount of memory my plugins use on startup with XmX. I requested they set it to half my ram allocation. II will get around to finding out which plugin it is but right now i don't have time as i need to learn the easiest way on how to locate the cuplrit. Can not say it's Itemsadder, this is a quick fix.

**Comment by RedZephon** [comment] 2021-07-01 00:45
> Is crash still happening you remove ItemsAdder?
> I don't have this problem on my server and I'm running the very latest Spigot.
> 
> Anyway would be nice to know your hardware specs, thanks.

Yes If I remove ItemsAdder my server boots properly. Also, if I remove ProtocolLib but leave Itemsadder it boots properly, but Itemsadder doesn't load since its a pre-requisite. Could be a combination of issues between both plugins. I opened a ticket with protocollib as well.

My Server specs are
AMD Ryzen 9 3900X (US)
10 GB DDR4 Memory
Dedicated CPU Core
Unmetered NVMe SSD*
1 GBit/s Connection

**Comment by LoneDev6** [comment] 2021-07-01 13:19
A memory leak is impossible to detect without proper tools to analyze server memory.
What makes me skeptical about the memory leak is that I didn't add any feature that could introduce this type of problem between pre 1.17 update and 1.17 update.

Try to use normal Spigot instead of Paper and let me know.
Anyway I doubt there is anything I can do about this since without a memory log I can't guess what can be the cause.
You may try to open a ticket on my Discord server and provide a file generated with this guide: https://www.spigotmc.org/threads/guide-finding-the-cause-of-a-ram-issue.272102/

**Comment by LoneDev6** [comment] 2021-07-13 12:31
Quotes from the support ticket:
> The pterodactyl panel is set to kill servers after it openns too many threads in order to prevent criplingn performance of other servers on the node
They said the best solution is for the plugin to be re-coded to stop using so many threads
They said to send this to you: https://github.com/pterodactyl/wings/commit/b618ec8877ae253d29c05613f95b3e11dc4074d0
GitHub

Basically seems to be a Pterodactyl/hosting problem.
I close this issue temporarily because I have no control or solution over this type of issues

**Closed by LoneDev6** 2021-07-13 12:31 UTC
Labels: can't reproduce, invalid
