### ISSUE TITLE
When shooting arrows, both crossbows and bows

### ISSUE THREAD

**Issue by Genomc** [PluginBugs/Issues-ItemsAdder#3828] opened 2024-07-26 10:35 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

nicesuei

### What happened?

When shooting an arrow, it will appear as shown in the picture. I checked everything correctly according to the wiki, but it appears like this.
![image](https://github.com/user-attachments/assets/d8c5d496-a594-4d1e-87f8-529d482d64bf)
![image](https://github.com/user-attachments/assets/a1369fe3-b80a-4d84-bd0d-ca895ede0a23)
![image](https://github.com/user-attachments/assets/0261997e-bbee-4ecf-a3f1-981ef3d88340)

### Steps to reproduce the issue

1.Give material custom model bow and crossbow
2.Right click hold
3.This problem occurs immediately after firing.

### Server version

This server is running Paper version 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

4.0.2-alpha-test-3

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.56

### Full server log

[latest.log](https://github.com/user-attachments/files/16390457/latest.log)

### Error (optional)

```shell
[03:34:43 ERROR]: Could not pass event EntityShootBowEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.ClassCastException: class ia.m.eH cannot be cast to class ia.m.eB (ia.m.eH and ia.m.eB are in unnamed module of loader 'ItemsAdder_4.0.2-alpha-test-3.jar' @321f32c1)
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.di.b(SourceFile:364) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-109-5a5035b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-109-5a5035b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-109-5a5035b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityShootBowEvent(CraftEventFactory.java:640) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.world.item.ProjectileWeaponItem.shoot(ProjectileWeaponItem.java:66) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.world.item.BowItem.releaseUsing(BowItem.java:35) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.world.item.ItemStack.releaseUsing(ItemStack.java:952) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.world.entity.LivingEntity.releaseUsingItem(LivingEntity.java:4127) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1770) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1536) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1513) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1506) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1465) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1472) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-109-5a5035b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by EIYISUS** [comment] 2024-08-05 02:49
tengo el mismo error

**Comment by Andre601** [comment] 2024-08-06 19:44
This is a duplicate of #3780

**Please check the issue tracker for pre-existing issues before making one!**

**Closed by Andre601** 2024-08-06 19:44 UTC
Labels: type: bug
