### ISSUE TITLE
a bug about custom block displaying

### ISSUE THREAD

**Issue by Steve29794** [PluginBugs/Issues-ItemsAdder#3891] opened 2024-08-16 08:42 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When I placed the note block on the grass block, nothing happened. When I place the note block on a stone block, the texture of the block will quickly switch. If a note box is stacked on top at this block, the block will become the texture of my custom blocks, and I can even switch between them

### Steps to reproduce the issue

1. You must have a custom block
2. Place a note block on a stone block
3. You will find that the texture switch quickly
4. Place another note block on the note block
5. The note block below will become your custom block (just texture), it still is a note block

### Server version

Current: git-Purpur-2176 (MC: 1.20.4)*
* You are running the latest version

### ItemsAdder Version

3.6.4-release-3

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.54

### Full server log

[15:20:52] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[15:20:53] [ServerMain/INFO]: Loaded 1174 recipes
[15:20:53] [ServerMain/INFO]: Loaded 1271 advancements
[15:20:53] [Server thread/INFO]: Starting minecraft server version 1.20.4
[15:20:53] [Server thread/INFO]: Loading properties
[15:20:53] [Server thread/INFO]: This server is running Purpur version git-Purpur-2127 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3d52f06 on HEAD)
[15:20:54] [Server thread/INFO]: Server Ping Player Sample Count: 12
[15:20:54] [Server thread/INFO]: Using 4 threads for Netty based IO
[15:20:54] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 2 worker threads, and gen parallelism of 2 threads
[15:20:54] [Server thread/WARN]: [Pufferfish] Will not enable SIMD! These optimizations are only safely supported on Java 17, Java 18, and Java 19.
[15:20:55] [Server thread/INFO]: Default game type: SURVIVAL
[15:20:55] [Server thread/INFO]: Generating keypair
[15:20:55] [Server thread/INFO]: Starting Minecraft server on *:12345
[15:20:55] [Server thread/INFO]: Using default channel type
[15:20:55] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[15:20:55] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[15:20:55] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loading 1 libraries... please wait
[15:20:55] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library E:\TestServer-1.20.4\libraries\org\apache\httpcomponents\httpmime\4.5.14\httpmime-4.5.14.jar
[15:20:55] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library E:\TestServer-1.20.4\libraries\org\apache\httpcomponents\httpclient\4.5.14\httpclient-4.5.14.jar
[15:20:55] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library E:\TestServer-1.20.4\libraries\org\apache\httpcomponents\httpcore\4.4.16\httpcore-4.4.16.jar
[15:20:55] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library E:\TestServer-1.20.4\libraries\commons-logging\commons-logging\1.2\commons-logging-1.2.jar
[15:20:55] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library E:\TestServer-1.20.4\libraries\commons-codec\commons-codec\1.11\commons-codec-1.11.jar
[15:20:55] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[15:20:56] [Server thread/INFO]: [LoneLibs] Loading server plugin LoneLibs v1.0.56
[15:20:56] [Server thread/INFO]: [spark] Loading server plugin spark v1.10.97
[15:20:56] [Server thread/INFO]: [ItemsAdder] Loading server plugin ItemsAdder v3.6.4-release-3
[15:20:56] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:20:56] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679
[15:20:56] [Server thread/INFO]: [LoneLibs] Enabling LoneLibs v1.0.56
[15:20:56] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[15:20:56] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[15:20:56] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[15:20:56] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[15:20:56] [Server thread/INFO]: Preparing level "world"
[15:20:56] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[15:20:57] [Server thread/INFO]: Time elapsed: 615 ms
[15:20:57] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[15:20:57] [Server thread/INFO]: Time elapsed: 26 ms
[15:20:57] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[15:20:57] [Server thread/INFO]: Time elapsed: 15 ms
[15:20:57] [Server thread/INFO]: [spark] Enabling spark v1.10.97
[15:20:57] [Server thread/INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[15:20:57] [Server thread/INFO]: [spark] Starting background profiler...
[15:20:57] [Server thread/INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows11/amd64), so the built-in Java engine will be used instead.
[15:20:57] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.6.4-release-3
[15:20:58] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Minecraft: v1_20_R3! Trying to find NMS support
[15:20:58] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_20_R3' loaded!
[15:20:58] [Server thread/INFO]: [NBTAPI] [NBTAPI] Using the plugin 'LoneLibs' to create a bStats instance!
[15:20:59] [Server thread/INFO]: [物品添加] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.6.4-release-3
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.56
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur git-Purpur-2127 (MC: 1.20.4)
                                               
[15:20:59] [Server thread/INFO]: [物品添加] [Host] Starting self-host webserver on port: 15105
[15:20:59] [Server thread/INFO]: Running delayed init tasks
[15:20:59] [Server thread/INFO]: [物品添加] [Pack] Extracting internal contents from .jar
[15:20:59] [Server thread/INFO]: [物品添加] [Pack] DONE extracting internal contents from .jar
[15:21:00] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [物品添加]  
[15:21:00] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [物品添加] UPDATE available: https://www.spigotmc.org/resources/73355/
[15:21:00] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [物品添加] Current version: 3.6.4-release-3 | Online version: 4.0.2-alpha-test-3
[15:21:00] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [物品添加]  
[15:21:00] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [物品添加] [License] Spigot product licensed to: xiaogeyr (469039)
[15:21:00] [Server thread/INFO]: Done (7.049s)! For help, type "help"
[15:21:00] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [物品添加] Loaded 163 items
[15:21:00] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [物品添加] Used 0/188 REAL block IDs
[15:21:00] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [物品添加] Used 12/750 REAL_NOTE block IDs
[15:21:00] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [物品添加] Used 0/63 REAL_TRANSPARENT block IDs
[15:21:00] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [物品添加] Used 0/127 REAL_WIRE block IDs
[15:21:00] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [物品添加] Used 0/14 FIRE block IDs
[15:21:00] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [物品添加] Used 39/6608 font_images
[15:21:00] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [物品添加] [Init] Loaded 9 categories
[15:21:01] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [物品添加] [Init] Loaded successfully.
[15:21:01] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [物品添加] [Pack] Resourcepack URL (self-host): http://127.0.0.1:15105/generated.zip
[15:21:03] [User Authenticator #0/INFO]: UUID of player Steve29794 is 8dd6136c-9321-3be5-95cb-bd896452dea9
[15:21:03] [Server thread/INFO]: Steve29794 joined the game
[15:21:03] [Server thread/INFO]: Steve29794[/127.0.0.1:59424] logged in with entity id 83 at ([world]-35.081710909164755, 68.0, -137.07579912057793)
[15:21:16] [Server thread/INFO]: Steve29794 has made the advancement [Stone Age]
[15:23:29] [Async Chat Thread - #1/INFO]: [Not Secure] <Steve29794> if the block is on the grass block, no any mistake
[15:23:49] [Async Chat Thread - #0/INFO]: [Not Secure] <Steve29794> if the block is on stone
[15:23:53] [Async Chat Thread - #1/INFO]: [Not Secure] <Steve29794> and
[15:27:59] [Server thread/INFO]: Steve29794 lost connection: Disconnected
[15:27:59] [Server thread/INFO]: Steve29794 left the game
[15:28:04] [Server thread/INFO]: Stopping the server
[15:28:04] [Server thread/INFO]: Stopping server
[15:28:04] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.6.4-release-3
[15:28:04] [pool-16-thread-1/INFO]: [物品添加] [Host] Stopped self-host webserver on port: 15105
[15:28:04] [Server thread/INFO]: [spark] Disabling spark v1.10.97
[15:28:04] [Server thread/INFO]: [LoneLibs] Disabling LoneLibs v1.0.56
[15:28:04] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v5.2.0-SNAPSHOT-679
[15:28:04] [Server thread/INFO]: Saving players
[15:28:05] [Server thread/INFO]: Saving worlds
[15:28:05] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[15:28:05] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[15:28:05] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[15:28:05] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world'
[15:28:05] [Server thread/INFO]: [ChunkHolderManager] Saved 8 block chunks, 72 entity chunks, 0 poi chunks in world 'world' in 0.04s
[15:28:05] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[15:28:05] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[15:28:05] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[15:28:05] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[15:28:05] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_nether'
[15:28:05] [Server thread/INFO]: [ChunkHolderManager] Saved 0 block chunks, 6 entity chunks, 0 poi chunks in world 'world_nether' in 0.08s
[15:28:05] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[15:28:05] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[15:28:05] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[15:28:05] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[15:28:05] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_the_end'
[15:28:05] [Server thread/INFO]: [ChunkHolderManager] Saved 0 block chunks, 0 entity chunks, 0 poi chunks in world 'world_the_end' in 0.00s
[15:28:05] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[15:28:05] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[15:28:05] [Server thread/INFO]: Flushing Chunk IO
[15:28:05] [Server thread/INFO]: Closing Thread Pool
[15:28:05] [Server thread/INFO]: Closing Server

### Error (optional)

```shell
nothing
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: custom
items:
  deepslate_ruby_ore:
    display_name: display-name-deepslate_ruby_ore
    resource:
      generate: true
      material: PAPER
      textures:
        - block/deepslate_ruby_ore.png
    specific_properties:
      block:
        cancel_drop: true
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        break_tools_whitelist:
          - DIAMOND_PICKAXE
          - NETHERITE_PICKAXE
        hardness: 12
  ruby_ore:
    display_name: display-name-ruby_ore
    resource:
      generate: true
      material: PAPER
      textures:
        - block/ruby_ore.png
    specific_properties:
      block:
        cancel_drop: true
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        break_tools_whitelist:
          - DIAMOND_PICKAXE
          - NETHERITE_PICKAXE
        hardness: 8
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/def6b5a9-d391-4ce3-a718-5e5838ab224a)
video: https://1drv.ms/v/c/45e82de034226652/EZS53drMR7hBiEo5cnGgVkcBuQYc69nej2-HjZkmUVBMgw?e=poakcS
https://1drv.ms/v/c/45e82de034226652/Ecw2ZcPSAgdLnltqt5fq9r4BmHQ0tyvrUtaCfklunrKFfA?e=PCXyQu

**Comment by LoneDev6** [comment] 2024-08-19 13:13
1. try in survival
2. probably this can't be fixed because it's predicted by the client, so I can't fix that without introducing overhead to the server (and won't be fixed completely as you'd still see it for some milliseconds due to the client delay)

**Comment by Steve29794** [comment] 2024-08-19 13:18
> 1. try in survival, it could be something that happens only in creative due to the fact that creative mode is less restrictive over some stuff.
> 2. probably this can't be fixed because it's predicted by the client, so I can't fix that without introducing overhead to the server (and won't be fixed completely as you'd still see it for some milliseconds due to the client delay)

I'm just showing you Creative mode for ease of use, and the same goes for survival mode. I don't care about the block displays wrong textures instantly, but could you fix the error of "permanent" wrong display bug?

**Comment by Steve29794** [comment] 2024-08-19 13:19
> 1. try in survival, it could be something that happens only in creative due to the fact that creative mode is less restrictive over some stuff.
> 2. probably this can't be fixed because it's predicted by the client, so I can't fix that without introducing overhead to the server (and won't be fixed completely as you'd still see it for some milliseconds due to the client delay)

I'm just showing you Creative mode for ease of use, and the same goes for survival mode. I don't care about the block displays wrong textures instantly, but could you fix the error of "permanent" wrong display bug? All of my players can look the wrong texture. Are you sure that this is a client mod bug? I used the vanilla client to test this bug and record videos.

**Comment by Steve29794** [comment] 2024-08-19 13:20
> 1. try in survival, it could be something that happens only in creative due to the fact that creative mode is less restrictive over some stuff.
> 2. probably this can't be fixed because it's predicted by the client, so I can't fix that without introducing overhead to the server (and won't be fixed completely as you'd still see it for some milliseconds due to the client delay)

All of my players can look the wrong texture. Are you sure that this is a client mod bug? I used the vanilla client to test this bug and record videos.

**Comment by Steve29794** [comment] 2024-08-19 13:40
> 1. try in survival, it could be something that happens only in creative due to the fact that creative mode is less restrictive over some stuff.
> 2. probably this can't be fixed because it's predicted by the client, so I can't fix that without introducing overhead to the server (and won't be fixed completely as you'd still see it for some milliseconds due to the client delay)

i tested this bug in vanilla client just now, please reopen this issue.
https://1drv.ms/v/c/45e82de034226652/EZosOxZwoQBIuja5-WUQxRYBzTPoW6HchedEHW85dbWiQw?e=LpiYN7

**Comment by Steve29794** [comment] 2024-08-19 14:48
> 1. try in survival, it could be something that happens only in creative due to the fact that creative mode is less restrictive over some stuff.
> 2. probably this can't be fixed because it's predicted by the client, so I can't fix that without introducing overhead to the server (and won't be fixed completely as you'd still see it for some milliseconds due to the client delay)

Are you free now?

**Comment by LoneDev6** [comment] 2024-08-19 15:45
Note that this will be fixed only on v4, v3 is legacy and won't receive new updates for minor bugs.
This is considered a minor priority bug.

If you plan to stay on 1.20.4 for a lot of months then let me know so that I can change the priority of this and backport the fix to v3 too.

**Comment by Steve29794** [comment] 2024-08-19 15:48
I'm happy I have your support.and I have plans to upgrade 1.21

**Comment by LoneDev6** [comment] 2024-08-19 15:50
Thank you so much for your kind patience

**Comment by Steve29794** [comment] 2024-08-22 14:59
Recently, I know why there will be #3885 error. 
Example, if i use /itemnbt to see the nbt of the ia item, we will see the text below
![image](https://github.com/user-attachments/assets/287ede5d-6015-4890-a2fc-819964782494)
And, if i get a ia item in creative mode, then open and close my inventory, use /itemnbt again
![image](https://github.com/user-attachments/assets/42e7430c-208e-449b-86c1-1ed4bfac3b25)
This issue also occurs when giving items to other plugins
One reason is that in creation mode the packet's fake lore is converted into actual lore
One solution is to turn the game mode to survival every time, but that doesn't solve the problem at all, and as a server staff, it's cumbersome
So can you add a judgment on the creation mode in the plugin? When the player is in creation mode, no packets will be sent.I'm sure it's easy for you.

Another issue is that no matter what game mode I'm in, when I put items into other plugins' inventories, it still converts the packet lore to actual lore, I'm not sure if that's due to ia or other plugins, but it's the same with any other plugin. I hope it can be fixed, if it really can't, forget about it :)

**Comment by LoneDev6** [comment] 2024-08-23 10:08
CREATIVE gamemode is known to cause issues with NBT because NBT is handled clientside sometimes and sometimes serverside.
The server trusts the client because is in CREATIVE, this makes some NBT changes unpredictable.

This also could be caused by another plugin, as explained here: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3885#issuecomment-2296595730

Sadly I can't do much as I don't have ideas to fix that.

I don't understand what you mean by "fake lore" as ItemsAdder doesn't use any fake lore.
The fake lore is created by another plugin and CREATIVE gamemode is consolidating it into real lore because of the special permissions owned by CREATIVE mode discussed before.

This is mostly a game issue.

**Comment by LoneDev6** [comment] 2024-08-23 10:09
Anyway you're mixing two issues, please discuss on the other issue page not here: #3885

**Comment by Steve29794** [comment] 2024-08-23 10:17
Okay, I guess I clicked the wrong button to get to this screen and leave this feedback. :)

**Comment by Steve29794** [comment] 2024-08-23 10:24
> CREATIVE gamemode is known to cause issues with NBT because NBT is handled clientside sometimes and sometimes serverside.众所周知，CREATIVE 游戏模式会导致 NBT 出现问题，因为 NBT 有时会在客户端处理，有时在服务器端处理。 The server trusts the client because is in CREATIVE, this makes some NBT changes unpredictable.服务器信任客户端，因为它处于 CREATIVE 中，这使得一些 NBT 更改不可预测。
> 
> This also could be caused by another plugin, as explained here: [#3885 (comment)](https://github.com/PluginBugs/Issues-ItemsAdder/issues/3885#issuecomment-2296595730)这也可能是由另一个插件引起的，如此处所述： [#3885 (comment)](https://github.com/PluginBugs/Issues-ItemsAdder/issues/3885#issuecomment-2296595730)
> 
> Sadly I can't do much as I don't have ideas to fix that.可悲的是，我无能为力，因为我没有解决这个问题的想法。
> 
> I don't understand what you mean by "fake lore" as ItemsAdder doesn't use any fake lore.我不明白你说的“假传说”是什么意思，因为 ItemsAdder 不使用任何假传说。 The fake lore is created by another plugin and CREATIVE gamemode is consolidating it into real lore because of the special permissions owned by CREATIVE mode discussed before.虚假的传说是由另一个插件创建的，而CREATIVE游戏模式正在将其整合为真实的传说，因为前面讨论过的CREATIVE模式拥有特殊权限。
> 
> This is mostly a game issue.这主要是一个游戏问题。

i'm so sorry, I mistakenly thought the JSON component of vanilla minecraft was made by your plugin

**Comment by Steve29794** [comment] 2024-08-23 10:38
I just discovered a new phenomenon of this issue. In addition to the note box on top of the detector, the note box on top of the detector also exhibits this issue and must be directly above the detector's face.
![image](https://github.com/user-attachments/assets/64c3572b-c502-4809-aef4-0f81ab39321b)

**Comment by Steve29794** [comment] 2024-08-23 15:08
ok thanks

**Closed** 2024-08-27 14:24 UTC
Labels: type: bug, verdict: workaround implemented
