### ISSUE TITLE
Could not pass event ArmorEquipEvent

### ISSUE THREAD

**Issue by daniel-skopek** [PluginBugs/Issues-ItemsAdder#2883] opened 2023-07-16 20:45 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

There is error in the console.

### Steps to reproduce the issue

Equip armor

### ItemsAdder Version

3.5.0c-r2

### ProtocolLib Version

5.1.0-SNAPSHOT-652

### LoneLibs Version

1.0.25

### Error (optional)

```shell
https://pastebin.com/raw/huPFAvKk
```

**Comment by LoneDev6** [comment] 2023-07-17 09:17
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2847

**Closed by LoneDev6** 2023-07-17 09:17 UTC
Labels: type: bug
