### ISSUE TITLE
MMOItems item stat randomize won't work for ItemsAdder linked items

### ISSUE THREAD

**Issue by hkkongou** [PluginBugs/Issues-ItemsAdder#2008] opened 2022-10-04 03:55 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

himehina#7861

### What happened?

1. I have an mmoitems with modifiers setting which will randomize item stats when item is taken( using mmoitems to get it).
2. when i hooked the mmoitems to itemadder using the compatibility method, the randomization is gone when , the number is fixed at anytime i want to get it using `/iagive`, until i restart the server.

### Steps to reproduce the issue

1. make an mmoitem with modifiers
2. hook the mmoitem to IA
3. take the item

### Server version

[11:52:07 INFO]: Checking version, please wait...
[11:52:08 INFO]: This server is running Paper version git-Paper-379 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 276d830)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Purpur-1623 (MC: 1.18.2)

### ItemsAdder Version

[11:52:21 INFO]: ItemsAdder version 3.2.3-r9
[11:52:21 INFO]: Customized Minecraft without client mods!
[11:52:21 INFO]: Website: devs.beer
[11:52:21 INFO]: Author: LoneDev
> 

### ProtocolLib Version

[11:52:42 INFO]: ProtocolLib version 4.8.0
[11:52:42 INFO]: Provides read/write access to the Minecraft protocol.
[11:52:42 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[11:52:52 INFO]: LoneLibs version 1.0.21
[11:52:52 INFO]: Collection of libs used by my plugins
[11:52:52 INFO]: Authors: LoneDev and others

### LightAPI Version (optional)

> version LightAPI
[11:52:58 INFO]: LightAPI version bukkit-5.3.0 (build SNAPSHOT)
[11:52:58 INFO]: Bukkit library for edit light levels
[11:52:58 INFO]: Website: https://github.com/BeYkeRYkt/LightAPI
[11:52:58 INFO]: Authors: BeYkeRYkt and other contributors in GitHub

### LibsDisguises Version (optional)

> version LibsDisguises
[11:53:06 INFO]: LibsDisguises version 10.0.31-SNAPSHOT
[11:53:06 INFO]: A disguise plugin with various disguises.
[11:53:06 INFO]: Authors: libraryaddict, Byteflux and Navid K.

### FULL server log

https://paste.denizenscript.com/View/101950

### Error (optional)

```shell
no errors
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: censored ip
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-configs: true
  legacy_pack: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
chat-preview: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: custom_armor
armors_rendering:
  custom_armor:
    color: '#d60000'
    layer_1: armor/custom_1_layer_1
    layer_2: armor/custom_1_layer_2
    use_color: false
  custom_armor1:
    color: '#ffffff'
    layer_1: armor/custom_2_layer_1
    layer_2: armor/custom_2_layer_2
    use_color: false
items:
  custom_armor_helmet_1:
    display_name: Custom helmet 1
    permission: simple
    resource:
      generate: true
      textures:
      - armor/custom_1_icons1.png
    mmoitem:
      type: HELMET
      id: AR1_HELMET_1
    specific_properties:
      armor:
        slot: head
        custom_armor: custom_armor
  custom_armor_chestplate_1:
    display_name: Custom chestplate 1
    permission: simple
    resource:
      generate: true
      textures:
      - armor/custom_1_icons2.png
    mmoitem:
      type: CHESTPLATE
      id: AR1_CHESTPLATE_1
    specific_properties:
      armor:
        slot: chest
        custom_armor: custom_armor
  custom_armor_leggings_1:
    display_name: Custom Leggings 1
    permission: simple
    resource:
      generate: true
      textures:
      - armor/custom_1_icons3.png
    mmoitem:
      type: LEGGINGS
      id: AR1_LEGGINGS_1
    specific_properties:
      armor:
        slot: legs
        custom_armor: custom_armor
  custom_armor_boots_1:
    display_name: Custom Boots 1
    permission: simple
    resource:
      generate: true
      textures:
      - armor/custom_1_icons4.png
    mmoitem:
      type: BOOT
      id: AR1_BOOT_1
    specific_properties:
      armor:
        slot: feet
        custom_armor: custom_armor
  custom_armor_helmet_2:
    display_name: Custom helmet 2
    permission: simple
    resource:
      generate: true
      textures:
      - armor/custom_2_icons5.png
    mmoitem:
      type: HELMET
      id: AR2_HELMET_2
    specific_properties:
      armor:
        slot: head
        custom_armor: custom_armor1
  custom_armor_chestplate_2:
    display_name: Custom chestplate 2
    permission: simple
    resource:
      generate: true
      textures:
      - armor/custom_2_icons6.png
    mmoitem:
      type: CHESTPLATE
      id: AR2_CHESTPLATE_2
    specific_properties:
      armor:
        slot: chest
        custom_armor: custom_armor1
  custom_armor_leggings_2:
    display_name: Custom Leggings 2
    permission: simple
    resource:
      generate: true
      textures:
      - armor/custom_2_icons7.png
    mmoitem:
      type: LEGGINGS
      id: AR2_LEGGINGS_2
    specific_properties:
      armor:
        slot: legs
        custom_armor: custom_armor1
  custom_armor_boots_2:
    display_name: Custom Boots 2
    permission: simple
    resource:
      generate: true
      textures:
      - armor/custom_2_icons8.png
    mmoitem:
      type: BOOT
      id: AR2_BOOT_2
    specific_properties:
      armor:
        slot: feet
        custom_armor: custom_armor1
```

### Other files, you can drag and drop them here to upload. (optional)
MMOITEMS item
https://paste.denizenscript.com/View/101951

**Comment by LoneDev6** [comment] 2023-01-04 15:41
Duplicate of: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1239

**Closed by LoneDev6** 2023-01-04 15:41 UTC
Labels: Duplicate
