### ISSUE TITLE
It is not possible to remove blocks set from IA.

### ISSUE THREAD

**Issue by JuergenUniVie** [PluginBugs/Issues-ItemsAdder#3427] opened 2024-02-14 07:58 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

vSqu33zy

### What happened?

It is not possible to remove blocks set from IA.

### Steps to reproduce the issue

1.) Place Block
2.) Try to remove

### Server version

This server is running Paper version git-Paper-423 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 31699ae)
You are running the latest version
Previous version: git-Paper-422 (MC: 1.20.4)

### ItemsAdder Version

3.6.3-beta-12

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Error (optional)

```shell
[08:54:35 WARN]: [ItemsAdder] Task #326905 for ItemsAdder v3.6.3-beta-12 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.event.entity.EntityDamageByEntityEvent.<init>(org.bukkit.entity.Entity, org.bukkit.entity.Entity, org.bukkit.event.entity.EntityDamageEvent$DamageCause, java.util.Map, java.util.Map)'
        at ia.m.sj.<init>(SourceFile:19) ~[ItemsAdder_3.6.3-beta-12.jar:?]
        at ia.m.rt.a(SourceFile:636) ~[ItemsAdder_3.6.3-beta-12.jar:?]
        at ia.m.cf.b(SourceFile:159) ~[ItemsAdder_3.6.3-beta-12.jar:?]
        at ia.m.cf.a(SourceFile:118) ~[ItemsAdder_3.6.3-beta-12.jar:?]
        at ia.m.cf.a(SourceFile:396) ~[ItemsAdder_3.6.3-beta-12.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-423]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-423]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.20.4.jar:git-Paper-423]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-423]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[paper-1.20.4.jar:git-Paper-423]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[paper-1.20.4.jar:git-Paper-423]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-423]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/61051829/04cfd896-07f3-42b4-8fac-719d1cfff813)

**Comment by LoneDev6** [comment] 2024-02-28 15:43
Duplicate of #3449

**Closed by LoneDev6** 2024-02-28 15:43 UTC
Labels: type: bug
