### ISSUE TITLE
Player stats saving performance optimization on world save - wasn't fixed

### ISSUE THREAD

**Issue by yngdrms** [PluginBugs/Issues-ItemsAdder#3438] opened 2024-02-17 00:20 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

yngdrms

### What happened?

I ran the spark profiler and got the following picture, which I show in the screenshots below. Can you message me on discord so I can send you the spark data?
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/79171955/4c269be3-e7a0-47f2-846a-e8ab00209673)

### Steps to reproduce the issue

Make a spark profiler

### Server version

1.20.1

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-12

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.45

**Comment by LoneDev6** [comment] 2024-02-18 16:37
Post the report URL for me to better check, not just a screenshot.
Thanks

**Comment by LoneDev6** [comment] 2024-02-18 16:39
Anyway this has to do with players stats saving, duplicate of this issue: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3286

Seems that it wasn't completely mitigated. I will try to find another solution, anyway it's caused by the shit implementation of Mojang NBT saving. I probably will have to get rid of it and use my own implementation.

**Comment by LoneDev6** [comment] 2024-02-20 10:29
Yep it's a duplicate of the other issue.
Basically this happens on player quit, it saves the player data.
I will schedule the saving on another thread to avoid this issue.

**Closed** 2024-02-20 14:13 UTC
Labels: type: bug, type: performance
