### ISSUE TITLE
Could not initialize class ia.m.G

### ISSUE THREAD

**Issue by Paradis4432** [PluginBugs/Issues-ItemsAdder#3244] opened 2023-12-22 17:56 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

.paradis

### What happened?

all plugins load fine, until i add CMI
then i get the following 

https://paste.md-5.net/racaqihehe.rb
causing:
https://paste.md-5.net/oginubiqib.cs

slightly reduced log: https://paste.md-5.net/uvivufisag.sql
without cmi: https://paste.md-5.net/ducojiniti.sql

### Steps to reproduce the issue

to make it work:
add itemloader
add cosmetics core
add lonelibs

to brake it:
do the same but add CMI and cmilib

**i have tested without cmilib and it works fine**

### Server version

This server is running Arclight version arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) 

### ItemsAdder Version

ItemsAdder_3.6.2.c

ItemsAdder_3.6.2.d-beta-2 throws a few errors https://paste.md-5.net/oliroxefap.bash

### ProtocolLib Version

ProtocolLib v5.1.1-SNAPSHOT-673 

### LoneLibs Version

LoneLibs version 1.0.31 

### FULL server log

added earlier 

### Error (optional)

```shell
added earlier
```

### Problematic items yml configuration file (optional)

```shell
config was never updated, only the jars
```

### Other files, you can drag and drop them here to upload. (optional)

none

### Screenshots/Videos (you can drag and drop files or paste links)

none

**Comment by Paradis4432** [comment] 2023-12-22 17:57
cmi version CMI-9.6.1.0
cmilib version CMILib1.4.4.2

**Comment by Paradis4432** [comment] 2023-12-22 17:58
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/49301263/4d44f058-c8d2-434d-aba5-f93bc0757713)
this is a small showcase of the plugins, the crossed ones are for sure not causing any issues 
lmk if you need anything else

**Comment by LoneDev6** [comment] 2023-12-24 17:27
Seems to be a duplicate of this issue report: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3201

This issue is very strange. For some reason CMI is interfering with ItemsAdder loading.
I suspect it's because CMI has ItemsAdder added in its plugin.yml file `softdepend` plugins list.
What you can try to do is open the ItemsAdder jar with a zip file manager, open plugin.yml, remove `- CMI`, then put the new plugin.yml file inside the ItemsAdder jar and start your server.
Let me know.

**Comment by Paradis4432** [comment] 2023-12-25 21:00
seems to be working, thank you!
ill close this in a week if nothing goes wrong

**Closed** 2024-01-05 11:14 UTC
Labels: type: bug, compat: plugin
