### ISSUE TITLE
Broken block breaking speed

### ISSUE THREAD

**Issue by tetanik-x** [PluginBugs/Issues-ItemsAdder#4096] opened 2024-11-02 21:30 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

The strange speed of breaking blocks

Check video: https://www.youtube.com/watch?v=r62zQBM-VNE

### Steps to reproduce the issue

https://www.youtube.com/watch?v=r62zQBM-VNE

### Server version

1.21-2275-82ccc76 (MC: 1.21)*

### ItemsAdder Version

ItemsAdder version 4.0.3

### ProtocolLib Version

5.3.0-SNAPSHOT-732

### LoneLibs Version

LoneLibs version 1.0.59

### Full Server Log

no

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=r62zQBM-VNE

**Comment by Andre601** [comment] 2024-11-02 21:37
I cannot see a real difference in the video (Mainly due to YouTube compressing the hell out of it and making it a pixelated sludge). At most I can see a cooldown on the pickaxe?

Also, provide the full server logs. We ask for them for a reason.

**Comment by Borplesnoots** [comment] 2024-11-03 09:39
@Andre601 The issue can also be seen in my posting #4076

**Comment by Verzante** [comment] 2024-11-17 19:07
Just wanted to report this bug. I can confirm this bug is still happening. Please fix it as this is extremely critical since breaking blocks is corrupted

**Comment by LoneDev6** [comment] 2024-11-20 11:33
Duplicate of #4076

**Closed** 2024-11-20 11:33 UTC
Labels: type: duplicate
