### ISSUE TITLE
[Suggestion] Trigger Sound on Vehicle Move.

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#1215] opened 2021-09-22 10:51 UTC
The ability to trigger a sound when a Vehicle initially moves and is constantly moving, I think this would improve Vehicles so much if at all possible.

**Comment by SirCraftypants** [comment] 2023-01-18 11:06
apologies, i didn't realize i already asked for this feature last year.

**Comment by LoneDev6** [comment] 2023-04-06 13:02
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/566

**Closed by LoneDev6** 2023-04-06 13:02 UTC
Labels: type: feature request
