### ISSUE TITLE
Circular plugin loading error

### ISSUE THREAD

**Issue by dusty01534** [PluginBugs/Issues-ItemsAdder#2979] opened 2023-08-30 09:50 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

shanaop

### What happened?

i get a Circular plugin loading and cant load

### Steps to reproduce the issue

install the plugims in error and start server

### Server version

this server is running purpur-1.19.4.jar:git-Purpur-1985

### ItemsAdder Version

ItemsAdder version 3.5.0c-r4

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-668

### LoneLibs Version

 LoneLibs version 1.0.25

### Error (optional)

```shell
[10:47:27 ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[10:47:27 ERROR]: [SimpleProviderStorage] Circular load order:
[10:47:27 ERROR]: [SimpleProviderStorage]   ItemsAdder -> ModelEngine -> Citizens -> CMI -> HyronicFriends -> ItemsAdder
[10:47:27 ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[10:47:27 ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[10:47:27 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins ItemsAdder
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:78) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:43) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:47:27 ERROR]: This crash report has been saved to: C:\Users\marut\Dropbox\My PC (DESKTOP-98IOMQJ)\Desktop\server\servers\purpur-1.19.2-1762\.\crash-reports\crash-2023-08-30_10.47.27-server.txt
[10:47:27 INFO]: Stopping server
```

**Comment by paulreob** [comment] 2023-08-31 15:41
https://help.sparkedhost.com/en/article/how-to-solve-the-circular-dependencies-detected-error-1afjdcm/#1-what-are-circular-dependencies-and-why-does-this-happen

**Comment by LoneDev6** [comment] 2023-09-03 14:57
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2363#issuecomment-1448287859

**Comment by LoneDev6** [comment] 2023-09-03 14:58
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2363

**Closed by LoneDev6** 2023-09-03 14:57 UTC
Labels: type: bug
