### ISSUE TITLE
server crash  from infinite recursive call

### ISSUE THREAD

**Issue by aaa8881** [PluginBugs/Issues-ItemsAdder#2338] opened 2023-02-12 20:32 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

signition#0001

### What happened?

server crashed with giant infinite recursive stacktrace.
unsure how it happened, but I see boat in the stack trace 

### Steps to reproduce the issue

I mean, can't really reproduce because it just happened. unsure

### Server version

paper #386 ( 1.19.3 )

### ItemsAdder Version

3.3.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### LoneLibs Version

1.0.23

### LightAPI Version (optional)

not installed

### LibsDisguises Version (optional)

10.0.32

### FULL server log

full log is 800k lines, so I believe you won't want that :P it's just repeat of same giant stack trace so, will put part of one stack trace

### Error (optional)

```shell
[02:33:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.1
java.lang.IllegalStateException: Recursion depth became negative: -1
	at org.apache.logging.log4j.spi.AbstractLogger.decrementRecursionDepth(AbstractLogger.java:2181) ~[log4j-api-2.19.0.jar:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2161) ~[log4j-api-2.19.0.jar:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142) ~[log4j-api-2.19.0.jar:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017) ~[log4j-api-2.19.0.jar:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983) ~[log4j-api-2.19.0.jar:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:750) ~[log4j-api-2.19.0.jar:2.19.0]
	at org.bukkit.craftbukkit.v1_19_R2.util.ForwardLogHandler.publish(ForwardLogHandler.java:32) ~[paper-1.19.3.jar:git-Paper-386]
	at java.util.logging.Logger.log(Logger.java:980) ~[?:?]
	at java.util.logging.Logger.doLog(Logger.java:1007) ~[?:?]
	at java.util.logging.Logger.log(Logger.java:1118) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:689) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:493) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.world.item.BoatItem.use(BoatItem.java:62) ~[?:?]
	at ia.nms.aU.impl.v1_19_R2.a(SourceFile:65) ~[ItemsAdder_3.3.1.jar:?]
	at ia.nms.aU.bK.a(SourceFile:64) ~[ItemsAdder_3.3.1.jar:?]
	at ia.m.cB.a(SourceFile:309) ~[ItemsAdder_3.3.1.jar:?]
	at ia.m.cB.k(SourceFile:160) ~[ItemsAdder_3.3.1.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-386]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:493) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.world.item.BoatItem.use(BoatItem.java:62) ~[?:?]
	at ia.nms.aU.impl.v1_19_R2.a(SourceFile:65) ~[ItemsAdder_3.3.1.jar:?]
	at ia.nms.aU.bK.a(SourceFile:64) ~[ItemsAdder_3.3.1.jar:?]
	at ia.m.cB.a(SourceFile:309) ~[ItemsAdder_3.3.1.jar:?]
	at ia.m.cB.k(SourceFile:160) ~[ItemsAdder_3.3.1.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-386]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:493) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.world.item.BoatItem.use(BoatItem.java:62) ~[?:?]
	at ia.nms.aU.impl.v1_19_R2.a(SourceFile:65) ~[ItemsAdder_3.3.1.jar:?]
	at ia.nms.aU.bK.a(SourceFile:64) ~[ItemsAdder_3.3.1.jar:?]
	at ia.m.cB.a(SourceFile:309) ~[ItemsAdder_3.3.1.jar:?]
	at ia.m.cB.k(SourceFile:160) ~[ItemsAdder_3.3.1.jar:?]
.... (infinite repeat of same stacktrace )
```

### Problematic items yml configuration file (optional)

```shell
not related to specific configuration I believe
```

**Comment by aaa8881** [comment] 2023-02-14 09:11
happened 3 times in past 2 days, causing serve runable to run properly

**Comment by LoneDev6** [comment] 2023-02-14 11:47
Will be checked as soon as possible.

Seems to be caused by a player interacting with a noteblock with a boat in hand.
I'll do some tests.

**Comment by LoneDev6** [comment] 2023-02-15 14:28
Fixed in upcoming update

**Closed by LoneDev6** 2023-02-15 14:28 UTC
Labels: Bug, HIGH PRIORITY
