### ISSUE TITLE
Creative mode hotbar glitch on block placement

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-ItemsAdder#2089] opened 2022-11-12 19:52 UTC
### Discord tag (optional)

EpicPlayerA10#3800

### What happened?

When I place custom block on non custom block in creative mode, it will disappear from inventory. Tested with these plugins: `ItemsAdder`, `LoneLibs`, `ProtocolLib`.
This issue is related to #2007 .

#### Note for developers:

I debugged a bit by modifying paper source code a bit and i found out that this bug is caused by ItemsAdder. You can see the debugs here: https://pastebin.com/rufjaytU . You can see there a packet that is sent, fields of this packet and what sent this packet (in form of a stacktrace). It shows that ItemsAdder sends an `EntityEquipment` packet on `PlayerInteractEvent` event. This packet sets the main hand to air.

### Steps to reproduce the issue

1. Switch gamemode to creative.
2. Get a custom block.
3. Place it on a non custom block (eg. grass block)
4. ! Custom block disappeared from inventory

### Server version

This server is running Paper version git-Paper-224 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 5cdb5f9)

### ItemsAdder Version

ItemsAdder version 3.2.5-r3

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b602

### LoneLibs Version

LoneLibs version 1.0.21

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=uUCQVc74Kyk

**Comment by BookWyrm114** [comment] 2022-11-12 21:06
I’ve been been having this issue as well on purpur

**Comment by nhanledev** [comment] 2022-11-17 02:32
I have the same issue on Paper 1.19.2

**Comment by LoneDev6** [comment] 2022-11-18 11:31
Remove all plugins and test only with ItemsAdder and its dependencies.
Check if the issue still occurs.
If the issue doesn't occur you have to find the plugin which is causing the problem and let me know.

**Comment by nhanledev** [comment] 2022-11-18 11:39
This issue might be at IA side because 3.2.3-r9 does not have this problem.

**Comment by LoneDev6** [comment] 2022-11-18 11:54
[3.2.5-r2](https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/update?update=477914) 
[3.2.5-beta5](https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/update?update=477663) 
[3.2.4-beta1](https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/update?update=476678) 
[3.2.3-r10](https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/update?update=476113) 
Do these versions have this issue too?

**Comment by EpicPlayerA10** [comment] 2022-11-18 12:59
> This issue might be at IA side because 3.2.3-r9 does not have this problem.

Hmm, I still have issue on this version.

LoneDev, try to look at my debugs in this issue (it is a pastebin link). There we can see the ItemsAdder package. Try to deobfuscate it and maybe this will say something why this is happening.

**Comment by EpicPlayerA10** [comment] 2022-11-18 13:21
> [3.2.5-r2](https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/update?update=477914) [3.2.5-beta5](https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/update?update=477663) [3.2.4-beta1](https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/update?update=476678) [3.2.3-r10](https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/update?update=476113) Do these versions have this issue too?

This bug didnt happend in version `3.2.3-r10` but it broke again in version `3.2.5-beta5`

**Comment by LoneDev6** [comment] 2022-11-22 16:03
Can't reproduce, definitely something else interfering.


https://user-images.githubusercontent.com/27242001/203362374-10f1fcc4-3244-40d8-8530-f821f5d37bed.mp4

**Comment by iqtesterr** [comment] 2022-11-22 21:20
Happend to me when I update to new IA version.

**Comment by iqtesterr** [comment] 2022-11-23 04:49
I tested on a brand new and clean server using the newest Paper and only with ItemsAdder, LoneLibs, ProtocoLib. This got reproduce.

**Comment by nhanledev** [comment] 2022-11-23 05:43
This can be reproduced on `ItemsAdder_3.3.0-beta-r8` with minimal plugins
![image](https://user-images.githubusercontent.com/28459250/203477059-d7bf82f3-1a73-4389-a601-3d8b9630f2e0.png)


https://user-images.githubusercontent.com/28459250/203477738-1e1eb28d-1abb-4fa5-8d91-8380f1301a9e.mp4

**Comment by EpicPlayerA10** [comment] 2022-11-23 17:43
> Can't reproduce, definitely something else interfering.
> Minecraft_.1.19.-.Multiplayer.3rd-party.Server.2022-11-22.17-00-25.mp4_compressed.mp4

What is your server version?

**Comment by iqtesterr** [comment] 2022-11-23 17:46
> > Can't reproduce, definitely something else interfering.
> > Minecraft_.1.19.-.Multiplayer.3rd-party.Server.2022-11-22.17-00-25.mp4_compressed.mp4
> 
> What is your server version?

Look like he using 1.19.

**Comment by EpicPlayerA10** [comment] 2022-11-23 17:48
> > > Can't reproduce, definitely something else interfering.
> > > Minecraft_.1.19.-.Multiplayer.3rd-party.Server.2022-11-22.17-00-25.mp4_compressed.mp4
> > 
> > 
> > What is your server version?
> 
> Look like he using 1.19.

but maybe he has viaversion on the server

**Comment by iqtesterr** [comment] 2022-11-23 17:49
> > > > Can't reproduce, definitely something else interfering.
> > > > Minecraft_.1.19.-.Multiplayer.3rd-party.Server.2022-11-22.17-00-25.mp4_compressed.mp4
> > > 
> > > 
> > > What is your server version?
> > 
> > 
> > Look like he using 1.19.
> 
> but maybe he has viaversion on the server

What is the point to use via version on local host xd.

**Comment by EpicPlayerA10** [comment] 2022-11-23 17:50
i just want to be sure

**Comment by iqtesterr** [comment] 2022-11-23 17:52
It must really easy to reproduce with everything newest.

**Comment by EpicPlayerA10** [comment] 2022-11-23 17:55
Also I found out that when you hold a custom block in your off-hand and place it then the block doesnt disappear from the inventory.
Video: https://www.youtube.com/watch?v=E9iaxJl8jgU

**Comment by iqtesterr** [comment] 2022-11-23 18:16
> It gets even more interesting when you have custom block in your offhand AND any non-placeable item in your main hand. Then item in your main hand will disappear. Video: https://www.youtube.com/watch?v=L3xbMw1RnZs

I see, really interesting. There are more bug on new version of Ia. The Brown Mushroom Block is totally break. It not display like what it should be any more. Can you see if that happen to you either.

**Comment by iqtesterr** [comment] 2022-11-23 18:35
> Okay, I think that I know what causes this issue. From my tests it seems that it is ProtocolLib. This bug wasnt occured in ProtocolLib 4.8.0 but this bug started happening in ProtocolLib 5.0.0 . Something changed between 4.8.0 -> 5.0.0

There are few dev version on 5.0.0, if this issue cause by protocolib try the past few 5.0.0 version to see.

**Comment by EpicPlayerA10** [comment] 2022-11-23 18:38
Oh, I mean version 4.9.0

**Comment by EpicPlayerA10** [comment] 2022-11-23 18:56
So LoneDev, update ProtocolLib to the latest release and then try to reproduce this bug.

**Comment by iqtesterr** [comment] 2022-11-24 14:32
Any updates?

**Comment by matyasvane** [comment] 2022-11-26 15:17
Hey, i have same problem with that.

https://youtu.be/KKx_Q7PLJpI

**Comment by iqtesterr** [comment] 2022-11-26 19:44
@LoneDev6

**Comment by TeiBri** [comment] 2022-11-28 18:39
I have this too

**Comment by iqtesterr** [comment] 2022-11-29 04:43
@LoneDev6

**Comment by iqtesterr** [comment] 2022-11-30 17:47
WE NEED HELP XD

**Comment by matyasvane** [comment] 2022-11-30 17:55
@LoneDev6

**Comment by LoneDev6** [comment] 2022-11-30 17:56
Please stop spamming this Github report, it doesn't speed up the fixing process and it just adds pressure to my work with the risk of getting a rushed release with possible bugs.

**Comment by matyasvane** [comment] 2022-11-30 17:57
"[LoneDev6](https://github.com/LoneDev6) added the [Can't reproduce](https://github.com/PluginBugs/Issues-ItemsAdder/labels/Can%27t%20reproduce) This issue cannot be reproduced by the developerslabel [8 days ago](https://github.com/PluginBugs/Issues-ItemsAdder/issues/2089#event-7869423058)"

So we cant know, if you want fix this bug.. :)

**Comment by LoneDev6** [comment] 2022-11-30 17:59
If the bug page is still opened means that I still am finding a solution. Spamming the report has no sense ".. :)"
So avoid doing that, there are other [21 reports](https://github.com/PluginBugs/Issues-ItemsAdder/issues?q=is%3Aissue+is%3Aopen+label%3ABug) to manage, this is not the only report I have to handle.

**Comment by LoneDev6** [comment] 2022-12-08 14:19
I cannot reproduce the issue.
```
[14:14:33 INFO]: This server is running Paper version git-Paper-298 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 309133e)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads
version itemsadder
[14:14:36 INFO]: ItemsAdder version 3.3.0-beta-r10
[14:14:36 INFO]: Customized Minecraft without client mods!
[14:14:36 INFO]: Website: devs.beer
[14:14:36 INFO]: Author: LoneDev
version protocollib
[14:14:40 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b586
[14:14:40 INFO]: Provides read/write access to the Minecraft protocol.
[14:14:40 INFO]: Authors: dmulloy2 and comphenix
```

## Tested on:
- vanilla 1.19, 1.19.1, 1.19.2.
- fabric 1.19 with [Fabulously Optimized](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/) modpack

https://user-images.githubusercontent.com/27242001/206468665-85bc7dfe-0c71-4cfc-a810-42c15b6b7ea2.mp4

## Item configuration:

```yml
  test_block_2076:
    display_name: test_block_2076
    resource:
      generate: false
      model_path: minecraft:block/stone
      material: PAPER
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
        cancel_drop: false
```

**Comment by LoneDev6** [comment] 2022-12-08 14:20
Remove every plugin and test if it still happens.

**Comment by nhanledev** [comment] 2022-12-08 15:19
I think you should update Paper and especially ProtocolLib to the latest build and try it

**Comment by LoneDev6** [comment] 2022-12-08 16:25
Seems to be related to ProtocoLib or Paper recent updates.
Will be fixed in the new update.

Internal note: it is caused by this fix: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1292

**Closed** 2022-12-08 16:40 UTC
Labels: Bug
