### ISSUE TITLE
attribute_modifiers attackDamage is lower than configurated amount

### ISSUE THREAD

**Issue by nhanledev** [PluginBugs/Issues-ItemsAdder#2201] opened 2022-12-22 16:51 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

supermamoru#7462

### What happened?

Custom items with custom attack damage deal lower damage than expected.
Tested with plugin that show damage amount (CMI bossbar and DecentHologram)

### Steps to reproduce the issue

1. Create a custom sword
2. Set its `attribute_modifiers.mainhand.attackDamage` to 10
3. Attack a random mob with a plugin that show damage. It always deals 1 damage less than the configurated modifier.

### Server version

Paper 1.19.3 build 

### ItemsAdder Version

3.3.0b

### ProtocolLib Version

5.0 snapshot build b608

### LoneLibs Version

Lonelibs 1.0.22

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: debugitem
items:
  debug_sword:
    display_name: Debug Sword
    lore:
    - '&f'
    resource:
      material: DIAMOND_SWORD
      generate: true
      textures:
      - items/debug_sword
    attribute_modifiers:
      mainhand:
        attackDamage: 10
        attackSpeed: 5.6
```

### Screenshots/Videos (you can drag and drop files or paste links)

In this video I have
1 Vanilla Netherite Sword with damage 8
1 custom sword with damage 10

The vanilla sword always deal 8 damages, but the custom sword is only 9, always 9 instead of 10

https://user-images.githubusercontent.com/28459250/209185648-90287aee-f8ba-426a-baf4-48c0a3bea1fb.mp4

**Comment by LoneDev6** [comment] 2023-01-04 16:13
Are you sure?
It might be a bug of the plugin you use to detect attack damage.

**Comment by nhanledev** [comment] 2023-01-04 17:36
Hello. I used both CMI (premium) hpbar and DecentHologram damage indicator (download here https://www.spigotmc.org/resources/decentholograms-1-8-1-19-3-papi-support-no-dependencies.96927/ ) and they return the same result.

**Comment by LoneDev6** [comment] 2023-01-09 13:26
I'll try to reproduce the issue and let you know, thanks

**Comment by LoneDev6** [comment] 2023-01-19 13:51
I tested your item and I cannot reproduce the issue.
I used this plugin: https://www.spigotmc.org/resources/%E2%9C%A8damage-indicator-%E2%9C%A8.87113/

https://user-images.githubusercontent.com/27242001/213459755-f614b5d9-9e3b-48a7-9c33-186e5562cbde.mp4

**Comment by nhanledev** [comment] 2023-01-26 05:37
> 

Did you notice that it writes 10 attack damages on the sword, but it only deals -9 damages?

**Comment by LoneDev6** [comment] 2023-01-30 10:33
Thanks I see.
I got confused in your video because you're attacking multiple mobs and dealing also partial damages (1) to surrounding mobs.

**Comment by LoneDev6** [comment] 2023-03-01 15:49
Fixed in the upcoming version

**Closed** 2023-03-02 11:55 UTC
Labels: Bug
