### ISSUE TITLE
[Enhancement] Custom items can't be crafted in the inventory crafting space 

### ISSUE THREAD

**Issue by chickenmcjesus** [PluginBugs/Issues-ItemsAdder#267] opened 2020-05-24 20:49 UTC
When you try a custom recipe in your survival crafting space (by pressing E), it won't be created.

Steps to reproduce:
1. Press E in survival
2. Try to use a custom recipe added by the plugin in the crafting grid

**Expected behavior**
It should create the custom item.

**Info:**
 - Server version: Paper 1.15.2
 - Client version: Java Edition 1.15.2
 - Plugin version: 2.0.24

**Comment by LoneDev6** [comment] 2020-06-02 10:09
This is an intended behaviour, I had to keep it like that in order to avoid duplication bugs and heavy checks.
Maybe in the future I'll be able to add this feature, but now I don't have any idea on how to add this without breaking the recipes system which is complex

**Comment by 100petr** [comment] 2021-04-16 17:53
Isn't this already added? https://itemsadder.plugin.ga/plugin-usage/adding-content/advanced/recipes#example-2x2-recipe

**Comment by LoneDev6** [comment] 2021-04-19 10:41
Yes, I forgot to close the issue

**Closed by LoneDev6** 2021-04-19 10:41 UTC
Labels: Future update, enhancement
