### ISSUE TITLE
Use `item_display` to make custom entities instead of armorstands

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-ItemsAdder#3082] opened 2023-10-14 12:32 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

DinoBoss

### Describe the solution you'd like

Block Display	block_display	entity.minecraft.block_display
Item Display	item_display	entity.minecraft.item_display
Text Display	text_display	entity.minecraft.text_display

I come here with a more serious suggestion, almost a demand or a very significant statement. The problem we are facing is with the furniture and other items. We humbly request that displays be added to optimize our players' server and finally put an end to the armor stand, item frame, and tripwire issues. We can now optimize all aspects of the server better with the release of MEG4 items adder. It advertised a feature related to entities, but it fell short in that functionality. We are at a point where we need to expedite some things, focusing on what is truly necessary, such as the display function.

### Is your feature request related to a problem?

We already know the issue with objects that are not displays. Depending on the angle from which you view them, they may or may not be visible. With displays, this problem does not occur, as it is a complete entity that we would see, not parts of armor stands or other objects with a small hitbox. I should note that this is a limitation of Minecraft itself. That's why when displays were added in MEG4, the entire community was thrilled. We are still amazed at all the work put into displays and the many creative possibilities they offer, such as creating scales and various other incredible things.

I emphasize that performance is the most concerning issue for me when it comes to furniture that is not of the display type. Using armor stands, the performance decreases by 0.1 TPS, with item frames it's 0.001 TPS, and with a tripwire, it's 0.1 TPS. We're facing the same problem. It's better to address this issue at its core and start afresh with furniture and other items.

### Describe alternatives you've considered

Using Oraxen is not an alternative; it's out of the question for any reason. It's not because it's bad but because each update of the plugin breaks another mechanism within it. So, it's better to stick with ItemsAdder. However, it's also better if you open your eyes and say, "Okay, I'll add it in the next update." I'm taking advantage of the fact that we're in beta; if there are a few errors, few will complain, and they will report to me because, after all, that's what a beta is for.

### Additional context

With much love, this complaint is not meant to make you angry or anything, but rather a formal statement, as I always express my opinions as a respectful critique of the current state of ItemsAdder.

**Comment by paulreob** [comment] 2023-10-14 13:12
This suggestion is required to be implemented, it is essential for external plugins like [ToolTips ](https://www.spigotmc.org/resources/%E2%AD%90tooltips.109912/)to better detect the custom-hitbox that can be created with item_display, since the current hitbox detection system is not accurate.

**Comment by LoneDev6** [comment] 2023-10-23 08:37
Related to #3082

**Comment by ShizuArt** [comment] 2023-11-07 05:50
Any news on when this feature will be added ?

**Comment by dinobossytnew** [comment] 2023-11-13 13:08
> Any news on when this feature will be added ?

2024

**Comment by LoneDev6** [comment] 2023-11-13 17:08
Probably next year as it requires 1.19.4+ clients and not every server is updated to that version + some people will complain that Geyser is not compatible with display entities.
I'm still trying to understand if this is a very requested and important change or not.

**Comment by dinobossytnew** [comment] 2023-11-14 12:14
> Probably next year as it requires 1.19.4+ clients and not every server is updated to that version + some people will complain that Geyser is not compatible with display entities. I'm still trying to understand if this is a very requested and important change or not.

Do you even know what the problem is? Because of these things, you leave behind the performance that affects Java more than Bedrock. To be honest, for Geyser in Bedrock, it's better to use Oraxen because it interacts more with the .json files, and you have simpler ways to convert them. Moreover, they added support for displayers without breaking Bedrock ones. Also, Meg4 has been released, which renders animated models and scales them. All the previous errors no longer exist in Meg4. Imagine Meg3; before, we rendered a model that disappeared if you looked at it upside down. Without mentioning other plugins that aren't AI, we are currently very behind. We need a Display for furnitures that are item frames and armor stands, which consumes too much. Moreover, the display will work for all types of furnitures or blocks, so it's not just one improvement; it's a significant change. Since when do you care about Geyser, which always bugs with AI where AI has no way of providing so much support to Geyser? It's impossible. Geyser works by giving crossplay to achieve compatibility; creating an AI for Bedrock, knowing that it has Bedrock, and from Nukki for Bedrock only because in Bedrock and Java, the way to support it is to provide the Resource Pack outside of AI and convert it with some converter and/or manually.

**Comment by dinobossytnew** [comment] 2023-11-14 12:16
If the problem is due to old versions of Minecraft that use AI, I recommend creating one bstats to collect information about the versions that use AI

**Comment by LoneDev6** [comment] 2023-11-14 15:21
> it's better to use Oraxen because it interacts more with the .json files, and you have simpler ways to convert them. 

No idea what you mean, ItemsAdder is a more complete and complex solution to handle resourcepacks compared to Oraxen which is a less feature rich and incline to break (based on the feedback I got from multiple customers migrating from Oraxen to ItemsAdder. I never used Oraxen in my life.).

> Also, Meg4 has been released, which renders animated models and scales them.

ItemsAdder also has this feature, but doesn't use display entities.

> All the previous errors no longer exist in Meg4. Imagine Meg3; before, we rendered a model that disappeared if you looked at it upside down

Known limitation of armorstands.

> We need a Display for furnitures that are item frames and armor stands, which consumes too much.

Planned: #2458

> Since when do you care about Geyser, which always bugs with IA where IA has no way of providing so much support to Geyser?

You are right, I should start again to ignore Geyser suggestions.
Recently I got bombarded with people asking me to add Geyser compactivity, but I don't see much good stuff from that idea.
Display entities are a better thing compared to Geyser compatibility.


> the way to support it is to provide the Resource Pack outside of IA and convert it with some converter and/or manually.

Display entities don't exist on Geyser so people might bet pissed off. Armorstands exist.

> If the problem is due to old versions of Minecraft that use IA, I recommend creating one bstats to collect information about the versions that use IA

People starting using 1.19.4+ extensively only in the recent months, so this is why this idea wasn't worked on.

---

I plan to work on that as soon as I find the time and I will try to maintain backwards compatibility with old armorstand entities, to support Geyser and support older clients connecting with ViaVersion.

**Comment by dinobossytnew** [comment] 2023-11-14 16:33
We request this update for version 3.6.3 or 3.6.4 because, seriously, we are very behind in this version. Our competitors, like Oraxen, despite what they may say, have support for displayers, and we don't even have that. We don't have display entities; we literally have nothing. Lone, you are chaining us down. I know you care about Geyser, but if Geyser doesn't contribute, we can't either. Additionally, it's not Geyser's fault. When you add Display, it will be obvious that Bedrock will be left without support. This decision is obvious; it's a tough one, but we can't wait for Mojang to dedicate themselves to adding it in a future update. It's been months since version 1.20 was released, and I asked you for the Display update. You replied that you wanted to work on something related to plants. Three months have passed, and now we are here on GitHub, pleading for you to listen and add Display, something that the competition has already done. It's no surprise; it was obvious that Display would be the best way for Minecraft servers. Almost no one uses Meg3 anymore because it's not practical. The same is happening with ItemsAdder; we are running out of options, and I can't replace IA with any competitor. One, because it's not profitable to change so many models, as you know. Two, because it would be an unnecessary change, knowing that you always implement functions that are profitable for Java. We can't just sit around waiting with our fingers crossed to see whether Display will be added or not. That's why we ask that in this or the next update, which will be 3.6.3 and 3.6.4, at least the groundwork for Display is added so that you can fully implement it in version 3.6.5. We understand that it will be challenging coding.

**Comment by dinobossytnew** [comment] 2023-11-14 16:37
And I repeat, if you want to wait for Geyser users, that would be a mistake we don't want to consider. However, when it comes to those still using ItemsAdder in 1.19.x or 1.18.x, which I highly doubt is the majority, then we can wait for Displays until version 3.6.8. It would be too long to wait, but we are willing to endure this time without Display because, I swear, Lone, you have me tied hands. We can't do anything extravagant; item frames are a hassle, and armor stands are the same.

**Comment by ShizuArt** [comment] 2023-11-15 05:47
I haven't had time to participate in the conversation since my previous message but here I am :
I'm currently working on a project and I couldn't agree more with what dino says.
All the models which are a little large, I divide them into several parts to avoid as much as possible the textures from being unloaded depending on the vision.
It takes a lot of time to do for nothing and as a bonus these are models which will never be accessible to players because they become downright puzzles and above all it multiplies the number of armor stands just for a single model
Also who says several parts means several files instead of one and therefore more weight in the resource pack

Currently I'm super jealous that Oraxen offers them but not IA, but having used Oraxen more than a year and a half before IA, I will never use it again since over a long period it's impossible to deal with it, each update breaks something else, enough to drive you crazy.

I don't understand why it should be a choice between armor stand and display entities, why not leave both and give us the choice to choose what we prefer for display our models?

**Comment by LoneDev6** [comment] 2023-11-15 10:02
I think I could just ignore Geyser compatibility like I did since 2019 since I don't really see the advantage of having a partially working experience and bugged gameplay just to have crossplatform.
So, as I said, I will work on display entities in the next months, but please do not rush it otherwise you would get a bad update.
Good things take time.

Also seems the poll is winning, no one cares about Geyser, luckly.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/c5924926-c804-4c4c-8832-3834f7b75725)

**Comment by LoneDev6** [comment] 2023-11-15 10:05
> I don't understand why it should be a choice between armor stand and display entities, why not leave both and give us the choice to choose what we prefer for display our models?

I have to decide if it's easier to integrate the display entities directly or to maintain both implementations.
I'm referring to custom entities, furniture will still allow for armorstands and itemframes.

**Comment by dinobossytnew** [comment] 2023-11-15 16:48
As I said, there is no problem as long as you gradually get into it. For example, in version 3.6.3, you already have code to implement. In version 3.6.4, you finish the class from 3.6.3 that you implemented something in, and by version 3.6.6, you would already have the plugin in displayers. This is mainly to get the needle out of the chest of the Oraxen show-offs ;(

**Comment by LoneDev6** [comment] 2023-11-16 18:51
As first step I will introduce furniture https://github.com/PluginBugs/Issues-ItemsAdder/issues/2458 , after furnitures I'll work on emotes and custom entities support.

**Comment by Ridz-design** [comment] 2024-01-29 03:16
Please dont remove the old methods in that case since i do own a geyser servee

**Comment by ciliomine** [comment] 2024-03-17 11:39
![2c41ef0de5afe034edf037a7fe3e0551](https://github.com/PluginBugs/Issues-ItemsAdder/assets/99097647/c8f5d2f2-f771-4ecb-99a5-2d4239bcdda4)
Please add this function, I have a roleplay server and my current tps consumption problem is for the Armor Stands, I cannot remove them either since it would leave them without furnitures, if you would add this function, it would be incredible.

**Comment by MrStreeet** [comment] 2024-03-20 12:44
Any news on this?

**Comment by bkgktp** [comment] 2024-03-23 22:22
Why don't we add this feature and make it something that users can edit according to their needs? I mean, just like in oraxen, those who want to use it as ArmorStand can set it as display_entity without configuring it, and those who want to change the settings accordingly can set it as display_entity, so we leave the end of alternatives open for servers using gayser. it's been almost 5 versions since this feature was added and it seems to be quite late, a professional project like itemsadder is making a mistake not to add it. this is not a feature need, it is a feature addition obligation. and also interaction hitbox support for furniture. This was my favorite feature when I was working with Oraxen and it would be a very good decision to see it as an itemsadder feature. @LoneDev6

**Comment by LoneDev6** [comment] 2024-04-04 12:07
@bkgktp implementing item displays for custom entities is not as straight forward as changing the entity type used to show the bones.
It requires restructuring of the calculations because these entities have different hardcoded location/pivots values.
So I will probably have to get rid of armorstands and directly use item displays instead.

**Comment by LoneDev6** [comment] 2024-04-04 12:08
@ciliomine 
> Please add this function, I have a roleplay server and my current tps consumption problem is for the Armor Stands, I cannot remove them either since it would leave them without furnitures, if you would add this function, it would be incredible.

This is impossible as armorstands are packet based, so the screenshot you sent is related to real armorstands spawned by other plugins, not ItemsAdder.

**Comment by ciliomine** [comment] 2024-04-04 22:30
> @ciliomine
> 
> > Please add this function, I have a roleplay server and my current tps consumption problem is for the Armor Stands, I cannot remove them either since it would leave them without furnitures, if you would add this function, it would be incredible.
> 
> This is impossible as armorstands are packet based, so the screenshot you sent is related to real armorstands spawned by other plugins, not ItemsAdder.

![007cd399bd08867c29031d5b23f83664](https://github.com/PluginBugs/Issues-ItemsAdder/assets/99097647/ad7e260c-c0e0-4033-bf69-fbada54b0a95)
![2024-04-04_19 24 04](https://github.com/PluginBugs/Issues-ItemsAdder/assets/99097647/1a351709-e583-43cd-ade3-c8fe6166f859)

I was reviewing the chunks that they have the most and they are fornitures of itemsadder, also to make the test more effective, I changed all the street lamps for real blocks and now I have 2 thousand fewer entities

**Comment by LoneDev6** [comment] 2024-05-15 14:43
Duplicate of #2458

**Closed by LoneDev6** 2024-05-15 14:43 UTC
Labels: type: enhancement, type: feature request, type: performance
