### ISSUE TITLE
FastAsyncWorldedit Itemsadder

### ISSUE THREAD

**Issue by Truongvv10** [PluginBugs/Issues-ItemsAdder#2852] opened 2023-07-06 18:45 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Wassabi#0317

### What happened?

I can't use itemsadder worldedit addon, it would set the block to just be noteblocks. 

Or it doesnt support 1.20.1 or fastasyncworldedit changed their api but please look in to this when you can.

### Steps to reproduce the issue

//set something

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/f809785e-2a3a-46c3-a9c4-56e64a5d4a25)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/cd9e7edb-6d9d-44bf-ad94-a6072f257956)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/fd8ff9b4-e3e7-4b3d-80e5-d283e2558d94)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/b43d9e0e-569f-4131-930e-09b28fc9d8f4)

**Comment by LoneDev6** [comment] 2023-07-07 08:37
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2653#issuecomment-1618838851

**Closed by LoneDev6** 2023-07-07 08:37 UTC
Labels: type: bug
