### ISSUE TITLE
[Feature Request] Custom plants like TRIPWIRE

### ISSUE THREAD

**Issue by TeiBri** [PluginBugs/Issues-ItemsAdder#847] opened 2021-04-18 12:06 UTC
** Describe the alternatives you have considered **
Your plugin is very great and very useful and has many features, but something else is missing. One thing that would be very useful not just for me. I have the blocks I create as REAL_NOTE, but I would like you to add one more type, and which would definitely work well and that is CUSTOM PLANTS. TRIPWIRE is best suited for this. Although it has only about 10 vacancies, I think that for those who want to have their own plants and some decorations (eg stones on the ground, etc.) it would be very great. Advantages of TRIPWIRE and why it should represent CUSTOM PLANTS: It is a TRANSPARENT, it can be walked through it, it breaks after one bang of the hand. Disadvantage of CUSTOM PLANTS: If we destroyed the block under CUSTLOM PLANT, the plant (TRIPWIRE) would remain levitated in the air.

** Other context **
![2021-04-18 (1)](https://user-images.githubusercontent.com/62265168/115144786-dec0c280-a04e-11eb-9f74-8fd014a23887.png)
![2021-04-18 (2)](https://user-images.githubusercontent.com/62265168/115144806-f8620a00-a04e-11eb-8b1d-5fd81ac0f0ae.png)
*Edit*
I'm sorry for the mistake. TRIPWIRE has over about 80+ tips! So I think it would definitely pay off!

**Comment by LoneDev6** [comment] 2021-04-19 10:33
duplicate of #741

**Closed by LoneDev6** 2021-04-19 10:33 UTC
Labels: Feature request
