### ISSUE TITLE
Villager trades are duplicated when open and then close villager trade menu

### ISSUE THREAD

**Issue by IncludivicS** [PluginBugs/Issues-ItemsAdder#3358] opened 2024-01-21 12:13 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

includivics

### What happened?

Villager trades are duplicated when open and then close villager trade menu. And there is no error show in console.

### Steps to reproduce the issue

Just run the server and plugin work normally and wait for the time (I dont actually know how to actually reproduce this issue) and then open and then close villager trade menu. it gonna duplicate trade list

### Server version

This server is running Paper version git-Paper-393 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: b48d737)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-9

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

**Comment by IncludivicS** [comment] 2024-01-21 12:16
On version ItemsAdder version 3.6.3-beta-8 don't have this issue btw hope this information will help.

**Comment by IncludivicS** [comment] 2024-01-28 03:50
@LoneDev6 sry I have to tag you it important to my server.

**Comment by LoneDev6** [comment] 2024-01-29 15:27
Related to this: #2294

I will try to reproduce the issue but I tested it extensively before releasing `3.6.3-beta-9` and couldn't trigger any similar issue.
Would you mind making a video and explaining if the trade GUI was from a real villager or a plugin?

Thanks.

**Comment by LoneDev6** [comment] 2024-01-30 13:36
## Villager GUI
Cannot reproduce

![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/edd56375-a57e-4273-9879-e290e583a0c2)


## ItemsAdder furniture_trade_machine GUI
Cannot reproduce (second recipe diamond is a custom item)

![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/2459103b-34f3-4b41-a720-bbd88fb1f514)


## ShopKeepers GUI
Cannot reproduce (diamond is a custom item)

![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/bc1ea04c-e0dc-4556-b0e0-f69a19687b33)

**Comment by LoneDev6** [comment] 2024-01-30 13:38
https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/6913c65f-90e5-4659-bed3-02edf5cf403d

**Comment by IncludivicS** [comment] 2024-01-30 14:32
maybe same of #3372 You need to open the server for a while (like 10-20 mins) and have atleast a player playing and the bug will appear.

**Comment by LoneDev6** [comment] 2024-01-30 17:11
How is your trade gui created?
Vanilla villager? Custom plugin?
Also are the trades containing any itemsadder item? Or only vanilla items?

**Comment by IncludivicS** [comment] 2024-01-30 20:36
Vanilla villager , only vanilla items.

**Comment by LoneDev6** [comment] 2024-01-31 18:37
Duplicate of #3372

**Closed** 2024-01-31 21:02 UTC
Labels: type: bug
