### ISSUE TITLE
Hats not showing on playing emots

### ISSUE THREAD

**Issue by Yassounou** [PluginBugs/Issues-ItemsAdder#2793] opened 2023-06-21 11:52 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

yassou_

### What happened?

hat not follow heads whene emote played
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69685202/889160f8-fd8e-4bfe-9f2a-919094853cd8)

### Steps to reproduce the issue

get a hat
play any emote

### Server version

git-Purpur-1970 MC 1.19.4
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69685202/d09bf11e-1a27-4168-8db4-9a67bb56fe7e)

### ItemsAdder Version

 **3.5.0b**
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69685202/bc84e833-9d96-4170-9181-6ad7f75448ec)

### ProtocolLib Version

5.1.0-SNAPSHOT-654
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69685202/59793ebd-d94f-4ac2-9194-547f88c43723)

### LoneLibs Version

1.0.25
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69685202/66dc4352-3c9f-4f10-9a5d-c01c3482f606)

**Comment by LoneDev6** [comment] 2023-06-21 13:37
Duplicate of: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2232#issuecomment-1496117329

Basically you have an old version of the emotes pack which lacks some bones.
Make sure your emotes file has all needed bones.

**Closed by LoneDev6** 2023-06-21 13:37 UTC
Labels: type: bug

**Comment by Yassounou** [comment] 2023-06-21 15:11
thnak you, what is the procedure than ? where can I found the new version of emotes pack ?

**Comment by Yassounou** [comment] 2023-06-21 15:12
My bad, fixed !
