### ISSUE TITLE
ItemsAdder_4.0.2-beta-release-9

### ISSUE THREAD

**Issue by Htjake** [PluginBugs/Issues-ItemsAdder#3982] opened 2024-09-05 07:31 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

666jake

### What happened?

[02:19:38] [Server thread/ERROR]: [ItemsAdder] Error moving corrupted region to 'corrupted_data' folder
[02:19:38] [Server thread/WARN]: java.io.FileNotFoundException: File system element for parameter 'source' does not exist: '.\world\itemsadder\region\r.-1.-1.pregion'
[02:19:38] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.requireExistsChecked(FileUtils.java:2802)
[02:19:38] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.requireFileCopy(FileUtils.java:2833)
[02:19:38] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:799)
[02:19:38] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:834)
[02:19:38] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:742)
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cP.a(SourceFile:134)
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.b(SourceFile:71)
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.d(SourceFile:112)
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.a(SourceFile:148)
[02:19:38] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[02:19:38] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:19:38] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:19:38] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[02:19:38] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[02:19:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:665)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.common.util.ChunkSystem.onChunkBorder(ChunkSystem.java:91)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1281)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1364)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1348)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1303)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:341)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:743)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:337)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1525)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1588)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[02:19:38] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[02:19:38] [Server thread/ERROR]: [ItemsAdder] Failed to load chunk (region is null). -6 | -10
[02:19:38] [Server thread/ERROR]: [ItemsAdder] Corrupted region data! Copying it into '_corrupted' folder. 
[02:19:38] [Server thread/WARN]: java.lang.NoClassDefFoundError: io/protostuff/Message
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cY.fO(SourceFile:64)
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.da.<init>(SourceFile:87)
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cP.a(SourceFile:123)
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.b(SourceFile:71)
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.d(SourceFile:112)
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.a(SourceFile:148)
[02:19:38] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[02:19:38] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:19:38] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:19:38] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[02:19:38] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[02:19:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:665)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.common.util.ChunkSystem.onChunkBorder(ChunkSystem.java:91)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1281)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1364)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1348)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1303)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:790)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:90)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:399)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:689)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[02:19:38] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[02:19:38] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: io.protostuff.Message
[02:19:38] [Server thread/WARN]: 	... 28 more
[02:19:38] [Server thread/ERROR]: [ItemsAdder] Error moving corrupted region to 'corrupted_data' folder
[02:19:38] [Server thread/WARN]: java.io.FileNotFoundException: File system element for parameter 'source' does not exist: '.\world\itemsadder\region\r.-1.-1.pregion'
[02:19:38] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.requireExistsChecked(FileUtils.java:2802)
[02:19:38] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.requireFileCopy(FileUtils.java:2833)
[02:19:38] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:799)
[02:19:38] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:834)
[02:19:38] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:742)
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cP.a(SourceFile:134)
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.b(SourceFile:71)
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.d(SourceFile:112)
[02:19:38] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.a(SourceFile:148)
[02:19:38] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[02:19:38] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:19:38] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:19:38] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[02:19:38] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[02:19:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:665)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.common.util.ChunkSystem.onChunkBorder(ChunkSystem.java:91)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1281)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1364)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1348)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1303)
[02:19:38] [Server thread/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:790)
[02:19:38] [Server thread/WARN]: 	at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:90)

### Steps to reproduce the issue

Just add the update to my server

### Server version

paper-1.21.1-40

### ItemsAdder Version

ItemsAdder_4.0.2-beta-release-9

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs_1.0.58

### Full Server Log

https://mclo.gs/E5VON2F#L1003

**Comment by LoneDev6** [comment] 2024-09-05 07:52
Duplicate of #3966

**Closed by LoneDev6** 2024-09-05 07:52 UTC
Labels: type: bug
