### ISSUE TITLE
[ItemsAdder] Failed to protect zip file.

### ISSUE THREAD

**Issue by ArdayraL** [PluginBugs/Issues-ItemsAdder#3968] opened 2024-09-02 18:31 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

ardayral.

### What happened?

I get this error when I use the /iazip command

### Steps to reproduce the issue

1. use the command /iazip
2. and get this error

### Server version

git-Purpur-2176 (MC: 1.20.4)*

### ItemsAdder Version

3.6.4-release-3

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.57

### Full Server Log

https://mclo.gs/mpZ5BiD

### Error (optional)

```shell
[21:23:32 ERROR]: [ItemsAdder] Failed to protect zip file.
[21:23:32 WARN]: java.lang.IndexOutOfBoundsException
[21:23:32 WARN]:        at java.base/java.io.RandomAccessFile.writeBytes0(Native Method)
[21:23:32 WARN]:        at java.base/java.io.RandomAccessFile.writeBytes(RandomAccessFile.java:572)
[21:23:32 WARN]:        at java.base/java.io.RandomAccessFile.write(RandomAccessFile.java:602)
[21:23:32 WARN]:        at ItemsAdder_3.6.4-release-3.jar//ia.m.qk.e(SourceFile:116)
[21:23:32 WARN]:        at ItemsAdder_3.6.4-release-3.jar//ia.m.pZ.a(SourceFile:229)
[21:23:32 WARN]:        at ItemsAdder_3.6.4-release-3.jar//ia.m.qd.a(SourceFile:454)
[21:23:32 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[21:23:32 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:23:32 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:23:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:23:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:23:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Andre601** [comment] 2024-09-02 18:49
Duplicate of #3919

**Closed** 2024-09-02 18:50 UTC
Labels: type: bug, type: duplicate
