### ISSUE TITLE
[SUGGEST] Add support for SlimeworldManager

### ISSUE THREAD

**Issue by matyasvane** [PluginBugs/Issues-ItemsAdder#2371] opened 2023-02-26 17:20 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

SinFileX#7759

### Describe the solution you'd like

I would like to suggest adding support for the SlimeWorldManager (new name is AdvancedSlimePaper) plugin. It is a plugin that can effectively reduce the size of the worlds and at the same time it is possible to save the worlds to a database etc. The problem is that the ItemsAdder plugin saves files in the form of mca files in the world. Which AdvancedSlimePaper itself does not support precisely because it is an outdated solution. AdvancedSlimePaper uses a new compression class to save space.

I think it would be good to add something like AdvancedSlimePaper: true/false.

https://github.com/InfernalSuite/AdvancedSlimePaper

### Is your feature request related to a problem?

In a way, yes, because by using the AdvancedSlimePaper plugin, custom items are loading poorly.

### Describe alternatives you've considered

There is no other option either to be stuck with the old version and that my world will be several gb or to use an alternative plugin that does not use mca files.

**Comment by LoneDev6** [comment] 2023-02-27 10:49
The new upcoming update should support this.
If not I'll try to check if I can easily add support.

Notes:
I hope you know that Slime format is not ideal for survival and for similar game modes since the Slime format is meant to make the server load EVERY chunk in RAM, so if you have a big survival world the server will explode.
I have no idea if AdvancedSlimePaper breaks the Slime format specification and loads only needed chunks, but as I said the normal Slime format is meant to load every chunk from disk into RAM on world load. So be careful.

**Comment by LoneDev6** [comment] 2023-02-27 10:51
Duplicate of: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1589

**Closed by LoneDev6** 2023-02-27 10:51 UTC
Labels: Enhancement, Feature request, Future update, Compatibility with other stuff, Unofficial Spigot Fork
