### ISSUE TITLE
1.19.4 - Emoji display in /e is broken

### ISSUE THREAD

**Issue by w1th0utme** [PluginBugs/Issues-ItemsAdder#3330] opened 2024-01-13 19:59 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/137961937/8e90e8d9-d515-4799-a10a-7d08c8083524)

### Steps to reproduce the issue

Write /e and see what is shown in my screenshot

### Server version

1.20.1

### ItemsAdder Version

3.6.3-beta-7

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.45

**Comment by w1th0utme** [comment] 2024-01-16 20:07
`[23:06:46 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: java.lang.ClassCastException: Cannot cast net.kyori.adventure.text.TextComponentImpl to net.minecraft.network.chat.IChatBaseComponent
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializerPatched.deserialize(MinecraftComponentSerializerPatched.java:206) ~[LoneLibs (14).jar:?]
        at dev.lone.LoneLibs.chat.Comp.nmsToComponent(Comp.java:188) ~[LoneLibs (14).jar:?]
        at ia.m.hE.a(SourceFile:24) ~[ItemsAdder_3.6.3-beta-8.jar:?]
        at ia.m.hC.i(SourceFile:124) ~[ItemsAdder_3.6.3-beta-8.jar:?]
        at ia.m.hv.onPacketSending(SourceFile:99) ~[ItemsAdder_3.6.3-beta-8.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:565) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:468) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:449) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2217) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.sendSystemMessage(ServerPlayer.java:1983) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.sendSystemMessage(ServerPlayer.java:1978) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:329) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:319) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:336) ~[paper-1.20.1.jar:git-Paper-196]
        at com.gmail.llmdlio.townyflight.util.MessageBuilder.to(MessageBuilder.java:20) ~[TownyFlight-1.8.7.jar:?]
        at com.gmail.llmdlio.townyflight.TownyFlightAPI.addFlight(TownyFlightAPI.java:169) ~[TownyFlight-1.8.7.jar:?]
        at com.gmail.llmdlio.townyflight.listeners.PlayerJoinListener.lambda$0(PlayerJoinListener.java:35) ~[TownyFlight-1.8.7.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassCastException: Cannot cast net.kyori.adventure.text.TextComponentImpl to net.minecraft.network.chat.IChatBaseComponent
        at java.lang.Class.cast(Class.java:3889) ~[?:?]
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializerPatched.deserialize(MinecraftComponentSerializerPatched.java:198) ~[LoneLibs (14).jar:?]
        ... 34 more
[23:06:46 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundSystemChatPacket@663d077[
    content=<null>
    b=false
  ]`

**Comment by LoneDev6** [comment] 2024-01-17 22:12
> ```
> [23:06:46 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
> java.lang.UnsupportedOperationException: java.lang.ClassCastException: Cannot cast net.kyori.adventure.text.TextComponentImpl to net.minecraft.network.chat.IChatBaseComponent
> ```

Duplicate of #3346

> Write /e and see what is shown in my screenshot

About the book issue, I cannot reproduce it on the latest ItemsAdder version beta-9.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/0a6f8286-1186-4bea-b0f5-cad7851172b6)

**Comment by w1th0utme** [comment] 2024-01-17 23:01
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/137961937/b9b19cb8-9512-43c3-9bff-6e7a53baad83)
I've now installed the beta-9 version and still the display is broken on the first 6 pages, on page 7 in the book the emoji display normally. Do you know what could be the problem? I noticed the text and increased the contrast in photoshop

**Comment by w1th0utme** [comment] 2024-01-17 23:03
@LoneDev6 There is no such problem on version 3.6.3-beta-5

**Comment by LoneDev6** [comment] 2024-01-18 12:22
I'll check, but this is strange, might be related to 1.20.1

**Comment by mario638** [comment] 2024-01-18 16:07
It happen too in 1.19.4

**Comment by LoneDev6** [comment] 2024-01-19 12:28
@mario638 
As shown in my screenshot it doesnt happen on 1.19.4.
Please make sure you have the LATEST 1.19.4 build.
If you still have issues provide a full server log.

**Closed** 2024-01-31 21:02 UTC
Labels: type: bug, outdated: server
