### ISSUE TITLE
rendertype_entity_translucent | Shader | Purpur 1.21.1 | ItemsAdder 4.0.5

### ISSUE THREAD

**Issue by DxrkCat** [PluginBugs/Issues-ItemsAdder#4249] opened 2024-12-14 11:34 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

I installed the latest versions of all plugins: ProtocolLib, ModelEngine, ItemsAdder, LoneLibs, after restarting the server. I wrote /meg reload, then /iazip, then filled a file with a unique name in cloud storage and uploaded to the server. I get Resourcepack failed.
Tested on Fabric 1.21.1/1.21.4, FO 6.2.1, Fabric 1.21.4 + ViaFabricPlus, Vanilla 1.21.4/1.21.1.
Error I encountered for the first time: https://mclo.gs/V61yrl9 (client log)
After disabling text-effects, emotes, extract-shader in the ItemsAdder config and after a complete reboot of the server and /iazip: https://mclo.gs/fVm0ae4.

### Steps to reproduce the issue

I installed the latest versions of all plugins: ProtocolLib, ModelEngine, ItemsAdder, LoneLibs, after restarting the server. I wrote /meg reload, then /iazip, then filled a file with a unique name in cloud storage and uploaded to the server. I get Resourcepack failed.
Tested on Fabric 1.21.1/1.21.4, FO 6.2.1, Fabric 1.21.4 + ViaFabricPlus, Vanilla 1.21.4/1.21.1.
Error I encountered for the first time: https://mclo.gs/V61yrl9 (client log)
After disabling text-effects, emotes, extract-shader in the ItemsAdder config and after a complete reboot of the server and /iazip: https://mclo.gs/fVm0ae4.

### Server version

 Server version: [Purpur 1.21.1 build 2329 official](https://api.purpurmc.org/v2/purpur/1.21.1/2329/download)

### ItemsAdder Version

ItemsAdder 4.0.5

### ProtocolLib Version

ver protocoll
[14:34:14 INFO]: ProtocolLib version 5.3.0
[14:34:14 INFO]: Provides read/write access to the Minecraft protocol.
[14:34:14 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

ver lone
[14:34:22 INFO]: LoneLibs version 1.0.62
[14:34:22 INFO]: Collection of libs used by my plugins
[14:34:22 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/fVm0ae4

### Error (optional)

```shell
https://mclo.gs/fVm0ae4
```

**Comment by Andre601** [comment] 2024-12-14 12:34
Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue. Sending just the error doesn't help us at all here.

**Comment by DxrkCat** [comment] 2024-12-14 12:37
> Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue. Sending just the error doesn't help us at all here.

/iazip https://mclo.gs/oDiG7oV

I can't provide a full log, because there is a lot of technical information from my plugins in the console.

**Comment by Andre601** [comment] 2024-12-14 12:40
I'm certain whatever "technical information" there is, it's not sensitive at all. And if it is shouldn't you print it in the console in the first place.

**Comment by DxrkCat** [comment] 2024-12-14 12:41
> I'm certain whatever "technical information" there is, it's not sensitive at all. And if it is shouldn't you print it in the console in the first place.

I understand that and realize I'm creating difficulties, but I can provide any log information individually.

**Comment by Andre601** [comment] 2024-12-14 12:44
And I ask you provide the full log as-is.

The one you provided is already questionable as the generated zip path lacks the path dividers (`/`) wich is odd and something no default logging would do here. Neither in console not log file.

**Comment by DxrkCat** [comment] 2024-12-14 12:44
https://github.com/PluginBugs/Issues-ItemsAdder/issues/4177

I've seen this, can't this patch do that? I just noticed someone trying to get at the /core/core path which seems very odd.

**Comment by DxrkCat** [comment] 2024-12-14 12:46
> And I ask you provide the full log as-is.
> 
> The one you provided is already questionable as the generated zip path lacks the path dividers (`/`) wich is odd and something no default logging would do here. Neither in console not log file.

My servers are running in docker via PufferPanel, this is a problem with the ItemsAdder code, specifically just the visual which is only output to the log, but previously everything worked I've been using ItemsAdder for a few years now.

**Comment by KrazyxWolf** [comment] 2024-12-14 16:47
I had the same problem with the same cause, the cause is that rendertype_entity_translucent.json is added in the shaders folder causing the texturepack not to be applied correctly because the file was not found in a directory that repeats “core” twice

the solution I applied was to disable shader generation in the ModelEngine config, copy the shaders folder that generates model engine to the minecraft folder, delete the rendertype_entity_translucent.json file and delete the “minecraft:” part of the rendertype_entity_translucent.vsh and rendertype_entity_translucent.fsh file amounts, I don't know if it is correct to do it but it worked in my case

**Comment by breitwan** [comment] 2024-12-14 18:13
I've got the same problem today.

**Comment by DxrkCat** [comment] 2024-12-14 21:06
A solution that worked for me:
1) Go into the ModelEngine folder and into config.yml and set the following value: Create-Shader: false
2) Delete the folder in the ModelEngine folder 'resource pack' and '.data' folders.
3) Write the command /iazip and use the new resourcepack

**Comment by AnaNazzDev** [comment] 2024-12-15 14:57
Solution: 
Disable the config setting added here: #4177

**Comment by DxrkCat** [comment] 2024-12-15 15:04
> Solution: Disable the config setting added here: #4177
  | [15:36:25 WARN]: [ItemsAdder] [Pack] pre-1.21.3 shader JSON found. Adding 1.21.3+ compatibility. File: resource pack/assets/minecraft/shaders/core/rendertype_entity_translucent.json


In the logs I threw above, you can see that this function is already working.
But for some reason, it's not working.

**Comment by LoneDev6** [comment] 2024-12-17 18:23
Possible duplicate of #4159
https://github.com/PluginBugs/Issues-ItemsAdder/issues/4159#issuecomment-2548599162

**Closed by LoneDev6** 2024-12-17 18:23 UTC
Labels: type: bug
