### ISSUE TITLE
Custom growth process models for seeds

### ISSUE THREAD

**Issue by LM5610** [PluginBugs/Issues-ItemsAdder#3742] opened 2024-06-16 18:38 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I want to be able to customize the growth process of the crop and replace it, for example, when the wheat seeds are planted, replace them with my custom configuration

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

I didn't consider replacing it with another plugin

**Comment by LoneDev6** [comment] 2024-06-18 10:08
Duplicate of #554

**Closed by LoneDev6** 2024-06-18 10:08 UTC
Labels: type: enhancement, type: feature request
