### ISSUE TITLE
REAL_NOTE blocks can be duplicated with an axe

### ISSUE THREAD

**Issue by Xiao-MoMi** [PluginBugs/Issues-ItemsAdder#991] opened 2021-06-29 16:18 UTC
Describe the bug
REAL_NOTE blocks can be duplicated with an axe

Info (please complete the following information):
Test 1: 
Server Core spigot1.17
Client vanilla 1.17
Plugin version 2.4.0 ,2.4.1

Test 2:
Server Core Purpur 1.16.5 - 1171
Client vanilla 1.16.5
Plugin version 2.3.12

items:
  bamboo_block:
    display_name: 竹子块
    resource:
      model_id: 1000
      material: NOTE_BLOCK
      generate: true
      textures:
      - block/decoration/bamboo_block_top.png
      - block/decoration/bamboo_block.png
      - block/decoration/bamboo_block.png
      - block/decoration/bamboo_block.png
      - block/decoration/bamboo_block_top.png
      - block/decoration/bamboo_block.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM

This is an example block. 

When I break it with an axe (first left click and then **keep right click**, ps: this means when the block is broken I'm doing right clicks) 
Then the blcok will be restored and drop itself
Maybe something wrong with "tune the note_block"

https://imgtu.com/i/RwBk4O
GIF here : https://imgtu.com/i/RwrCtK

**Comment by Xiao-MoMi** [comment] 2021-06-29 16:54
In Addtion, the block can only be dupilicated when this is no block above it. If this a block on it, it won't work.

**Comment by LoneDev6** [comment] 2021-06-30 09:35
I tested and it's not happening, I can't reproduce the issue (check the video)

https://user-images.githubusercontent.com/27242001/123938106-1cb75c80-d997-11eb-8229-71e7cff9d9fb.mp4

`/version`  -> `This server is running CraftBukkit version 3162-Spigot-f773da8-b121d3b (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)`

Config:
```yml
  bamboo_block:
    display_name: 竹子块
    resource:
      model_id: 1000
      material: NOTE_BLOCK
      generate: true
      textures:
      - block/decoration/bamboo_block_top.png
      - block/decoration/bamboo_block.png
      - block/decoration/bamboo_block.png
      - block/decoration/bamboo_block.png
      - block/decoration/bamboo_block_top.png
      - block/decoration/bamboo_block.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
```

**Comment by Xiao-MoMi** [comment] 2021-06-30 10:55
I tested this with my friend and he has the same problem. Maybe you didn't break it with **"right click".**

**Comment by Xiao-MoMi** [comment] 2021-06-30 11:05
I record another video and you can check it here.
https://imgtu.com/i/RBIgLq

**Comment by LoneDev6** [comment] 2021-06-30 12:15
Thanks, I finally managed to trigger the issue, this will be fixed in the new update

**Closed** 2021-06-30 13:08 UTC
Labels: bug
