### ISSUE TITLE
The item is not working

### ISSUE THREAD

**Issue by Primot-Off** [PluginBugs/Issues-ItemsAdder#3522] opened 2024-03-27 21:13 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

primotoff

### What happened?

It throws an error to the console when I add a cooldown and many other parameters to an item and try to use it

### Steps to reproduce the issue

Well, put paper 1.20.4, all the necessary plugins, write the same config and try to use the item

### Server version

[00:08:21 INFO]: This server is running Paper version git-Paper-462 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 00fd87a)
You are running the latest version
Previous version: git-Paper-447 (MC: 1.20.4)

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Error (optional)

```shell
[23:59:08 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.6.3-beta-13
java.lang.NullPointerException: Cannot read field "B" because the return value of "java.util.Map.get(Object)" is null
        at ia.m.bp.a(SourceFile:357) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.du.a(SourceFile:192) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1228) ~[?:?]
        at dev.lone.LoneLibs.S.mapData(S.java:20) ~[LoneLibs.jar:?]
        at ia.m.du.a(SourceFile:190) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.dp.a(SourceFile:861) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.eM.a(SourceFile:570) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.eM.a(SourceFile:578) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.ey.j(SourceFile:352) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.du.a(SourceFile:176) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.du.h(SourceFile:292) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-462]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-462]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-462]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593) ~[paper-1.20.4.jar:git-Paper-462]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[paper-1.20.4.jar:git-Paper-462]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.20.4.jar:git-Paper-462]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:540) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1993) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1516) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-462]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Problematic items yml configuration file (optional)

```shell
potato_heart:
    display_name: "<gradient:#58CC30:#32AC3C:#58CC30>Картофельное сердце"
    permission: potatoes.potato_heart
    lore:
      - ""
      - "<#58CC30>  ★ <#A8A8A8>Призывает картофель-индейца  "
      - ""
      - "&9Питомцы"
    events_settings:
      cooldown:
        indicator: HIDDEN
        ticks: 120
    events:
      interact:
        right:
          execute_commands_2:
            cmd2:
              command: 'lp user {player} permission set mcpets.indian_potato_warrior'
              as_console: true
            cmd3:
              command: 'tellraw {player} {"text": "Вы получили питомца Картофель-индеец\nОн доступен по команду /pets", "color": "#58CC30"}'
              as_console: true
```

**Comment by LoneDev6** [comment] 2024-04-04 14:24
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/3488

**Closed by LoneDev6** 2024-04-04 14:24 UTC
Labels: type: bug
