### ISSUE TITLE
bug of name and lore

### ISSUE THREAD

**Issue by Steve29794** [PluginBugs/Issues-ItemsAdder#3885] opened 2024-08-13 14:04 UTC
### Terms

- [ ] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When I put items made by ItemsAdder into other plugins, the color format of lore and name will change, usually to purple, because white disappears (&f->&r) from nbt, and the durability translation will also change. The nbt before and after the change are below.Many plugins have this problem with itemsadder items

====Before NBT====[22:01:59 INFO]: itemsadder (Compound)
[22:01:59 INFO]:   custom_durability (Int): 9000
[22:01:59 INFO]:   namespace (String): custom
[22:01:59 INFO]:   id (String): nightfall_moon_shadow_3
[22:01:59 INFO]:   fake_durability (Double): 2031.0
[22:01:59 INFO]:   max_custom_durability (Int): 9000
[22:01:59 INFO]: display (Compound)
[22:01:59 INFO]:   Name (String): {"italic":false,"color":"white","extra":[{"bold":true,"extra":[{"color":"#1616EE","text":"夜"},{"color":"#221AEA","text":"幕"},{"color":"#2F1EE5","text":"月"},{"color":"#3B23E1","text":"影"},{"color":"#4827DD","text":" "},{"obfuscated":true,"text":"A"},{"extra":[{"color":"#612FD4","text":" "},{"color":"#6D33D0","text":"N"},{"color":"#7A38CB","text":"i"},{"color":"#863CC7","text":"g"},{"color":"#9340C3","text":"h"},{"color":"#9F44BE","text":"t"},{"color":"#AC48BA","text":"f"},{"color":"#B84DB6","text":"a"},{"color":"#C551B1","text":"l"},{"color":"#D155AD","text":"l"}],"text":""}],"text":""}," ",{"bold":true,"extra":[{"color":"#51FF00","text":"["},{"color":"#44F52B","text":"R"},{"color":"#36EB55","text":"a"},{"color":"#29E180","text":"n"},{"color":"#1BD7AA","text":"k"},{"color":"#0ECDD5","text":"3"},{"color":"#00C3FF","text":"]"}],"text":""}],"text":""}
[22:01:59 INFO]:   Lore (List)
[22:01:59 INFO]:     - {"italic":false,"color":"red","text":"[!] 需要自然合成台"}
[22:01:59 INFO]:     - {"italic":false,"color":"black","text":"nightfall_moon_shadow_3"}
[22:01:59 INFO]:     - {"italic":false,"color":"white","extra":[{"color":"gray","text":"刀光如月光倾泻，既幽美又致命"}],"text":" ? "}
[22:01:59 INFO]:     - {"italic":false,"color":"white","extra":[{"color":"gray","text":"如鬼魅般在黑暗中舞动，刀光伴随月光流转"}],"text":" ? "}
[22:01:59 INFO]:     - {"italic":false,"color":"white","text":""}
[22:01:59 INFO]:     - {"italic":false,"color":"white","extra":[{"color":"aqua","text":"被动: 月光庇护"}],"text":" ? "}
[22:01:59 INFO]:     - {"italic":false,"color":"white","extra":[{"color":"gray","text":"[生命恢复 II][力量 II][抗性提升 I] "},"效果"],"text":" ? 给予自身 "}
[22:01:59 INFO]:     - {"italic":false,"color":"white","text":""}
[22:01:59 INFO]:     - {"italic":false,"color":"white","extra":[{"color":"aqua","text":"被动: 代表月亮消灭你"}],"text":" ? "}
[22:01:59 INFO]:     - {"italic":false,"color":"white","extra":[{"color":"gray","text":"50%"},", 给予目标 ",{"color":"gray","text":"[瞬间伤害 II] (15%)"}],"text":" ? 若目标血量低于 "}
[22:01:59 INFO]:     - {"italic":false,"color":"white","text":""}
[22:01:59 INFO]:     - {"italic":false,"color":"white","extra":[{"color":"yellow","text":"主动: 陨星"}],"text":" ? "}
[22:01:59 INFO]:     - {"italic":false,"color":"white","extra":[{"color":"gray","text":"60 "},"伤害和 ",{"color":"gray","text":"[缓慢 II 5s] (CD: 20s)"}],"text":" ? 召唤陨石从天而降, 击中造成 "}
[22:01:59 INFO]:     - {"italic":false,"color":"white","text":""}
[22:01:59 INFO]:     - {"italic":false,"color":"white","extra":[{"bold":true,"color":"blue","text":"合"},{"bold":true,"color":"#6A6AFD","text":"成"},{"bold":true,"color":"#7E7EFA","text":"武"},{"bold":true,"color":"#9393F8","text":"器 "},"? ",{"bold":true,"color":"aqua","text":"后期 "},"?"],"text":" ? "}
[22:01:59 INFO]:     - ""
[22:01:59 INFO]:     - {"italic":false,"color":"gray","translate":"item.modifiers.mainhand"}
[22:01:59 INFO]:     - {"italic":false,"color":"dark_green","extra":[{"translate":"attribute.name.generic.attack_damage"}],"text":" 60 "}
[22:01:59 INFO]:     - {"italic":false,"color":"dark_green","extra":[{"translate":"attribute.name.generic.attack_speed"}],"text":" 1.6 "}
[22:01:59 INFO]:     - {"italic":false,"color":"gray","translate":"item.durability","with":["9000","9000"]}
[22:01:59 INFO]: CustomModelData (Int): 10035
[22:01:59 INFO]: AttributeModifiers (List): [{Amount:59.0d,AttributeName:"minecraft:generic.attack_damage",Name:"itemsadder",Operation:0,Slot:"mainhand",UUID:[I;-1021815546,956249177,-1761678598,-1975758316]},{Amount:-2.4d,AttributeName:"minecraft:generic.attack_speed",Name:"itemsadder",Operation:0,Slot:"mainhand",UUID:[I;-382952925,1706897539,-2132299899,-42273457]},{Amount:10.0d,AttributeName:"minecraft:generic.max_health",Name:"itemsadder",Operation:0,Slot:"mainhand",UUID:[I;-162055191,1119829387,-1761047183,554763831]},{Amount:3.0d,AttributeName:"minecraft:generic.armor",Name:"itemsadder",Operation:0,Slot:"mainhand",UUID:[I;1251030560,362034937,-1151768085,-2048396924]}]
[22:01:59 INFO]: Damage (Int): 0
[22:01:59 INFO]: HideFlags (Int): 2
====After NBT====
[22:02:30 INFO]: itemsadder (Compound)
[22:02:30 INFO]:   custom_durability (Int): 9000
[22:02:30 INFO]:   namespace (String): custom
[22:02:30 INFO]:   id (String): nightfall_moon_shadow_3
[22:02:30 INFO]:   fake_durability (Double): 2031.0
[22:02:30 INFO]:   max_custom_durability (Int): 9000
[22:02:30 INFO]: display (Compound)
[22:02:30 INFO]:   Name (String): {"text":"","extra":[{"text":"夜","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#1616EE","bold":false},{"text":"幕","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#221AEA","bold":false},{"text":"月","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#2F1EE5","bold":false},{"text":"影","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#3B23E1","bold":false},{"text":" ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#4827DD","bold":false},{"text":"A","obfuscated":true,"italic":false},{"text":" ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#612FD4","bold":false},{"text":"N","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#6D33D0","bold":false},{"text":"i","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#7A38CB","bold":false},{"text":"g","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#863CC7","bold":false},{"text":"h","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#9340C3","bold":false},{"text":"t","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#9F44BE","bold":false},{"text":"f","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#AC48BA","bold":false},{"text":"a","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#B84DB6","bold":false},{"text":"l","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#C551B1","bold":false},{"text":"l","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#D155AD","bold":false},{"text":" ","italic":false},{"text":"[","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#51FF00","bold":false},{"text":"R","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#44F52B","bold":false},{"text":"a","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#36EB55","bold":false},{"text":"n","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#29E180","bold":false},{"text":"k","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#1BD7AA","bold":false},{"text":"3","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#0ECDD5","bold":false},{"text":"]","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#00C3FF","bold":false}]}
[22:02:30 INFO]:   Lore (List)
[22:02:30 INFO]:     - {"text":"","extra":[{"text":"[!] 需要自然合成台","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"red","bold":false}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":"nightfall_moon_shadow_3","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"black","bold":false}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":" ? ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false},{"text":"刀光如月光倾泻，既幽美又致命","italic":false,"color":"gray"}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":" ? ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false},{"text":"如鬼魅般在黑暗中舞动，刀光伴随月光流转","italic":false,"color":"gray"}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":"","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":" ? ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false},{"text":"被动: 月光庇护","italic":false,"color":"aqua"}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":" ? 给予自身 ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false},{"text":"[生命恢复 II][力量 II][抗性提升 I] ","italic":false,"color":"gray"},{"text":"效果","italic":false}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":"","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":" ? ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false},{"text":"被动: 代表月亮消灭你","italic":false,"color":"aqua"}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":" ? 若目标血量低于 ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false},{"text":"50%","italic":false,"color":"gray"},{"text":", 给予目标 ","italic":false},{"text":"[瞬间伤害 II] (15%)","italic":false,"color":"gray"}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":"","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":" ? ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false},{"text":"主动: 陨星","italic":false,"color":"yellow"}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":" ? 召唤陨石从天而降, 击中造成 ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false},{"text":"60 ","italic":false,"color":"gray"},{"text":"伤害和 ","italic":false},{"text":"[缓慢 II 5s] (CD: 20s)","italic":false,"color":"gray"}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":"","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":" ? ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false},{"text":"合","italic":false,"color":"blue","bold":true},{"text":"成","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#6A6AFD","bold":true},{"text":"武","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#7E7EFA","bold":true},{"text":"器 ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#9393F8","bold":true},{"text":"? ","italic":false,"bold":false},{"text":"后期 ","italic":false,"color":"aqua","bold":true},{"text":"?","italic":false,"bold":false}]}
[22:02:30 INFO]:     - ""
[22:02:30 INFO]:     - {"text":"","extra":[{"text":"When in Main Hand:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":" 60 ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"dark_green","bold":false},{"text":"Attack Damage","italic":false}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":" 1.6 ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"dark_green","bold":false},{"text":"Attack Speed","italic":false}]}
[22:02:30 INFO]:     - {"text":"","extra":[{"text":"Durability: 9000 / 9000","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}
[22:02:30 INFO]: CustomModelData (Int): 10035
[22:02:30 INFO]: AttributeModifiers (List): [{Amount:59.0d,AttributeName:"minecraft:generic.attack_damage",Name:"itemsadder",Operation:0,Slot:"mainhand",UUID:[I;-1021815546,956249177,-1761678598,-1975758316]},{Amount:-2.4d,AttributeName:"minecraft:generic.attack_speed",Name:"itemsadder",Operation:0,Slot:"mainhand",UUID:[I;-382952925,1706897539,-2132299899,-42273457]},{Amount:10.0d,AttributeName:"minecraft:generic.max_health",Name:"itemsadder",Operation:0,Slot:"mainhand",UUID:[I;-162055191,1119829387,-1761047183,554763831]},{Amount:3.0d,AttributeName:"minecraft:generic.armor",Name:"itemsadder",Operation:0,Slot:"mainhand",UUID:[I;1251030560,362034937,-1151768085,-2048396924]}]
[22:02:30 INFO]: Damage (Int): 0
[22:02:30 INFO]: HideFlags (Int): 2

### Steps to reproduce the issue

1. get a "ia" item
2. put the item into the other plugins like "cmi inv" or "ecraft create"
3. you will notice that name's and lore's colors have changed

### Server version

Current: git-Purpur-2176 (MC: 1.20.4)*
* You are running the latest version

### ItemsAdder Version

3.6.4-release-2

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.54

### Full server log

https://mclo.gs/CrMAsNc

### Error (optional)

```shell
none
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: custom
items:
  nightfall_moon_shadow_1:
    enabled: true
    display_name: display-name-nightfall_moon_shadow_1
    lore:
      - "display-lore-need_natural_workbench"
      - "&0nightfall_moon_shadow_1"
      - "display-lore-nightfall_moon_shadow-1"
      - "display-lore-nightfall_moon_shadow-2"
      - ""
      - "display-lore-nightfall_moon_shadow-passive-1"
      - "display-lore-nightfall_moon_shadow-passive-2"
      - ""
      - "display-lore-nightfall_moon_shadow-passive-3"
      - "display-lore-nightfall_moon_shadow-passive-4"
      - ""
      - "display-lore-nightfall_moon_shadow-skill-1"
      - "display-lore-nightfall_moon_shadow-skill-2-1"
      - ""
      - "display-lore-weapon-3"
    durability:
      max_custom_durability: 9000
    resource:
      material: NETHERITE_SWORD
      generate: true
      textures:
        - item/weapons/nightfall_moon_shadow.png
    attribute_modifiers:
      mainhand:
        attackDamage: 47
        attackSpeed: 1.6
        maxHealth: 10
        armor: 3
    events:
      held:
        execute_commands:
          cmd1:
            command: "ppo {player} add sculk_charge move"
            as_console: true
            delay: 0
          cmd2:
            command: "ppo {player} add enchant swords"
            as_console: true
            delay: 0
          cmd3:
            command: "ppo {player} add dust orbit rainbow"
            as_console: true
            delay: 0
      unheld:
        execute_commands:
          cmd1:
            command: "ppo {player} remove sculk_charge"
            as_console: true
            delay: 0
          cmd2:
            command: "ppo {player} remove enchant"
            as_console: true
            delay: 0
          cmd3:
            command: "ppo {player} remove dust"
            as_console: true
            delay: 0
```

### Other files, you can drag and drop them here to upload. (optional)

![image](https://github.com/user-attachments/assets/2322a961-128d-4c8c-96f6-75e4cfe818e9)

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/user-attachments/assets/3708d3cc-a284-4884-b891-04bbd1b4ca9f

**Comment by Andre601** [comment] 2024-08-13 14:32
First of all, you are outdated. Please update the plugin to the latest available v3 version on Spigot (NOT v4!).

Next do I believe that this may not directly be an ItemsAdder issue here, but more a general issue with how ItemMeta (The stuff containing the Item display name, lore, etc) is handled. It could also be an issue with ViaVersion causing issues too due to their conversion stuff.

To properly debug this, please test this issue on a 1.20.4 server with only ItemsAdder and its dependencies installed. No other plugins should be installed. And also test with a vanilla 1.20.4 client to filter out possible mod issues.
If the issue still exists in this environment (i.e. by moving it in and out of a chest), then it's an ItemsAdder issue most likely. If not, then it may indeed be an issue with either ViaVersion or just the server itself.

**Comment by AwesomeDY** [comment] 2024-08-14 12:21
> First of all, you are outdated. Please update the plugin to the latest available v3 version on Spigot (NOT v4!).
> 
> Next do I believe that this may not directly be an ItemsAdder issue here, but more a general issue with how ItemMeta (The stuff containing the Item display name, lore, etc) is handled. It could also be an issue with ViaVersion causing issues too due to their conversion stuff.
> 
> To properly debug this, please test this issue on a 1.20.4 server with only ItemsAdder and its dependencies installed. No other plugins should be installed. And also test with a vanilla 1.20.4 client to filter out possible mod issues. If the issue still exists in this environment (i.e. by moving it in and out of a chest), then it's an ItemsAdder issue most likely. If not, then it may indeed be an issue with either ViaVersion or just the server itself.

I'm sorry that I didn't notice the version of IA. I tested it according to your method and found no problems, but I don't think this means that IA itself has no issues. Firstly, there are no Bukkit API calls involved when putting it into the chest and then taking it out, so naturally there should be no changes in nbt. Moreover, even if I install many plugins, there was no mistakes when I putting it in and taking it out of the chest. At the same time, I copied Lore to the items manager of MythiMobs for testing and found that the problem I encountered did not occur.

**Comment by LoneDev6** [comment] 2024-08-19 13:35
> put the item into the other plugins like "cmi inv" or "ecraft create"
you will notice that name's and lore's colors have changed

This is caused by other plugins using different API to handle texts, this makes the lore/name properties format in another order.
I can't do anything about that sadly.

**Closed by LoneDev6** 2024-08-19 13:35 UTC
Labels: type: bug
