### ISSUE TITLE
Texture pack sending each time after a server change

### ISSUE THREAD

**Issue by LuluxClient** [PluginBugs/Issues-ItemsAdder#3387] opened 2024-02-01 08:51 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

xdLulux

### What happened?

After updating my velocity, itemsadder, lonelibs, bungeepackfix, protocollib on ANY version on my 1.20.1 server, each time I change servers the texture pack gets downloaded again doesn't matter the version, even if I'm on 1.20.1 or 1.20.2-.4 

### Steps to reproduce the issue

1. update all of these plugins to the latest version available
2. change servers, boom 

### Server version

This server is running Pufferfish version git-Pufferfish-"979d3a2" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 979d3a2 on HEAD)
You are running 19 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Pufferfish-26 (MC: 1.20.1)

### ItemsAdder Version

ItemsAdder_3.6.3-beta-10

### ProtocolLib Version

5.2.0 b679

### LoneLibs Version

1.0.45

### Error (optional)

```shell
none
```

### Problematic items yml configuration file (optional)

```shell
none
```

**Comment by LuluxClient** [comment] 2024-02-01 08:56
What I tried:
- Downgrading itemsadder to my "ItemsAdder-3.6.1-beta-r2.jar" ver + latest bungeepackfix (1.1.5 beta-1), still fucked
- Using bungeepackfix 1.1.4 with the latest of itemsadder, still fucked
- other dumb combinations but none of them worked.

**Comment by LoneDev6** [comment] 2024-02-01 11:10
Seems a duplicate of this: https://github.com/LoneDev6/BungeePackFix/issues/44
Anyway I will do some more tests but I can't reproduce this issue.

**Closed by LoneDev6** 2024-02-01 11:10 UTC
Labels: type: bug

**Comment by LuluxClient** [comment] 2024-02-01 11:12
> Seems a duplicate of this: https://github.com/LoneDev6/BungeePackFix/issues/44
> 
> Anyway I will do some more tests but I can't reproduce this issue.

Feel free to contact me on discord so I could help you out with your tests !
