### ISSUE TITLE
[BUG] Fly is not enabled on this server

### ISSUE THREAD

**Issue by jurajplayercze** [PluginBugs/Issues-ItemsAdder#1007] opened 2021-07-06 08:57 UTC
**Describe the bug**
I think this is the simpliest description
Joining as owner: https://youtu.be/Qd8LgjGknNQ
Joining as player: https://youtu.be/lIgGywnn_-Y

It giving all players fly, when they join server. I think its prevention from bugging into textures or something like that. But it keeps kicking players
IF player have set option "prompt", its not kicking anyone i think

**Info (please complete the following information):**
 - Server version: (example: paper 1.16.5)
 - Client version: (example: fabric 1.16.5)

**Special Info**
 - ItemsAdder version: (example: 2.4.2)
 - LightAPI Fork version: (example: 3.5.0)
 - LoneLibs version: (example: 1.0.13)
 - ProtocolLib version: (example: 4.6.0)

**Comment by LoneDev6** [comment] 2021-07-06 09:43
ItemsAdder sets slowfalling potion effect to avoid people from falling while installing the pack.
I think this message is from an anticheat or another plugin. You should find the cause and disable this check.

If needed I may provide an option to disable the slowfalling potion effect on join

**Comment by jurajplayercze** [comment] 2021-07-06 09:48
Well, we don't have anticheat at all. I think its from spigot/paper/bukkit

**Comment by 100petr** [comment] 2021-07-10 10:17
server.properties -> allow-flight set to true

**Comment by LoneDev6** [comment] 2021-07-12 14:05
This will be fixed in the next update

**Closed by LoneDev6** 2021-07-12 14:05 UTC
Labels: bug
