### ISSUE TITLE
Breaking block sound without wooden sound

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1260] opened 2021-10-16 01:10 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

SLoKer#5953

### Describe the solution you'd like

Add functionality, the sound of breaking the block, that is, in time for the very process of breaking the block.
sound:
  break:
    name: BLOCK_STONE_BREAK
    volume: 1
    pitch: 0.9
  place:
    name: BLOCK_STONE_PLACE
    volume: 1
    pitch: 0.9
  breaking:
    name: BLOCK_STONE_HIT
    volume: 1
    pitch: 0.9  

### Is your feature request related to a problem?

No, you will just hear sound of BLOCK_WOOD_HIT when you break any blocks

### Describe alternatives you've considered

this is the best way to do it 
  breaking:
    name: BLOCK_STONE_HIT
    volume: 1
    pitch: 0.9

**Comment by MrJorman** [comment] 2022-07-04 22:24
A year has passed, there are no functions. The developer doesn't care)

**Comment by MrJorman** [comment] 2022-07-04 23:05
I don't see it adding a Hit sound feature.

**Comment by LoneDev6** [comment] 2022-07-05 12:54
I explained multiple times why this task is difficult to be implemented and has tons of downsides.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1732#issuecomment-1167522897

> If I recall I already did some tests in the past because I had the same idea, the issue is that I'd have to replace the wood sound with a blank sound which would require me to simulate the wood sound each time the server tries to play it, to avoid playing an empty sound.
> 
> I don't know if this is a really good solution sincerely.



I will make more tests to see if I can implement that feature without causing issues, but it's not that easy to avoid breaking servers functionality with that feature.

**Comment by LoneDev6** [comment] 2023-09-26 14:12
Duplicate of this more recent report which has more information: #2999

**Closed by LoneDev6** 2023-09-26 14:12 UTC
Labels: type: feature request
