### ISSUE TITLE
Black box texture (not solid block) on join

### ISSUE THREAD

**Issue by iceyy0044** [PluginBugs/Issues-ItemsAdder#2522] opened 2023-04-10 20:57 UTC
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Iceyy#0044

### What happened?

On join or when resourcepack reloads there are weird black texture which i need to place block inside of to make it go away + sometimes theres fire which can be seen from few angles but also from few angles you cant see theres an fire (you can hear it)

### Steps to reproduce the issue

As said above when i rejoin i just get this weird black texture usually + the fire just works when something burns from under it stays invisible above and stays in mid air without any blocks near it 

### Server version

![image](https://user-images.githubusercontent.com/115655879/230996717-ea53b3f1-1e24-4451-aa15-065ddd407820.png)

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/115655879/230996821-98909586-a22d-432f-9424-d80a7df19f88.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/115655879/230996892-ded5d97e-2315-472c-8d60-6f57ab1ec736.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/115655879/230996986-9e723a39-a9f2-4f4e-bccb-751bfc1bd987.png)

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11193944/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/115655879/230997503-da05564c-8756-43ba-9ce1-4216df00c921.png)
sadly dont have the fire issue on screen/video

**Comment by iceyy0044** [comment] 2023-04-12 12:27
Oh well we are using /iareload and /iazip pretty frequently as we are still working with the textures, but as the server is already in open beta i announced to the players that if this box issue happens to them they are supposed to send screen to us and which client are they using (pvp, vanilla, forge, fabric) and also if they happen to see the fire issue they will send me screens so if i still get the issue ill send screens here. Thanks for the answer tho...

**Comment by iceyy0044** [comment] 2023-04-12 12:37
Well right after i joined the server i got the black box issue .... ill see if i get more of those or the fire issues ....
![image](https://user-images.githubusercontent.com/115655879/231459397-463ada0f-990c-4229-a3b6-a4a52072ea80.png)

**Comment by iceyy0044** [comment] 2023-04-12 16:55
I just made an wood platform with world edit and then just ignited it ... thats it

**Comment by LoneDev6** [comment] 2023-04-17 15:46
The black box issue seems to be a duplicate of #2472 which should have been already fixed.
This is very strange. It happens only on modded clients.
I tested it for almost an hour and could not reproduce the black box issue anymore on r5, for some reason it still happens on your client.
What client is it?

**Comment by imhinotori** [comment] 2023-04-28 17:58
> > The fire just stays in middle of air and sometimes it is invisible from above
> 
> Do you have a way for me to precisely know how to reproduce the issue? Like how was the structure before igniting it?

Currently im having the same issue, there isnt a specific way to reproduce the problem, it happen on all burnable blocks

**Comment by iceyy0044** [comment] 2023-04-29 09:47
> The black box issue seems to be a duplicate of #2472 which should have been already fixed. This is very strange. It happens only on modded clients. I tested it for almost an hour and could not reproduce the black box issue anymore on r5, for some reason it still happens on your client. What client is it?

Iam using feather client but people with clients such as lunar or just forge get the black box issue too... i dont know where is the issue

**Comment by LoneDev6** [comment] 2023-05-02 12:22
I'll try to reproduce them again, it's very strange I could not

**Comment by LoneDev6** [comment] 2023-09-19 13:43
I can't reproduce the issue

**Comment by LoneDev6** [comment] 2024-05-07 16:12
Completely got rid of the black screen feature as it's useless for 1.20.3+ clients because the download bar is shown in a toast and not in a transparent background and the installation bar is fullscreen.
Also the new ItemsAdder feature allows installing the pack during login phase and not after the player logged in: #3616

**Closed** 2024-06-04 12:22 UTC
Labels: type: bug, verdict: can't reproduce, verdict: reintroduced after update
