### ISSUE TITLE
Itemsadder preventing deleting maps from Mythic Dungeon

### ISSUE THREAD

**Issue by LPPRR123** [PluginBugs/Issues-ItemsAdder#3845] opened 2024-07-31 15:31 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

same problem with https://github.com/PluginBugs/Issues-ItemsAdder/issues/3691
There's still an issue in Itemsadder v3.6.4-release-3

### Steps to reproduce the issue

same problem with https://github.com/PluginBugs/Issues-ItemsAdder/issues/3691

### Server version

 This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

### ItemsAdder Version

v3.6.4-release-3

### ProtocolLib Version

 ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.56

### Full server log

https://api.mclo.gs/1/raw/alR1stF

### Error (optional)

```shell
https://api.mclo.gs/1/raw/alR1stF
```

**Comment by LoneDev6** [comment] 2024-08-19 15:02
Duplicate of: #3245
Currently I have no solution for that issue as I can't find the cause, I also can't reproduce it, I already tested multiple times with MythicDungeons and I can't get the same result.

**Closed by LoneDev6** 2024-08-19 15:02 UTC
Labels: type: bug
