### ISSUE TITLE
Bug with Unexpected I/O error while handling webserver request

### ISSUE THREAD

**Issue by WataLaker37821** [PluginBugs/Issues-ItemsAdder#2632] opened 2023-05-17 08:44 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

DOGE#1690

### What happened?

bug appears sometimes in console and i dont understand why, i use self-host method for my pack and everything works fine in game 

### Steps to reproduce the issue

open console and see error in there from time to time

### Server version

git-Purpur-1632 (MC: 1.18.2)

### ItemsAdder Version

ItemsAdder version 3.4.1c

### ProtocolLib Version

ProtocolLib v5.0.0

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11495930/latest.log)

### Error (optional)

```shell
[10:40:11 ERROR]: [ItemsAdder] [m[0;31;1mUnexpected I/O error while handling webserver request: [m
[10:40:11 WARN]: java.net.SocketException: Connection reset
[10:40:11 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
[10:40:11 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
[10:40:11 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
[10:40:11 WARN]: 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
[10:40:11 WARN]: 	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
[10:40:11 WARN]: 	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
[10:40:11 WARN]: 	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
[10:40:11 WARN]: 	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
[10:40:11 WARN]: 	at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
[10:40:11 WARN]: 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
[10:40:11 WARN]: 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
[10:40:11 WARN]: 	at ItemsAdder_3.4.1c.jar//ia.m.jm.run(SourceFile:40)
```

### Other files, you can drag and drop them here to upload. (optional)

logs for past 2 days: 
[2023-05-16-1.log.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/11495939/2023-05-16-1.log.gz)
[2023-05-17-4.log.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/11495940/2023-05-17-4.log.gz)
[2023-05-17-3.log.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/11495941/2023-05-17-3.log.gz)
[2023-05-17-2.log.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/11495942/2023-05-17-2.log.gz)
[2023-05-16-5.log.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/11495943/2023-05-16-5.log.gz)
[2023-05-17-1.log.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/11495944/2023-05-17-1.log.gz)
[2023-05-16-4.log.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/11495945/2023-05-16-4.log.gz)
[2023-05-16-3.log.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/11495946/2023-05-16-3.log.gz)
[2023-05-16-2.log.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/11495947/2023-05-16-2.log.gz)

**Comment by WataLaker37821** [comment] 2023-05-17 08:46
also, I use hosting where i can just edit needed port in config of the plugin and it will work, i used default one in IA config for self-hosting method and pack works

**Comment by LoneDev6** [comment] 2023-05-17 09:56
Make sure to use a port which is not used by any other process, probably another process is trying to use that port causing this issue, I think.

Another cause could be someone trying to download the pack but closing their game during the download.

**Comment by WataLaker37821** [comment] 2023-05-17 16:49
I think its cos of users with weak connections, ill try to change the port and tell you if error will keep appearing

**Comment by LoneDev6** [comment] 2023-05-17 19:14
Thanks let me know, if the issue is about users losing connection I can probably fix it easily.
I wait for your test

**Comment by WataLaker37821** [comment] 2023-05-19 07:35
> Thanks let me know, if the issue is about users losing connection I can probably fix it easily. I wait for your test

i tested changing port, but still got that error, can you fix please when you will be able to?

**Closed** 2023-05-25 12:57 UTC
Labels: type: bug, verdict: workaround implemented
