### ISSUE TITLE
itemsadder version 4 custom equipment appears as leather, while version 3 is normal.

### ISSUE THREAD

**Issue by CeydOuO** [PluginBugs/Issues-ItemsAdder#3781] opened 2024-07-04 17:14 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

itemsadder version 4 custom equipment appears as leather, while version 3 is normal.

### Steps to reproduce the issue

1.20.6 purpur, then install the plugin, then use the material pack

### Server version

1.20.6

### ItemsAdder Version

ItemsAdder version 4.0.1-alpha-test-5

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-721

### LoneLibs Version

LoneLibs version 1.0.55

### Error (optional)

```shell
none
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://cdn.discordapp.com/attachments/533413171403292712/1258352587552329758/image.png?ex=6687bbab&is=66866a2b&hm=190b05232eb3ece32114f7aa903e525f64f22cbf2a2dcbe928aa8dc9fd533a80&
https://cdn.discordapp.com/attachments/533413171403292712/1258353152734920796/image.png?ex=6687bc32&is=66866ab2&hm=e2a8e8918f2ab582d71612135fb18ffbb986224c139788556074bc62c266a266&

**Comment by Andre601** [comment] 2024-07-04 21:02
Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.

**Comment by SignorPollito** [comment] 2024-07-10 16:13
Same bug, the armor texture are not showing anymore when worn, only the item texture is still correct.
They show up only with changed color (the one you set).

**Comment by kylemarham** [comment] 2024-07-25 21:19
Same bug. Items and blocks have correct textures, leather armour when worn does not.

**Comment by kylemarham** [comment] 2024-07-25 21:20
https://mclo.gs/E7SEajb

**Comment by kylemarham** [comment] 2024-07-31 10:41
Does this have an update? It's the only thing stopping IA working perfectly on 1.21

**Comment by Sweet-Duck** [comment] 2024-08-01 10:02
Same problem, please fix it.

**Comment by iFranticman** [comment] 2024-08-01 16:26
same issues

**Comment by VISION6969** [comment] 2024-08-01 21:53
Same issue

**Comment by kylemarham** [comment] 2024-08-04 20:41
Unable to create attribute: Cannot invoke "net.minecraft.class_2520.method_23258()" because "$$0" is null

Something to do with this

**Comment by kylemarham** [comment] 2024-08-05 11:17
@Andre601 is there any update on this? It's one of the final bugs preventing 1.21 from working flawlessly.

**Comment by Andre601** [comment] 2024-08-05 11:44
Be patient. Lone does this on his own, and it's tiring.

**Comment by Andre601** [comment] 2024-08-05 11:46
Also, to everyone else: Stop replying with stuff like "Same issue", "I have the same problem", etc.

It does not help speeding up the fixing of this issue. All it does is spam the inboxes of those watching this issue, which is annoying and tiresome.
If you have the same issue react [to the original post](https://github.com/PluginBugs/Issues-ItemsAdder/issues/3781#issue-2391238982) with a 👍 
Has the same influence as replying, but is less spammy.

Thanks.

**Comment by kylemarham** [comment] 2024-08-05 20:28
@Andre601 Respectfully, this issue was reported over a month ago and has yet to be acknowledged. We have all paid a lot of money for this plugin, and we have been patiently awaiting support for Minecraft 1.21. 

1.21 is almost working flawlessly, bar this one issue that should be a relatively painless fix. I note the spigot page that says LoneDev is taking the summer off, which is fine, but it does sound like this won't be resolved until he is back. 

He does not need to work alone on this plugin. That is through choice. At the end of the day, we are all paying customers.

**Comment by Andre601** [comment] 2024-08-05 20:54
> @Andre601 Respectfully, this issue was reported over a month ago and has yet to be acknowledged. We have all paid a lot of money for this plugin, and we have been patiently awaiting support for Minecraft 1.21.

Respectfully, [the amount of money you spent does not result in Support nor any guarantee of updates whatsoever.](https://andre601.ch/blog/2024/07-24-buying-plugin-wont-give-support/)
You agree to these terms when you purchase the resource (At least you do on Spigot, not sure how other platforms handle this).  
1.21 support does work here. It's just that this particular feature seems to be broken. This seems like splitting hair, but it's not. You claim 1.21 isn't working, yet it does.

> 1.21 is almost working flawlessly, bar this one issue that should be a relatively painless fix. I note the spigot page that says LoneDev is taking the summer off, which is fine, but it does sound like this won't be resolved until he is back.

Pretty sure this isn't a "painless fix". It's always the same with people like you, claiming that such stuff is easy to fix, yet not knowing how it is actually implemented, nor how difficult it truly is.
Granted, the plugin isn't open source, so we can't say for sure how it's implemented here, but I doubt it's really that easy here, so please stop assuming stuff is easy.

> He does not need to work alone on this plugin. That is through choice. At the end of the day, we are all paying customers.

And at the end of the day does this not matter. Sure, he can have another dev working on IA, but [as I mentioned myself](https://andre601.ch/blog/2024/07-24-buying-plugin-wont-give-support/#they-can-just-hire-more-devs) are there various reasons for why hiring a dev wouldn't be easy. Here are some:

- Devs aren't cheap. A good dev will for for at least a 4 figure sallary here and many others for way more. And I don't think LoneDev has the reserves to pay for that.
- Trusting another dev with this means trusting them with the code, which is risky as they could use it for their own stuff, publicly share it or even sell it.
- Dev first would need to learn and understand the coding practices LoneDev uses here, which can take weeks if not months until they can actually work on this.

Also, yes he does take a break, because having to deal with countless requests, not just on ItemsAdder alone, will cause a mental strain in the end.
However, on his Forums did he mention that he will continue to update the plugins, whenever he finds time, even while he won't accept new customers during this time.

So with all due respect I can (and should) give: Just stop complaining like this and accept this as the current state that it is...
If you want to help LoneDev, consider giving customer support yourself. Maybe that will make you apreciate the work he has to put into all this, not just coding.

**Comment by Skyslycer** [comment] 2024-08-05 21:08
It should be noted here that v4 is still in the _alpha test stage_, so I recommend everybody to not expect feature-completeness. It's obviously an unfortunate circumstance as other plugins with similar features have already updated to 1.21, added trim armor and have been stable doing so, but buying ItemsAdder is a choice you have made and as Andre stated, it's not a requirement for LoneDev to provide continuous support. Just stay hopeful that v4 will be better than any versions preceding it. 

As for the issue, from my share of investigation (so please take it with a grain of salt): When OptiFine and/or CIT Resewn updates to 1.21 I expect this to work as the required files are in the resource pack. So if anybody wants to try it with OptiFine alpha/beta, please do and report back. As for people not using either of those, usually core shaders were used to solve this. Surprisingly, for some reason, those that enable custom armor in vanilla, seem to be missing from the texture pack. I expect this to have happened in preparation for switching to trim-based custom armor.

For now, let LoneDev have his deserved vacation and sometimes remember that he is a human too.

**Comment by TH2403y** [comment] 2024-08-07 11:00
Same problem, please fix it.

**Comment by kylemarham** [comment] 2024-08-13 08:46
> It should be noted here that v4 is still in the _alpha test stage_, so I recommend everybody to not expect feature-completeness. It's obviously an unfortunate circumstance as other plugins with similar features have already updated to 1.21, added trim armor and have been stable doing so, but buying ItemsAdder is a choice you have made and as Andre stated, it's not a requirement for LoneDev to provide continuous support. Just stay hopeful that v4 will be better than any versions preceding it.
> 
> As for the issue, from my share of investigation (so please take it with a grain of salt): When OptiFine and/or CIT Resewn updates to 1.21 I expect this to work as the required files are in the resource pack. So if anybody wants to try it with OptiFine alpha/beta, please do and report back. As for people not using either of those, usually core shaders were used to solve this. Surprisingly, for some reason, those that enable custom armor in vanilla, seem to be missing from the texture pack. I expect this to have happened in preparation for switching to trim-based custom armor.
> 
> For now, let LoneDev have his deserved vacation and sometimes remember that he is a human too.

Oraxen was able to resolve all issues within days of 1.21 releasing.

**Comment by LoneDev6** [comment] 2024-08-28 16:01
Duplicate of
#3926
#3895
#3909

Custom armors work fine for me.

```
This server is running Paper version 1.21.1-40-master@2fdb2e9
ItemsAdder version 4.0.2-alpha-test-8
```

https://itemsadder.devs.beer/plugin-usage/adding-content/armors/custom-textured-armor

![image](https://github.com/user-attachments/assets/97d2a7d0-c5a8-42cf-8ad9-ed14cf5601a2)

**Closed by LoneDev6** 2024-08-28 16:01 UTC
Labels: type: bug
