### ISSUE TITLE
Luckperms / Itemsadder bug

### ISSUE THREAD

**Issue by nederliver** [PluginBugs/Issues-ItemsAdder#3281] opened 2024-01-03 09:37 UTC
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

nederliver

### What happened?

I have itemsadder installed and I also have luckperms. But then I run /lp editor command, luckperms send me "[]".
This also happens with other plugins like WorldGuard. 

### Steps to reproduce the issue

1. run /lp editor 
2. and u will see "[]" from luckperms in chat

Uploading Screen_Recording_2024-01-01_at_20.14.15_compressed.mp4…

### Server version

[10:29:34 INFO]: Checking version, please wait...
[10:29:34 INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version

### ItemsAdder Version

[10:30:14 INFO]: ItemsAdder version 3.6.3-beta-5
[10:30:14 INFO]: Customized Minecraft without client mods!
[10:30:14 INFO]: Website: devs.beer
[10:30:14 INFO]: Author: LoneDev

### ProtocolLib Version

[10:30:41 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[10:30:41 INFO]: Provides read/write access to the Minecraft protocol.
[10:30:41 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[10:31:11 INFO]: LoneLibs version 1.0.42
[10:31:11 INFO]: Collection of libs used by my plugins
[10:31:11 INFO]: Authors: LoneDev and others

### FULL server log

[10:31:46] [ServerMain/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[10:31:47] [Worker-Main-1/ERROR]: Couldn't load tag minecraft:placeable_blocks_1_20_4 as it is missing following references: minecraft:short_grass (from file/tool-trims-DP-v2-0-2c-1-20)
[10:31:47] [ServerMain/INFO]: Loaded 1176 recipes
[10:31:47] [ServerMain/INFO]: Loaded 1280 advancements
[10:31:47] [ServerMain/WARN]: Not all defined tags for registry ResourceKey[minecraft:root / minecraft:block] are present in data pack: minecraft:placeable_blocks_1_20_4
[10:31:47] [Server thread/INFO]: Starting minecraft server version 1.20.2
[10:31:47] [Server thread/INFO]: Loading properties
[10:31:47] [Server thread/INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
[10:31:48] [Server thread/INFO]: Server Ping Player Sample Count: 12
[10:31:48] [Server thread/INFO]: Using 4 threads for Netty based IO
[10:31:48] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[10:31:48] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[10:31:48] [Server thread/INFO]: Default game type: SURVIVAL
[10:31:48] [Server thread/INFO]: Generating keypair
[10:31:48] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25501
[10:31:48] [Server thread/INFO]: Using epoll channel type
[10:31:48] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[10:31:48] [Server thread/INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[10:31:48] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/PlaceholderAPI-Expansion-1.2.0.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [MiniPlaceholders]. Please download and install these plugins to run 'PlaceholderAPI-Expansion'.
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[10:31:49] [Server thread/WARN]: [org.bukkit.craftbukkit.v1_20_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[10:31:51] [Server thread/WARN]: Legacy plugin FriendSystemGUI v3.6 does not specify an api-version.
[10:31:51] [Server thread/WARN]: Legacy plugin finaltry v1.0 does not specify an api-version.
[10:31:51] [Server thread/WARN]: Legacy plugin PlayTime v3.6 does not specify an api-version.
[10:31:51] [Server thread/WARN]: Legacy plugin CustomHeads v3.0.10 does not specify an api-version.
[10:31:51] [Server thread/WARN]: Legacy plugin GoldDropRemover v1.0.0 does not specify an api-version.
[10:31:51] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loading 1 libraries... please wait
[10:31:51] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/container/libraries/org/apache/httpcomponents/httpmime/4.5.14/httpmime-4.5.14.jar
[10:31:51] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/container/libraries/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar
[10:31:51] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/container/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
[10:31:51] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/container/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[10:31:51] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/container/libraries/commons-codec/commons-codec/1.11/commons-codec-1.11.jar
[10:31:51] [Server thread/WARN]: Legacy plugin NoVoid v1.0 does not specify an api-version.
[10:31:51] [Server thread/INFO]: [ViaVersion] Loading server plugin ViaVersion v4.9.2
[10:31:51] [Server thread/INFO]: [ViaVersion] ViaVersion 4.9.2 is now loaded. Registering protocol transformers and injecting...
[10:31:51] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...
[10:31:51] [Server thread/INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.113
[10:31:51] [Via-Mappingloader-0/INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[10:31:51] [Server thread/INFO]: [Vault] Loading server plugin Vault v1.7.3-b131
[10:31:51] [Server thread/INFO]: [WorldEdit] Loading server plugin WorldEdit v7.2.17+6544-56d0383
[10:31:52] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@1c647ac3]
[10:31:52] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[10:31:52] [Server thread/INFO]: [WorldGuard] Loading server plugin WorldGuard v7.0.9+5934e49
[10:31:52] [Server thread/INFO]: [PlaceholderAPI] Loading server plugin PlaceholderAPI v2.11.5
[10:31:52] [Server thread/INFO]: [Essentials] Loading server plugin Essentials v2.20.1
[10:31:52] [Server thread/INFO]: [Multiverse-Core] Loading server plugin Multiverse-Core v4.3.12
[10:31:52] [Server thread/INFO]: [LoneLibs] Loading server plugin LoneLibs v1.0.42
[10:31:52] [Server thread/INFO]: [Citizens] Loading server plugin Citizens v2.0.33-SNAPSHOT (build 3277)
[10:31:52] [Server thread/INFO]: [FriendSystemGUI] Loading server plugin FriendSystemGUI v3.6
[10:31:52] [Server thread/INFO]: [EssentialsChat] Loading server plugin EssentialsChat v2.21.0-dev+24-0af4436
[10:31:52] [Server thread/INFO]: [SimpleScore] Loading server plugin SimpleScore v3.12.5
[10:31:53] [Server thread/INFO]: [SimplePortals] Loading server plugin SimplePortals v1.7.4
[10:31:53] [Server thread/INFO]: [BuycraftX] Loading server plugin BuycraftX v12.0.8
[10:31:53] [Server thread/INFO]: [TheNewEconomy] Loading server plugin TheNewEconomy v0.1.2.0
[10:31:53] [Server thread/INFO]: [TheNewEconomy] Hooked into Vault
[10:31:53] [Server thread/INFO]: [finaltry] Loading server plugin finaltry v1.0
[10:31:53] [Server thread/INFO]: [pvpstats] Loading server plugin pvpstats v1.11.52
[10:31:53] [Server thread/INFO]: [pvpstats] Loaded config file!
[10:31:53] [Server thread/WARN]: [pvpstats] Specific stats can be turned off as they are never used, they are intended for SQL and web frontend usage!
[10:31:53] [Server thread/WARN]: [pvpstats] Please either switch to SQLite or re-enable this by setting 'YML.collectPreciseOverride' to true
[10:31:53] [Server thread/WARN]: [pvpstats] Database: YML
[10:31:53] [Server thread/INFO]: [pvpstats] Database Initializing
[10:31:53] [Server thread/INFO]: [pvpstats] Database connection successful
[10:31:53] [Server thread/INFO]: [Chairs] Loading server plugin Chairs v7.0
[10:31:53] [Server thread/INFO]: [Multiverse-Portals] Loading server plugin Multiverse-Portals v4.2.3
[10:31:53] [Server thread/INFO]: [ChatFilter] Loading server plugin ChatFilter v2.0.14
[10:31:53] [Server thread/INFO]: [PlayTime] Loading server plugin PlayTime v3.6
[10:31:53] [Server thread/INFO]: [TAB] Loading server plugin TAB v4.1.2
[10:31:53] [Server thread/INFO]: [CustomHeads] Loading server plugin CustomHeads v3.0.10
[10:31:53] [Server thread/INFO]: [GoldDropRemover] Loading server plugin GoldDropRemover v1.0.0
[10:31:53] [Server thread/INFO]: [ItemsAdder] Loading server plugin ItemsAdder v3.6.3-beta-5
[10:31:53] [Server thread/INFO]: [DecentHolograms] Loading server plugin DecentHolograms v2.8.6
[10:31:53] [Server thread/INFO]: [Multiverse-Inventories] Loading server plugin Multiverse-Inventories v4.2.6
[10:31:53] [Server thread/INFO]: [NoVoid] Loading server plugin NoVoid v1.0
[10:31:53] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:31:53] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.4.113
[10:31:53] [Server thread/INFO]:         __    
[10:31:53] [Server thread/INFO]:   |    |__)   LuckPerms v5.4.113
[10:31:53] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[10:31:53] [Server thread/INFO]: 
[10:31:53] [Server thread/INFO]: [LuckPerms] Loading configuration...
[10:31:53] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[10:31:54] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[10:31:54] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[10:31:54] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 1278ms)
[10:31:54] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131
[10:31:54] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[10:31:54] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[10:31:54] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b131
[10:31:54] [Server thread/INFO]: [LuckPerms] Registered Vault permission & chat hook.
[10:31:54] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.2.17+6544-56d0383
[10:31:54] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[10:31:54] [Server thread/INFO]: WEPIF: Vault detected! Using Vault for permissions
[10:31:54] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R2.PaperweightAdapter as the Bukkit adapter
[10:31:55] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679
[10:31:55] [Server thread/INFO]: [LoneLibs] Enabling LoneLibs v1.0.42
[10:31:55] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[10:31:55] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[10:31:55] [Server thread/WARN]: Whilst this makes it possible to use Velocity, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[10:31:55] [Server thread/WARN]: Please see https://docs.papermc.io/velocity/security for further information.
[10:31:55] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[10:31:55] [Server thread/INFO]: Preparing level "world"
[10:31:55] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[10:31:56] [Server thread/INFO]: Time elapsed: 235 ms
[10:31:56] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[10:31:56] [Server thread/INFO]: Time elapsed: 63 ms
[10:31:56] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[10:31:56] [Server thread/INFO]: Time elapsed: 22 ms
[10:31:56] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.9.2
[10:31:56] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.20.2 (764)
[10:31:56] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v7.0.9+5934e49
[10:31:56] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[10:31:56] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[10:31:56] [Server thread/INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
[10:31:56] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[10:31:56] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[10:31:56] [Server thread/INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[10:31:56] [Server thread/INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[10:31:56] [Server thread/INFO]: [WorldGuard] (world_nether) Lava fire is PERMITTED.
[10:31:56] [Server thread/INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[10:31:56] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[10:31:56] [Server thread/INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[10:31:56] [Server thread/INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[10:31:56] [Server thread/INFO]: [WorldGuard] (world_the_end) Lava fire is PERMITTED.
[10:31:56] [Server thread/INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[10:31:56] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[10:31:56] [Server thread/INFO]: [WorldGuard] Loading region data...
[10:31:56] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.5
[10:31:56] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[10:31:56] [Server thread/INFO]: [Essentials] Enabling Essentials v2.20.1
[10:31:56] [Server thread/ERROR]: [Essentials] You are running an unsupported server version!
[10:31:56] [Server thread/WARN]: [Essentials] Version mismatch! Please update EssentialsChat to the same version.
[10:31:56] [Server thread/INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[10:31:56] [Server thread/INFO]: [Essentials] No kits found to migrate.
[10:31:57] [Server thread/INFO]: [Essentials] Loaded 39094 items from items.json.
[10:31:57] [Server thread/INFO]: [Essentials] Using locale en_US
[10:31:57] [Server thread/INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[10:31:57] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[10:31:57] [Server thread/INFO]: [Vault] [Economy] Essentials Economy hooked.
[10:31:57] [Server thread/INFO]: [Essentials] Using Vault based permissions (LuckPerms)
[10:31:57] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.12
[10:31:57] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.3.12" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[10:31:57] [Server thread/INFO]: [Multiverse-Core] §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[10:31:57] [Server thread/INFO]: Preparing start region for dimension minecraft:lobby
[10:31:57] [Server thread/INFO]: Time elapsed: 393 ms
[10:31:57] [Server thread/INFO]: [WorldGuard] (lobby) TNT ignition is PERMITTED.
[10:31:57] [Server thread/INFO]: [WorldGuard] (lobby) Lighters are PERMITTED.
[10:31:57] [Server thread/INFO]: [WorldGuard] (lobby) Lava fire is PERMITTED.
[10:31:57] [Server thread/INFO]: [WorldGuard] (lobby) Fire spread is UNRESTRICTED.
[10:31:57] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'lobby'
[10:31:57] [Server thread/INFO]: [Multiverse-Core] 4 - World(s) loaded.
[10:31:57] [Server thread/WARN]: [Multiverse-Core] Buscript failed to load! The script command will be disabled! If you would like not to see this message, use `/mv conf enablebuscript false` to disable Buscript from loading.
[10:31:57] [Server thread/INFO]: [Multiverse-Core] Version 4.3.12 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--
[10:31:57] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.33-SNAPSHOT (build 3277)
[10:31:58] [Server thread/INFO]: [Citizens] Loading external libraries
[10:31:58] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: citizensplaceholder [1.0.0]
[10:31:58] [Server thread/INFO]: [Citizens] Loaded economy handling via Vault.
[10:31:58] [Server thread/INFO]: [FriendSystemGUI] Enabling FriendSystemGUI v3.6*
[10:31:58] [Server thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[10:31:59] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: friendsystem [3.6]
[10:31:59] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat v2.21.0-dev+24-0af4436
[10:31:59] [Server thread/WARN]: [EssentialsChat] Version mismatch! Please update all Essentials jars to the same version.
[10:31:59] [Server thread/INFO]: [EssentialsChat] Starting Metrics. Opt-out using the global bStats config.
[10:31:59] [Server thread/INFO]: [SimpleScore] Enabling SimpleScore v3.12.5
[10:31:59] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: SimpleScore [3.12.5]
[10:31:59] [Server thread/INFO]: [SimplePortals] Enabling SimplePortals v1.7.4
[10:31:59] [Server thread/INFO]: [SimplePortals] Everything inside the configuration seems to be up to date. (Took 1ms)
[10:31:59] [Server thread/INFO]: [SimplePortals] Packets have been setup for v1_20_R2!
[10:31:59] [Server thread/INFO]: [SimplePortals] Everything looks like it is up to date!
[10:31:59] [Server thread/INFO]: [BuycraftX] Enabling BuycraftX v12.0.8
[10:31:59] [Server thread/INFO]: [BuycraftX] Validating your server key...
[10:31:59] [Server thread/WARN]: [BuycraftX] Your server and webstore online mode settings are mismatched. Unless you are using a proxy and server combination (such as BungeeCord/Spigot or LilyPad/Connect) that corrects UUIDs, then you may experience issues with packages not applying.
[10:31:59] [Server thread/WARN]: [BuycraftX] If you have verified that your set up is correct, you can suppress this message by setting is-bungeecord=true in your BuycraftX config.properties.
[10:32:00] [Server thread/INFO]: [BuycraftX] Fetching all server packages...
[10:32:00] [Server thread/INFO]: [TheNewEconomy] Enabling TheNewEconomy v0.1.2.0
[10:32:00] [Server thread/INFO]: [TheNewEconomy] Loading configurations!
[10:32:00] [Server thread/INFO]: [TheNewEconomy] Attempting to load currency: Gold.yml
[10:32:01] [Server thread/INFO]: [TheNewEconomy] Build Stability: Not Stable
[10:32:01] [Server thread/INFO]: [TheNewEconomy] Update Available! Latest: 0.1.2.3
[10:32:01] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: TNE [0.1.2.0]
[10:32:01] [Server thread/INFO]: [TheNewEconomy] The New Economy has been enabled!
[10:32:01] [Server thread/INFO]: [finaltry] Enabling finaltry v1.0*
[10:32:01] [Server thread/INFO]: [finaltry] Plugin enabled!
[10:32:01] [Server thread/INFO]: [pvpstats] Enabling pvpstats v1.11.52
[10:32:01] [Thread-13/INFO]: [pvpstats] Checking for updates...
[10:32:01] [Server thread/INFO]: [pvpstats] sending full Metrics! You can deactivate this in the config.yml
[10:32:01] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: sps [0.0.1]
[10:32:01] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: slipcorpvpstats [0.0.4]
[10:32:01] [Server thread/INFO]: [pvpstats] debugging: off
[10:32:01] [Server thread/INFO]: [pvpstats] Player list had no duplicates!
[10:32:01] [Server thread/INFO]: [pvpstats] enabled. (version 1.11.52)
[10:32:01] [Server thread/INFO]: [Chairs] Enabling Chairs v7.0
[10:32:01] [Server thread/INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v4.2.3
[10:32:01] [Server thread/INFO]: [Multiverse-Portals] 0 - Portals(s) loaded
[10:32:01] [Server thread/INFO]: [Multiverse-Portals] Found WorldEdit. Using it for selections.
[10:32:01] [Server thread/INFO]: [Multiverse-Portals 4.2.3]  Enabled - By Rigby and fernferret
[10:32:01] [Server thread/INFO]: [ChatFilter] Enabling ChatFilter v2.0.14
[10:32:01] [Server thread/INFO]: [ChatFilter] Loaded using locale: en
[10:32:01] [Server thread/INFO]: [ChatFilter] 66 Enabled word filters.
[10:32:01] [Server thread/INFO]: [ChatFilter] 2 Enabled advertising filters.
[10:32:01] [Server thread/INFO]: [ChatFilter] 348 whitelisted items.
[10:32:01] [Server thread/INFO]: [PlayTime] Enabling PlayTime v3.6*
[10:32:01] [Server thread/INFO]: [PlayTime] PlaceholderAPI was found! Registering Placeholders.
[10:32:01] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: playtime [3.6]
[10:32:01] [Server thread/INFO]: [TAB] Enabling TAB v4.1.2
[10:32:01] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: tab [4.1.2]
[10:32:01] [Server thread/INFO]: [TAB] Enabled in 94ms
[10:32:01] [Server thread/INFO]: [CustomHeads] Enabling CustomHeads v3.0.10*
[10:32:01] [Server thread/INFO]: [CustomHeads] Using LATEST as Version Handler
[10:32:01] [Server thread/INFO]: [CustomHeads] Warning : Hrm. Seems like CustomHeads wasn't tested on this Minecraft Version (v1_20_R2) yet...
[10:32:01] [Server thread/INFO]: [CustomHeads] Warning : Feel free to join my Discord to know when it gets updated
[10:32:02] [Server thread/INFO]: [GoldDropRemover] Enabling GoldDropRemover v1.0.0*
[10:32:02] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.6.3-beta-5
[10:32:02] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_20_R2! Trying to find NMS support
[10:32:02] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_20_R2' loaded!
[10:32:02] [Server thread/INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.6.3-beta-5
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.42
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-318 (MC: 1.20.2)
                                               
[10:32:02] [Server thread/WARN]: [ProtocolLib] [PacketFilterManager] Plugin ItemsAdder tried to register listener for unknown packet ADD_RESOURCE_PACK[PLAY, SERVER, 68, classNames: [net.minecraft.network.protocol.game.PacketPlayOutResourcePackPushPacket, net.minecraft.network.protocol.game.ClientboundResourcePackPushPacketPacket] (unregistered)] [direction: from SERVER]
[10:32:02] [Server thread/INFO]: [ItemsAdder] Registered Citizens NPC Trait: customentity
[10:32:02] [Server thread/INFO]: [DecentHolograms] Enabling DecentHolograms v2.8.6
[10:32:02] [Server thread/INFO]: [Multiverse-Inventories] Enabling Multiverse-Inventories v4.2.6
[10:32:02] [Server thread/INFO]: [Multiverse-Inventories 4.2.6] enabled.
[10:32:02] [Server thread/INFO]: [NoVoid] Enabling NoVoid v1.0*
[10:32:03] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[10:32:03] [Server thread/INFO]: Running delayed init tasks
[10:32:03] [Craft Scheduler Thread - 4 - Essentials/INFO]: [Essentials] Fetching version information...
[10:32:03] [Craft Scheduler Thread - 1 - ViaVersion/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[10:32:03] [Craft Scheduler Thread - 16 - DecentHolograms/INFO]: [DecentHolograms] Loading holograms... 
[10:32:03] [Server thread/INFO]: [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[10:32:03] [Server thread/INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[10:32:03] [Craft Scheduler Thread - 16 - DecentHolograms/INFO]: [DecentHolograms] Loaded 6 holograms!
[10:32:03] [Craft Scheduler Thread - 12 - PlayTime/INFO]: [PlayTime] Latest version is installed! - v3.6
[10:32:03] [Server thread/INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[10:32:03] [Craft Scheduler Thread - 15 - ItemsAdder/INFO]: [ItemsAdder] [License] Spigot product licensed to: nederliver (1892191)
[10:32:03] [Server thread/INFO]: [Citizens] Loaded 0 NPCs.
[10:32:03] [Server thread/INFO]: [Multiverse-Inventories] First run!
[10:32:03] [Server thread/INFO]: [PlaceholderAPI] Successfully registered external expansion: player [2.0.7]
[10:32:03] [Server thread/INFO]: [PlaceholderAPI] Successfully registered external expansion: servertime [3.2]
[10:32:03] [Server thread/INFO]: [PlaceholderAPI] Successfully registered external expansion: luckperms [5.4-R2]
[10:32:03] [Server thread/INFO]: [PlaceholderAPI] Successfully registered external expansion: time [1.0.0]
[10:32:03] [Server thread/INFO]: 4 placeholder hook(s) registered!
[10:32:03] [Server thread/INFO]: Done (15.858s)! For help, type "help"
[10:32:03] [Server thread/INFO]: Timings Reset
[10:32:03] [Craft Scheduler Thread - 11 - Vault/INFO]: [Vault] Checking for Updates ... 
[10:32:03] [Craft Scheduler Thread - 11 - Vault/INFO]: [Vault] No new version available
[10:32:03] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Loaded 7 items
[10:32:03] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Used 0/188 REAL block IDs
[10:32:03] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Used 0/750 REAL_NOTE block IDs
[10:32:03] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
[10:32:03] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs
[10:32:03] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[10:32:03] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Used 27/6608 font_images
[10:32:03] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] [Init] Loaded 1 categories
[10:32:03] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] [Init] Loaded successfully.
[10:32:03] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: img [1.0.1]
[10:32:03] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: iaplayerstat [1.0.1]
[10:32:03] [Server thread/INFO]: [ItemsAdder] Reloading ItemsAdder Custom Entities Citizens NPCs
[10:32:04] [Craft Scheduler Thread - 14 - BuycraftX/INFO]: [BuycraftX] Fetching all due players...
[10:32:04] [Craft Scheduler Thread - 14 - BuycraftX/INFO]: [BuycraftX] Fetched due players (0 found).
[10:32:04] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Resourcepack URL is valid (lobfile). Url: https://lobfile.com/file/FSer.zip

### Other files, you can drag and drop them here to upload. (optional)

[ItemsAdder.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/13817451/ItemsAdder.zip)
My itemsadder folder

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/135690868/1ddbc928-6abd-4346-9009-6893e8fd387d

**Comment by nederliver** [comment] 2024-01-03 09:41
hi

**Comment by Fiber-Official** [comment] 2024-01-03 11:28
> hi

Hy, can upload ItemsAdder latest plugin because I think that issue is solved in ItemsAdder latest version

**Comment by nederliver** [comment] 2024-01-03 13:26
ok I will change jar to latest version

**Comment by nederliver** [comment] 2024-01-03 13:27
no I already have last version ItemsAdder_3.6.3-beta-5.jar

**Comment by LoneDev6** [comment] 2024-01-03 17:26
Strange.
I will do some tests but I cannot reproduce this issue.
Try to update LoneLibs.

**Comment by Fiber-Official** [comment] 2024-01-03 19:43
> no I already have last version ItemsAdder_3.6.3-beta-5.jar

Upload your jar file do I check it some time plugin names can be make issue like on 1.2 version jar it's written 1.3 so upload your jar file so I check.

**Comment by EpicPlayerA10** [comment] 2024-01-05 23:10
Duplicate of #3265

**Closed** 2024-01-07 20:07 UTC
Labels: type: bug, compat: plugin
