### ISSUE TITLE
Block Dupe [BUG] 

### ISSUE THREAD

**Issue by ShockCharge** [PluginBugs/Issues-ItemsAdder#1128] opened 2021-08-23 12:01 UTC
When you break ore blocks it gets dupe it acts like an Ore when its not supposed to.

e.g. if you break a Diamond ore of course its gonna drop a lot of Diamond
and when you break a Diamond Block it will only drop 1 Diamond Block nothing else.

That does not seem to be the case for this blocks:
![image](https://user-images.githubusercontent.com/48907444/130443386-6f7f1054-cc03-4ad1-977d-87b6ad83fc86.png)
Ruby, Crystal, Spinel, Turquoise, Aqua Aura, Amethyst Prism, Amethyst Block

they're supposed to be only dropping 1 item which is the block itself when you mine it.

There are no custom enchantments only vanilla but buffed.
![image](https://user-images.githubusercontent.com/48907444/130443527-1735a7ac-d4b4-4da8-b68f-b32a0f2dae8c.png)

![image](https://user-images.githubusercontent.com/48907444/130443606-353066c7-f5e1-4c5d-9f79-a3b3665a01b9.png)
![image](https://user-images.githubusercontent.com/48907444/130443614-7e9fdb85-3cc4-49fe-9fb1-746cfae88325.png)
![image](https://user-images.githubusercontent.com/48907444/130443627-1fd50d37-7bf7-474c-b8af-ea9f0e09d88f.png)
![image](https://user-images.githubusercontent.com/48907444/130443650-acdb85c4-81b9-4787-852d-9033159b81a8.png)
![image](https://user-images.githubusercontent.com/48907444/130443691-8b32fd02-d644-412f-8f22-381f42dd035e.png)
![image](https://user-images.githubusercontent.com/48907444/130443712-4cc77857-89e5-43f2-8d16-550a514f4e24.png)

**Comment by LoneDev6** [comment] 2021-08-23 13:46
Make a video please, thanks.

**Comment by FokaStudio** [comment] 2021-08-29 07:31
Is that Fortune 60 related to the bug?

**Comment by LoneDev6** [comment] 2021-09-02 16:04
Yep I can confirm it's due to efficiency 70.
It starts to dupe from level 60.

I'm working on a fix for this (keep in mind that these are unsafe enchants which the game wasn't made for and may lead to other issues with ItemsAdder and surely other plugins, but I'll try my best to avoid these bugs).

Have a nice day

**Closed** 2021-09-08 15:40 UTC
Labels: bug
