### ISSUE TITLE
Custom Crop Error

### ISSUE THREAD

**Issue by cats-love** [PluginBugs/Issues-ItemsAdder#2408] opened 2023-03-12 01:56 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

cats#0935

### What happened?

Currently, it operates a server with 200-300 people.
The current situation of the problem is as follows:

1) Custom crops supported by itemsadder are not functioning properly
- For example, harvesting a custom raspberry crop yields raspberries or regular sweet fruits. The same goes for other beet, wheat, and carrot-based custom crops. There is a problem with the custom crop.

2) Using custom crops, the soil returns to the note block with similar problems as above. Crops also use tripwire, which changes everything.

Both of them need to be done with /iareload to get back to the original, and that's only temporary.

### Steps to reproduce the issue

It starts to happen when 100 to 150 people start to go over. It happens quite frequently in 250 people. It may be related to tps drop. (13~16)
When you interact after a certain period of time, the custom crops and soil planted in the existing world cause problems. There is a problem with both custom crops made with itemsadders and custom crops.

### Server version

1.19.2

### ItemsAdder Version

[3.4.0c-beta]

### ProtocolLib Version

#606 1.19.2 build

### LoneLibs Version

1.0.23

### Error (optional)

```shell
A LOG)
[00:14:41] [Server thread/INFO]: cats_love issued server command: /iareload
[00:14:41] [Server thread/INFO]: [ItemsAdder] [m[0;33;1mReloading...[m
[00:14:41] [pool-77-thread-58/INFO]: [ItemsAdder] [m[0;36;1m[Host] Stopped self-host webserver on port: 8163[m
[00:14:41] [Server thread/INFO]: [ItemsAdder] [m[0;36;1m[Host] Starting self-host webserver on port: 8163[m
[00:14:41] [Server thread/INFO]: [ItemsAdder] [m[0;36;1m[Pack] Extracting internal contents from .jar[m
[00:14:41] [Server thread/INFO]: [ItemsAdder] [m[0;32;1m[Pack] DONE extracting internal contents from .jar[m
[00:14:42] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.0c-beta
java.lang.NullPointerException: null
[00:14:42] [Craft Scheduler Thread - 266506 - VentureChat/INFO]: [지역채팅] [너나들이] [하모] 니카 ★ : 직접 ???
[00:14:42] [Craft Scheduler Thread - 266818 - VentureChat/INFO]: [지역채팅] [GENESIS] [유저] 리안이 ★ : 날개 얼마에요?
[00:14:42] [Craft Scheduler Thread - 266601 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mLoaded [0;36;1m1827[0;33;1m items[m
[00:14:42] [Craft Scheduler Thread - 266601 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m188[0;33;1m REAL block IDs[m
[00:14:42] [Craft Scheduler Thread - 266601 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m298[0;33;1m/[0;36;1m750[0;33;1m REAL_NOTE block IDs[m
[00:14:42] [Craft Scheduler Thread - 266601 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m18[0;33;1m/[0;36;1m63[0;33;1m REAL_TRANSPARENT block IDs[m
[00:14:42] [Craft Scheduler Thread - 266601 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m95[0;33;1m/[0;36;1m127[0;33;1m REAL_WIRE block IDs[m
[00:14:42] [Craft Scheduler Thread - 266601 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m14[0;33;1m FIRE block IDs[m
[00:14:42] [Craft Scheduler Thread - 266601 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m89[0;33;1m/[0;36;1m6608[0;33;1m font_images[m
[00:14:42] [Craft Scheduler Thread - 266601 - ItemsAdder/INFO]: [ItemsAdder] [m[0;32;1m[Init] Loaded [0;36;1m39[0;33;1m categories[m
[00:14:42] [Craft Scheduler Thread - 266601 - ItemsAdder/INFO]: [ItemsAdder] [m[0;32;1m[Init] Loaded successfully in [0;36;1m973ms[m
[00:14:42] [Craft Scheduler Thread - 266601 - ItemsAdder/INFO]: [ItemsAdder] [m[0;36;1m[Pack] Checking resourcepack url... [m
[00:14:42] [Craft Scheduler Thread - 266739 - ItemsAdder/INFO]: [ItemsAdder] [m[0;32;1m[Pack] Resourcepack URL (self-host): http://119.201.117.86:8163/generated.zip[m
[00:14:42] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[00:14:42] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[00:14:42] [Server thread/INFO]: [ItemsAdder] [mReloading ItemsAdder Custom Entities Citizens NPCs[m
[00:14:43] [Server thread/INFO]: [Mythic] Reloading plugin...
[00:14:43] [Server thread/INFO]: [MythicMobs] Mythic beginning reload procedure...[0m
[00:14:43] [Server thread/INFO]: [io.lumine.mythic.utils.reflections.Reflections] Reflections took 9 ms to scan 1 urls, producing 4 keys and 14 values 
[00:14:43] [Server thread/INFO]: [MythicMobs] Loading Packs...[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] Loading Items...[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] Loading Item Groups...[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] Loading Skills...[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] Loading Drop Tables...[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] Loading Random Spawns...[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] Loading Spawn Blocks...[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] [32m?[37m Loaded 28 mobs.[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] [32m?[37m Loaded 1 vanilla mob overrides.[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] [32m?[37m Loaded 0 mob stacks.[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] [32m?[37m Loaded 172 skills.[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] [32m?[37m Loaded 0 random spawns.[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] [32m?[37m Loaded 8 mythic items.[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] [32m?[37m Loaded 2 drop tables.[0m
[00:14:43] [Server thread/INFO]: [MythicMobs] [32m?[37m Loaded 0 mob spawners.[0m
[00:14:43] [Server thread/INFO]: [Mythic] Mythic has finished reloading!
[00:14:43] [Server thread/INFO]: [MythicMobs] Mythic has finished reloading![0m



B LOG)
[00:18:41] [pool-77-thread-58/ERROR]: Thread pool-77-thread-58 failed main thread check: block remove
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.world.level.block.state.BlockBehaviour.onRemove(BlockBehaviour.java:155) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onRemove(BlockBehaviour.java:1010) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:601) ~[?:?]
	at ia.nms.aI.impl.v1_19_R1_2.a(SourceFile:61) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.nms.aI.impl.v1_19_R1_2.setBlockData(SourceFile:47) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.cz.f(SourceFile:240) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.cz.a(SourceFile:507) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.cG.b(SourceFile:42) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.cH.a(SourceFile:118) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.cX.a(SourceFile:78) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:18:41] [Server thread/INFO]: ju_kan issued server command: /cmi tpaccept BNC_diamond tpa


C LOG) 
[00:34:46] [Craft Scheduler Thread - 271784 - ItemsAdder/WARN]: [ItemsAdder] Plugin ItemsAdder v3.4.0c-beta generated an exception while executing task 191582503
java.lang.StringIndexOutOfBoundsException: begin 0, end 10, length 5
	at java.lang.String.checkBoundsBeginEnd(String.java:4604) ~[?:?]
	at java.lang.String.substring(String.java:2707) ~[?:?]
	at ia.m.gU.b(SourceFile:97) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.gU.C(SourceFile:34) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?] 

E LOG) 
[03:49:11] [Craft Scheduler Thread - 337095 - ItemsAdder/WARN]: [ItemsAdder] Plugin ItemsAdder v3.4.0c-beta generated an exception while executing task 229533866
java.lang.StringIndexOutOfBoundsException: begin 0, end 10, length 5
	at java.lang.String.checkBoundsBeginEnd(String.java:4604) ~[?:?]
	at java.lang.String.substring(String.java:2707) ~[?:?]
	at ia.m.gU.b(SourceFile:97) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.gU.C(SourceFile:34) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

D LOG) [03:29:51] [pool-77-thread-121/ERROR]: Thread pool-77-thread-121 failed main thread check: block remove
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.world.level.block.state.BlockBehaviour.onRemove(BlockBehaviour.java:155) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onRemove(BlockBehaviour.java:1010) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:601) ~[?:?]
	at ia.nms.aI.impl.v1_19_R1_2.a(SourceFile:61) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.nms.aI.impl.v1_19_R1_2.setBlockData(SourceFile:47) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.cz.f(SourceFile:240) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.cz.a(SourceFile:507) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.cG.b(SourceFile:42) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.cH.a(SourceFile:118) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at ia.m.cX.a(SourceFile:78) ~[ItemsAdder_3.4.0c-beta.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Problematic items yml configuration file (optional)

items:
  raspberryseeds:
    display_name: "&f[ &a작물 &f] &a산딸기씨"
    permission: raspberryseeds
    resource:
      material: WHEAT_SEEDS
      generate: true
      textures:
      - item/seeds/raspberryseeds.png
    specific_properties:
      seed:
        crop_block: SWEET_BERRY_BUSH
        results:
          result_1:
            item: munchies:blackraspberry
            min_amount: 1
            max_amount: 2
            chance: 50
          result_2:
            item: munchies:redraspberry
            min_amount: 1
            max_amount: 2
            chance: 50
          result_3:
            item: munchies:crops
            min_amount: 1
            max_amount: 1
            chance: 50
            
            **These crops are not harvested as custom crops, but as SWEET_BERRY**

### Other files, you can drag and drop them here to upload. (optional)

![2023-03-09_20 36 41_2](https://user-images.githubusercontent.com/87476958/224519715-8b3d9ae4-ec63-4270-a988-07ff5e60cea9.png)
![image](https://user-images.githubusercontent.com/87476958/224519717-2e59012e-eabf-4897-860a-f509bb569d62.png)
![2023-03-09_20 32 51](https://user-images.githubusercontent.com/87476958/224519719-78052bbf-7cb7-4a68-8bb7-522f46904808.png)

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/c4YSVQ8rjYs

**Comment by LoneDev6** [comment] 2023-03-13 10:27
I'll try to reproduce it as soon as possible.

**Comment by LoneDev6** [comment] 2023-03-14 16:05
```
[00:18:41] [pool-77-thread-58/ERROR]: Thread pool-77-thread-58 failed main thread check: block remove
java.lang.Throwable: null
```

Fixed

```
[00:34:46] [Craft Scheduler Thread - 271784 - ItemsAdder/WARN]: [ItemsAdder] Plugin ItemsAdder v3.4.0c-beta generated an exception while executing task 191582503
java.lang.StringIndexOutOfBoundsException: begin 0, end 10, length 5
```

Has to do with the `/e` command book.
It probably is caused  by some specific emoji you have. I cannot reproduce the issue, but I should have fixed that in the upcoming update.
It's hard for me to identify that precisely because I'd need ALL your emojis (configs + images), but I won't ask you to share them publicly.
It should be fixed as I said, let me know how the next update goes.

> https://youtu.be/c4YSVQ8rjYs

I cannot reproduce the issue.
I think it's caused by CustomCrops plugin (which I'm not the developer of).
Please contact them and share this issue page with them, anyway I doubt it has to do with ItemsAdder itself.

> In the past, customized crops of bushes did not return to seeds even if the ground dried up, but when it dried up, they returned like this.

Will be fixed in the upcoming release.

**Comment by LoneDev6** [comment] 2023-03-14 16:05
Please next time create a single report for each bug, do not squash everything in a single page.
It makes things hard to manage.

**Closed by LoneDev6** 2023-03-14 16:05 UTC
Labels: Bug, Need testing
