### ISSUE TITLE
Could not pass event InventoryClickEvent to ItemsAdder v4.0.6

### ISSUE THREAD

**Issue by pjindras** [PluginBugs/Issues-ItemsAdder#4278] opened 2024-12-26 19:46 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [X] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

There is an error when player is using recipe.

### Steps to reproduce the issue

I dont know, it is related to recipes

### Server version

Paper build 132 minecraft 1.21.1

### ItemsAdder Version

ItemsAdder version 4.0.6

### ProtocolLib Version

ProtocolLib version 5.3.0

### LoneLibs Version

LoneLibs version 1.0.63

### Full Server Log

https://mclo.gs/bQhVedk

### Error (optional)

```shell
[13:28:45] [Server thread/ERROR]: Could not pass event InventoryClickEvent to ItemsAdder v4.0.6
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.crafting.RecipeHolder.id()" because "recipeholder" is null
	at net.minecraft.stats.ServerRecipeBook.addRecipes(ServerRecipeBook.java:39) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.level.ServerPlayer.awardRecipes(ServerPlayer.java:2003) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at ItemsAdder_4.0.6.jar/itemsadder.m.zp.b(SourceFile:200) ~[ItemsAdder_4.0.6.jar:?]
	at ItemsAdder_4.0.6.jar/itemsadder.m.zh.c(SourceFile:87) ~[ItemsAdder_4.0.6.jar:?]
	at ItemsAdder_4.0.6.jar/itemsadder.m.zh.a(SourceFile:48) ~[ItemsAdder_4.0.6.jar:?]
	at ItemsAdder_4.0.6.jar/itemsadder.m.mm.f(SourceFile:88) ~[ItemsAdder_4.0.6.jar:?]
	at ItemsAdder_4.0.6.jar/itemsadder.m.hn.a(SourceFile:174) ~[ItemsAdder_4.0.6.jar:?]
	at ItemsAdder_4.0.6.jar/itemsadder.m.hn.d(SourceFile:607) ~[ItemsAdder_4.0.6.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:71) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3366) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:189) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1665) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1325) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by Andre601** [comment] 2024-12-26 19:48
Duplicate of #4101

**Closed** 2024-12-26 19:49 UTC
Labels: type: duplicate
