### ISSUE TITLE
Plugin dont load under newest Paper / Purpur

### ISSUE THREAD

**Issue by editon96** [PluginBugs/Issues-ItemsAdder#2368] opened 2023-02-26 15:00 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

editon#9622

### What happened?

I start my Server and Iteam Adder craches.

### Steps to reproduce the issue

I dont now how to repuduce.
I only Update and Start the Server.

### Server version

Purpur version git-Purpur-1921 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 387a581 on HEAD)

under Velocity 3.1.2 Snapchot Build 207

### ItemsAdder Version

IteamsAdder 3.4.0-beta

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b614

### LoneLibs Version

LoneLib 1.0.23

### LightAPI Version (optional)

LightAPI vbukkit-5.3.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises v10.0.32

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10833968/latest.log)

### Error (optional)

```shell
https://pastebin.com/SXD7rmkS
```

**Comment by Akiranya** [comment] 2023-02-26 16:11
Your IA is not the latest, can you try updating it and see if the issue still persists?

**Comment by editon96** [comment] 2023-02-26 17:41
It is the Latest I can get from Polymart download it there. Today

**Comment by editon96** [comment] 2023-02-26 18:17
![Latest](https://user-images.githubusercontent.com/42817235/221428827-c169705b-6969-453e-bcde-082a197705ce.png)

Look for youself

**Comment by Akiranya** [comment] 2023-02-26 19:40
Nvm I just read it wrong :P then wait for LoneDev

FYI: I'm also running latest Purpur server but with IA 3.3.1 release (not beta) and everything works just fine

I have no LightAPI installed tho

**Comment by editon96** [comment] 2023-02-26 20:14
I have before the stabel build and it workes before I update to the new Purpur what Implement a new Plugin Handeling from Paper.

I think it is because of that.

**Comment by editon96** [comment] 2023-02-26 20:14
But I cant downgarde my world.

**Comment by editon96** [comment] 2023-02-26 20:20
"🧷 **Introducing Paper Plugins**
*We are introducing an experimental type of plugin that Paper is able to load in order to expand the future of the Paper API.*

**As a Server Admin, what does this mean?**
This should not change much for you, as the changes that have occurred are mostly internal and are for development purposes only.

It should be noted that cyclic dependencies between plugins are no longer supported. 
For more information, see https://docs.papermc.io/paper/reference/paper-plugins#cyclic-dependency-detection.

When doing ``/plugins``, you are now able to see all the Paper/Bukkit plugins that are loaded. 
This change required a large refactor to plugin loading, please ensure that all your plugins load correctly. If you find an issue introduced in this update, __please make a bug report__ with a plugin debug dump by using ``/paper dumpplugins``.

**As a Developer, what does this mean?**
Paper plugins are still under heavy development, therefore, may be subject to change in the future.
Current simple documentation can be seen at https://docs.papermc.io/paper/dev/getting-started/paper-plugins."



I mean that.

**Comment by Akiranya** [comment] 2023-02-27 06:25
From the `latest.log` you provided it's hard to say this issue is related to paper's new plugin system.

And it's hard whether the issue is on IA's side or LighAPI's side.

But from this:

```
[15:34:30] [Server thread/INFO]: [ItemsAdder] [m[0;36;1m
[0;36;1m  ___  ___        __        __   __   ___  __  [0;32;22m    ItemsAdder[0;37;22m 3.4.0-beta
[0;36;1m|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__) [0;32;22m    LoneLibs[0;37;22m 1.0.23
[0;36;1m|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \ [0;30;1m    Purpur git-Purpur-1921 (MC: 1.19.3)
[0;36;1m                                               [m
[15:34:30] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.4.0-beta (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "ru.beykerykt.minecraft.lightapi.bukkit.api.extension.IBukkitExtension.getHandler()" because "this.a" is null
```

This is somehow related to LightAPI. Try remove it

**Comment by editon96** [comment] 2023-02-27 06:44
I do when I am Back home

**Comment by LoneDev6** [comment] 2023-02-27 10:53
Remove IteamsAdder 3.4.0-beta, this version is old and contains issues.
Please rollback.

I forgot to remove it from Polymart.

**Comment by LoneDev6** [comment] 2023-02-27 10:54
Note: it was clearly maked as beta and I clearly stated to make backup before updating, so I hope you did.
Rollback to the previous version.

**Comment by editon96** [comment] 2023-02-27 15:09
> Remove IteamsAdder 3.4.0-beta, this version is old and contains issues. Please rollback.
> 
> I forgot to remove it from Polymart.

With the Stable Build I have the Same Problem so it should not be closed.

**Comment by LoneDev6** [comment] 2023-02-27 15:11
Post a log of the issue with the latest stable 3.1.1

**Comment by LoneDev6** [comment] 2023-02-27 15:11
Anyway try to remove lightapi

**Comment by editon96** [comment] 2023-02-27 15:20
I do. And then you can get the log again

**Comment by editon96** [comment] 2023-02-27 15:21
Do it when I am home. Thanks for the fast reply.

**Comment by editon96** [comment] 2023-03-01 19:43
Now It loads without Light Api and with.
I update to you newest Iteam Adder and the newest Purpur.

**Comment by LoneDev6** [comment] 2023-03-01 22:23
Hello, currently I'm working on an implementation of the light code to avoid having to rely on the unstable one provided by LightAPI.

**Comment by LoneDev6** [comment] 2023-03-01 22:24
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2378

**Closed by LoneDev6** 2023-03-01 22:24 UTC
Labels: Bug, Compatibility with other plugin
