### ISSUE TITLE
Bug with citizens hitbox

### ISSUE THREAD

**Issue by morphin06** [PluginBugs/Issues-ItemsAdder#2002] opened 2022-10-03 01:15 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

The latest ItemsAdder doesn't have a hitbox for citizens plugin regarding npc models.
You can't click on them.
If i downgrade the itemsadder it will fixed but the problem is citizens skin showing the real entity,
So i need to downgrade again,:D

No error in console anything
Using latest version of 1.19.

### Steps to reproduce the issue

I only update itemsadder to the latest version and wala, citizens hitbox gone, can''t click

### Server version

Paper 1.19.2

### ItemsAdder Version

LATEST

### ProtocolLib Version

LATEST

### LoneLibs Version

LATEST

**Comment by LoneDev6** [comment] 2022-10-14 11:51
Please provide a video.
Also do not write "LATEST" I have no idea what the latest version is.

Thanks

**Comment by morphin06** [comment] 2022-10-14 13:24
Why not try for yourself, 
make a citizens and add a model from itemsadder entity. right click it with supposedly command nothing happen.
Latest you don't know your latest version, that sucks
You don't even know what's the meaning of latest version of yours.
Latest newest. Why not admitting  You just want to ignore this issue.
we already report this in discord with gif and you said report githut. 
Your funny. 1 star again

**Comment by morphin06** [comment] 2022-10-14 13:29
I am Doing right click here nothing happen, 
this is a menu for npc. a model from itemsadder
https://media.giphy.com/media/55timxLRU2Q8m1AUao/giphy.gif
[https://media.giphy.com/media/55timxLRU2Q8m1AUao/giphy.gif](url)

Last time you close my ticket regarding cosmeticcore without disclosure or update that could fix it

**Comment by LoneDev6** [comment] 2022-10-20 10:13
If you want help you have to follow the guidelines. Completely ignoring the guidelines and expect me to magically understand and fix issues is nonsensical.

It's extremely vague to say "If i downgrade the itemsadder it will fixed".
I need both precise versions specified in order to trace back changes between them.
Current version -> Working version.

> you are just making as like your talking to a kid.

You are the one saying that not me, I won't ever insult a customer.
I treat you as a customer who is constantly ignoring guidelines.
I didn't set rules to have fun or to piss customers off but to make identifying issues faster.
Ignoring the requested information just makes identifying issues extremely hard, slow and not optimal for both parties.
I hope you understand that I'm trying my best to deliver the best product.


### Answer to the bug report

I identified the cause, it's a Citizens bug, precisely [here](https://github.com/CitizensDev/Citizens2/blob/84e59407e4f34a756a2501f1948272ca800d4352/main/src/main/java/net/citizensnpcs/EventListen.java#L469).
They didn't register the correct event. I am implementing a way to bypass this limitation and it will be available in the next update (will be released this week).

**Closed** 2022-10-20 15:53 UTC
Labels: Bug, Invalid, Other plugin bug, Workaround implemented
