### ISSUE TITLE
Request for Addition of Rotation or Facing Option for Solid Custom Furniture

### ISSUE THREAD

**Issue by dlams** [PluginBugs/Issues-ItemsAdder#3519] opened 2024-03-26 05:40 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

kim_ssammwu_18792

### Describe the solution you'd like

I'm reaching out regarding the Itemsadder plugin, which allows users to add custom furniture to Minecraft servers. 

  Currently, there's a limitation in the deployed API where solid furniture can only be installed facing one direction, specifically towards the north.

  To address this issue, I propose the addition of a rotation or facing option. This would empower users to rotate and place furniture in the desired direction, enhancing both creativity and user experience. I believe this added flexibility would greatly benefit server operators and players using the Itemsadder plugin.

### Is your feature request related to a problem?

public API spawn function(solid) only provide `spawn(String namespacedId, org.bukkit.block.Block blockLocation)`, [spawn](https://lonedev6.github.io/API-ItemsAdder/dev/lone/itemsadder/api/CustomFurniture.html#spawn-java.lang.String-org.bukkit.block.Block-)

### Describe alternatives you've considered

I think we can add a function to import sets of target furniture's barrier blocks from the API. If this function is added, it would be great to be able to import more information about custom furniture as a whole

### Additional context

  Additionally, if there are any alternative solutions available to address this issue, we would greatly appreciate your insights. Providing information on possible solutions would be immensely beneficial to our server operators and players.

**Comment by LoneDev6** [comment] 2024-11-15 15:22
Seems a duplicate of #3913

**Closed** 2024-11-15 15:22 UTC
Labels: type: duplicate
