### ISSUE TITLE
get EXP for crafting

### ISSUE THREAD

**Issue by DayzDuck** [PluginBugs/Issues-ItemsAdder#2062] opened 2022-10-28 17:40 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Raccoon#4485

### Describe the solution you'd like

the possibility to get EXP for crafting an item.

### Is your feature request related to a problem?

yes. because i want to get EXP fpr crafting stuff =)

### Describe alternatives you've considered

As an example:
```
   knife:
      permission: knife
      enabled: true
      pattern:
      - XXX
      - XDX
      - XSX
      ingredients:
        D: IRON_NUGGET
        S: STICK
      result:
        item: knife
        amount: 1
        give_exp:
          chance: 100
          min_amount: 0
          max_amount: 3
```
```
      result:
        give_exp:
          chance: 100
          min_amount: 0
          max_amount: 3
```

**Comment by DayzDuck** [comment] 2022-11-21 21:52
still does not work in 3.0.0

**Comment by LoneDev6** [comment] 2022-11-30 18:13
It's planned for 3.3.1 as you can see.
There is no need to bump this.

![image](https://user-images.githubusercontent.com/27242001/204875964-cb900164-71f3-4ff7-a530-41f8bce6744c.png)

**Comment by LoneDev6** [comment] 2023-01-23 15:38
Is the chance really needed?
People might get confused on why they get exp only sometimes.

I think it should work like vanilla cooking recipes which always give exp.

**Comment by DayzDuck** [comment] 2023-01-23 15:44
Is a "nice to have" idea with the chance.
I think, however, that you should leave the minimum and maximum inside. This would give you more leeway. Thus, the chance would not be necessary.
In the end, you decide how it is exactly implemtiert

**Comment by LoneDev6** [comment] 2023-01-23 16:25
I can add it like that:
`exp: 0-3` which automatically will get a random value between 0-3.

**Comment by DayzDuck** [comment] 2023-01-23 17:21
i think the idea with 

exp: 0-3

is very good!

**Comment by LoneDev6** [comment] 2023-03-15 14:00
Scheduled for 3.4.2 as you can see on the upper right corner of the page

**Comment by LoneDev6** [comment] 2023-09-19 14:56
Duplicate of #1952

**Closed by LoneDev6** 2023-09-19 14:56 UTC
Labels: type: feature request, status: need more info
