### ISSUE TITLE
[Customentity] Iaentity with citizens becomes invisible

### ISSUE THREAD

**Issue by NoHere32** [PluginBugs/Issues-ItemsAdder#3556] opened 2024-04-15 07:11 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

nohere.

### What happened?

Lorsque l'on lie une iaentity a citizens cette dernière va par moment (très souvent) devenir invisible lors de chargement de chunck.

### Steps to reproduce the issue

1. have a citizen with iatentity.
2. move away from 3 to blocks see less sometimes 
3. come back
4. the npc will probably be invisible to you

### Server version

This server is running Pufferfish version git-Pufferfish-47 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9d12215 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-44 (MC: 1.20.4)

### ItemsAdder Version

[09:09:36 INFO]: ItemsAdder version 3.6.3-beta-13
[09:09:36 INFO]: Customized Minecraft without client mods!
[09:09:36 INFO]: Website: devs.beer
[09:09:36 INFO]: Author: LoneDev

### ProtocolLib Version

[09:09:57 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[09:09:57 INFO]: Provides read/write access to the Minecraft protocol.
[09:09:57 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[09:10:09 INFO]: LoneLibs version 1.0.45
[09:10:09 INFO]: Collection of libs used by my plugins
[09:10:09 INFO]: Authors: LoneDev and others

### FULL server log

https://paste.denizenscript.com/View/121989

### Screenshots/Videos (you can drag and drop files or paste links)

![322326953-d3baed85-5f5a-4a5d-8e47-ff6748383953](https://github.com/PluginBugs/Issues-ItemsAdder/assets/123643370/a05ce0f1-af5a-441d-9a5f-41a147311344)
![322327005-34787b2f-c459-4afb-a026-98611abf9039](https://github.com/PluginBugs/Issues-ItemsAdder/assets/123643370/695f4491-c9e1-477a-b582-19bc28a18cae)

**Comment by LoneDev6** [comment] 2024-04-15 14:43
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/3350

**Closed by LoneDev6** 2024-04-15 14:43 UTC
Labels: type: bug
