### ISSUE TITLE
Chat formatting breaks yet again

### ISSUE THREAD

**Issue by AGuyNamedJens** [PluginBugs/Issues-ItemsAdder#3499] opened 2024-03-15 00:32 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

aguynamedjensbot

### What happened?

The chat formatting once again is broken as far as i'm experiencing it. VentureChat adds JSON based logic to messages, making it really useful for complete customization of chats being sent/received. However for some odd reason ItemsAdder recently has stopped properly formatting the messages, giving 
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/34610614/02feb8c7-814b-485b-a485-b4d40f74a5dc)
this weird outcome.. However i'm not sure if it's VentureChat or ItemsAdder's issue, seemingly it's related to ItemsAdder's Effects and Chat color settings according to https://github.com/Aust1n46/VentureChat/issues/105

### Steps to reproduce the issue

1. Use PaperMC 1.20.2 latest version
2. (optional?) Install the plugins: ViaVersion, Geyser, Floodgate, VentureChat, ItemsAdder (and dependencies), EssentialsX
3. You should probably already notice (some) messages fail to format, and get thrown as JSON into the chat, however console shows no issues and shows the expected outcome as normal.
4. Set both Chat Effects and Font Effects off in IA's config.yml file for the Chat only
5. Chat will behave like normal

### Server version

Current: git-Purpur-2095 (MC: 1.20.2)*
* You are running the latest version

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

ProtocolLib v5.1.1-SNAPSHOT-673

### LoneLibs Version

1.0.45

**Comment by LoneDev6** [comment] 2024-04-04 14:48
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/3397

**Closed by LoneDev6** 2024-04-04 14:48 UTC
Labels: type: bug
