### ISSUE TITLE
Title [BUG] Effects not properly removed (unresolved)

### ISSUE THREAD

**Issue by Distolfix** [PluginBugs/Issues-ItemsAdder#2619] opened 2023-05-13 08:28 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When you execute a command, for example, to remove armor with /invsee (cmi) or remove a tool/sword that has an effect or when you execute a simple clear command, the effects remain and do not disappear.

### Steps to reproduce the issue

1) Obtain a sword with an effect or armor.

2) Remove it with /clear or a simple /invsee command.

### Server version

This server is running Pufferfish version git-Pufferfish-61 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 47c34ca on HEAD)
You are running 8 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Purpur-1933 (MC: 1.19.3)

### ItemsAdder Version

3.4.1 c

### ProtocolLib Version

5.0.0 SNAPSHOT-b616

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/73421268/a4647451-1117-472e-9eb9-b475d4c7cf01)

**Comment by SirCraftypants** [comment] 2023-05-13 10:26
I'm guessing you are referring to items that provide potion/enchant effect.

Maybe you could run the remove status effect from player at the same time?

[[](url)](https://www.sportskeeda.com/minecraft/how-remove-effects-minecraft)

**Comment by Distolfix** [comment] 2023-05-13 10:49
Don't you think it's impossible to do it every time to remove an effect or a potion when I have to remove an object or do a clear? It would be enough to simply implement it in the plugin.

**Comment by SirCraftypants** [comment] 2023-05-13 10:53
> Don't you think it's impossible to do it every time to remove an effect or a potion when I have to remove an object or do a clear? It would be enough to simply implement it in the plugin.

I've only just installed invsee so i'm not experienced with it yet, is there not a way to get invsee to run it for you when it removes the item?

**Comment by Distolfix** [comment] 2023-05-13 11:35
No

**Comment by SirCraftypants** [comment] 2023-05-13 11:37
> No

As item removal is invsee's job with it's own command, it's unlikely Lonedev would implement it, i'd like to see invsee dev implement it within invsee. If you create a feature request with invsee and send me a link i will give it my support.

**Comment by LoneDev6** [comment] 2023-05-13 12:42
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2620

**Closed by LoneDev6** 2023-05-13 12:42 UTC
Labels: type: bug
