### ISSUE TITLE
Make the plugin listen for cancellations on specific click events.

### ISSUE THREAD

**Issue by WasaTG** [PluginBugs/Issues-ItemsAdder#3374] opened 2024-01-26 17:34 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

elcory

### Describe the solution you'd like

Adding 2 lines of code, aka. adding the "ignoreCancelled = true" annotation (it's just an attribute) to the 1-2 relevant click handlers.

### Is your feature request related to a problem?

It would be very useful to be able to use scripts or plugins that cancel events every time a user clicks specifically holding an ia Item (left click, or right click, or shift + left click, or shift + left click, etc).

### Describe alternatives you've considered

Adding 2 lines of code, aka. adding the "ignoreCancelled = true" annotation (it's just an attribute) to the 1-2 relevant click handlers.

**Comment by LoneDev6** [comment] 2024-01-29 15:16
Duplicate of: #3373

**Closed by LoneDev6** 2024-01-29 15:16 UTC
Labels: type: feature request
