### ISSUE TITLE
Does not finish loading the plugin

### ISSUE THREAD

**Issue by Kiritoita75** [PluginBugs/Issues-ItemsAdder#3335] opened 2024-01-14 19:48 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

kiritoita

### What happened?

when i try to run the server, i wait for all plugins to laod, and when is time  for itemsadder it's show no error but a the end of the starting of the server it' show the error

### Steps to reproduce the issue

1. start the server
2. wait for the server is finaly load
3. see the error
4. try to type a command
5. read "Plugin is still loading... Please wait before using /ia"

### Server version

[20:44:34 INFO]: This server is running Paper version git-Paper-379 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 570cfb4)

You are 9 version(s) behind

Download the new version at: https://papermc.io/downloads/paper

Previous version: git-Paper-243 (MC: 1.20.2)

### ItemsAdder Version

[20:45:23 INFO]: ItemsAdder version 3.6.3-beta-7

[20:45:23 INFO]: Customized Minecraft without client mods!

[20:45:23 INFO]: Website: devs.beer

[20:45:23 INFO]: Author: LoneDev

### ProtocolLib Version

[20:45:44 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679

[20:45:44 INFO]: Provides read/write access to the Minecraft protocol.

[20:45:44 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[20:45:57 INFO]: LoneLibs version 1.0.45

[20:45:57 INFO]: Collection of libs used by my plugins

[20:45:57 INFO]: Authors: LoneDev and others

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13932912/latest.log)

### Error (optional)

```shell
[20:39:37 WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.3-beta-7 generated an exception while executing task 132

java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.setTabCompleter(org.bukkit.command.TabCompleter)" because the return value of "dev.lone.itemsadder.Main.a(String)" is null

at ia.m.hA.<init>(SourceFile:81) ~[ItemsAdder_3.6.3-beta-7.jar:?]

at ia.m.G.a(SourceFile:957) ~[ItemsAdder_3.6.3-beta-7.jar:?]

at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-379]

at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-379]

at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/127886361/264f77b3-b3d2-48eb-9b35-4d18b99a10d4)

**Comment by LoneDev6** [comment] 2024-01-15 17:30
For some reason ItemsAdder cannot find the command `iaimage`.
This is not normal and I see no reason for this to happen.

Anyway I read this in your log, can you try deleting your permissions.yml file in the server root? (make a backup of it before deleting it).
It might be the cause.
```yml
[20:39:12] [Server thread/WARN]: Server permissions file permissions.yml is not valid YAML.
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadCustomPermissions(CraftServer.java:1174) ~[paper-1.20.4.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:541) ~[paper-1.20.4.jar:git-Paper-379]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-379]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

You could also try removing all other plugins and keep only ItemsAdder and its dependencies.

Let me know.

**Comment by LoneDev6** [comment] 2024-01-15 17:30
Duplicate of this issue: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3187

**Closed by LoneDev6** 2024-01-15 17:30 UTC
Labels: type: bug
