### ISSUE TITLE
NMS or method handling (NoSuchMethodError) issue 1.19.4

### ISSUE THREAD

**Issue by Vooperino** [PluginBugs/Issues-ItemsAdder#2519] opened 2023-04-09 06:13 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Voop#0001

### What happened?

NMS or method issues or NoSuchMethodError has is being thrown out in the console.

### Steps to reproduce the issue

1. Use 1.19.4 PaperSpigot
2. Download CustomCrops Plugin
3. Try to place down any blocks.

### Server version

This server is running Paper version git-Paper-501 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9cda284)
You are running the latest version
Previous version: git-Paper-477 (MC: 1.19.4)

### ItemsAdder Version

3.4.1-r5

### ProtocolLib Version

5.0.0-SNAPSHOT-b614

### LoneLibs Version

LoneLibs version 1.0.24

### Error (optional)

```shell
[08:06:33 WARN]: [ItemsAdder] Task #3519 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-501]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-501]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

[08:06:13 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1-r5
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at ia.nms.aI.impl.v1_19_R3.setBlockData(SourceFile:45) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.nms.aI.aP.a(SourceFile:37) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.eF.e(SourceFile:497) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.en.a(SourceFile:256) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.en.b(SourceFile:208) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.ck.b(SourceFile:400) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.ck.a(SourceFile:318) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.ck.a(SourceFile:203) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.ck.a(SourceFile:178) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.ck.g(SourceFile:134) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.de.a(SourceFile:145) ~[ItemsAdder_3.4.1-r5.jar:?]
        at ia.m.de.k(SourceFile:235) ~[ItemsAdder_3.4.1-r5.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-501]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-501]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-501]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:562) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1957) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-501]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment] 2023-04-12 10:03
Seems to be related to this, will be checked.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2512

**Comment by LoneDev6** [comment] 2023-04-12 10:19
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2498

**Closed by LoneDev6** 2023-04-12 10:19 UTC
Labels: type: bug
