### ISSUE TITLE
Getting Errors On Console

### ISSUE THREAD

**Issue by HuzaifaMughal0024** [PluginBugs/Issues-ItemsAdder#3554] opened 2024-04-13 18:03 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

huzaifa_xd#0

### What happened?

I am getting this error on console when I try to reload or zip items adder:

[[17:59:27 WARN]: java.net.SocketTimeoutException: Connect timed out
[17:59:27 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
[17:59:27 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
[17:59:27 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[17:59:27 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[17:59:27 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
[17:59:27 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
[17:59:27 WARN]:        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:281)
[17:59:27 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
[17:59:27 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
[17:59:27 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
[17:59:27 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[17:59:27 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[17:59:27 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
[17:59:27 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[17:59:27 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[17:59:27 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.qG.t(SourceFile:484)
[17:59:27 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.qG.bA(SourceFile:310)
[17:59:27 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.qG.cU(SourceFile:290)
[17:59:27 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.G.a(SourceFile:1219)
[17:59:27 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.qe.a(SourceFile:471)
[17:59:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:59:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:59:27 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:59:27 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:59:27 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:59:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[17:59:27 INFO]: [ItemsAdder] [Pack] Compressed in 15156ms
[17:59:27 INFO]: [ItemsAdder] [Pack] Applying to every player... 
[17:59:27 WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.3-beta-13 generated an exception while executing task 2496
java.lang.NullPointerException: Cannot invoke "String.length()" because "string2" is null
        at net.minecraft.network.protocol.common.ClientboundResourcePackPushPacket.url(ClientboundResourcePackPushPacket.java:13) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at ia.m.mr.a(SourceFile:26) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.mj.a(SourceFile:40) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qG.ax(SourceFile:186) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qP.av(SourceFile:67) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qG.aa(SourceFile:136) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.iu.b(SourceFile:182) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.iu.b(SourceFile:104) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.G.a(SourceFile:1222) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qe.a(SourceFile:471) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### Steps to reproduce the issue

...

### Server version

1.20.4

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.20.0

### LoneLibs Version

1.0.45

### FULL server log

[17:58:56 INFO]: __Huzi issued server command: /iazip all
[17:58:56 INFO]: [ItemsAdder] [Host] Stopped self-host webserver on port: 25596
[17:58:56 INFO]: [ItemsAdder] [Host] Starting self-host webserver on port: 25596
[17:58:56 WARN]: [ItemsAdder] Warning: forcefully setting player resourcepack status to installed because the plugin was reloaded.
[17:58:56 INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[17:58:56 INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[17:58:56 INFO]: [ItemsAdder] Loaded 7 items
[17:58:56 INFO]: [ItemsAdder] Used 0/188 REAL block IDs
[17:58:56 INFO]: [ItemsAdder] Used 0/750 REAL_NOTE block IDs
[17:58:56 INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
[17:58:56 INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs
[17:58:56 INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[17:58:56 INFO]: [ItemsAdder] Used 32/6608 font_images
[17:59:11 ERROR]: [ItemsAdder] Failed to calculate resourcepack hash form remote URL http://138.201.125.82:25596/generated.zip#86ed7137ff0c03aead097658649fc45117952491.
[17:59:11 WARN]: java.net.SocketTimeoutException: Connect timed out
[17:59:11 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
[17:59:11 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
[17:59:11 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[17:59:11 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[17:59:11 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
[17:59:11 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
[17:59:11 WARN]:        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:281)
[17:59:11 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
[17:59:11 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
[17:59:11 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
[17:59:11 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[17:59:11 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[17:59:11 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
[17:59:11 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[17:59:11 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[17:59:11 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.qG.t(SourceFile:484)
[17:59:11 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.qG.bA(SourceFile:310)
[17:59:11 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.qG.cU(SourceFile:290)
[17:59:11 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.G.a(SourceFile:923)
[17:59:11 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:59:11 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:59:11 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:59:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:59:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:59:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[17:59:12 INFO]: [ItemsAdder] [Init] Loaded 1 categories
[17:59:12 INFO]: [ItemsAdder] [Init] Loaded successfully in 15107ms
[17:59:12 INFO]: [ItemsAdder]  
[17:59:12 INFO]: [ItemsAdder]  
[17:59:12 INFO]: [ItemsAdder] [Pack] Started generation
[17:59:12 INFO]: [PlaceholderAPI] Successfully registered internal expansion: img [1.0.1]
[17:59:12 INFO]: [PlaceholderAPI] Successfully registered internal expansion: iaplayerstat [1.0.1]
[17:59:12 INFO]: [ItemsAdder]  
[17:59:12 INFO]: [ItemsAdder] [Pack] Generated resourcepack
[17:59:12 INFO]: [ItemsAdder] [OK] Your zip file will be protected from unzip (as set in config.yml)
[17:59:12 INFO]: [ItemsAdder] [Pack] Compressing resource_pack ... 
[17:59:12 INFO]: [ItemsAdder]  
[17:59:12 INFO]: [ItemsAdder]  
[17:59:12 INFO]: [ItemsAdder] [Pack] Saved into /container/plugins/ItemsAdder/output/generated.zip
[17:59:27 ERROR]: [ItemsAdder] Failed to calculate resourcepack hash form remote URL http://138.201.125.82:25596/generated.zip#131a6d3fbc1df6b6c3b73169920525e142bbe25b.
[17:59:27 WARN]: java.net.SocketTimeoutException: Connect timed out
[17:59:27 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
[17:59:27 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
[17:59:27 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[17:59:27 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[17:59:27 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
[17:59:27 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
[17:59:27 WARN]:        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:281)
[17:59:27 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
[17:59:27 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
[17:59:27 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
[17:59:27 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[17:59:27 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[17:59:27 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
[17:59:27 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[17:59:27 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[17:59:27 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.qG.t(SourceFile:484)
[17:59:27 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.qG.bA(SourceFile:310)
[17:59:27 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.qG.cU(SourceFile:290)
[17:59:27 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.G.a(SourceFile:1219)
[17:59:27 WARN]:        at ItemsAdder_3.6.3-beta-13.jar//ia.m.qe.a(SourceFile:471)
[17:59:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:59:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:59:27 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:59:27 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:59:27 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:59:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[17:59:27 INFO]: [ItemsAdder] [Pack] Compressed in 15156ms
[17:59:27 INFO]: [ItemsAdder] [Pack] Applying to every player... 
[17:59:27 WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.3-beta-13 generated an exception while executing task 2496
java.lang.NullPointerException: Cannot invoke "String.length()" because "string2" is null
        at net.minecraft.network.protocol.common.ClientboundResourcePackPushPacket.url(ClientboundResourcePackPushPacket.java:13) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at ia.m.mr.a(SourceFile:26) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.mj.a(SourceFile:40) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qG.ax(SourceFile:186) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qP.av(SourceFile:67) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qG.aa(SourceFile:136) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.iu.b(SourceFile:182) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.iu.b(SourceFile:104) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.G.a(SourceFile:1222) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qe.a(SourceFile:471) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[18:01:01 INFO]: __Huzi issued server command: /version
[18:01:24 INFO]: __Huzi issued server command: /version ItemsAdder
[18:01:54 INFO]: __Huzi issued server command: /version ProtocolLib
[18:02:07 INFO]: __Huzi issued server command: /version LoneLibs

### Other files, you can drag and drop them here to upload. (optional)

...

### Screenshots/Videos (you can drag and drop files or paste links)

..

**Comment by LoneDev6** [comment] 2024-04-15 14:05
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/3413

**Closed by LoneDev6** 2024-04-15 14:05 UTC
Labels: type: bug
