### ISSUE TITLE
sometimes customblock changed note block

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-ItemsAdder#3430] opened 2024-02-15 05:00 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

EclipseMC#7777

### What happened?

sometimes customblock changed note block
![2024-02-15_13 17 42_](https://github.com/PluginBugs/Issues-ItemsAdder/assets/25452835/339b00f4-71ae-4556-94ae-f2b9561a711c)

### Steps to reproduce the issue

idk how to reproduce them. but this problems occured frequently.

### Server version

paper 1.20.2-RO.1-SNAPSHOT

### ItemsAdder Version

3.6.2c

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### LoneLibs Version

1.0.45

### Problematic items yml configuration file (optional)

```shell
crops_pot:
    display_name: 작물통
    resource:
      generate: false
      material: PAPER
      model_path: crops/crops_pot
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        break_tools_whitelist:
        - AXE
        hardness: 10
        sound:
          place:
            name: block.wood.place
          break:
            name: block.wood.break
  crops_watered_pot:
    display_name: 젖은 작물 통
    resource:
      generate: false
      material: PAPER
      model_path: crops/watered_pot
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        break_tools_whitelist:
        - AXE
        hardness: 10
        cancel_drop: true
        sound:
          place:
            name: block.wood.place
          break:
            name: block.wood.break
```

**Comment by LoneDev6** [comment] 2024-04-10 09:47
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2403

**Closed by LoneDev6** 2024-04-10 09:47 UTC
Labels: type: bug
