### ISSUE TITLE
Emotes have no texture on some parts when using slim-type model

### ISSUE THREAD

**Issue by glutaminus** [PluginBugs/Issues-ItemsAdder#2870] opened 2023-07-12 07:05 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

when using emote while having slim-type skin, emotes will have result with some untextured/black texture part on the model
( this happen on any emotes)

### Steps to reproduce the issue

1. use slim-type skin
2. /iaemote <any-emote)

### Server version

git-Purpur-1858 (MC: 1.19.2)

### ItemsAdder Version

3.5.0c-r2

### ProtocolLib Version

5.1.0-SNAPSHOT-660

### LoneLibs Version

1.0.25

### FULL server log

nothing is wrong in log

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/90768288/edf56950-4390-4d2f-8858-413d772f9066

**Comment by LoneDev6** [comment] 2023-07-12 09:13
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2770

**Closed by LoneDev6** 2023-07-12 09:13 UTC
Labels: type: bug
