### ISSUE TITLE
onPacketSending error was broadcast frequently to all players.

### ISSUE THREAD

**Issue by NCSV** [PluginBugs/Issues-ItemsAdder#1431] opened 2022-01-17 12:21 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

이클립스#1221

### What happened?

after update 1.18 and IA,
onPacketSending error was broadcast frequently to all players.

### Steps to reproduce the issue

i uploaded screenshot downbelow

### Server version

Purpur 1.18.1-RO.1-SNAPSHOT

### ItemsAdder Version

2.5.1-beta4

### ProtocolLib Version

4.8.0-SNAPSHOT-b540

### LoneLibs Version

 1.0.16b

### LightAPI Version (optional)

bukkit-5.1.0

### LibsDisguises Version (optional)

10.0.27

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7881761/latest.log)

### ItemsAdder config.yml

```shell
metrics: true
update-checker: false
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: https://download.mc-packs.net/pack/2b0f00ab9c0d1b75c6bf14ecf84e7b16d80a3df7.zip
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: false
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: false
    cancel-movement: true
    lock-player: true
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    protect-file-from-unzip:
      enabled: true
      extreme: true
    overwrite-vanilla-models: true
    overwrite-vanilla-lang-json: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      _: 'Available values: VANILLA_1_17 or OPTIFINE'
      enabled: true
      mode: VANILLA_1_17
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  command:
    usage-cooldown-seconds: 60
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    seach-also-in-these-biomes: {}
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: false
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

![unknown](https://user-images.githubusercontent.com/25452835/149768387-6503b3fd-78b1-4669-84fc-a2d3b10549b8.png)

**Comment by NCSV** [comment] 2022-01-18 19:59
+ i use venturechat hover features. but after update lastest version of IA, emoji hover features are override it.
so i set false emoji features in config, but it also override (It's set up so that hover doesn't)

**Comment by LoneDev6** [comment] 2022-01-19 15:54
@NCSV Please open a separate Github issue report for each one of the issues, don't use the same one.
Thanks.

**Comment by LoneDev6** [comment] 2022-01-19 15:56
Can you send me the message a user/plugin had send in chat to trigger the error?
It's very important, thanks.

Because sadly I can't manage to read the file correctly.
> [14:50:27] [ForkJoinPool.commonPool-worker-71/INFO]:  :notify_green: ������ ���������� ���۵Ǿ����ϴ�.

**Comment by LoneDev6** [comment] 2022-01-19 15:57
> ![3](https://user-images.githubusercontent.com/25452835/149768677-156694cc-6c20-42cb-b6b3-fe61dde5dc46.PNG)
> 
> and scoreboard issue. when i set hide-scoreboard-numbers: true, mcmmo scoreboard, and holograms with &c was not viewed properly

Disable the hide scoreboard numbers feature.
Why are you using this feature if you don't want to hide numbers?

If you want to hide numbers make sure to use only single digit numbers, not `2417` `1094` `179` etc.
This is a Minecraft limitation and I'm not sure if I can fix it.

**Comment by NCSV** [comment] 2022-01-19 16:10
> Can you send me the message a user/plugin had send in chat to trigger the error? It's very important, thanks.
> 
> Because sadly I can't manage to read the file correctly.
> 
> > [14:50:27] [ForkJoinPool.commonPool-worker-71/INFO]:  :notify_green: ������ ���������� ���۵Ǿ����ϴ�.
![3](https://user-images.githubusercontent.com/25452835/150169629-d6e823a7-fc1b-42cb-be95-1eb751365b62.PNG)

this is image font in IA. (i copy, paste in message files.
There was no such error when writing the old version IA in version 1.16.5.

**Comment by NCSV** [comment] 2022-01-19 18:16
> > ![3](https://user-images.githubusercontent.com/25452835/149768677-156694cc-6c20-42cb-b6b3-fe61dde5dc46.PNG)
> > and scoreboard issue. when i set hide-scoreboard-numbers: true, mcmmo scoreboard, and holograms with &c was not viewed properly
> 
> Disable the hide scoreboard numbers feature. Why are you using this feature if you don't want to hide numbers?
> 
> If you want to hide numbers make sure to use only single digit numbers, not `2417` `1094` `179` etc. This is a Minecraft limitation and I'm not sure if I ca
![2022-01-20_03 14 53](https://user-images.githubusercontent.com/25452835/150189966-9a4a9232-ceda-4558-a31f-9893332c4315.png)
n fix it.

 this problems also happend in hologram. can't it fixed?

**Comment by LoneDev6** [comment] 2022-01-20 09:21
Check here please: https://itemsadder.devs.beer/plugin-usage/scoreboard/hide-scoreboard-numbers-1.17+#warning
It's a temporary solution until I find a proper way to differentiate scoreboard rendering and other renderings.

**Comment by LoneDev6** [comment] 2022-01-20 09:22
> > Can you send me the message a user/plugin had send in chat to trigger the error? It's very important, thanks.
> > Because sadly I can't manage to read the file correctly.
> > > [14:50:27] [ForkJoinPool.commonPool-worker-71/INFO]:  :notify_green: ������ ���������� ���۵Ǿ����ϴ�.
> > > ![3](https://user-images.githubusercontent.com/25452835/150169629-d6e823a7-fc1b-42cb-be95-1eb751365b62.PNG)
> 
> this is image font in IA. (i copy, paste in message files. There was no such error when writing the old version IA in version 1.16.5.

This is probably already fixed in my next release, please let me know after I release the update.
Thanks!

**Comment by NCSV** [comment] 2022-01-28 12:09
> > > Can you send me the message a user/plugin had send in chat to trigger the error? It's very important, thanks.
> > > Because sadly I can't manage to read the file correctly.
> > > > [14:50:27] [ForkJoinPool.commonPool-worker-71/INFO]:  :notify_green: ������ ���������� ���۵Ǿ����ϴ�.
> > > > ![3](https://user-images.githubusercontent.com/25452835/150169629-d6e823a7-fc1b-42cb-be95-1eb751365b62.PNG)
> > 
> > 
> > this is image font in IA. (i copy, paste in message files. There was no such error when writing the old version IA in version 1.16.5.
> 
> This is probably already fixed in my next release, please let me know after I release the update. Thanks!

after update, but still same issue.

**Comment by NCSV** [comment] 2022-01-29 10:03
![2022-01-29_19 03 27](https://user-images.githubusercontent.com/25452835/151656741-6a06a228-0496-49b7-a64d-8d7144ea2839.png)

**Comment by LoneDev6** [comment] 2022-02-14 08:58
The issue is that it's hard for me to identify the precise cause of this error because it has no detail about the line of my code which is triggering it.
Somehow ProtocolLib is not printing that information in console, which is not normal.


Another strange thing is this:
> 20:10:26] [Craft Scheduler Thread - 73820 - MysqlPlayerDataBridge/ERROR]: [ProtocolLib] [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder

For some reason the plugin who printed the error is `MysqlPlayerDataBridge`, why?
I suspect this error is from another server where you have ItemsAdder installed, can you check if you have another server which is syncing chat or data and it has ItemAdder installed?
If yes, please send me the log of the other server.

**Comment by NCSV** [comment] 2022-03-01 15:23
> 
my server is installed waterfall (also bungeepackfix is installed.) and sync inventory and money, etc (mysqlplayerdata)

below 3 server are sync with mpdb(mysqlplayerdatabridge)
survival lobby - survival ch1 - survival ch2
that error's message is joining message (1. "daya syncing...", 2. "data sync complete")

all server has same itemsadder's setting. (only force apply in survival lobby server)

**Comment by NCSV** [comment] 2022-03-01 15:24
this is server log files
[survival.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8162654/survival.log)
[ch 1.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8162657/ch.1.log)
[ch 2.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8162660/ch.2.log)

**Comment by NCSV** [comment] 2022-03-13 12:26
@LoneDev6

**Comment by LoneDev6** [comment] 2022-03-14 09:32
> this is server log files [survival.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8162654/survival.log) [ch 1.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8162657/ch.1.log) [ch 2.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8162660/ch.2.log)

Are these the exact logs of when the issue happened?

**Comment by NCSV** [comment] 2022-03-14 09:40
> > this is server log files [survival.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8162654/survival.log) [ch 1.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8162657/ch.1.log) [ch 2.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8162660/ch.2.log)
> 
> Are these the exact logs of when the issue happened?

that text componment message is occured when player joined server.

**Comment by LoneDev6** [comment] 2022-03-15 09:33
I need the log of when this happened

**Comment by NCSV** [comment] 2022-03-15 13:45
i sent you before..

[22:44:19] [Craft Scheduler Thread - 11625 - MysqlPlayerDataBridge/ERROR]: [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder
java.lang.NullPointerException: null
[22:44:19] [Craft Scheduler Thread - 11625 - MysqlPlayerDataBridge/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutChat@2ddac571[
    a=TextComponent{text='', siblings=[TextComponent{text='  유저 데이터 연동에 ', siblings=[], style=Style{ color=white, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='성공', siblings=[], style=Style{ color=green, bold=null, italic=false, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='하였습니다.', siblings=[], style=Style{ color=white, bold=null, italic=false, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
    components=<null>
    b=SYSTEM
    c=00000000-0000-0000-0000-000000000000
  ]

**Comment by NCSV** [comment] 2022-03-15 13:45
> I need the log of when this happened

i sent you before..

[22:44:19] [Craft Scheduler Thread - 11625 - MysqlPlayerDataBridge/ERROR]: [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder
java.lang.NullPointerException: null
[22:44:19] [Craft Scheduler Thread - 11625 - MysqlPlayerDataBridge/ERROR]: Parameters:
net.minecraft.network.protocol.game.PacketPlayOutChat@2ddac571[
a=TextComponent{text='', siblings=[TextComponent{text='  유저 데이터 연동에 ', siblings=[], style=Style{ color=white, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='성공', siblings=[], style=Style{ color=green, bold=null, italic=false, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='하였습니다.', siblings=[], style=Style{ color=white, bold=null, italic=false, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
components=
b=SYSTEM
c=00000000-0000-0000-0000-000000000000
]

**Comment by LoneDev6** [comment] 2022-03-15 13:59
The full log of all your servers of when this issue occurred.
That's what I need.

**Comment by LoneDev6** [comment] 2022-03-15 13:59
You can also try to enable this in protocollib config.yml file:
```yml
detailed error: true
```

**Comment by LoneDev6** [comment] 2022-03-17 11:06
This was already fixed in 3.0.0, update please.
Let me know.

**Closed by LoneDev6** 2022-03-17 11:06 UTC
Labels: Bug, Compatibility with other plugin, Inactivity, Can't reproduce

**Comment by NCSV** [comment] 2022-03-20 11:14
> This was already fixed in 3.0.0, update please. Let me know.
![2022-03-20_20 13 27](https://user-images.githubusercontent.com/25452835/159159566-7f2e1a2a-216a-47e4-82a1-d18bc1e1e395.png)

are you sure? i already update lastest build twice times.
(3.0.3-beta4)

**Comment by LoneDev6** [comment] 2022-03-21 10:22
Please send me the new updated log.
Make sure to keep this ProtocoLib option enabled:
```yml
detailed error: true
```


Thanks

**Comment by Jefferson7u78** [comment] 2024-01-02 01:58
I am experiencing the same error. I have all the plugins updated to the latest version. I'm sending some screenshots for reference, I get this error when I try to join the server and I am automatically kicked out.

![chrome_PQGeWAFRKn](https://github.com/PluginBugs/Issues-ItemsAdder/assets/128727190/3e40eb50-76cc-4c58-8c85-94f1f9e43ac1)

![chrome_QkZgfsvI8x](https://github.com/PluginBugs/Issues-ItemsAdder/assets/128727190/b2bd080a-7e12-4c7f-bc10-c5d581e1d4e1)

**Comment by LoneDev6** [comment] 2024-01-02 16:17
Update LoneLibs and let me know

**Comment by Jefferson7u78** [comment] 2024-01-02 16:55
I updated it again and the same error continues.
![chrome_WuFWMl3scN](https://github.com/PluginBugs/Issues-ItemsAdder/assets/128727190/0521bf44-d416-474b-a3e7-e037e1342349)

**Comment by LoneDev6** [comment] 2024-01-03 11:12
This is very strange, I cannot reproduce this issue.

**Comment by LoneDev6** [comment] 2024-01-03 17:24
I'm sure that if you change it back to selfhost you would have the same error, they are unrelated.

**Comment by Jefferson7u78** [comment] 2024-01-03 19:54
So, for now, is there no solution? And could the previous guy have been able to solve it? Since I have the same bug, and he reported it two years ago.

**Comment by LoneDev6** [comment] 2024-01-03 20:24
I didn't notice this was an old issue.
Please do not bump closed issues from years ago, instead create a new issue with all your current server information.
Anyway I fixed the issue, seems to be a duplicate of this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3282
I will post an update later, thanks.
