### ISSUE TITLE
Itemsadder not starting correctly

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1389] opened 2022-01-02 19:10 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

The plugin, along with the chestcommands and betterHUDs  addons, fail to enable

### Steps to reproduce the issue

install the mentioned plugins and run a 1.17.1 server

### Server version

git-airplane-67 1.17.1 (airplane-purpur)

### ItemsAdder Version

2.5.2-beta4

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.16b

### LightAPI Version (optional)

bukkit 5.1.0

### LibsDisguises Version (optional)

10.0.17-SNAPSHOT

### Error (optional)

```shell
{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red202\green51\blue35;}
{\*\expandedcolortbl;;\csgray\c0;\cssrgb\c83898\c28665\c18024;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs22 \cf2 \CocoaLigature0 [18:42:52 INFO]: [ChestCommands] Enabling ChestCommands v4.0.4-SNAPSHOT-unofficial\
\cf3 [18:42:52 INFO]: [ChestCommands] Fatal unexpected error while enabling plugin:\cf2 \
\
\cf3 java.lang.ExceptionInInitializerError\cf2 \
	at ItemsAdder.jar//dev.lone.itemsadder.api.ItemsAdder.areItemsLoaded(SourceFile:37)\
	at chestcommands-plugin-4.0.4-SNAPSHOT-unofficial.jar//me.filoghost.chestcommands.hook.ItemsAdderHook.setup(ItemsAdderHook.java:26)\
	at chestcommands-plugin-4.0.4-SNAPSHOT-unofficial.jar//me.filoghost.chestcommands.ChestCommands.onCheckedEnable(ChestCommands.java:91)\
	at chestcommands-plugin-4.0.4-SNAPSHOT-unofficial.jar//me.filoghost.chestcommands.fcommons.FCommonsPlugin.onEnable(FCommonsPlugin.java:22)\
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)\
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)\
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)\
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)\
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)\
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:735)\
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:328)\
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1224)\
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)\
	at java.base/java.lang.Thread.run(Thread.java:831)\
\cf3 Caused by: java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.Main.getDataFolder()" because the return value of "dev.lone.itemsadder.Main.a()" is null\cf2 \
	at ItemsAdder.jar//dev.lone.itemsadder.main.az.<clinit>(SourceFile:104)\
	... 14 more\
\
ChestCommands has been disabled.\
[18:43:06 INFO]: [ItemsAdder] Enabling ItemsAdder v2.5.1-beta4\
[18:43:06 INFO]: [ItemsAdder] \
  ___  ___        __        __   __   ___  __      ItemsAdder 2.5.1-beta4\
|  |  |__   |\\/| /__`  /\\  |  \\ |  \\ |__  |__)     LoneLibs 1.0.16b\
|  |  |___  |  | .__/ /--\\ |__/ |__/ |___ |  \\     Airplane git-Airplane-67 (MC: 1.17.1)\
                                               \
\cf3 [18:43:06 ERROR]: Error occurred while enabling ItemsAdder v2.5.1-beta4 (Is it up to date?)\cf2 \
\cf3 java.lang.NoClassDefFoundError: Could not initialize class dev.lone.itemsadder.main.az\cf2 \
	at dev.lone.itemsadder.Main.onEnable(SourceFile:392) ~[ItemsAdder.jar:?]\
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Airplane-67]\
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Airplane-67]\
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Airplane-67]\
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Airplane-67]\
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Airplane-67]\
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:735) ~[patched_1.17.1.jar:git-Airplane-67]\
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:328) ~[patched_1.17.1.jar:git-Airplane-67]\
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224) ~[patched_1.17.1.jar:git-Airplane-67]\
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Airplane-67]\
	at java.lang.Thread.run(Thread.java:831) ~[?:?]\
[18:43:06 INFO]: [ItemsAdder] Disabling ItemsAdder v2.5.1-beta4\
[18:43:06 INFO]: [BetterHud] Enabling BetterHud v2.2-b04\
[18:43:06 INFO]: [BetterHud] Successfully hooked into ItemsAdder!\
[18:43:06 INFO]: [BetterHud] Successfully hooked into PlaceholderAPI!\
\cf3 [18:43:06 ERROR]: Error occurred while enabling BetterHud v2.2-b04 (Is it up to date?)\cf2 \
\cf3 java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getBoolean(String)" because the return value of "org.bukkit.configuration.ConfigurationSection.getConfigurationSection(String)" is null\cf2 \
	at cz.apigames.betterhud.BetterHud.isIASelfHosted(BetterHud.java:225) ~[BetterHud-2.2-b04.jar:?]\
	at cz.apigames.betterhud.BetterHud.onEnable(BetterHud.java:116) ~[BetterHud-2.2-b04.jar:?]\
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Airplane-67]\
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Airplane-67]\
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Airplane-67]\
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Airplane-67]\
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Airplane-67]\
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:735) ~[patched_1.17.1.jar:git-Airplane-67]\
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:328) ~[patched_1.17.1.jar:git-Airplane-67]\
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224) ~[patched_1.17.1.jar:git-Airplane-67]\
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Airplane-67]\
	at java.lang.Thread.run(Thread.java:831) ~[?:?]\
[18:43:06 INFO]: [BetterHud] Disabling BetterHud v2.2-b04\
[18:43:06 INFO]: [BetterHud] Plugin was successfully disabled! Version: 2.2-b04\
[18:43:06 INFO]: [ScreenEffects] Enabling ScreenEffects v1.0.7\
[18:43:06 INFO]: [ScreenEffects]     Extracting default effects from .jar\
[18:43:06 INFO]: [ScreenEffects]       DONE extracting default effects from .jar}
```

### ItemsAdder config.yml

```shell
IA config: I have changed nothing from the default config yet
```

### Problematic items yml configuration file (optional)

```shell
IA items: I have added nothing as of yet
```

**Comment by LoneDev6** [comment] 2022-01-04 14:41
Try to redownload the plugin.
It seems corrupted.
> \cf3 java.lang.NoClassDefFoundError: Could not initialize class dev.lone.itemsadder.main.az\cf2

**Comment by LoneDev6** [comment] 2022-01-04 16:12
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/1381

**Closed by LoneDev6** 2022-01-04 16:12 UTC
Labels: bug, Waiting answer

**Comment by BookWyrm114** [comment] 2022-01-04 16:58
Upon redownloading IA the bug still occurs
