### ISSUE TITLE
Apply resource pack - Black screen - only goes away on death

### ISSUE THREAD

**Issue by Sjd6795** [PluginBugs/Issues-ItemsAdder#2512] opened 2023-04-08 06:11 UTC
### What happened?

When I first launch into my server the black screen with applying resource pack stays for a very long time. It finally goes away but the black screen remains. To be able to get rid of it I have to use /kill command. I am using battlepass and battlepass ui

### Steps to reproduce the issue

Launch Server
Resource pack starts loading
black screen never goes away until death and respawn.

### Server version

This server is running Paper version git-Paper-499 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 29b17a8)

### ItemsAdder Version

ItemsAdder version 3.4.1-r5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b631

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

```
[22:50:02] [Server thread/WARN]: [ItemsAdder] Task #233 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
	at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-499]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:50:02] [Server thread/WARN]: [ItemsAdder] Task #236 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
	at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
```

### Error (optional)

```shell
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:51:30] [Server thread/ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.4.1-r5
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
	at ia.nms.aF.impl.v1_19_R3.a(SourceFile:205) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.nms.aF.aK.a(SourceFile:55) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.iJ.cB(SourceFile:111) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.iI.ak(SourceFile:184) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.iA.a(SourceFile:175) ~[ItemsAdder_3.4.1-r5.jar:?]
```

**Comment by LoneDev6** [comment] 2023-04-17 13:18
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2498

**Closed by LoneDev6** 2023-04-17 13:18 UTC
Labels: type: bug
