### ISSUE TITLE
Warn from console

### ISSUE THREAD

**Issue by egebege231** [PluginBugs/Issues-ItemsAdder#3418] opened 2024-02-09 12:52 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

egebege231

### Describe the solution you'd like

[12:50:01 INFO]: ItemsAdder 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.6.3-beta-9
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.45
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Pufferfish git-Pufferfish-72 (MC: 1.18.2)
                                               
[12:50:01 INFO]: ItemsAdder Registered Citizens NPC Trait: customentity
[12:50:01 INFO]: ItemsAdder Registered Skript API
[12:50:01 WARN]: ItemsAdder (Liquids disabled. If you want to use liquids enable them in config.yml please)
[12:50:01 WARN]: [ItemsAdder] "ItemsAdder v3.6.3-beta-9" has registered a listener for com.destroystokyo.paper.event.inventory.PrepareGrindstoneEvent on method "private void ia.m.gt.a(com.destroystokyo.paper.event.inventory.PrepareGrindstoneEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [LoneDev]. 

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

-w

### Additional context

Idk what is that

**Comment by LoneDev6** [comment] 2024-02-20 13:58
Please use the search button.
Duplicate of: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2453#issuecomment-1484883049

**Closed by LoneDev6** 2024-02-20 13:58 UTC
Labels: type: feature request
