### ISSUE TITLE
ItemsAdder 4.0.2-alpha-test-3 API Issue

### ISSUE THREAD

**Issue by Jsinco** [PluginBugs/Issues-ItemsAdder#3844] opened 2024-07-30 23:26 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

jsinco#0

### What happened?

Unable to get Bukkit ItemStack from ItemsAdder 'CustomStack' in MC 1.21.

### Steps to reproduce the issue

Attempt to obtain an ItemStack from a CustomStack using the ItemsAdder API and insert the item into a world somehow through a GUI, dropping it, or adding to a players inventory.

### Server version

Current Purpur Version: 1.21-2276-72ccfbd (MC: 1.21)*
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21-2257-cb0f04b (MC: 1.21)

### ItemsAdder Version

[19:24:45 INFO]: ItemsAdder version 4.0.2-alpha-test-3
[19:24:45 INFO]: Customized Minecraft without client mods!
[19:24:45 INFO]: Website: devs.beer
[19:24:45 INFO]: Author: LoneDev

### ProtocolLib Version

[19:24:59 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-726
[19:24:59 INFO]: Provides read/write access to the Minecraft protocol.
[19:24:59 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[19:25:08 INFO]: LoneLibs version 1.0.56
[19:25:08 INFO]: Collection of libs used by my plugins
[19:25:08 INFO]: Authors: LoneDev and others

### Error (optional)

```shell
[18:51:34] [Server thread/ERROR]: Could not pass event InventoryClickEvent to LumaUtilities v1.0.0
java.lang.ClassCastException: Cannot cast ia.m.eH to org.bukkit.craftbukkit.inventory.CraftItemStack
	at java.base/java.lang.Class.cast(Class.java:4067) ~[?:?]
	at org.bukkit.craftbukkit.inventory.CraftItemStack.getCraftStack(CraftItemStack.java:46) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:97) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at LumaUtilities.jar/dev.jsinco.lumautilities.guis.PaginatedGui.<init>(PaginatedGui.kt:49) ~[LumaUtilities.jar:?]
	at LumaUtilities.jar/dev.jsinco.lumautilities.features.furniture.FurnitureSectionGui.<init>(FurnitureSectionGui.kt:46) ~[LumaUtilities.jar:?]
	at LumaUtilities.jar/dev.jsinco.lumautilities.features.furniture.FurnitureStore.openFurniturePack(FurnitureStore.kt:60) ~[LumaUtilities.jar:?]
	at LumaUtilities.jar/dev.jsinco.lumautilities.features.furniture.FurnitureStore.handleClickEvent(FurnitureStore.kt:98) ~[LumaUtilities.jar:?]
	at LumaUtilities.jar/dev.jsinco.lumautilities.guis.GuiListeners.onInvClick(GuiListeners.kt:13) ~[LumaUtilities.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1120.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2276-72ccfbd]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3204) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Andre601** [comment] 2024-07-30 23:48
Duplicate of #3825 

**Always check the issue tracker first before making a new issue**

**Closed by Andre601** 2024-07-30 23:48 UTC
Labels: type: bug
