### ISSUE TITLE
Failed to encode packet 'clientbound/minecraft:update_attributes

### ISSUE THREAD

**Issue by WhiteProject1** [PluginBugs/Issues-ItemsAdder#3716] opened 2024-06-10 16:31 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

batuhan____

### What happened?

crashed server

### Steps to reproduce the issue

I deleted and installed all plugins and when I delete itemsadder the problem is fixed

### Server version

1.20.6 paper

### ItemsAdder Version

4.0.1-alpha-test-3

### ProtocolLib Version

5.3.0-SNAPSHOT-713

### LoneLibs Version

1.0.54

### Error (optional)

```shell
[19:18:19] [Netty Server IO #2/ERROR]: Error sending packet clientbound/minecraft:update_attributes (skippable? false)
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:update_attributes'
	at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
	at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:20) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:26) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection$2.write(Connection.java:758) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at AxQuestBoard-1.4.2.jar/com.artillexstudios.axquestboard.libs.axapi.nms.v1_20_R4.packet.PacketListener.write(PacketListener.java:291) ~[AxQuestBoard-1.4.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at AxVaults-1.5.1.jar/com.artillexstudios.axvaults.libs.axapi.nms.v1_20_R4.packet.PacketListener.write(PacketListener.java:291) ~[AxVaults-1.5.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at AxTrade-1.4.0.jar/com.artillexstudios.axtrade.libs.axapi.nms.v1_20_R4.packet.PacketListener.write(PacketListener.java:291) ~[AxTrade-1.4.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at AxCalendar-1.7.0.jar/com.artillexstudios.axcalendar.libs.axapi.nms.v1_20_R4.packet.PacketListener.write(PacketListener.java:272) ~[AxCalendar-1.7.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at AxAuctions-1.9.2.jar/com.artillexstudios.axauctions.libs.axapi.nms.v1_20_R4.packet.PacketListener.write(PacketListener.java:291) ~[AxAuctions-1.9.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at TAB v4.1.5.jar/me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:115) ~[TAB v4.1.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at ProtocolLib (14).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210) ~[ProtocolLib (14).jar:?]
	at ProtocolLib (14).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199) ~[ProtocolLib (14).jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:504) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
	at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:489) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
	at ProtocolLib (14).jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib (14).jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095) ~[?:?]
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049) ~[?:?]
	at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:412) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
	at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:395) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
	at net.minecraft.network.codec.StreamCodec$8.encode(StreamCodec.java:141) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
	at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:88) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
	at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:78) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
	... 75 more
[19:18:19] [Server thread/INFO]: SGabby lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:update_attributes'
[19:18:20] [Server thread/INFO]: SGabby left the game
```

**Comment by Andre601** [comment] 2024-06-10 16:40
Duplicate of #3708
Please check the issues next time.

**Closed** 2024-06-10 16:40 UTC
Labels: type: bug

**Comment by WhiteProject1** [comment] 2024-06-10 17:00
I have last version Protocollib

**Comment by WhiteProject1** [comment] 2024-06-10 17:29
fixed

**Comment by WhiteProject1** [comment] 2024-06-10 17:47
not fixed still have same problem

**Comment by WhiteProject1** [comment] 2024-06-11 12:26
[15:25:37 ERROR]: Could not pass event PlayerItemHeldEvent to ItemsAdder v4.0.1-
alpha-test-3
java.lang.NullPointerException: Cannot invoke "lonelibs.dev.lone.fastnbt.nms.nbt
.NCompound.setString(String, String)" because the return value of "lonelibs.dev.
lone.fastnbt.nms.nbt.NItem.getCompound(String)" is null
        at ItemsAdder_4.0.1-alpha-test-3.jar/ia.m.kK.a(SourceFile:69) ~[ItemsAdd
er_4.0.1-alpha-test-3.jar:?]
        at ItemsAdder_4.0.1-alpha-test-3.jar/ia.m.kK.a(SourceFile:205) ~[ItemsAd
der_4.0.1-alpha-test-3.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.exec
ute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:7
7) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2219-b1464f3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEven
tManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(Pape
rPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:627) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCa
rriedItem(ServerGamePacketListenerImpl.java:2196) ~[purpur-1.20.6.jar:1.20.6-221
9-b1464f3]
        at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.h
andle(ServerboundSetCarriedItemPacket.java:33) ~[purpur-1.20.6.jar:1.20.6-2219-b
1464f3]
        at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.h
andle(ServerboundSetCarriedItemPacket.java:15) ~[purpur-1.20.6.jar:1.20.6-2219-b
1464f3]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSame
Thread$0(PacketUtils.java:55) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.j
ar:1.20.6-2219-b1464f3]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEvent
Loop.java:151) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(Reent
rantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1
546) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1
95) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventL
oop.java:125) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer
.java:1523) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:14
46) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEv
entLoop.java:135) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServe
r.java:1412) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1
273) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.ja
va:326) ~[purpur-1.20.6.jar:1.20.6-2219-b1464f3]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
>
