### ISSUE TITLE
ResourcePack problem

### ISSUE THREAD

**Issue by OrsoSgravato34** [PluginBugs/Issues-ItemsAdder#3834] opened 2024-07-28 15:49 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

orso_34

### What happened?

After i put the ip and port for the self-host texture and /iazip the console launched this error saying that the resource pack couldn't be enabled or something like that

### Steps to reproduce the issue

Go to config.yml of itemsadder
on self-host replace false with true and then replace the ip and port with your ip and port
use /iazip

### Server version

[17:34:17 INFO]: Checking version, please wait...
[17:34:18 INFO]: This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)
You are running the latest version
Previous version: git-Paper-1620 (MC: 1.12.2)

### ItemsAdder Version

[17:38:01 INFO]: ItemsAdder version 3.6.4-release-3
[17:38:01 INFO]: Customized Minecraft without client mods!
[17:38:01 INFO]: Website: devs.beer
[17:38:01 INFO]: Author: LoneDev

### ProtocolLib Version

[17:46:50 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[17:46:50 INFO]: Provides read/write access to the Minecraft protocol.
[17:46:50 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[17:47:06 INFO]: LoneLibs version 1.0.56
[17:47:06 INFO]: Collection of libs used by my plugins
[17:47:06 INFO]: Authors: LoneDev and others

### Full server log

https://mclo.gs/vTs9Z9x

### Error (optional)

```shell
[ItemsAdder] Failed to calculate resourcepack hash form remote URL http://49.12.168.17:42494/generated.zip#d3d7941159cc827499349bd806ea83bd9f04f0e6.
[17:32:16 WARN]: java.net.SocketTimeoutException: Connect timed out
[17:32:16 WARN]: at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
[17:32:16 WARN]: at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
[17:32:16 WARN]: at java.base/java.net.Socket.connect(Socket.java:633)
[17:32:16 WARN]: at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[17:32:16 WARN]: at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
[17:32:16 WARN]: at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
[17:32:16 WARN]: at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:281)
[17:32:16 WARN]: at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
[17:32:16 WARN]: at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
[17:32:16 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1308)
[17:32:16 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1241)
[17:32:16 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1127)
[17:32:16 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1056)
[17:32:16 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1686)
[17:32:16 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1610)
[17:32:16 WARN]: at ItemsAdder_3.6.4-release-3.jar//ia.m.qF.t(SourceFile:484)
[17:32:16 WARN]: at ItemsAdder_3.6.4-release-3.jar//ia.m.qF.bA(SourceFile:310)
[17:32:16 WARN]: at ItemsAdder_3.6.4-release-3.jar//ia.m.qF.cU(SourceFile:290)
[17:32:16 WARN]: at ItemsAdder_3.6.4-release-3.jar//ia.m.G.a(SourceFile:912)
[17:32:16 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:32:16 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:32:16 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:32:16 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:32:16 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:32:16 WARN]: at java.base/java.lang.Thread.run(Thread.java:840)
[17:32:16 INFO]: [ItemsAdder] [Init] Loaded 1 categories
[17:32:16 INFO]: [ItemsAdder] [Init] Loaded successfully in 15137ms
[17:32:16 INFO]: [ItemsAdder]
[17:32:16 INFO]: [ItemsAdder]
[17:32:16 INFO]: [ItemsAdder] [Pack] Started generation
[17:32:16 INFO]: [PlaceholderAPI] Successfully registered internal expansion: img [1.0.1]
[17:32:16 INFO]: [PlaceholderAPI] Successfully registered internal expansion: iaplayerstat [1.0.1]
[17:32:16 INFO]: [ItemsAdder]
[17:32:16 INFO]: [ItemsAdder] [Pack] Generated resourcepack
[17:32:17 INFO]: [ItemsAdder] [OK] Your zip file will be protected from unzip (as set in config.yml)
[17:32:17 INFO]: [ItemsAdder] [Pack] Compressing resource_pack ...
[17:32:17 INFO]: [ItemsAdder]
[17:32:17 INFO]: [ItemsAdder]
[17:32:17 INFO]: [ItemsAdder] [Pack] Saved into /container/plugins/ItemsAdder/output/generated.zip
[ItemsAdder] Failed to calculate resourcepack hash form remote URL http://49.12.168.17:42494/generated.zip#7b54d517285a9bb13c7e970abd4c533e58e6d243.
[17:32:32 WARN]: java.net.SocketTimeoutException: Connect timed out
[17:32:32 WARN]: at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
[17:32:32 WARN]: at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
[17:32:32 WARN]: at java.base/java.net.Socket.connect(Socket.java:633)
[17:32:32 WARN]: at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[17:32:32 WARN]: at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
[17:32:32 WARN]: at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
[17:32:32 WARN]: at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:281)
[17:32:32 WARN]: at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
[17:32:32 WARN]: at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
[17:32:32 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1308)
[17:32:32 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1241)
[17:32:32 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1127)
[17:32:32 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1056)
[17:32:32 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1686)
[17:32:32 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1610)
[17:32:32 WARN]: at ItemsAdder_3.6.4-release-3.jar//ia.m.qF.t(SourceFile:484)
[17:32:32 WARN]: at ItemsAdder_3.6.4-release-3.jar//ia.m.qF.bA(SourceFile:310)
[17:32:32 WARN]: at ItemsAdder_3.6.4-release-3.jar//ia.m.qF.cU(SourceFile:290)
[17:32:32 WARN]: at ItemsAdder_3.6.4-release-3.jar//ia.m.G.a(SourceFile:1208)
[17:32:32 WARN]: at ItemsAdder_3.6.4-release-3.jar//ia.m.qd.a(SourceFile:471)
[17:32:32 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:32:32 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:32:32 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:32:32 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:32:32 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:32:32 WARN]: at java.base/java.lang.Thread.run(Thread.java:840)
[17:32:32 INFO]: [ItemsAdder] [Pack] Compressed in 15200ms
[17:32:32 INFO]: [ItemsAdder] [Pack] Applying to every player...
[17:32:32 WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.4-release-3 generated an exception while executing task 10062
java.lang.NullPointerException: Cannot invoke "String.length()" because "hash" is null
at net.minecraft.network.protocol.game.ClientboundResourcePackPacket.<init>(ClientboundResourcePackPacket.java:20) ~[app:?]
at net.minecraft.server.level.ServerPlayer.sendTexturePack(ServerPlayer.java:1916) ~[app:?]
at ia.m.mj.a(SourceFile:23) ~[ItemsAdder_3.6.4-release-3.jar:?]
at ia.m.mi.a(SourceFile:40) ~[ItemsAdder_3.6.4-release-3.jar:?]
at ia.m.qF.ax(SourceFile:186) ~[ItemsAdder_3.6.4-release-3.jar:?]
at ia.m.qO.av(SourceFile:67) ~[ItemsAdder_3.6.4-release-3.jar:?]
at ia.m.qF.aa(SourceFile:136) ~[ItemsAdder_3.6.4-release-3.jar:?]
at ia.m.it.b(SourceFile:182) ~[ItemsAdder_3.6.4-release-3.jar:?]
at ia.m.it.b(SourceFile:104) ~[ItemsAdder_3.6.4-release-3.jar:?]
at ia.m.G.a(SourceFile:1211) ~[ItemsAdder_3.6.4-release-3.jar:?]
at ia.m.qd.a(SourceFile:471) ~[ItemsAdder_3.6.4-release-3.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-411]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-411]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by Andre601** [comment] 2024-07-28 15:54
This error appears when ItemsAdder can't connect to the url/IP.
Check that the IP + port actually works. Easiest way is to copy the URL (`http://<ip>:<port>/generated.zip`) and connect to it in your browser while IA is running. If it doesn't result in the Zip being downloaded, is the port not open.

**Comment by OrsoSgravato34** [comment] 2024-07-28 16:18
And how do i open the port? Since i can't use the primary one

**Comment by Andre601** [comment] 2024-07-28 16:27
Just to make things clear here: The port you use for the resource pack is **not** the same as the port you use for your MC server.

And if you use a server host, should you look if they have any info on this. Hosts such as PebbleHost offer the option to open ports to use, but this is something you would need to check yourself.

**Comment by OrsoSgravato34** [comment] 2024-07-28 16:29
The port seems working but the problem still arrive

**Comment by Andre601** [comment] 2024-07-28 16:37
Then it may be an issue with a firewall perhaps.

But either way is this effectively a duplicate of #3831 so I'm closing it. Forward any further info to that issue please.

**Closed by Andre601** 2024-07-28 16:37 UTC
Labels: type: bug
