### ISSUE TITLE
improvements in the cultivation system

### ISSUE THREAD

**Issue by RitsuElAnti** [PluginBugs/Issues-ItemsAdder#3570] opened 2024-04-22 18:43 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Ritsu#9014

### Describe the solution you'd like

I would like that in addition to being able to put a custom texture on the crop (I know you have mentioned this is difficult), I would also like that when breaking a certain percentage it would spawn an entity (example: mole)

### Is your feature request related to a problem?

none

### Describe alternatives you've considered

I don't have any ideas, but I came across "litefarm" on spigot and it made me want to see the texture customization on itemsadder.

### Additional context

These are ideas and simple suggestions to see itemsadder grow

**Comment by LoneDev6** [comment] 2024-04-23 09:34
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/554

**Closed by LoneDev6** 2024-04-23 09:34 UTC
Labels: type: feature request
