### ISSUE TITLE
ia recipe bug and some bug

### ISSUE THREAD

**Issue by p82183645** [PluginBugs/Issues-ItemsAdder#2123] opened 2022-11-23 05:07 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

1.
ia recipe bug ,Many items filled with recipes will become like this
![image](https://user-images.githubusercontent.com/5382252/203472556-574317cc-b82d-4cd9-bd88-fae46b181ce6.png)

2.  keep show on bar , can't close 
![image](https://user-images.githubusercontent.com/5382252/203472779-1ce16397-3304-48d1-a7af-4393d2574000.png)

3.  After updating the latest version of IA  , this no work on new version
![image](https://user-images.githubusercontent.com/5382252/203472829-f8adfe61-b10a-4138-ae8a-9fd8369da44c.png)

### Steps to reproduce the issue

Synthesize according to the picture

### Server version

![image](https://user-images.githubusercontent.com/5382252/203475053-13ab02b8-aa0d-40e5-8726-bc46cca412ea.png)

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/5382252/203472656-b18c1851-93d0-4180-b671-0ba3272500cd.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/5382252/203475053-13ab02b8-aa0d-40e5-8726-bc46cca412ea.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/5382252/203472680-3e6dafe4-ea1a-45d7-9cb7-69f1a3d0bb6f.png)

**Comment by g2213swo** [comment] 2022-11-23 07:55
I also have IA recipe issue and the console outputs errors when players crafting items.
I only have this issue when I use the latest version (ItemsAdder 3.3.0-beta-r5 purpur 1.19.2).
```
[12:48:03 ERROR]: Could not pass event PrepareItemCraftEvent to ItemsAdder v3.3.0-beta-r5
java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
        at dev.lone.itemsadder.main.fv.a(SourceFile:214) ~[ItemsAdder_3.3.0-beta-r5.jar:?]
        at dev.lone.itemsadder.main.fv.a(SourceFile:185) ~[ItemsAdder_3.3.0-beta-r5.jar:?]
        at dev.lone.itemsadder.main.fx.a(SourceFile:185) ~[ItemsAdder_3.3.0-beta-r5.jar:?]
        at dev.lone.itemsadder.main.fx.a(SourceFile:247) ~[ItemsAdder_3.3.0-beta-r5.jar:?]
        at dev.lone.itemsadder.main.fx.a(SourceFile:214) ~[ItemsAdder_3.3.0-beta-r5.jar:?]
        at dev.lone.itemsadder.main.fx.a(SourceFile:298) ~[ItemsAdder_3.3.0-beta-r5.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1835]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1392) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.world.inventory.CraftingMenu.slotChangedCraftingGrid(CraftingMenu.java:87) ~[?:?]
        at net.minecraft.world.inventory.InventoryMenu.slotsChanged(InventoryMenu.java:150) ~[?:?]
        at net.minecraft.world.inventory.CraftingContainer.removeItem(CraftingContainer.java:132) ~[?:?]
        at net.minecraft.world.inventory.ResultSlot.onTake(ResultSlot.java:67) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.lambda$doClick$3(AbstractContainerMenu.java:564) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:562) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:381) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3410) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by patatoplugin** [comment] 2022-11-23 08:19
add a information about the recipe bug.When two item use same ingredients to craft(for example,emearld helmet and emerald boots both use emerald),the recipe will mess up

**Comment by LoneDev6** [comment] 2022-11-23 11:14
I need your recipe and custom items configuration or I cannot trigger the issue and fix it.

**Comment by g2213swo** [comment] 2022-11-23 11:43
As shown in the picture, I wanted to make an IRONAXE, but what it returned was a chisel
![bug1](https://user-images.githubusercontent.com/93109410/203536357-3504f750-8c8a-42bc-acda-732e4a841d48.png)
The following is the configuration file of the chisel:
```
info:
  namespace: iasurvival
items:
  chisel:
    enabled: true
    display_name: display-name-chisel
    permission: iasurvival.items.chisel
    resource:
      material: WOODEN_SWORD
      generate: true
      textures:
        - item/tools/chisel
    durability:
      max_custom_durability: 32
    attribute_modifiers:
      mainhand:
        attackDamage: 1
        attackSpeed: 5
```
Then the following is the recipe configuration file of the chisel:
```
info:
  namespace: iasurvival
recipes:
  crafting_table:
    chisel:
      permission: iasurvival.chisel
      enabled: true
      pattern:
        - XXX
        - XXI
        - XSX
      ingredients:
        I: IRON_INGOT
        S: STICK
      result:
        item: iasurvival:chisel
        amount: 1

```
And it's not just this case...

**Comment by LoneDev6** [comment] 2022-11-23 14:07
Found the issue cause, will be fixed

**Comment by LoneDev6** [comment] 2022-11-23 14:08
About the other bugs, please report them as separate github issues, do not use the same page.

**Comment by LoneDev6** [comment] 2022-11-23 14:20
Anyway most of the lag is caused by CustomCrops plugin not by ItemsAdder.
Ask them to optimize the code, `getType` is using a lot of CPU.
![image](https://user-images.githubusercontent.com/27242001/203569764-e8383f6f-ce2b-4976-96d6-0bb083c48b9f.png)


ItemsAdder itself is not using a lot of CPU.
![image](https://user-images.githubusercontent.com/27242001/203569844-4ee3e3e5-7377-4d2f-a9fd-05b53c5313e7.png)

**Comment by p82183645** [comment] 2022-11-23 15:50
> About the other bugs, please report them as separate github issues, do not use the same page.

You can see that you can fix it by the way
It's tiring to open a few new ones ..

**Comment by Akiranya** [comment] 2022-11-27 08:30
> > About the other bugs, please report them as separate github issues, do not use the same page.
> 
> You can see that you can fix it by the way It's tiring to open a few new ones ..

I wanted to add some points to what LoneDev said. I am also a developer and it's just easier to organise things and track them and get them done if you report different issues seperately. At least it's how the github issues work, and every developer thinks that's the right way to report bugs. Most importantly LoneDev is the only developer who can actually fix bugs of IA, and the size of project and community of IA isn't small at all, which is why, again, it's really important to follow the rules

**Closed** 2022-11-28 11:28 UTC
Labels: Bug, HIGH PRIORITY
