### ISSUE TITLE
Could not pass event ProjectileLaunchEvent to ItemsAdder v4.0.1-alpha-test-5

### ISSUE THREAD

**Issue by SamaraGamer** [PluginBugs/Issues-ItemsAdder#3788] opened 2024-07-08 20:57 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

SamaraGamer#8285

### What happened?

I get spam in console when throwing a custom exp bottle even though the command still executes

### Steps to reproduce the issue

1. Create custom exp bottle
2. Assign an execute_command action on item_throw event to give exact exp levels
3. Throw this custom exp bottle

### Server version

This server is running Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.1-alpha-test-5

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-723

### LoneLibs Version

LoneLibs version 1.0.55

### Error (optional)

```shell
[20:20:30] [Server thread/ERROR]: Could not pass event ProjectileLaunchEvent to ItemsAdder v4.0.1-alpha-test-5
org.bukkit.command.CommandException: Unhandled exception executing 'minecraft:experience add SamaraGamerPS 15 levels' in org.bukkit.craftbukkit.command.VanillaCommandWrapper(minecraft:experience)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:175) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:986) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1099) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar/ia.m.jm.g(SourceFile:130) ~[ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar:?]
	at ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar/ia.m.dy.a(SourceFile:152) ~[ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar:?]
	at ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar/ia.m.dx.a(SourceFile:52) ~[ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar:?]
	at ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar/ia.m.dZ.a(SourceFile:115) ~[ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar:?]
	at ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar/ia.m.ew.b(SourceFile:50) ~[ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar:?]
	at ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar/ia.m.dd.a(SourceFile:974) ~[ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar:?]
	at ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar/ia.m.eH.b(SourceFile:571) ~[ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar:?]
	at ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar/ia.m.mI.d(SourceFile:110) ~[ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar:?]
	at ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar/ia.m.eH.a(SourceFile:570) ~[ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar:?]
	at ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar/ia.m.ew.b(SourceFile:49) ~[ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar:?]
	at ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar/ia.m.di.a(SourceFile:174) ~[ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar:?]
	at ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar/ia.m.di.b(SourceFile:395) ~[ItemsAdder_4.0.1-alpha-test-5-1720461253969.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-148-20f5165]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1467) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at org.bukkit.craftbukkit.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:698) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1705) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1627) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1622) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.item.ExperienceBottleItem.use(ExperienceBottleItem.java:30) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.item.ItemStack.use(ItemStack.java:598) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:483) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2016) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:39) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.AbstractMethodError: Receiver class ia.m.jn does not define or inherit an implementation of the resolved method 'abstract boolean acceptsSuccess()' of interface net.minecraft.commands.CommandSource.
	at net.minecraft.commands.CommandSourceStack.sendSuccess(CommandSourceStack.java:314) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.commands.ExperienceCommand.addExperience(ExperienceCommand.java:147) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.commands.ExperienceCommand.lambda$register$3(ExperienceCommand.java:58) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:332) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at org.bukkit.craftbukkit.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:55) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	... 45 more
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: exp
items:
  15_lvl:
    enabled: true
    display_name: "&eПузырёк опыта &a[15 ур.]"
    resource:
      material: EXPERIENCE_BOTTLE
      generate: true
      textures: 
      - item/15_lvl/15_lvl.png
    events:
      item_throw:
        execute_commands:
          cmd1:
            command: 'minecraft:experience add {player} 15 levels'
            as_console: true
            delay: 0
```

**Comment by Andre601** [comment] 2024-07-08 21:00
Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.

**Comment by SamaraGamer** [comment] 2024-07-08 21:04
> Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/42216755/702b7268-26df-4b4f-aafa-12d78ec33c6a)

**Comment by Andre601** [comment] 2024-07-08 21:05
Then use a different paste site.

**Comment by SamaraGamer** [comment] 2024-07-08 21:08
https://logpaste.com/Tqim9sgd

**Comment by Andre601** [comment] 2024-07-08 21:10
Thanks. We'll look into this. Your patience is apreciated.

**Comment by LoneDev6** [comment] 2024-08-29 12:57
Duplicate of #3869

**Closed by LoneDev6** 2024-08-29 12:57 UTC
Labels: type: duplicate
