### ISSUE TITLE
ERROR IN CONSOLE

### ISSUE THREAD

**Issue by maxextreme1** [PluginBugs/Issues-ItemsAdder#3348] opened 2024-01-17 18:01 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

maxy#6614

### What happened?

17.01 18:43:45 [Server] ERROR [ItemsAdder] Unhandled exception number 32 occurred in onPacketSending(PacketEvent) for ItemsAdder
I resterted server and this appears as error. And when  i add some texturepack "Betterranks" it dosnt load for some players.
Can you please help me fix this 

### Steps to reproduce the issue

1. Restarting a server
2. Joining server

### Server version

Current: git-Purpur-1985 (MC: 1.19.4)*

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-8

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

 LoneLibs version 1.0.45

### FULL server log

a

### Error (optional)

```shell
17.01 18:43:45 [Server] ERROR [ItemsAdder] Unhandled exception number 32 occurred in onPacketSending(PacketEvent) for ItemsAdder
17.01 18:43:45 [Server] INFO java.lang.UnsupportedOperationException: java.lang.ClassCastException: Cannot cast net.kyori.adventure.text.TextComponentImpl to net.minecraft.network.chat.IChatBaseComponent
17.01 18:43:45 [Server] INFO at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializerPatched.deserialize(MinecraftComponentSerializerPatched.java:206) ~[LoneLibs.jar:?]
17.01 18:43:45 [Server] INFO at dev.lone.LoneLibs.chat.Comp.nmsToComponent(Comp.java:188) ~[LoneLibs.jar:?]
17.01 18:43:45 [Server] INFO at ia.m.hE.a(SourceFile:24) ~[ItemsAdder_3.6.3-beta-8.jar:?]
17.01 18:43:45 [Server] INFO at ia.m.hC.i(SourceFile:124) ~[ItemsAdder_3.6.3-beta-8.jar:?]
17.01 18:43:45 [Server] INFO at ia.m.hv.onPacketSending(SourceFile:99) ~[ItemsAdder_3.6.3-beta-8.jar:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:565) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:468) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at net.minecraft.network.Connection.sendPacket(Connection.java:442) ~[?:?]
17.01 18:43:45 [Server] INFO at net.minecraft.network.Connection.send(Connection.java:385) ~[?:?]
17.01 18:43:45 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2252) ~[?:?]
17.01 18:43:45 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2238) ~[?:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:288) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$processOutbound$6(NettyChannelInjector.java:559) ~[ProtocolLib.jar:?]
17.01 18:43:45 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
17.01 18:43:45 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1985]
17.01 18:43:45 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1985]
17.01 18:43:45 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]
```

### Problematic items yml configuration file (optional)

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
ignore-server-compatibility-check: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    lobfile:
      enabled: true
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  1_19_3_atlas_support: true
  fix_force_unicode_font_images: true
  expert_users:
    allow_other_plugins_resourcepacks: false
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: true
    contents-folders-priority:
    - vanilla
    - _iainternal
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  custom_blocks_sounds_patch:
    enabled: true
    step:
      enabled: true
      allow_non_player: true
    other: true
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire_enhancements:
    enable: true
    unlit_on_place: true
    allow_any_item: true
    drop_when_broken: false
  disable-REAL: false
  disable-REAL_NOTE: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  convert-legacy-ia-region-files: true
  remove-unused-palettes-on-region-save: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: true
  show_item_durability:
    in_ia_menu: true
    in_inventory: false
  handle-wear-held-actions-on-unexpected-inventory-changes: true
liquids:
  enabled: true
huds:
  enabled: true
  force_color:
    enabled: false
    color: '#FFFFFF'
  hide_if_pack_not_accepted: true
cooldown_bars:
  enabled: true
  refresh_ticks: 1
  bossbar:
    color: WHITE
    style: SOLID
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    add-hover-suggestion: true
    tab-autocompletion_1_19_1_plus: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
effects:
  hide-scoreboard-numbers: false
  hide-scoreboard-numbers-old-clients: false
  text-effects:
    enabled: true
    customitem-name-and-lore:
      enabled: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    expert_users:
      fast_packets_creation: true
      bundle_packets: false
      delay_packets: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: true
        ingredients: true
      on-item-click:
        any: true
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
player_stats:
  save_type: CUSTOM_NBT # CUSTOM_NBT, PLAYER_DAT
debug:
  benchmark: false
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

**Comment by maxextreme1** [comment] 2024-01-17 18:05
17.01 19:02:42 [Server] ERROR [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
17.01 19:02:42 [Server] INFO java.lang.UnsupportedOperationException: java.lang.ClassCastException: Cannot cast net.kyori.adventure.text.TextComponentImpl to net.minecraft.network.chat.IChatBaseComponent
17.01 19:02:42 [Server] INFO at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializerPatched.deserialize(MinecraftComponentSerializerPatched.java:206) ~[LoneLibs.jar:?]
17.01 19:02:42 [Server] INFO at dev.lone.LoneLibs.chat.Comp.nmsToComponent(Comp.java:188) ~[LoneLibs.jar:?]
17.01 19:02:42 [Server] INFO at ia.m.hE.a(SourceFile:24) ~[ItemsAdder_3.6.3-beta-8.jar:?]
17.01 19:02:42 [Server] INFO at ia.m.hC.i(SourceFile:124) ~[ItemsAdder_3.6.3-beta-8.jar:?]
17.01 19:02:42 [Server] INFO at ia.m.hv.onPacketSending(SourceFile:99) ~[ItemsAdder_3.6.3-beta-8.jar:?]
17.01 19:02:42 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
17.01 19:02:42 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
17.01 19:02:42 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
17.01 19:02:42 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
17.01 19:02:42 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib.jar:?]
17.01 19:02:42 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
17.01 19:02:42 [Server] INFO at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
17.01 19:02:42 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:565) ~[ProtocolLib.jar:?]
17.01 19:02:42 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:468) ~[ProtocolLib.jar:?]
17.01 19:02:42 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
17.01 19:02:42 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
17.01 19:02:42 [Server] INFO at net.minecraft.network.Connection.sendPacket(Connection.java:442) ~[?:?]
17.01 19:02:42 [Server] INFO at net.minecraft.network.Connection.send(Connection.java:385) ~[?:?]
17.01 19:02:42 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2252) ~[?:?]
17.01 19:02:42 [Server] INFO at net.minecraft.server.level.ServerPlayer.sendSystemMessage(ServerPlayer.java:1993) ~[?:?]
17.01 19:02:42 [Server] INFO at net.minecraft.server.level.ServerPlayer.sendSystemMessage(ServerPlayer.java:1988) ~[?:?]
17.01 19:02:42 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:337) ~[purpur-1.19.4.jar:git-Purpur-1985]
17.01 19:02:42 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:353) ~[purpur-1.19.4.jar:git-Purpur-1985]
17.01 19:02:42 [Server] INFO at com.earth2me.essentials.User.sendMessage(User.java:1051) ~[EssentialsX-2.21.0-dev+21-c68b277.jar:?]
17.01 19:02:42 [Server] INFO at com.earth2me.essentials.commands.Commandgamemode.run(Commandgamemode.java:65) ~[EssentialsX-2.21.0-dev+21-c68b277.jar:?]
17.01 19:02:42 [Server] INFO at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:170) ~[EssentialsX-2.21.0-dev+21-c68b277.jar:?]
17.01 19:02:42 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:820) ~[EssentialsX-2.21.0-dev+21-c68b277.jar:?]
17.01 19:02:46 [Multicraft] Skipped 25 lines due to rate limit (30/s)
17.01 19:02:46 [Server] INFO Caused by: java.lang.ClassCastException: Cannot cast net.kyori.adventure.text.TextComponentImpl to net.minecraft.network.chat.IChatBaseComponent
17.01 19:02:46 [Server] INFO at java.lang.Class.cast(Class.java:3889) ~[?:?]
17.01 19:02:46 [Server] INFO at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializerPatched.deserialize(MinecraftComponentSerializerPatched.java:198) ~[LoneLibs.jar:?]
17.01 19:02:46 [Server] INFO ... 51 more
17.01 19:02:46 [Server] ERROR Parameters: 
17.01 19:02:46 [Server] INFO net.minecraft.network.protocol.game.ClientboundSystemChatPacket@2163eece[
17.01 19:02:46 [Server] INFO content=<null>
17.01 19:02:46 [Server] INFO b=false
17.01 19:02:46 [Server] INFO ]
17.01 19:04:04 [Server] WARN java.net.ConnectException: Connection timed out
17.01 19:04:04 [Server] WARN at java.base/sun.nio.ch.Net.connect0(Native Method)
17.01 19:04:04 [Server] WARN at java.base/sun.nio.ch.Net.connect(Net.java:579)
17.01 19:04:04 [Server] WARN at java.base/sun.nio.ch.Net.connect(Net.java:568)
17.01 19:04:04 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
17.01 19:04:04 [Server] WARN at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
17.01 19:04:04 [Server] WARN at java.base/java.net.Socket.connect(Socket.java:633)
17.01 19:04:04 [Server] WARN at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
17.01 19:04:04 [Server] WARN at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
17.01 19:04:04 [Server] WARN at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
17.01 19:04:04 [Server] WARN at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
17.01 19:04:04 [Server] WARN at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
17.01 19:04:04 [Server] WARN at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
17.01 19:04:04 [Server] WARN at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
17.01 19:04:04 [Server] WARN at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
17.01 19:04:04 [Server] WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
17.01 19:04:04 [Server] WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
17.01 19:04:04 [Server] WARN at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
17.01 19:04:04 [Server] WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
17.01 19:04:04 [Server] WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
17.01 19:04:04 [Server] WARN at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
17.01 19:04:04 [Server] WARN at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
17.01 19:04:04 [Server] WARN at ItemsAdder_3.6.3-beta-8.jar//ia.m.qv.a(SourceFile:306)
17.01 19:04:04 [Server] WARN at ItemsAdder_3.6.3-beta-8.jar//ia.m.qx.a(SourceFile:177)
17.01 19:04:04 [Server] WARN at ItemsAdder_3.6.3-beta-8.jar//ia.m.rr.run(SourceFile:108)
17.01 19:04:04 [Server] WARN at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
17.01 19:04:04 [Server] WARN at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
17.01 19:04:04 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
17.01 19:04:04 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
17.01 19:04:04 [Server] WARN at 


I like to add this

**Comment by LoneDev6** [comment] 2024-01-17 21:06
Please answer on Discord, thanks!

**Comment by LoneDev6** [comment] 2024-01-17 21:08
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/3346

**Closed by LoneDev6** 2024-01-17 21:08 UTC
Labels: type: duplicate
