### ISSUE TITLE
Make weapon bullets insertable into the weapon itself

### ISSUE THREAD

**Issue by chimal1994** [PluginBugs/Issues-ItemsAdder#1443] opened 2022-01-21 11:45 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Make weapon bullets work by having them in your inventory.

### Is your feature request related to a problem?

It would free one hand to perform other actions, for example eating and shooting

### Describe alternatives you've considered

Another way to do it could be that we have to combine the bullets with the weapon (like placing the magazine)

**Comment by LoneDev6** [comment] 2023-02-28 14:41
A better solution would be to implement something to reload weapons by directly mixing weapon + ammo item, to avoid having to carry it in the offhand, since the game inventory is already very small.

**Comment by LoneDev6** [comment] 2023-04-07 15:39
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/1107

**Closed by LoneDev6** 2023-04-07 15:39 UTC
Labels: type: enhancement, type: feature request
