### ISSUE TITLE
Resource Pack Hash Error when Rezipping Pack

### ISSUE THREAD

**Issue by SuperEms** [PluginBugs/Issues-ItemsAdder#3483] opened 2024-03-10 20:49 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

emileve

### What happened?

Since updating to latest Itemsadder and 1.20.4 my server has been experiencing issues where when we rezip the pack using /iazip, we get a hash error and the pack will not reload. If the server is restarted, then the pack will reload without issue albeit a little slow. Worth noting that we have not changed anything on our panel. The only things that changed were updating to 1.20.4 and updating plugin versions. The pack-port is not shared with any other server.

We use self-host using a pterodactyl port on our panel. 
```resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: XX.XXX.XX.XXX (blocked out for privacy)
      pack-port: 9086
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false

### Steps to reproduce the issue

1. Start up the server with the versions listed
2. Wait for resource pack to apply
3. Issue a `/iazip` command
4. Error

### Server version

This server is running Paper version git-Paper-435 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 681bbff)
You are 15 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-281 (MC: 1.20.2)

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

5.2.0-SNAPSHOT-679

### FULL server log

[latest_4.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14551754/latest_4.log)


### Error (optional)

```shell
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/ERROR]: [ItemsAdder] Failed to calculate resourcepack hash form remote URL http://XX.XXX.XX.XXX:9086/generated.zip#72af10e60f38c97afe87903d5e62582e86317b58.
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: java.net.SocketTimeoutException: Connect timed out
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/java.net.Socket.connect(Socket.java:633)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:281)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at ItemsAdder.jar//ia.m.qG.t(SourceFile:484)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at ItemsAdder.jar//ia.m.qG.bA(SourceFile:310)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at ItemsAdder.jar//ia.m.qG.cU(SourceFile:290)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at ItemsAdder.jar//ia.m.G.a(SourceFile:923)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:42:31] [Craft Scheduler Thread - 9 - ItemsAdder/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://drive.google.com/file/d/1AZ2RXjuZD2yprb61JqooP1XIpZge64UI/view?usp=sharing

**Comment by BravikDim** [comment] 2024-03-26 07:41
same problem, waiting for an answer

**Comment by LoneDev6** [comment] 2024-04-04 14:23
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/3413

**Closed by LoneDev6** 2024-04-04 14:23 UTC
Labels: type: bug
