### ISSUE TITLE
Error message when deleting folders within "contents" folder and running /iazip right after

### ISSUE THREAD

**Issue by imparium-de** [PluginBugs/Issues-ItemsAdder#3301] opened 2024-01-06 01:17 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

derMiepz#5898

### What happened?

When ItemsAdder is running and you're deleting files or rather whole folders within the "contents" folder and running /iazip without restarting the server first, you get the error message below.

### Steps to reproduce the issue

1. Go to /ItemsAdder/contents/
2. Delete a folder/category e.g. iasurvival
3. Run /iazip
4. See error in console

### Server version

[02:15:22 INFO]: This server is running Paper version git-Paper-365 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 1281f4f)

### ItemsAdder Version

[02:15:11 INFO]: ItemsAdder version 3.6.3-beta-6

### ProtocolLib Version

[02:15:47 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

[02:15:58 INFO]: LoneLibs version 1.0.43

### Error (optional)

```shell
iazip
[02:08:40 INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[02:08:40 INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[02:08:40 ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[02:08:40 WARN]: java.util.ConcurrentModificationException
[02:08:40 WARN]:        at java.base/java.util.HashMap$HashIterator.remove(HashMap.java:1611)
[02:08:40 WARN]:        at ItemsAdder_3.6.3-beta-6.jar//ia.m.G.b(SourceFile:633)
[02:08:40 WARN]:        at ItemsAdder_3.6.3-beta-6.jar//ia.m.G.c(SourceFile:578)
[02:08:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[02:08:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[02:08:40 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1639)
[02:08:40 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[02:08:40 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1518)
[02:08:40 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1214)
[02:08:40 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[02:08:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by LoneDev6** [comment] 2024-01-07 20:02
Duplicate of #3302

**Closed by LoneDev6** 2024-01-07 20:02 UTC
Labels: type: bug
