### ISSUE TITLE
Durability doesn't show up and goes bellow zero

### ISSUE THREAD

**Issue by tinyhelus** [PluginBugs/Issues-ItemsAdder#3774] opened 2024-06-30 15:08 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I am trying to configure a custom armor to be as strong as a netherite one. But when i try to make it have the same durability as the netherite one it doesn't work, it shows the default leather durability.

### Steps to reproduce the issue

I can't give steps. The durability just doesn't work right.

### Server version

1.20.6-2233-0d6766e (MC: 1.20.6)

### ItemsAdder Version

4.0.1-alpha-test-5

### ProtocolLib Version

5.2.1-SNAPSHOT-689

### LoneLibs Version

1.0.55

### Full server log

https://mclo.gs/hlspn0b

### Error (optional)

```shell
No errors.
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: summerset
armors_rendering:
  summerarmor:
    color: "#d60000"
    layer_1: armor/summer_armor_layer_1
    layer_2: armor/summer_armor_layer_2
    use_color: false
items:
  summerhelmet:
    display_name: Summer Helmet
    permission: summer.helmet
    resource:
      generate: true
      textures:
      - armor/summer_helmet_icon.png
    durability:
      max_custom_durability: 275
    specific_properties:
      armor:
        slot: head
        custom_armor: summerarmor
    attribute_modifiers:
      head:
        armor: 9
        armorToughness: 1
        knockbackResistance: 1
  summerchestplate:
    display_name: Summer Chestplate
    permission: summerchest
    resource:
      generate: true
      textures:
      - armor/summer_chestplate_icon.png
    durability:
      max_custom_durability: 400
    specific_properties:
      armor:
        slot: chest
        custom_armor: summerarmor
    attribute_modifiers:
      chest:
        armor: 7
        armorToughness: 1
        knockbackResistance: 1
  summerleggings:
    display_name: Summer Leggings
    permission: summerleggings
    resource:
      generate: true
      textures:
      - armor/summer_leggings_icon.png
    durability:
      max_custom_durability: 375
    specific_properties:
      armor:
        slot: legs
        custom_armor: summerarmor
    attribute_modifiers:
      legs:
        armor: 5
        armorToughness: 1
        knockbackResistance: 1
  summerboots:
    display_name: Summer Boots
    permission: summerboots
    resource:
      generate: true
      textures:
      - armor/summer_boots_icon.png
    durability:
      max_custom_durability: 325
    specific_properties:
      armor:
        slot: feet
        custom_armor: summerarmor
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 1
        knockbackResistance: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/173596116/ce4485b4-b7f2-4ed6-b432-dc6e690acad7)

**Comment by LoneDev6** [comment] 2024-08-29 13:00
Can't reproduce it on:
- upcoming ItemsAdder version 4.0.2-alpha-test-8-pre-release-2
- Paper version 1.21.1-40-master@2fdb2e9

Might have been a bug of a previous server version or might have been fixed involuntarily on the recent ItemsAdder upcoming version.

![image](https://github.com/user-attachments/assets/57f707e7-a7a8-4583-9826-41402676fbcb)

**Closed** 2024-09-02 14:49 UTC
Labels: type: bug, verdict: can't reproduce
