### ISSUE TITLE
MythicMobs Compatibility

### ISSUE THREAD

**Issue by ignjatradojicic** [PluginBugs/Issues-ItemsAdder#4164] opened 2024-11-22 14:13 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

I know you dropped 1.20.4, and I know you have alot on your plate but please if you could release another legacy IA version until the newer versions are fully stable, we just need a fix for MythicMobs item drop event compatibility, some servers including mine are currently soft locked on 1.20.4 and will be for some time, I know why you made decision and I fully support it although my hands as a server owner are currently tied.  

### Steps to reproduce the issue

Run MythicMobs latest with 1.20.4

### Server version

git-Paper-499 1.20.4

### ItemsAdder Version

Items Adder 3.6.5

### ProtocolLib Version

ProtocolLib 5.2.0

### LoneLibs Version

LoneLibs 1.0.5.4

### Full Server Log

https://mclo.gs/PQVgj27

**Comment by umutardafiliz** [comment] 2024-11-23 16:02
this problem occurs also on latest itemsAdder. not only for 1.20.4 version. 4.0.4 ItemsAdder has this problem too

**Comment by LoneDev6** [comment] 2024-12-09 16:04
Duplicate of #4110

**Closed** 2024-12-09 16:05 UTC
Labels: type: duplicate
