### ISSUE TITLE
java.lang.IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by YstalX** [PluginBugs/Issues-ItemsAdder#3401] opened 2024-02-04 12:32 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

plugin not working

### Steps to reproduce the issue

idk

### ItemsAdder Version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-673

### LoneLibs Version

LoneLibs version 1.0.45

### Error (optional)

```shell
[12:23:49] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.6.3-beta-11
[12:23:49] [Server thread/WARN]: Enabled plugin with unregistered ConfiguredPluginClassLoader ItemsAdder v3.6.3-beta-11
[12:23:49] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.6.3-beta-11 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:832) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at ia.m.iS.a(SourceFile:170) ~[ItemsAdder_3.6.3-beta-11.jar:?]
	at ia.m.iS.a(SourceFile:105) ~[ItemsAdder_3.6.3-beta-11.jar:?]
	at ia.m.iS.a(SourceFile:42) ~[ItemsAdder_3.6.3-beta-11.jar:?]
	at ia.m.iS.b(SourceFile:36) ~[ItemsAdder_3.6.3-beta-11.jar:?]
	at ia.m.mt.<init>(SourceFile:35) ~[ItemsAdder_3.6.3-beta-11.jar:?]
	at ia.m.mt.init(SourceFile:51) ~[ItemsAdder_3.6.3-beta-11.jar:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile:219) ~[ItemsAdder_3.6.3-beta-11.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at com.rylinaux.plugman.util.BukkitPluginUtil.enable(BukkitPluginUtil.java:135) ~[PlugManX.jar:?]
	at com.rylinaux.plugman.util.PaperPluginUtil.enable(PaperPluginUtil.java:157) ~[PlugManX.jar:?]
	at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:130) ~[PlugManX.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.2.jar:git-Paper-318]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2208) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2168) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[12:23:49] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.6.3-beta-11
```

**Comment by YstalX** [comment] 2024-02-04 12:36
[ItemsAdder] Error: org.yaml.snakeyaml.error.YAMLException: Nesting Depth exceeded max 50
[12:35:24] [Server thread/ERROR]: [ItemsAdder] Error initializing plugin 'ItemsAdder_3.6.3-beta-11.jar' in folder 'plugins' (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.getString(String, String)" because "this.a" is null
	at ia.m.re.d(SourceFile:473) ~[ItemsAdder_3.6.3-beta-11.jar:?]
	at dev.lone.itemsadder.Main.bP(SourceFile:576) ~[ItemsAdder_3.6.3-beta-11.jar:?]
	at dev.lone.itemsadder.Main.onLoad(SourceFile:180) ~[ItemsAdder_3.6.3-beta-11.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by LoneDev6** [comment] 2024-02-05 11:27
- try to redownload the JAR from the official website, this happens when the jar is corrupted.
- do not reload the plugin using plugman or similar software
- open config.yml and remove the bugged lines:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/3e2d183d-ba92-46ad-9b82-314761f3021e)
- restart

**Comment by LoneDev6** [comment] 2024-02-05 11:27
Might be a duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/3390

**Closed by LoneDev6** 2024-02-05 11:27 UTC
Labels: type: bug
