### ISSUE TITLE
Custom Tree will generate above some unintended blocks and generate with vanilla tree

### ISSUE THREAD

**Issue by DarrienZ** [PluginBugs/Issues-ItemsAdder#2845] opened 2023-07-04 19:20 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

darrienz

### What happened?

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/6434c3cb-2a5c-447d-9269-969e1745d65c)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/57a00ab1-fe58-4f11-aa61-b03e344fd8be)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/cfc843af-8430-44b2-9c9e-fad516587374)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/8a6c4f68-670f-44dc-a4f5-c0cf2b2052b8)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/a0f646b2-9d3c-48a4-b945-10c7df470da1)

### Steps to reproduce the issue

Reported this issues before.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2841

### Server version

[03:17:48 INFO]: Checking version, please wait...
[03:17:48 INFO]: Current: git-Purpur-2006 (MC: 1.20.1)*
Previous: git-Purpur-2005 (MC: 1.20.1)
* You are running the latest version

### ItemsAdder Version

[03:18:31 INFO]: ItemsAdder version 3.5.0c-r2
[03:18:31 INFO]: Customized Minecraft without client mods!
[03:18:31 INFO]: Website: devs.beer
[03:18:31 INFO]: Author: LoneDev

### ProtocolLib Version

[03:18:41 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-654
[03:18:41 INFO]: Provides read/write access to the Minecraft protocol.
[03:18:41 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[03:18:48 INFO]: LoneLibs version 1.0.25
[03:18:48 INFO]: Collection of libs used by my plugins
[03:18:48 INFO]: Authors: LoneDev and others

### Error (optional)

```shell
No error
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: cubimod
items:
  sakura_log:
    display_name: Sakura Log
    resource:
      generate: true
      material: PAPER
      textures:
        - logs/sakura_log_down
        - logs/sakura_log_south
        - logs/sakura_log_east
        - logs/sakura_log_north
        - logs/sakura_log_up
        - logs/sakura_log_west
    specific_properties:
      block:
        placed_model:
          type: REAL
          break_particles: ITEM
        cancel_drop: true
        hardness: 2
        ignore_fortune: true 
        sound:
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 1
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 1
    events:
        placed_block:
          break:
            drop_item:
              item: sakura_log
    lore:
      - '&7Can be burnt into charcoal for fuel.'
      - '&aCook Time: &e6 seconds.'
  sakura_leaves:
    display_name: Sakura Leaves
    resource:
      generate: true
      material: PAPER
      textures:
        - logs/sakura_leaves
    specific_properties:
      block:
        placed_model:
          type: REAL_TRANSPARENT
          break_particles: ITEM
        cancel_drop: true
        hardness: 0.2
        sound:
          break:
            name: block.grass.break
            volume: 1
            pitch: 0.9
          place:
            name: block.grass.break
            volume: 1
            pitch: 0.9
  sakura_tree_sapling:
    display_name: Sakura Sapling
    resource:
      material: PAPER
      generate: true
      textures:
      - logs/sakura_sapling.png
    behaviours:
      sapling:
        tree_populator: sakura_tree
  wisteria_log:
    display_name: Wisteria Log
    resource:
      generate: true
      material: PAPER
      textures:
        - logs/wisteria_log_down
        - logs/wisteria_log_south
        - logs/wisteria_log_east
        - logs/wisteria_log_north
        - logs/wisteria_log_up
        - logs/wisteria_log_west
    specific_properties:
      block:
        placed_model:
          type: REAL
          break_particles: ITEM
        cancel_drop: true
        hardness: 2
        ignore_fortune: true 
        sound:
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 1
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 1
    events:
        placed_block:
          break:
            drop_item:
              item: wisteria_log
    lore:
      - '&7Can be burnt into charcoal for fuel.'
      - '&aCook Time: &e6 seconds.'
  wisteria_leaves:
    display_name: Wisteria Leaves
    resource:
      generate: true
      material: PAPER
      textures:
        - logs/wisteria_leaves
    specific_properties:
     block:
        placed_model:
          type: REAL_TRANSPARENT
          break_particles: ITEM
        hardness: 0.2
        cancel_drop: true
        sound:
          break:
            name: block.grass.break
            volume: 1
            pitch: 0.9
          place:
            name: block.grass.break
            volume: 1
            pitch: 0.9
  wisteria_tree_sapling:
    display_name: Wisteria Sapling
    resource:
      material: PAPER
      generate: true
      textures:
      - logs/wisteria_sapling.png
    behaviours:
      sapling:
        tree_populator: wisteria_tree
  twilight_log:
    display_name: Twilight Log
    resource:
      generate: true
      material: PAPER
      textures:
        - logs/twilight_log_down
        - logs/twilight_log_south
        - logs/twilight_log_east
        - logs/twilight_log_north
        - logs/twilight_log_up
        - logs/twilight_log_west
    specific_properties:
      block:
        placed_model:
          type: REAL
          break_particles: ITEM
        cancel_drop: true
        hardness: 2
        ignore_fortune: true 
        sound:
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 1
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 1
    events:
        placed_block:
          break:
            drop_item:
              item: twilight_log
    lore:
      - '&7Can be burnt into charcoal for fuel.'
      - '&aCook Time: &e6 seconds.'
  twilight_leaves:
    display_name: Twilight Leaves
    resource:
      generate: true
      material: PAPER
      textures:
        - logs/twilight_leaves
    specific_properties:
     block:
        placed_model:
          type: REAL_TRANSPARENT
          break_particles: ITEM
        cancel_drop: true
        hardness: 0.2
        sound:
          break:
            name: block.grass.break
            volume: 1
            pitch: 0.9
          place:
            name: block.grass.break
            volume: 1
            pitch: 0.9
  twilight_tree_sapling:
    display_name: Twilight Sapling
    resource:
      material: PAPER
      generate: true
      textures:
      - logs/twilight_sapling.png
    behaviours:
      sapling:
        tree_populator: twilight_tree
  maple_log:
    display_name: Maple Log
    resource:
      generate: true
      material: PAPER
      textures:
        - logs/maple_log_down
        - logs/maple_log_south
        - logs/maple_log_east
        - logs/maple_log_north
        - logs/maple_log_up
        - logs/maple_log_west
    specific_properties:
      block:
        placed_model:
          type: REAL
          break_particles: ITEM
        cancel_drop: true
        hardness: 2
        ignore_fortune: true 
        sound:
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 1
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 1
    events:
        placed_block:
          break:
            drop_item:
              item: maple_log
    lore:
      - '&7Can be burnt into charcoal for fuel.'
      - '&aCook Time: &e6 seconds.'
  maple_leaves:
    display_name: Maple Leaves
    resource:
      generate: true
      material: PAPER
      textures:
        - logs/maple_leaves
    specific_properties:
     block:
        placed_model:
          type: REAL_TRANSPARENT
          break_particles: ITEM
        cancel_drop: true
        hardness: 0.2
        sound:
          break:
            name: block.grass.break
            volume: 1
            pitch: 0.9
          place:
            name: block.grass.break
            volume: 1
            pitch: 0.9
  maple_tree_sapling:
    display_name: Maple Sapling
    resource:
      material: PAPER
      generate: true
      textures:
      - logs/maple_sapling.png
    behaviours:
      sapling:
        tree_populator: maple_tree
loots:
  blocks:
    twilight_drop:
      type: cubimod:twilight_leaves
      items:
        twilight_sapling:
          item: cubimod:twilight_tree_sapling
          min_amount: 1
          max_amount: 2
          chance: 5
          ignore_fortune: true 
    wisteria_drop:
      type: cubimod:wisteria_leaves
      items:
        wisteria_sapling:
          item: cubimod:wisteria_tree_sapling
          min_amount: 1
          max_amount: 2
          chance: 5
          ignore_fortune: true 
    sakura_drop:
      type: cubimod:sakura_leaves
      items:
        sakura_sapling:
          item: cubimod:sakura_tree_sapling
          min_amount: 1
          max_amount: 2
          chance: 5
          ignore_fortune: true 
    maple_drop:
      type: cubimod:maple_leaves
      items:
        maple_sapling:
          item: cubimod:maple_tree_sapling
          min_amount: 1
          max_amount: 2
          chance: 5
          ignore_fortune: true
```

### Other files, you can drag and drop them here to upload. (optional)

info:
  namespace: cubimod
trees_populators:
  sakura_tree:
    worlds:
    - world
    chance: 30.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    log: cubimod:sakura_log
    leaves: cubimod:sakura_leaves
    tree_type: TREE
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
  wisteria_tree:
    worlds:
    - world
    chance: 30.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    log: cubimod:wisteria_log
    leaves: cubimod:wisteria_leaves
    tree_type: ACACIA
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
  twilight_tree:
    worlds:
    - world
    chance: 30.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    log: cubimod:twilight_log
    leaves: cubimod:twilight_leaves
    tree_type: REDWOOD
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
  maple_tree:
    worlds:
    - world
    chance: 30.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    log: cubimod:maple_log
    leaves: cubimod:maple_leaves
    tree_type: TALL_BIRCH
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL

**Comment by DarrienZ** [comment] 2023-07-05 06:11
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/e176e2a9-e3e7-4f18-9ca6-55ddd98310c9)

**Comment by DarrienZ** [comment] 2023-07-05 06:41
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/067157be-beb3-48fd-a73c-8e1ce1a8536e)

SlimeFun

**Comment by DarrienZ** [comment] 2023-07-05 06:41
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/4ce52029-58f9-479f-9656-30e6dc221dde)

**Comment by DarrienZ** [comment] 2023-07-05 06:42
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/73ea3a11-52ef-4188-8ece-e600fcb0ece1)

SlimeFun: ExoticGarden

**Comment by LoneDev6** [comment] 2023-07-05 08:40
What do you mean by "slimefun"?
Please explain

**Comment by DarrienZ** [comment] 2023-07-05 08:42
I'm not  sure this bugs from which plugins. But ExoticGarden will spawn with custom tree

**Comment by LoneDev6** [comment] 2023-07-05 08:45
thank you, anyway i don't think it's the cause.

i'll investigate but i'm not sure if it's possible to fix the issue where custom trees are spawned near other plugins/vanilla trees and their leaves are merged, it's a limitation of how the system works

**Comment by DarrienZ** [comment] 2023-07-05 08:46
Alright, thanks you

**Comment by LoneDev6** [comment] 2023-08-02 14:54
This issue can't be fixed because of how the game works.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/81800489-36ac-4f84-a944-6cdfc5c53cbb)

This issue was already fixed long time ago

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/61e0d42d-d75a-4c69-a665-657fba527141)


![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/39cf269b-37ab-4719-8438-f595c122cdb6)


I cannot reproduce this issue:

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/173fcf51-ff24-43e0-b839-ede9f36f977b)

**Closed** 2023-08-08 10:07 UTC
Labels: type: bug, status: need more info, verdict: can't reproduce
