### ISSUE TITLE
ia.m.cT.isCustomBlock() taking up significant tick when no custom blocks are configured

### ISSUE THREAD

**Issue by Projecki** [PluginBugs/Issues-ItemsAdder#2907] opened 2023-07-27 02:16 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Itemsadder is taking up significant tick from ia.m.cT.isCustomBlock() when I've configured no custom blocks at all. ItemsAdder shouldn't be checking for custom blocks when there's =0% chance they exist as currently configured; especially when doing so is taking up 0.2ms of tick

### Steps to reproduce the issue

1. Configure Itemsadder without any custom blocks
2. run server

### Server version

This server is running Pufferfish+ version git-PufferfishPlus-11 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6af76dc on HEAD)

### ItemsAdder Version

ItemsAdder version 3.5.0c-r2

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-661

### LoneLibs Version

LoneLibs version 1.0.25

**Comment by Projecki** [comment] 2023-07-27 02:17
https://spark.lucko.me/XtK9YGYgvT relevant spark report

**Comment by LoneDev6** [comment] 2023-07-27 07:28
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2864

**Comment by LoneDev6** [comment] 2023-07-27 07:28
Fixed in the upcoming update, thanks

**Closed by LoneDev6** 2023-07-27 07:28 UTC
Labels: type: duplicate
