### ISSUE TITLE
Itemsadder TPS

### ISSUE THREAD

**Issue by ZDaPlaY** [PluginBugs/Issues-ItemsAdder#1132] opened 2021-08-23 23:02 UTC
https://timings.pl3x.net/?id=c04dfa386cd94003811b23a94f05a1fe
I updated to purpur 1.17.1 from 1.16.5 and also the itemsadder to the latest version, but itemsadder is consuming a lot of tps, in the previous version of itemsadder, it was not happening

**Comment by LoneDev6** [comment] 2021-08-24 07:14
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/1125

Thanks for the report. You can read more about it in this comment: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1125#issuecomment-903604863

**Closed** 2021-08-24 07:14 UTC
Labels: bug
