### ISSUE TITLE
itemsadder custom armor doesnt work as equipment in mythicmobs mobs

### ISSUE THREAD

**Issue by umutardafiliz** [PluginBugs/Issues-ItemsAdder#4052] opened 2024-10-12 15:19 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

when you make itemsadder mob equip custom armors, it doesnt equip. custom loot from itemsadder works fine

### Steps to reproduce the issue

  - newores:crocodile_helmet HEAD
  - newores:crocodile_chestplate CHEST
  - newores:crocodile_leggings LEGS
  - newores:crocodile_boots FEET
  - wizard_staves:crocodile_spear HAND
  
  make mob equip like this, and it nothing will equip

### Server version

This server is running Pufferfish version 1.21.1-18-HEAD@63ce67d (2024-09-26T07:17:01Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are on the latest version

### ItemsAdder Version

4.0.2-beta-release-12

### ProtocolLib Version

[11:05:01 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-732
[11:05:01 INFO]: Provides read/write access to the Minecraft protocol.
[11:05:01 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs Version
version lonelibs
[11:05:15 INFO]: LoneLibs version 1.0.59
[11:05:15 INFO]: Collection of libs used by my plugins
[11:05:15 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/WCRbz8e

### Error (optional)

```shell
15:02:59 ERROR]: [MythicMobs] [SCHEDULER] Exception thrown whilst executing task
[15:02:59 WARN]: java.lang.InstantiationError: io.lumine.mythic.bukkit.adapters.BukkitItemStack
[15:02:59 WARN]:        at ItemsAdder_4.0.2-beta-release-12.jar//dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.drops.CustomItemDrop.getDrop(SourceFile:28)
[15:02:59 WARN]:        at MythicMobs-5.7.2.jar//io.lumine.mythic.core.drops.LootBag.equip(LootBag.java:242)
[15:02:59 WARN]:        at MythicMobs-5.7.2.jar//io.lumine.mythic.core.mobs.MobType.lambda$applyMobOptions$6(MobType.java:1176)
[15:02:59 WARN]:        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.Delegates$RunnableToSupplier.get(Delegates.java:121)
[15:02:59 WARN]:        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:654)
[15:02:59 WARN]:        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70)
[15:02:59 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[15:02:59 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[15:02:59 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1731)
[15:02:59 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:476)
[15:02:59 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1603)
[15:02:59 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303)
[15:02:59 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[15:02:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by LoneDev6** [comment] 2024-10-15 09:10
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/3879

**Closed** 2024-10-15 09:11 UTC
Labels: type: duplicate
