### ISSUE TITLE
ItemsAdder doesn't work in 1.21.1

### ISSUE THREAD

**Issue by SrMonsterYT** [PluginBugs/Issues-ItemsAdder#3958] opened 2024-08-31 13:00 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

mauriciooficial

### What happened?

here is a video showing all the necessary information

video: https://www.youtube.com/watch?v=b6jxu8mC1ts

my config: https://mclo.gs/fP3TSiX

the resourcepack is the default

the test was in the server lobby, when I enter through the bungeecord, I am thrown into the lobby where the texture is

### Steps to reproduce the issue

use ItemsAdder on 1.21.1 paper, with default settings

### Server version

Paper version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder v4.0.2-alpha-test-7

### ProtocolLib Version

ProtocolLib v5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs v1.0.57

### Full Server Log

https://mclo.gs/TnPdHGJ

**Comment by Andre601** [comment] 2024-08-31 20:44
@PortableGames Dude, you spill a lot of nonsense here for nothing of substance...

> Lonedev is trapped. The plugin is not ready for new versions and before everything is fixed there will be a new version. He's starting to miss the train. He should open the plugin as opensource and get help from loyal fans. But he thinks he can do it all by himself.

Currently, the latest version Mojang works on is 1.21.2, which by the looks of it changes nothing of substrance outside adding experimental tests for the community to play around with. It will most likely be the same as 1.21.1, as in making it compatible with 1.21 in general and may even be less of a hassle than 1.21.1 was itself.
If there are changes, they most likely will be small in nature and fast to adabt to. I myself provide LoneDev with updates on recent Snapshots, so he's aware of what is to come here.

And right now is IA - from what I understand - working on 1.21.1 itself. What you count as "working" is up to everyone's own interpretation, but I myself consider IA enabling and loading a RP as functional.

Also, your view of Open source is very flawed. Making a plugin OS does not result in it automatically getting a ton of contributors in the end.
Just look at [Nova](https://github.com/xenondevs/Nova): Open source and quite popular amongst people, yet like [99% of the commits are by the same core people](https://github.com/xenondevs/Nova/commits/main/) - mainly NichtStudioCode - and not from various outside contributions.

If anything, making ItemsAdder open source could even become counter productive. As of right now can LoneDev code the plugin his way in his coding style. With open sourcing it would there be a ton of extra work he had to teal with:

- Keep track of features other people want to implement.
- Ensure his code style is followed.
- Make proper tests of all the PRs to ensure there is no impact on performance or functionality.
- Constantly update his local copy with latest merged changes to keep it updated and not have merge conflicts.
- ...the list goes on.

And keep in mind that I say this as someone who is for open source projects and tries to make all my own projects open source here.

> Modern Minecraft is no longer spigot/paper but fabric or quilt. Most projects are opensource and the community participates in rapid updates to new versions.

Then go and use Fabric or Quilt (Also, there is NeoForge now, which also seems to gain popularity)?
Like, why mention this even?
And refer to my previous paragraph on why you have a dillusional view on open source. The ones you think gain lots of participants are often times the most popular ones, but that doesn't reflect the majority of every OS project out there, nor the complexity that is behind maintaining such a project.

> The idea of maintaining support for old versions is complete bullshit. Most people want the new features of the new version anyway. Why maintain compatibility for 4 year old versions? . Isn't it better to focus on always supporting the latest version? It would also be good advertising: we always support the latest version of mc.

You must've missed the last 2 months dude... LoneDev does not try to keep backwards compat for 4+ years old versions. Quite the oposite actually.
v4 is actually **dropping any support for versions before 1.20.5**, making its supported versions 1.20.5, 1.20.6, 1.21 and 1.21.1.
Given that you should stay with the latest patch versions for max security and bugfixes can we say v4 supports 1.20.6 and 1.21.1. 2 out of the countless versions before those that v4 supports.
And he at one occassion even mentioned that v3 won't receive updates anymore (maybe some smaller bugfixes), as nobody should stay on older versions. He knows this just as well as you do.

> Lonedev should think twice and instead of wasting time fixing old bugs in old versions he should step into real support for 1.21.1 and future 1.21.2 (btw many fabric mods already support 1.21.2 snapshots)

The main issue with new version support is the api a software relies on. Mods support 1.21.2 snapshots because Fabric, Quilt, NeoForge and Forge already have a mod loader and API version for it.
Spigot and Paper do not make versions of their API and server for snapshots as A) it takes time and B) is effectively wasted once the next snapshot or full version rolls around. And nobody really runs a snapshot version on their production server (unless it's something like an april fools snapshot maybe).
If ItemsAdder was a standalone thing, then perhaps asking for support of the snapshots would be okay. But the plugin is still a plugin and depends on the server it runs on, just like mods depend on the modloader they run on. You can't claim he should work on support for a version that has no active API support yet by the servers it needs to function.

You clearly have no idea of how the plugin world works here, especially in the open source section here, so with all due respect, please stop spreading nonsense in these places here, as it is not productive on any level, nor does it help LoneDev in improving the plugin. All it does is showing you as a complaining, entitled individual who thinks plugin development is the same as modding, which they are clearly not.

And to avoid this issue being further derailed will I lock it. Sorry, not sorry.

> [!NOTE]
> All the info stated above is *my* opinion on the matter. I do not speak on LoneDev's behalf here, nor do I have his agreement on anything said here. Do not assume what I said here is what he thinks too, as it may or may not be different.

**Comment by Andre601** [comment] 2024-08-31 20:48
@SrMonsterYT You've modified your log file, as the "licensed to" text wouldn't be censored at all by mclo.gs and not in such a way.
Please share the logs as-is without modifications so that we can be sure they share the proper info here.

Given this issue is now locked do I recommend to share the logs in the ItemsAdder channel on LoneDev's Discord.
I may also unlock this issue at a later point if I'm confident that there won't be any further derailing on the topic here.

**Comment by LoneDev6** [comment] 2024-09-02 13:11
I cannot reproduce the issue.
No one can help you or identify the causes without clear explanation on how to reproduce the issue.
This probably could be solved by reading this tutorial: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

**Closed by LoneDev6** 2024-09-02 13:11 UTC
Labels: type: bug, verdict: invalid, verdict: misconfigured
