### ISSUE TITLE
Creative mode hotbar glitches with furniture and blocks

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#2076] opened 2022-11-03 13:47 UTC
### What happened?

When i give myself a furniture item IN CREATIVE and it appears in my inventory. I attempt to move it to lets say slot 1 of my hotbar. I have slot 8 selected as in hand. When placing the item in to slot 1 or any other slot other than slot 8, the item automatically teleports to slot 8 or any other hotbar slot you have selected as in hand.

Then you remove it from slot 8 or whichever slot it ended up in, back to your inventory. Then you try put it in your hotbar again and the item disappear. This has been an issue for a few versions now up to todays version 3.2.5-r2

I've removed all possible plugins that may have caused a conflict, all plugins that deal with a players inventory but it did not fix the issue. Then i removed Itemsadder and the issue disappeared. This only seems to be happening with custom furniture or anything using furniture configuration.

### Steps to reproduce the issue

1. Give yourself a furniture item
2. move it from your inventory to an action slot not selected as in hand.
3. watch it teleport to the in hand slot. 
4. move item from in hand slot back to inventory
5. try placing in hotbar again
6. watch the item disappear

### Server version

[09:09:54 INFO]: This server is running Paper version git-Paper-256 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e30b082)
You are running the latest version
Previous version: git-Paper-211 (MC: 1.19.2)

### ItemsAdder Version

[09:11:03 INFO]: ItemsAdder version 3.2.3-r10
[09:11:03 INFO]: Customized Minecraft without client mods!
[09:11:03 INFO]: Website: devs.beer
[09:11:03 INFO]: Author: LoneDev

But i've tested the latest version  3.2.5-r2 and it's still occurring.

### ProtocolLib Version

[09:12:48 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b595
[09:12:48 INFO]: Provides read/write access to the Minecraft protocol.
[09:12:48 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[09:13:09 INFO]: LoneLibs version 1.0.21
[09:13:09 INFO]: Collection of libs used by my plugins
[09:13:09 INFO]: Authors: LoneDev and others

### ItemsAdder config.yml

```shell
metrics: false
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: ---.---.---.--1
      pack-port: ----5
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: false
    hide-hud: false
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: false
      extreme: false
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: true
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    compress-png-files: true
    compress-json-files: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    disable-overwrite-leather-armor-layers-textures: true
  items:
    CustomModelData-starting-value:
      ALL: 1
      DIAMOND: 1
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-resources: false
  extract-default-configs: false
  legacy_pack: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: false
    allow-any-item: false
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: false
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: false
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: false
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
entities:
  max-furniture-vehicles-per-chunk: 999
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: false
    optimized-packets: true
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: true
      on-pickup:
        any: false
        ingredients: true
  fix-packet-too-large-kick: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
chat-preview: false
```

### Problematic items yml configuration file (optional)

```shell
any item that uses the furniture attribute
```

**Comment by LoneDev6** [comment] 2022-11-03 14:43
Remove every other plugin and test with only ItemsAdder and its dependencies.

**Comment by SirCraftypants** [comment] 2022-11-04 10:37
I removed every single plugin i have one by one until all that was left was itemsadder and its dependencies and it's still happening. As i said before it's only furniture items in creative. 

I even proceeded by removing itemsadder and only then did the problem stop.

https://user-images.githubusercontent.com/66942713/199952615-236099d6-dfb0-4888-bd18-5fa99eb10cf2.mp4

**Comment by LoneDev6** [comment] 2022-11-04 12:04
I cannot reproduce the issue.
There is something interfering with the plugin or you are using a misconfigured item.

https://user-images.githubusercontent.com/27242001/199968196-223c5def-d530-4cee-9581-cb0c5d09ad15.mp4

**Comment by SirCraftypants** [comment] 2022-11-04 12:08
as there's no plugins on the paper 1.19.2 server other than itemsadder and it's dependencies, it's hard to see what else could be interfering. I can guarantee that theres nothing in my itemsadder content mis-configured without any shadow of doubt.

As stated before it happens with every single item using the furniture attribute.

**Comment by SirCraftypants** [comment] 2022-11-04 13:35
![2022-11-04](https://user-images.githubusercontent.com/66942713/199985302-32bff408-cba9-4118-9ac5-e8948baafd82.png)
 As you can see here i've eliminated all the plugins on my server other than these in this screenshot. It's still happening.

**Comment by SirCraftypants** [comment] 2022-11-04 13:37
I've done everything in my power that you've asked me too

**Comment by SirCraftypants** [comment] 2022-11-04 13:38
Try reproducing with the above list of plugins which are all available free

**Comment by SirCraftypants** [comment] 2022-11-04 14:47
but like i said, i removed all accept for IA's dependencies on Paper #256 1.19.2

**Comment by SirCraftypants** [comment] 2022-11-05 08:46
Here's how all my furniture are setup https://paste.helpch.at/curitafaqi.yaml

**Comment by LoneDev6** [comment] 2022-11-05 11:36
Remove all
![image](https://user-images.githubusercontent.com/27242001/200117938-a8b1f52e-cb55-4180-9a86-4d46beec0e03.png)

**Comment by SirCraftypants** [comment] 2022-11-05 11:40
> Remove all ![image](https://user-images.githubusercontent.com/27242001/200117938-a8b1f52e-cb55-4180-9a86-4d46beec0e03.png)

I did including Vault also, is was still happening, this was my point a said above, i removed all accept itemsadder and it's dependencies and it was still happening. then i removed itemsadder and it stopped happening. So i am suspecting whatever is causing it is between Paper 1.19.2 #256 and itemsadder because my furniture configurations are as they should be. Something has happened between 1.19 and 1.19.2 paper.

**Comment by EpicPlayerA10** [comment] 2022-11-11 22:18
I also have this bug on my server. I modified paper a bit to see what is responsible for this bug. You can see the debugs here: https://pastebin.com/akKzs3cb . This shows packets that are sent, fields of these packets and what sent these packets.

You can see there that ItemsAdder is doing something on `InventoryCreativeEvent` event. It sets a custom item in the held slot. Maybe ItemsAdder thinks that client just clicked with a scroll on a block.

**Comment by SirCraftypants** [comment] 2022-11-11 22:21
> I also have this bug on my server. I modified paper a bit to see what is responsible for this bug. You can see the debugs here: https://pastebin.com/akKzs3cb . This shows packets that are sent, fields of these packets and what sent these packets.
> 
> You can see there that ItemsAdder is doing something on `InventoryCreativeEvent` event. It sets a custom item in the held slot and it denies the event. Maybe ItemsAdder thinks that client just clicked with a scroll on a block.

yeah i knew it wasn't being caused by another plugin because i removed everything, only thing that stopped it was removing itemsadder itself.

**Comment by SirCraftypants** [comment] 2022-11-18 20:11
@LoneDev6 As someone else has now contributed to this, also having the same issue, maybe you could reopen it?

**Comment by SirCraftypants** [comment] 2022-11-30 18:23
on latest v3 IA and can confirm, when i place a custom furniture item in my inventory, then move it to my actionbar, the item automatically teleports to the slot selected as in hand in creative mode.

Then try to move the same item a second time in the actionbar and the item disappears.

Then log out and back in to the game again and the item that disappeared is in your hand again.

**Comment by LoneDev6** [comment] 2022-12-08 14:20
Fixed in the upcoming beta

**Closed** 2022-12-08 16:40 UTC
Labels: Bug
