### ISSUE TITLE
void org.bukkit.event.entity.EntityDamageByEntityEvent when break custom chest

### ISSUE THREAD

**Issue by hiiamken** [PluginBugs/Issues-ItemsAdder#3449] opened 2024-02-21 08:16 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

After I put the chest out, I can't destroy it. When I destroy it, the console says this (Erro option)

### Steps to reproduce the issue

1. get chest /iaget
2. put it out on the ground
3. break it

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/142149960/05419f6b-5869-4df7-af4f-c11a5490327f)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/142149960/690b136d-5e8c-447a-907e-1dfdcabdfc3e)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/142149960/8bb2818e-d6a4-4af2-8043-9217380d3264)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/142149960/30b6ace2-54bc-4b79-bdd9-d13c26fb6457)

### FULL server log

https://mclo.gs/iMyx75T

### Error (optional)

```shell
[08:11:59 WARN]: [ItemsAdder] Task #73647 for ItemsAdder v3.6.3-beta-13 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.event.entity.EntityDamageByEntityEvent.<init>(org.bukkit.entity.Entity, org.bukkit.entity.Entity, org.bukkit.event.entity.EntityDamageEvent$DamageCause, double)'
        at ia.m.sj.<init>(SourceFile:11) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.rt.a(SourceFile:631) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.cf.b(SourceFile:159) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.cf.a(SourceFile:118) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.cf.a(SourceFile:396) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-423]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-423]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.20.4.jar:git-Paper-423]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-423]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[paper-1.20.4.jar:git-Paper-423]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[paper-1.20.4.jar:git-Paper-423]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-423]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: arcanistset
categories:
  arcanistset:
    enabled: true
    skip_if_already: false
    icon: "arcanistset:arcanist_sword"
    name: Arcanist Weapons & Tools Set
    permission: ia.menu
    items:
      - "arcanistset:arcanist_sword"
      - "arcanistset:arcanist_greatsword"
      - "arcanistset:arcanist_spear"
      - "arcanistset:arcanist_trident"
      - "arcanistset:arcanist_hammer"
      - "arcanistset:arcanist_scythe"
      - "arcanistset:arcanist_staff"
      - "arcanistset:arcanist_bow"
      - "arcanistset:arcanist_crossbow"
      - "arcanistset:arcanist_axe"
      - "arcanistset:arcanist_hoe"
      - "arcanistset:arcanist_pickaxe"
      - "arcanistset:arcanist_shovel"
      - "arcanistset:arcanist_fishing_rod"
      - "arcanistset:arcanist_shield"
      - "arcanistset:arcanist_chest"
      - "arcanistset:arcanist_key"
      - "arcanistset:arcanisthelmet"
      - "arcanistset:arcanistchestplate"
      - "arcanistset:arcanistleggings"
      - "arcanistset:arcanistboots"
      - "arcanistset:arcanist_hat"
      - "arcanistset:arcanist_wings"
      - "arcanistset:arcanist_backpack"
```

**Comment by hiiamken** [comment] 2024-02-21 08:24
I changed to version ItemsAdder_3.6.3-beta-12 and was able to destroy the chest block

**Comment by hiiamken** [comment] 2024-02-21 08:25
I think it's because of the latest version

**Comment by LoneDev6** [comment] 2024-02-21 10:46
Related to: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3439

Can you update to the latest Paper build instead?

**Comment by hiiamken** [comment] 2024-02-21 17:22
> Related to: #3439
> 
> Can you update to the latest Paper build instead? Let me know.

i updated, it still there

**Comment by LoneDev6** [comment] 2024-02-22 09:54
I will test again, strangely I cannot reproduce the issue.
Thanks for the patience

**Comment by LoneDev6** [comment] 2024-04-23 11:57
I can't reproduce the issue, updating Paper might fix the issue.
Anyway I will try to remove annotations, might be the cause but I doubt.
`public FakeEntityDamageByEntityEvent(@NotNull Entity damager, @NotNull Entity damagee, @NotNull DamageCause cause, double damage)`


My new code:
```java
package dev.lone.itemsadder.utils.events;

import org.bukkit.entity.Entity;
import org.bukkit.event.entity.EntityDamageByEntityEvent;

public class FakeEntityDamageByEntityEvent extends EntityDamageByEntityEvent
{
    @SuppressWarnings("deprecation")
    public FakeEntityDamageByEntityEvent(Entity damager, Entity damagee, DamageCause cause, double damage)
    {
        super(damager, damagee, cause, damage);
    }
}
```

**Comment by LoneDev6** [comment] 2024-04-24 09:50
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/3426

**Closed by LoneDev6** 2024-04-24 09:50 UTC
Labels: type: bug, verdict: can't reproduce, verdict: reintroduced after update
