### ISSUE TITLE
Black armor texture

### ISSUE THREAD

**Issue by tajtinorbi** [PluginBugs/Issues-ItemsAdder#3601] opened 2024-05-04 09:24 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

dephloy3r

### What happened?

Overnight, 1 in 4 people can't see the armor textures, they only see the black textures that are put on armor.

What could be the problem?
![kép_2024-05-04_112123673](https://github.com/PluginBugs/Issues-ItemsAdder/assets/63115766/3c34a5d1-04ee-43d3-a04e-26241d60fdc8)
![kép_2024-05-04_112137637](https://github.com/PluginBugs/Issues-ItemsAdder/assets/63115766/41e76bcd-e972-43e7-b6d0-266b6597c736)

### Steps to reproduce the issue

we try iazip and after frp generate cuz we use the forceresourcespack .

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version

### ItemsAdder Version

itemsadder version: 3.6.3-beta-14

### ProtocolLib Version

ProtokolLib version: 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version : 1.0.45

**Comment by Andre601** [comment] 2024-05-04 09:28
Duplicate of #3599

**Closed** 2024-05-04 09:29 UTC
Labels: type: duplicate

**Comment by tajtinorbi** [comment] 2024-05-04 17:35
why close and no answering for me?

**Comment by SrMonsterYT** [comment] 2024-05-10 17:44
problem still occurs in the latest version

**Comment by LoneDev6** [comment] 2024-05-11 13:54
Try to join without any mods installed, probably is the cause.
Also might be an issue with GPU drivers of some of your players.

**Comment by SrMonsterYT** [comment] 2024-05-13 15:45
> Try to join without any mods installed, probably is the cause. Also might be an issue with GPU drivers of some of your players.

my server has no mods, they're in vanilla

**Comment by LoneDev6** [comment] 2024-05-13 15:47
> might be an issue with GPU drivers of some of your players.
