### ISSUE TITLE
There is a crossover with ExecutableItems, it crashes my server when adding ItemsAdder

### ISSUE THREAD

**Issue by GJ-Euphory** [PluginBugs/Issues-ItemsAdder#3550] opened 2024-04-11 18:12 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

gjeuphory21

### What happened?

It won't let me turn on my server through a loop.

### Steps to reproduce the issue

1. I turn on the server
2. It crashes ._.

### Server version

PaperMC 1.20.4 (latest)

### ItemsAdder Version

latest version

### ProtocolLib Version

latest version

### LoneLibs Version

latest version

### Error (optional)

```shell
[13:00:18 ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[13:00:18 ERROR]: [SimpleProviderStorage] Circular load order:
[13:00:18 ERROR]: [SimpleProviderStorage]   ExecutableItems -> eco -> zShop -> zMenu -> ItemsAdder -> ExecutableItems
[13:00:18 ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[13:00:18 ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[13:00:18 ERROR]: Encountered an unexpected exception
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/122542736/6734389b-7a5f-4b28-bda2-5a86eb5eed70)

**Comment by LoneDev6** [comment] 2024-04-15 14:07
Duplicate of #3273
Read here: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3273#issuecomment-1872970787

**Closed by LoneDev6** 2024-04-15 14:07 UTC
Labels: type: bug
