### ISSUE TITLE
Tools in loot configuration

### ISSUE THREAD

**Issue by P5ina** [PluginBugs/Issues-ItemsAdder#3523] opened 2024-03-28 15:05 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

p5ina

### Describe the solution you'd like

Add loot configuration fields to control when it will trigger when using a specific tool.

### Is your feature request related to a problem?

I need to drop custom item, when breaking `TALL_GRASS` using hoe.

### Describe alternatives you've considered

Writing a custom plugin or a datapack.

**Comment by LoneDev6** [comment] 2024-04-04 14:26
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/125

**Closed by LoneDev6** 2024-04-04 14:26 UTC
Labels: type: feature request
