### ISSUE TITLE
shapeless and duplicated ingredients

### ISSUE THREAD

**Issue by IPECTER** [PluginBugs/Issues-ItemsAdder#3417] opened 2024-02-09 10:20 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

If we use this
```yml
shapeless: true
ingredients:
  A: pamhc2foodcore:juicer
  B: APPLE
  C: APPLE
```
IA will warn it due to duplicated ingredients
but I need duplicated ingredients
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80433772/3b064a46-554d-4f95-aabe-50085a0ced1a)
because this.

Ia is so good. but sometimes there seem to be strange limit

### Is your feature request related to a problem?

We cant make creative-recipes

### Describe alternatives you've considered

make it can be duplicated ingredients

### Additional context

as possible as you can... plz fast update it

**Comment by LoneDev6** [comment] 2024-02-11 14:19
This is a limitation of shapeless recipes.
Duplicate of: #2831

**Closed by LoneDev6** 2024-02-11 14:19 UTC
Labels: type: feature request
