### ISSUE TITLE
Unicodes bugs on new version 

### ISSUE THREAD

**Issue by ciliomine** [PluginBugs/Issues-ItemsAdder#3504] opened 2024-03-18 23:15 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Im trying to upgrade the server from 1.19.2 to 1.20.4  but i cant because i have a lot of custom fonts in /minecraft/font/default like:

> 		},
> 		{
> 			"type":"bitmap",
> 			"file":"gui/phone/contact.png",
> 			"ascent":23,
> 			"height":31,
> 			"chars":["孔宜艾","石石石","石石石","石石石","石石石","石石石"]
> 		},
> 

they work fine with itemsadder old version (ItemsAdder_3.4.1-r5)
but if you put the latest version of itemsadder on 1.20.4 and open the server it work after you do /iazip and it break 
I made a lot of test but i cant get the fix, at the moment is like it didnt accept japanese letters or custom icons like :

>         {
>             "type": "bitmap",
>             "file": "npc:speech.png",
>             "ascent": 90,
>             "height": 180,
>             "chars": ["ꀁ"]
>         },
>         {
>             "type": "bitmap",
>             "file": "npc:dialogue/aco.png",
>             "ascent": 8,
>             "height": 42,
>             "chars": [""]
>         },
>         {
>             "type": "bitmap",
>             "file": "npc:dialogue/aco2.png",
>             "ascent": 8,
>             "height": 42,
>             "chars": [""]
>         },

I only get it work if i put the old resource pack and dont do /iazip 

### Steps to reproduce the issue

try to use custom chars like : "晨伏凶"   in default server font.

### Server version

pufferfish-paperclip-1.20.4-R0.1-SNAPSHOT-reobf

### ItemsAdder Version

ItemsAdder_3.6.3-beta-13

### ProtocolLib Version

version: 5.2.0-SNAPSHOT-679

### LoneLibs Version

version: 1.0.45

**Comment by LoneDev6** [comment] 2024-04-04 14:01
I will do some checks, for some reason the file gets saved with different encoding or the characters get handles incorrectly by the save algorithm.

Seems a duplicate of:
https://github.com/PluginBugs/Issues-ItemsAdder/issues/3388
https://github.com/PluginBugs/Issues-ItemsAdder/issues/3440

**Closed by LoneDev6** 2024-04-04 14:01 UTC
Labels: type: bug
