### ISSUE TITLE
An error log that appears when the plug-in is started

### ISSUE THREAD

**Issue by jiuwu02** [PluginBugs/Issues-ItemsAdder#3257] opened 2023-12-28 13:45 UTC
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

jw_jiuwu

### What happened?

The latest version of the plug-in will have an error log when it starts the server

### Steps to reproduce the issue

Startup server

### Server version

> version
[21:44:01 INFO]: Checking version, please wait...
[21:44:02 INFO]: Current: git-Purpur-2062 (MC: 1.20.1)*
Previous: git-Paper-196 (MC: 1.20.1)
* You are running the latest version

### ItemsAdder Version

> ver ItemsAdder
[21:44:25 INFO]: ItemsAdder version 3.6.3-beta-3
[21:44:25 INFO]: Customized Minecraft without client mods!
[21:44:25 INFO]: Website: devs.beer
[21:44:25 INFO]: Author: LoneDev

### ProtocolLib Version

> ver ProtocolLib
[21:44:42 INFO]: ProtocolLib version 5.1.0
[21:44:42 INFO]: Provides read/write access to the Minecraft protocol.
[21:44:42 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

> ver LoneLibs
[21:44:54 INFO]: LoneLibs version 1.0.42
[21:44:54 INFO]: Collection of libs used by my plugins
[21:44:54 INFO]: Authors: LoneDev and others

### Error (optional)

```shell
[21:40:38] [Server thread/ERROR]: [ItemsAdder] Error initializing plugin '[I][资源包]ItemsAdder_3.6.3-beta-3.jar' in folder 'plugins' (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.getDataFolder()" because "<parameter1>" is null
	at ia.m.qY.<init>(SourceFile:118) ~[[I][资源包]ItemsAdder_3.6.3-beta-3.jar:?]
	at ia.m.qY.<init>(SourceFile:78) ~[[I][资源包]ItemsAdder_3.6.3-beta-3.jar:?]
	at ia.m.qY.<init>(SourceFile:68) ~[[I][资源包]ItemsAdder_3.6.3-beta-3.jar:?]
	at ia.m.P.m(SourceFile:601) ~[[I][资源包]ItemsAdder_3.6.3-beta-3.jar:?]
	at ia.m.O.m(SourceFile:436) ~[[I][资源包]ItemsAdder_3.6.3-beta-3.jar:?]
	at dev.lone.itemsadder.Main.bN(SourceFile:592) ~[[I][资源包]ItemsAdder_3.6.3-beta-3.jar:?]
	at dev.lone.itemsadder.Main.onLoad(SourceFile:180) ~[[I][资源包]ItemsAdder_3.6.3-beta-3.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:524) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by LoneDev6** [comment] 2023-12-28 16:03
Duplicate of #3253

**Closed by LoneDev6** 2023-12-28 16:03 UTC
Labels: type: bug
