### ISSUE TITLE
Durability with max_custom_damage not applied when item has nbt in configuration

### ISSUE THREAD

**Issue by KrazyxWolf** [PluginBugs/Issues-ItemsAdder#4081] opened 2024-10-26 23:34 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

krazyxwolf_

### What happened?

Basically as the title says, items with custom nbt and max_custom_durability, for some reason the max_damage component is not applied to them

### Steps to reproduce the issue

1. Create and configure two items with max_custom_damage
2. add custom nbt to any of the two items
3. The item with custom nbt won't have max_damage in the output of the /iatag or /data command

### Server version

[20:07:40 INFO]: Checking version, please wait...
[20:07:41 INFO]: This server is running Paper version 1.20.6-150-ver/1.20.6@e61b73f (2024-09-16T19:18:19Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

### ItemsAdder Version

[20:11:15 INFO]: ItemsAdder version 4.0.3
[20:11:15 INFO]: Customized Minecraft without client mods!
[20:11:15 INFO]: Website: devs.beer
[20:11:15 INFO]: Author: LoneDev

### ProtocolLib Version

[20:06:13 INFO]: ProtocolLib version 5.3.0
[20:06:13 INFO]: Provides read/write access to the Minecraft protocol.
[20:06:13 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[20:04:57 INFO]: LoneLibs version 1.0.59
[20:04:57 INFO]: Collection of libs used by my plugins
[20:04:57 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/TfS1S5s

### Screenshots/Videos (you can drag and drop files or paste links)

![Captura de pantalla 2024-10-26 150347](https://github.com/user-attachments/assets/d16e8edd-25f1-4517-8e29-bbb7e57700b9)
![Captura de pantalla 2024-10-26 150426](https://github.com/user-attachments/assets/fdf150fc-6891-4af4-bfc7-5f67dda56953)

**Comment by LoneDev6** [comment] 2024-11-12 18:26
Seems a duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/4039
which is going to be fixed in 4.0.4.
Please join my Discord and test the pre release beta, it contains a fix for this.
let me know how it goes.

**Closed** 2024-11-12 18:26 UTC
Labels: type: duplicate

**Comment by KrazyxWolf** [comment] 2024-11-13 21:33
Hello, the issue stills happening, the max_damage is not applying to a item with custom nbt in 1.20.6

Item config: https://paste.md-5.net/gicodujete.bash
Plugin version: 4.0.4-indev-12 with LoneLibs 1.0.60

![Captura de pantalla 2024-11-13 162858](https://github.com/user-attachments/assets/110a4c51-9ac7-44f5-9bef-32665dfde4d9)

**Comment by KrazyxWolf** [comment] 2024-11-15 16:53
The issue stills present in ItemsAdder 4.0.4-indev-13
@LoneDev6

**Comment by LoneDev6** [comment] 2024-12-05 16:43
Update to beta 4.0.5 by joining the beta channel on Discord and let me know.
