### ISSUE TITLE
Custom durability does not apply if the items has custom nbt

### ISSUE THREAD

**Issue by KrazyxWolf** [PluginBugs/Issues-ItemsAdder#4156] opened 2024-11-20 23:36 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

krazyxwolf_

### What happened?

I already reported this bug in #4081 on custom armors with custom nbt but was closed for being an apparent duplicate of issue with different conditions under which it occurs and the current issue was not fixed in the version 4.0.4

### Steps to reproduce the issue

Test the contents of the armor configurations and see the output of /data or /iatag of those items

### Server version

[22:56:18 INFO]: Checking version, please wait...
[22:56:18 INFO]: This server is running Paper version 1.20.6-151-ver/1.20.6@a4f0f5c (2024-10-30T19:13:22Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

### ItemsAdder Version

[22:57:29 INFO]: ItemsAdder version 4.0.4

### ProtocolLib Version

[22:58:43 INFO]: ProtocolLib version 5.3.0

### LoneLibs Version

[22:59:23 INFO]: LoneLibs version 1.0.61

### Full Server Log

https://mclo.gs/aTo29Su

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: expansion
items:
  fake_helmet_nbt:
    nbt: '{HasDamage: 1b}'
    fire_resistant: true
    item_flags:
    - HIDE_ENCHANTS
    enchants:
    - PROTECTION:5
    - THORNS:4
    - UNBREAKING:5
    resource:
      generate: true
    durability:
      max_custom_durability: 140
    specific_properties:
      armor:
        slot: head
  fake_helmet:
    fire_resistant: true
    item_flags:
    - HIDE_ENCHANTS
    enchants:
    - PROTECTION:5
    - THORNS:4
    - UNBREAKING:5
    resource:
      generate: true
    durability:
      max_custom_durability: 140
    specific_properties:
      armor:
        slot: head
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Captura de pantalla 2024-11-13 162858](https://github.com/user-attachments/assets/1b839efa-020a-4e45-b947-5dab7cfc80c0)

**Comment by Andre601** [comment] 2024-11-20 23:40
If the other issue was marked a duplicate, opening yet another one stating basically the same issue won't change much. If you want to help, provide your info on the **original issue** that has been mentioned.

Duplicate of #4039

**Closed** 2024-11-20 23:40 UTC
Labels: type: duplicate
