### ISSUE TITLE
Pannel error

### ISSUE THREAD

**Issue by Hiroce** [PluginBugs/Issues-ItemsAdder#2575] opened 2023-04-28 12:24 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Hiroce#4522

### What happened?

When I start my server in 1.19.3 with the plugins ItemsAdder (3.4.1-r6), ProtocolLib (616) and LoneLibs, the server shows me an error that is incomprehensible to me.
On my server there are also the following plugins:
- Citizen
- EssentialX
- EssentialXChat
- EssentialXSpawn
- Global Market Chest
- Iridium
- JetsMinions
-Luck Permit
- Multiverse Core
- NametagEdit
- Skip
- Rear
- ViaVersion
- World edit

### Steps to reproduce the issue

1. Upload ProtocolLib plugin to the server
2. Upload LoneLibs plugin to the server
3. Upload ItemsAdder plugin to the server

### Server version

This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)

### ItemsAdder Version

ItemsAdder version 3.4.1-r6

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11353414/latest.log)

**Comment by LoneDev6** [comment] 2023-04-28 15:54
Duplicate of this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2569

**Closed by LoneDev6** 2023-04-28 15:54 UTC
Labels: type: bug
