### ISSUE TITLE
i/o console error 

### ISSUE THREAD

**Issue by robtbs** [PluginBugs/Issues-ItemsAdder#2606] opened 2023-05-05 23:00 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

05.05 21:08:08 [Server] ERROR [ItemsAdder] Unexpected I/O error while handling webserver request: 
05.05 21:08:08 [Server] WARN java.net.SocketException: Connection reset
05.05 21:08:08 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
05.05 21:08:08 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
05.05 21:08:08 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
05.05 21:08:08 [Server] WARN at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
05.05 21:08:08 [Server] WARN at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
05.05 21:08:08 [Server] WARN at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
05.05 21:08:08 [Server] WARN at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
05.05 21:08:08 [Server] WARN at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
05.05 21:08:08 [Server] WARN at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
05.05 21:08:08 [Server] WARN at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
05.05 21:08:08 [Server] WARN at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
05.05 21:08:08 [Server] WARN at ItemsAdder_3.4.1-r6.jar//ia.m.jp.run(SourceFile:40)

### Steps to reproduce the issue

console error

### Server version

05.05 22:57:14 [Server] INFO This server is running Paper version git-Paper-524 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9846d0d)
05.05 22:57:14 [Server] INFO You are running the latest version
05.05 22:57:14 [Server] INFO Previous version: git-Paper-448 (MC: 1.19.3)

### ItemsAdder Version

ItemsAdder version 3.4.1-r6

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-636

### LoneLibs Version

LoneLibs version 1.0.24

**Comment by LoneDev6** [comment] 2023-05-08 11:55
Remove all other plugins and test.
Make sure the selfhost port is open and not used by another process.
Post the whole log.

**Comment by LoneDev6** [comment] 2023-05-18 19:43
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2632

**Closed** 2023-05-18 19:43 UTC
Labels: type: bug, status: need more info
