### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by howiepvpmc** [PluginBugs/Issues-ItemsAdder#2532] opened 2023-04-13 00:54 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

gine#3345

### What happened?

items adder error spam (also tried this with no plugins except dependencies) same errors for r4 and r5

### Steps to reproduce the issue

Start up server, observe errors

### Server version

This server is running Pufferfish version git-Pufferfish-66 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: b778163 on HEAD)

### ItemsAdder Version

ItemsAdder version 3.4.1-r4

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOP-b633

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[2023-04-12-9.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11217175/2023-04-12-9.log)

### Error (optional)

```shell
[00:22:57] [Server thread/WARN]: [ItemsAdder] Task #865 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
	at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5 (1).jar:?]
	at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5 (1).jar:?]
	at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5 (1).jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.4.jar:git-Pufferfish-66]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.19.4.jar:git-Pufferfish-66]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[pufferfish-1.19.4.jar:git-Pufferfish-66]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[pufferfish-1.19.4.jar:git-Pufferfish-66]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by howiepvpmc** [comment] 2023-04-13 01:30
Now seeing someone put down a similar error under resource pack black screen ( which is also happening to us )

**Comment by datarat010** [comment] 2023-04-13 02:06
i updated to the most current paper jar file and it caused this, after rolling back my server to previous paper version the error is no more.

**Comment by LoneDev6** [comment] 2023-04-13 09:59
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2498

**Closed by LoneDev6** 2023-04-13 09:59 UTC
Labels: type: bug
