### ISSUE TITLE
[Bug] Cannot break any placed IA items and getting error in console (1.20.4)

### ISSUE THREAD

**Issue by Dynamite99** [PluginBugs/Issues-ItemsAdder#3511] opened 2024-03-22 03:34 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Dynamite99

### What happened?

Placing an item from itemsadder and then trying to break it spits this error out. https://pastebin.com/apJCu0fi

To delete the item, I have to left click it, then run /killall named (radius) and then sometimes worldedit the space it occupied. 

### Steps to reproduce the issue

See steps above

### Server version

Current: git-Purpur-2141 (MC: 1.20.4)*

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### FULL server log

https://pastebin.com/LBLGEZgS

**Comment by LoneDev6** [comment] 2024-04-04 14:12
Seems a duplicate of: #3426

**Closed by LoneDev6** 2024-04-04 14:12 UTC
Labels: type: bug
