### ISSUE TITLE
Can he support geysers

### ISSUE THREAD

**Issue by Blskk** [PluginBugs/Issues-ItemsAdder#2706] opened 2023-06-05 15:52 UTC
### Terms

- [ ] I'm using the very latest version of ItemsAdder and its dependencies.
- [ ] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [ ] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [ ] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

ia未来能否支持[Geyser](https://geysermc.org/)
或许您已经支持了，可能我没找到相关教程

### Is your feature request related to a problem?

none

### Describe alternatives you've considered

none

**Comment by LoneDev6** [comment] 2023-06-05 15:56
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/206

**Closed by LoneDev6** 2023-06-05 15:56 UTC
Labels: type: feature request
