### ISSUE TITLE
Particles list seems broken, 1.21, 4.0.2 alpha 3

### ISSUE THREAD

**Issue by The-Gust** [PluginBugs/Issues-ItemsAdder#3870] opened 2024-08-07 17:38 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

@gust1337

### What happened?

Any particle in any configuration cause **error** "Unknown particle for action shoot_particle of item"

`[21:29:03 ERROR]: [ItemsAdder] Unknown particle FLAME for action shoot_particle of item zl_items:wand_of_sparking. Available particles: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html`

### Steps to reproduce the issue

1. Create item with shoot_particle event
2. Type /iazip, error will appear, using item cause ItemsAdder crash

### Server version

PaperSpigot version 1.21-46 (API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.2 alpha 3

### ProtocolLib Version

5.3.0-726

### LoneLibs Version

1.0.56

### Error (optional)

```shell
[21:29:03 ERROR]: [ItemsAdder] Unknown particle FLAME for action shoot_particle of item zl_items:wand_of_sparking. Available particles: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: zl_items
items:
  wand_of_sparking:
    display_name: "Палочка для розжига"
    permission: magic_wand
    resource:
      material: WOODEN_SWORD
      generate: false
      model_path: weapon/magic/wand_of_sparking
    durability:
      max_custom_durability: 256
    attribute_modifiers:
      mainhand:
        attackDamage: 2
    blocked_enchants:
    - ALL
    events_settings:
      cooldown:
        indicator: HUD
        ticks: 20
        custom_hud: _iainternal:small_cooldown_bar 
    events_needed_player_stats:
      mana: ">1"
    events:
      interact_mainhand:
        left:
          damage_entity_in_sight:
            damage: 2
            distance: 9
          decrement_durability:
            amount: 1
          shoot_particle:
            name: FLAME
            distance: 8
          target_potion_effect:
            type: WITHER
            duration: 3
```

**Comment by Andre601** [comment] 2024-08-07 19:04
Duplicate of #3815

**Check the issue tracker before making a new issue!**

**Closed by Andre601** 2024-08-07 19:04 UTC
Labels: type: bug
