### ISSUE TITLE
Could not pass event EntityShootBowEvent to ItemsAdder v4.0.2-alpha-test-3

### ISSUE THREAD

**Issue by Jameskarl28** [PluginBugs/Issues-ItemsAdder#3866] opened 2024-08-06 19:32 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

lexyluther23

### What happened?

everytime player shoots bow this appears in console "Could not pass event EntityShootBowEvent to ItemsAdder v4.0.2-alpha-test-3"

### Steps to reproduce the issue

idk how please help

### Server version

This server is running Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.20.6-147-e41d44f (MC: 1.20.6)

### ItemsAdder Version

4.0.2-alpha-test-3

### ProtocolLib Version

4.0.2-alpha-test-3

### LoneLibs Version

1.0.56

### Full server log

https://mclo.gs/cL83hmh

### Error (optional)

```shell
[06:52:18] [Server thread/ERROR]: Could not pass event EntityShootBowEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.ClassCastException: class ia.m.eH cannot be cast to class ia.m.eB (ia.m.eH and ia.m.eB are in unnamed module of loader 'ItemsAdder_4.0.2-alpha-test-3.jar' @40420e7b)
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.di.b(SourceFile:364) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-148-20f5165]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityShootBowEvent(CraftEventFactory.java:635) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.item.ProjectileWeaponItem.shoot(ProjectileWeaponItem.java:67) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.item.BowItem.releaseUsing(BowItem.java:34) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.item.ItemStack.releaseUsing(ItemStack.java:940) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.entity.LivingEntity.releaseUsingItem(LivingEntity.java:4045) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1830) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Andre601** [comment] 2024-08-06 19:45
This is a duplicate of #3780

**Please check the issue tracker for pre-existing issues before making one!**

**Closed by Andre601** 2024-08-06 19:45 UTC
Labels: type: bug
