### ISSUE TITLE
Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder when open vending machine

### ISSUE THREAD

**Issue by jeffry1829** [PluginBugs/Issues-ItemsAdder#4032] opened 2024-09-26 02:24 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

jeffry1829

### What happened?

Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder when open vending machine (or other things with GUI)

### Steps to reproduce the issue

1. Put vending machines
2. Open it

### Server version

1.21.1-2305-fdfc12e (MC: 1.21.1)

### ItemsAdder Version

4.0.2-beta-release-12

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.58

### Full Server Log

https://mclo.gs/dxJI6bB

### Error (optional)

```shell
[10:19:17] [Server thread/ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.IncompatibleClassChangeError: Found class org.bukkit.craftbukkit.inventory.CraftMerchant, but interface was expected
	at ItemsAdder_4.0.2-beta-release-12.jar/itemsadder.m.yl.a(SourceFile:91) ~[ItemsAdder_4.0.2-beta-release-12.jar:?]
	at ItemsAdder_4.0.2-beta-release-12.jar/itemsadder.m.yl.b(SourceFile:51) ~[ItemsAdder_4.0.2-beta-release-12.jar:?]
	at ItemsAdder_4.0.2-beta-release-12.jar/itemsadder.m.aco.d(SourceFile:130) ~[ItemsAdder_4.0.2-beta-release-12.jar:?]
	at ItemsAdder_4.0.2-beta-release-12.jar/itemsadder.m.yl.f(SourceFile:50) ~[ItemsAdder_4.0.2-beta-release-12.jar:?]
	at ItemsAdder_4.0.2-beta-release-12.jar/itemsadder.m.aw.onPacketSending(SourceFile:55) ~[ItemsAdder_4.0.2-beta-release-12.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:120) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:120) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:99) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:497) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.network.Connection.send(Connection.java:457) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:346) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:327) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.level.ServerPlayer.sendMerchantOffers(ServerPlayer.java:1785) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.world.item.trading.Merchant.openTradingScreen(Merchant.java:49) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at org.bukkit.craftbukkit.entity.CraftHumanEntity.openMerchant(CraftHumanEntity.java:504) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at ItemsAdder_4.0.2-beta-release-12.jar/itemsadder.m.em.P(SourceFile:95) ~[ItemsAdder_4.0.2-beta-release-12.jar:?]
	at ItemsAdder_4.0.2-beta-release-12.jar/itemsadder.m.fh.d(SourceFile:149) ~[ItemsAdder_4.0.2-beta-release-12.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2305-fdfc12e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:604) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:538) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2020) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[10:19:17] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundMerchantOffersPacket@3d798c4c[
    containerId=50
    offers=[net.minecraft.world.item.trading.MerchantOffer@6460baeb, net.minecraft.world.item.trading.MerchantOffer@3c6d32ba, net.minecraft.world.item.trading.MerchantOffer@5f36db41, net.minecraft.world.item.trading.MerchantOffer@2e5c3707, net.minecraft.world.item.trading.MerchantOffer@4f0a77c5]
    villagerLevel=1
    villagerXp=0
    showProgress=false
    canRestock=false
  ]
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/9c6e0417-dea2-4719-bb59-4d8081cef43b)

No item being sold (it's ok in previous pre-release)

**Comment by LoneDev6** [comment] 2024-11-04 09:34
Duplicate of #4014
Will be fixed asap

**Closed by LoneDev6** 2024-11-04 09:34 UTC
Labels: type: bug
