### ISSUE TITLE
Villager Trade Offer Duplication

### ISSUE THREAD

**Issue by pelicanium** [PluginBugs/Issues-ItemsAdder#3385] opened 2024-01-31 12:34 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Vanilla villager trades gets duplicated when villager's GUI opened. It happens randomly but when it happens, ItemsAdder outputs an error to the console. 

### Steps to reproduce the issue

1. Open a villager's trade GUI and look if any trade offer is duplicated. 
2. Retry until a trade offer is duplicated.
3. Get an error(IndexOutOfBoundsException) at console.

### Server version

git-Purpur-2094 (MC: 1.20.2)

### ItemsAdder Version

3.6.3-beta-9

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Error (optional)

```shell
[22:28:47] [Server thread/ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.IndexOutOfBoundsException: Index 15 out of bounds for length 15
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
	at java.util.ArrayList.remove(ArrayList.java:504) ~[?:?]
	at ia.m.mF.k(SourceFile:234) ~[ItemsAdder_3.6.3-beta-9.jar:?]
	at ia.m.X.onPacketSending(SourceFile:48) ~[ItemsAdder_3.6.3-beta-9.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:276) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:261) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at net.minecraft.server.level.ServerPlayer.sendMerchantOffers(ServerPlayer.java:1652) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.resendOffersToTradingPlayer(Villager.java:520) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.restock(Villager.java:510) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:356) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:341) ~[?:?]
	at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:967) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3483) ~[?:?]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:705) ~[?:?]
	at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:155) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3137) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:461) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.tick(Villager.java:399) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1469) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:924) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:901) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1577) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[22:28:47] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutOpenWindowMerchant@652bc536[
    a=17
    b=[net.minecraft.world.item.trading.MerchantRecipe@2217ef83, net.minecraft.world.item.trading.MerchantRecipe@19ecf5b, net.minecraft.world.item.trading.MerchantRecipe@7afe0636, net.minecraft.world.item.trading.MerchantRecipe@41c77e2a, net.minecraft.world.item.trading.MerchantRecipe@5c31ea66, net.minecraft.world.item.trading.MerchantRecipe@2b2202ac, net.minecraft.world.item.trading.MerchantRecipe@21677e48, net.minecraft.world.item.trading.MerchantRecipe@5b2b7260, net.minecraft.world.item.trading.MerchantRecipe@81ad1b9, net.minecraft.world.item.trading.MerchantRecipe@33169574, net.minecraft.world.item.trading.MerchantRecipe@29192860, net.minecraft.world.item.trading.MerchantRecipe@2921e751, net.minecraft.world.item.trading.MerchantRecipe@77e87cd5, net.minecraft.world.item.trading.MerchantRecipe@7052ea69]
    c=5
    d=948
    e=true
    f=true
  ]
```

### Other files, you can drag and drop them here to upload. (optional)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/158287961/d09a30c8-fda0-4a09-afcd-063897080ff1)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/158287961/9abb4025-d8bd-4d17-8685-cbd169f30a5f)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/158287961/4913664b-7284-4ff2-9490-429225b2fec3)

**Comment by LoneDev6** [comment] 2024-01-31 18:57
Duplicate of #3358

**Closed by LoneDev6** 2024-01-31 18:57 UTC
Labels: type: duplicate
