### ISSUE TITLE
[ItemsAdder] Error loading the plugin, something is not configured right or an exception occured.

### ISSUE THREAD

**Issue by DrLemony** [PluginBugs/Issues-ItemsAdder#3302] opened 2024-01-06 11:34 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

drlemony

### What happened?

When i added betterranks addons this starting to happen

### Steps to reproduce the issue

I just added betterranks addon to contents file. nothing

### Server version

Current: git-Purpur-2118 (MC: 1.20.4)
* You are running the latest version

### ItemsAdder Version

3.6.3-beta-6

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.43

### Error (optional)

```shell
[14:31:00 ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[14:31:00 WARN]: java.util.ConcurrentModificationException
[14:31:00 WARN]:        at java.base/java.util.HashMap$HashIterator.remove(HashMap.java:1593)
[14:31:00 WARN]:        at ItemsAdder_3.6.3-beta-6.jar//ia.m.G.b(SourceFile:633)
[14:31:00 WARN]:        at ItemsAdder_3.6.3-beta-6.jar//ia.m.G.c(SourceFile:578)
[14:31:00 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[14:31:00 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[14:31:00 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1666)
[14:31:00 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[14:31:00 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1545)
[14:31:00 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1235)
[14:31:00 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[14:31:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by AsleeppMC** [comment] 2024-01-06 22:12
+ 1 to this ^

**Comment by gabriel262m** [comment] 2024-01-07 18:05
same here

**Comment by LoneDev6** [comment] 2024-01-08 14:33
Duplicate of: #3293
Seems not fixed, I will do some changes again, sadly I cannot reproduce it on my end.

**Closed** 2024-01-08 15:30 UTC
Labels: type: bug, result: breaks configurations
