### ISSUE TITLE
[Suggestion] Saving Custom items ( other plugins ) to be used as Loot Drops.

### ISSUE THREAD

**Issue by RustyDagger** [PluginBugs/Issues-ItemsAdder#142] opened 2020-04-16 04:25 UTC
**Is your feature request related to a problem? Please describe.**
I would like to drop some items from slimefun4 from some IA ore blocks in the map. the issue is I cant seem to create exact copy's of the slimefun items inside IA. ( due to nbt data and such they dont stack ) this feature could also improve compatibility with many other plugins such as mythic mobs.

**Describe the solution you'd like**
A command to save the held item to a NameSpace to be used later to create exactly that item. and be able to be used in Loot tables.  example:  /IA saveitem <NameSpace> <ItemName>

**Describe alternatives you've considered**
There is a plugin called ItemBridge that does exactly this It seems to be made for a plugin called CustomItems. you could implement that I guess However more dependency for such a small feature I'm not sure that's desirable
https://www.spigotmc.org/resources/itembridge-save-items-and-use-them-wherever-you-want-including-other-plugins.77080/

**Additional context**
slimefun4 has some 400+ items of its own currently the only known way to texture them iv found is with optifine and a pack from planetminecraft i located it uses the items name to apply it client side outside of vanillas system. 🤮 it does look like from their files that they are moving towards making a pack as they have a file to set custommodel data for each item now.

**Comment by LoneDev6** [comment] 2023-04-07 15:28
This has a downside: what if an item of the other plugin changes? The returned item from an hypothetical command `/iagetsaved <id>` would return an outdated item causing confusion to both admins and players.
There is no easy and clean way to implement something like that and ItemBridge has the same issue.

What would be more useful would be to implement ItemBridge compatibility to recipes ingredients/results and give actions and some other stuff to allow not only ItemsAdder items IDs.

So it's a duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/1585 which will eventually be implemented in the future if people still require that.

Anyway as I said this kind of compatibility bridges just cause more confusion other than being useful as if NBT changes every item already in the world or player inventory will be useless and won't work correctly anymore.

**Closed by LoneDev6** 2023-04-07 15:28 UTC
Labels: type: feature request
