### ISSUE TITLE
Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e

### ISSUE THREAD

**Issue by Distolfix** [PluginBugs/Issues-ItemsAdder#2690] opened 2023-06-01 22:24 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Since the last update, the console spams me with this error and I often see the ticks go up

 [00:19:40 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:40 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:42 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:42 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:42 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:42 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:43 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:43 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:44 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:45 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:45 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:45 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:45 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:46 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null
[00:19:46 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: null

I can't tell you why or how it happens, but something causes an error

### Steps to reproduce the issue

i don't know

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/73421268/da3fcdce-19a3-453d-860b-4511c052c2da)

### ItemsAdder Version

 ItemsAdder v3.4.1e

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/73421268/9253cc0c-5099-4021-bd17-7e694e146672)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/73421268/91434820-4596-4693-a062-a975c4e629ec)

**Comment by LoneDev6** [comment] 2023-06-02 09:34
post the whole log.
this is only a part of the error.

**Comment by Distolfix** [comment] 2023-06-02 10:50
[2023-06-02-1.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11634538/2023-06-02-1.log)

**Comment by LoneDev6** [comment] 2023-06-02 10:55
Dato che sei italiano ti scrivo in italiano.
Cerca tra i log precedenti un log dove l'errore `Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e` è apparso per la prima volta perché lo noterai subito che è puù lungo e contiene molte informazioni.
Questo non contiene nessuna informazione dato che il server dopo che un errore viene mostrato troppe volte lo taglia per evitare troppo spam.

Grazie.

**Comment by Distolfix** [comment] 2023-06-02 12:46
https://pastebin.com/b7LfRSf6

questo va bene?

**Comment by LoneDev6** [comment] 2023-06-05 09:12
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2702
Verrà fixato.

**Closed by LoneDev6** 2023-06-05 09:12 UTC
Labels: type: bug, status: need more info
