### ISSUE TITLE
server crash and kick me out

### ISSUE THREAD

**Issue by Sapherises** [PluginBugs/Issues-ItemsAdder#3045] opened 2023-09-27 07:32 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

After upgrading the server to 1.20.2, I updated the latest IA version
IA is displayed to have loaded normally during the server startup phase
But when I entered the server through Waterfall, I was kicked out and the server crashed
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/54004190/21058efe-153c-4c56-b9bc-48d714aba255)
**I have checked that the IA plugin is causing kicks and crashes, and this bug still appears when my server only installs IA, indicating that this bug is caused by IA**

### Steps to reproduce the issue

normal start
join form waterfall
server kick me out and crash

### Server version

paper - 1.20.2 - git203

### ItemsAdder Version

ia version - 3.5.1

### ProtocolLib Version

protocol 5.1.0

### LoneLibs Version

lonelibs - 1.0.26

### FULL server log

**full crash log**
[crash-2023-09-27_15.11.33-server.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/12735718/crash-2023-09-27_15.11.33-server.txt)

### Error (optional)

```shell
**server error log**
[15:11:32] [User Authenticator #0/INFO]: UUID of player Sapherise is 2da21d0b-6ea9-44e1-b70a-1f233818d63b
[15:11:32] [Netty Epoll Server IO #1/ERROR]: Packet encoding of packet ID 111 threw (skippable? false)
java.lang.ClassCastException: class net.minecraft.world.item.crafting.ShapelessRecipes cannot be cast to class net.minecraft.world.item.crafting.RecipeHolder (net.minecraft.world.item.crafting.ShapelessRecipes and net.minecraft.world.item.crafting.RecipeHolder are in unnamed module of loader java.net.URLClassLoader @7aec35a)
	at net.minecraft.network.FriendlyByteBuf.writeCollection(FriendlyByteBuf.java:226) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.write(ClientboundUpdateRecipesPacket.java:26) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:42) ~[paper-1.20.2.jar:git-Paper-203]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.20.2.jar:git-Paper-203]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:448) ~[?:?]
	at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:433) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by LoneDev6** [comment] 2023-09-27 10:59
Thanks! I found the cause of the issue and fixed it.
Will be released in the next days.

**Comment by Sapherises** [comment] 2023-10-01 00:52
I would like to know if there is an estimated date for this bug fix? Because the server has been upgraded to 1.20.2, it cannot be downgraded to 1.20.1. And this version seems to be the first version to support 1.20.2. The bug persists and players have been unable to enter the server. Or is there any way to temporarily solve this problem?

**Comment by Sapherises** [comment] 2023-10-01 00:52
Or can I just turn off this plug-in for now?

**Comment by LoneDev6** [comment] 2023-10-01 09:10
I am waiting the beta testing team to finish testing the new update, it will be released in max 24 hours.
Thanks for the patience!

**Closed** 2023-10-02 09:02 UTC
Labels: type: bug, compat: new minecraft update
